import Foundation
import XCTest

final class AppSourceRegressionTests: XCTestCase {
    func testDaemonReadOnlySnapshotsUseShortCacheButFanWritesClearIt() throws {
        let daemon = try read("Sources/ViftyDaemon/main.swift")

        XCTAssertTrue(daemon.contains("private let snapshotCacheTTL: TimeInterval = 1"))
        XCTAssertTrue(daemon.contains("private let snapshotCacheLock = NSLock()"))
        XCTAssertTrue(daemon.contains("private var cachedSnapshot: (capturedAt: Date, snapshot: HardwareSnapshot)?"))
        XCTAssertTrue(daemon.contains("if let cached = cachedSnapshotIfFresh(now: now)"))
        XCTAssertTrue(daemon.contains("storeSnapshotCache(snapshot, capturedAt: now)"))
        XCTAssertTrue(daemon.contains("private func clearSnapshotCache()"))
        XCTAssertTrue(daemon.contains("Task {\n            defer { clearSnapshotCache() }\n            do {\n                let status = try await agentControl.prepare(decoded)"))
        XCTAssertTrue(daemon.contains("Task {\n            defer { clearSnapshotCache() }\n            do {\n                let status = try await agentControl.restoreAuto(reason: reason)"))
        XCTAssertTrue(daemon.contains("Task {\n            defer { clearSnapshotCache() }\n            let status = await agentControl.status()"))
        XCTAssertTrue(daemon.contains("defer { clearSnapshotCache() }\n        do {\n            let fan = try resolveWritableFan(fanID: fanID)"))
        XCTAssertTrue(daemon.contains("private func resolveWritableFan(fanID: Int) throws -> Fan"))
        XCTAssertTrue(daemon.contains("let snapshot = try hardware.localSnapshot()"))
        XCTAssertTrue(daemon.contains("snapshot.fans.first(where: { $0.id == fanID })"))
        XCTAssertTrue(daemon.contains("Fan \\(fanID) is not present in daemon hardware telemetry; refusing privileged fan write."))
        XCTAssertTrue(daemon.contains("throw ViftyError.noControllableFans"))
        XCTAssertTrue(daemon.contains("try LocalFanHelperClient().apply(FanCommand(fanID: fanID, mode: .fixedRPM(rpm)), fan: fan)\n                reply(true, nil)"))
        XCTAssertTrue(daemon.contains("try LocalFanHelperClient().restoreAuto(fan: fan)\n            let agentControl = self.agentControl"))
        XCTAssertFalse(daemon.contains("try LocalFanHelperClient().apply(FanCommand(fanID: fanID, mode: .fixedRPM(rpm)), fan: fan)\n                clearSnapshotCache()"))
        XCTAssertFalse(daemon.contains("try LocalFanHelperClient().restoreAuto(fan: fan)\n            clearSnapshotCache()"))
        XCTAssertFalse(daemon.contains("currentRPM: rpm"))
        XCTAssertFalse(daemon.contains("currentRPM: minimumRPM"))
        XCTAssertFalse(daemon.contains("minimumRPM: minimumRPM"))
        XCTAssertFalse(daemon.contains("maximumRPM: maximumRPM"))
        XCTAssertFalse(daemon.contains("controllable: true"))
    }

    func testMenuBarHelperHealthOffersRepairAndRefreshesAfterAction() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(menuBarView.contains("@StateObject private var daemonInstaller = DaemonInstaller()"))
        XCTAssertTrue(menuBarView.contains("@State private var helperRefreshTask: Task<Void, Never>?"))
        XCTAssertTrue(menuBarView.contains("Button(daemonInstaller.actionTitle)"))
        XCTAssertTrue(menuBarView.contains("if model.helperRepairActionAvailable {"))
        XCTAssertTrue(menuBarView.contains(".disabled(!daemonInstaller.canInstall)"))
        XCTAssertTrue(menuBarView.contains("daemonInstaller.installOrOpenApproval()"))
        XCTAssertTrue(menuBarView.contains("try? await Task.sleep(for: .milliseconds(750))"))
        XCTAssertTrue(menuBarView.contains("daemonInstaller.refresh()"))
        XCTAssertTrue(menuBarView.contains("daemonInstaller.actionDescription"))
        XCTAssertTrue(menuBarView.contains("Text(daemonInstaller.helperStatusSummary)"))
        XCTAssertTrue(menuBarView.contains("if let context = model.helperInstallRuntimeContext"))
        XCTAssertTrue(menuBarView.contains("@State private var helperDiagnosticsCopied = false"))
        XCTAssertTrue(menuBarView.contains("model.helperHealthMenuSummary"))
        XCTAssertTrue(menuBarView.contains("model.helperMenuRecoverySuggestion"))
        XCTAssertFalse(menuBarView.contains("model.helperRecoverySuggestion"))
        XCTAssertTrue(menuBarView.contains("if model.helperHealthNeedsAttention"))
        XCTAssertTrue(menuBarView.contains("copyHelperDiagnosticsCommand()"))
        XCTAssertTrue(menuBarView.contains("Label(\"Copy Support Evidence\", systemImage: \"doc.on.doc\")"))
        XCTAssertTrue(menuBarView.contains("HelperDiagnosticsSupport.copySupportEvidenceCommand(context: model.helperSupportEvidenceContext)"))
        XCTAssertTrue(menuBarView.contains(".help(HelperDiagnosticsSupport.copyHelp)"))
        XCTAssertTrue(menuBarView.contains("Text(HelperDiagnosticsSupport.copiedMessage)"))
        XCTAssertEqual(menuBarView.components(separatedBy: "await model.pollOnce()").count - 1, 2)
        XCTAssertTrue(menuBarView.contains("helperRefreshTask?.cancel()"))
    }

    func testOperatorSurfacesUseFilteredLastError() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var visibleLastError: String?"))
        XCTAssertTrue(appModel.contains("lastErrorIsCoveredByHelperRecovery"))
        XCTAssertTrue(menuBarView.contains("if let error = model.visibleLastError"))
        XCTAssertTrue(contentView.contains("if let error = model.visibleLastError"))
        XCTAssertFalse(menuBarView.contains("if let error = model.lastError"))
        XCTAssertFalse(contentView.contains("if let error = model.lastError"))
    }

    func testTerminationFailsClosedWhenAppModelIsUnavailable() throws {
        let app = try read("Sources/Vifty/ViftyApp.swift")

        XCTAssertTrue(app.contains("guard let model else { return .terminateCancel }"))
        XCTAssertFalse(app.contains("guard let model else { return .terminateNow }"))
    }

    func testMainWindowHelperHealthShowsRepairAndReadOnlyDiagnosticsActions() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("daemonInstaller.actionDescription"))
        XCTAssertTrue(contentView.contains("Text(daemonInstaller.helperStatusSummary)"))
        XCTAssertTrue(contentView.contains("if let context = model.helperInstallRuntimeContext"))
        XCTAssertTrue(contentView.contains("@State private var helperDiagnosticsCopied = false"))
        XCTAssertTrue(contentView.contains("if model.helperRepairActionAvailable || model.helperHealthNeedsAttention {"))
        XCTAssertTrue(contentView.contains("if model.helperRepairActionAvailable {\n                        Button(daemonInstaller.actionTitle)"))
        XCTAssertTrue(contentView.contains("Button {\n                            copyHelperDiagnosticsCommand()\n                        } label: {\n                            Label(\"Copy Support Evidence\", systemImage: \"doc.on.doc\")"))
        XCTAssertTrue(contentView.contains("HelperDiagnosticsSupport.copySupportEvidenceCommand(context: model.helperSupportEvidenceContext)"))
        XCTAssertTrue(contentView.contains(".help(HelperDiagnosticsSupport.copyHelp)"))
        XCTAssertTrue(contentView.contains("Text(HelperDiagnosticsSupport.copiedMessage)"))
        XCTAssertTrue(contentView.contains("Text(suggestion)"))
        XCTAssertTrue(contentView.contains(".fixedSize(horizontal: false, vertical: true)"))
    }

    func testAgentWorkflowRuleCanBeCopiedFromNativeSettingsOnly() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let settingsTools = try read("Sources/Vifty/SettingsToolsPanel.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(settingsTools.contains("@State private var agentRuleCopied = false"))
        XCTAssertTrue(settingsTools.contains("@State private var agentCommandCopied = false"))
        XCTAssertTrue(settingsView.contains("SettingsToolsPanel(model: model)"))
        XCTAssertTrue(settingsView.contains("Label(\"Settings & Tools\", systemImage: \"gearshape\")"))
        XCTAssertTrue(settingsTools.contains("Label(\"Agent workflows\", systemImage: \"terminal\")"))
        XCTAssertTrue(settingsTools.contains("Label(\"Copy Command\", systemImage: \"terminal\")"))
        XCTAssertTrue(settingsTools.contains("AgentWorkflowSupport.WorkloadCommandMode.allCases"))
        XCTAssertTrue(settingsTools.contains("AgentWorkflowSupport.safeWorkloadCommandTemplates"))
        XCTAssertTrue(settingsTools.contains("copyAgentWorkflowCommand(template, mode)"))
        XCTAssertTrue(settingsTools.contains(".help(AgentWorkflowSupport.copyCommandHelp)"))
        XCTAssertTrue(settingsTools.contains("Label(\"Copy Agent Rule\", systemImage: \"doc.on.doc\")"))
        XCTAssertTrue(settingsTools.contains("copyAgentWorkflowRule()"))
        XCTAssertTrue(settingsTools.contains(".help(AgentWorkflowSupport.copyHelp)"))
        XCTAssertTrue(settingsTools.contains("Text(AgentWorkflowSupport.copiedMessage)"))
        XCTAssertTrue(settingsTools.contains("Text(AgentWorkflowSupport.copiedCommandMessage)"))
        XCTAssertTrue(settingsTools.contains("private func copyAgentWorkflowCommand("))
        XCTAssertTrue(settingsTools.contains("private func copyAgentWorkflowRule()"))
        XCTAssertTrue(settingsTools.contains("private func menuBarCustomFieldBinding(_ field: MenuBarField)"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertFalse(contentView.contains("AgentWorkflowSupport"))

        XCTAssertFalse(menuBarView.contains("@State private var agentRuleCopied = false"))
        XCTAssertFalse(menuBarView.contains("@State private var agentCommandCopied = false"))
        XCTAssertFalse(menuBarView.contains("Label(\"Copy Safe Command\", systemImage: \"terminal\")"))
        XCTAssertFalse(menuBarView.contains("AgentWorkflowSupport.WorkloadCommandMode.allCases"))
        XCTAssertFalse(menuBarView.contains("AgentWorkflowSupport.safeWorkloadCommandTemplates"))
        XCTAssertFalse(menuBarView.contains("copyAgentWorkflowCommand(template, mode: mode)"))
        XCTAssertFalse(menuBarView.contains("AgentWorkflowSupport.copyWorkloadCommand(template, mode: mode)"))
        XCTAssertFalse(menuBarView.contains(".help(AgentWorkflowSupport.copyCommandHelp)"))
        XCTAssertFalse(menuBarView.contains("Label(\"Copy Agent Rule\", systemImage: \"terminal\")"))
        XCTAssertFalse(menuBarView.contains("AgentWorkflowSupport.copyAgentRule()"))
        XCTAssertFalse(menuBarView.contains(".help(AgentWorkflowSupport.copyHelp)"))
        XCTAssertFalse(menuBarView.contains("Text(AgentWorkflowSupport.copiedMessage)"))
        XCTAssertFalse(menuBarView.contains("Text(AgentWorkflowSupport.copiedCommandMessage)"))
    }

    func testMainWindowHeaderAndEmptyFanFallbackGateRepairActions() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("if model.helperRepairActionAvailable {\n                Button {\n                    performHelperAction()"))
        XCTAssertTrue(contentView.contains("Label(\"Diagnostics only\", systemImage: \"doc.text.magnifyingglass\")"))
        XCTAssertTrue(contentView.contains("if model.helperRepairActionAvailable {\n                        Button {\n                            performHelperAction()"))
        XCTAssertTrue(contentView.contains("} else {\n                        Button {\n                            copyHelperDiagnosticsCommand()"))
        XCTAssertTrue(contentView.contains("Label(\"Copy Support Evidence\", systemImage: \"doc.on.doc\")\n                                .frame(maxWidth: 260)"))
    }

    func testEmptyTemperatureStateAndDeveloperLauncherAreBundleSafe() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let launcher = try read("scripts/build-and-run-vifty.sh")
        let makefile = try read("Makefile")

        XCTAssertFalse(contentView.contains("thermometer.slash"))
        XCTAssertTrue(contentView.contains("thermometer.medium"))
        XCTAssertTrue(launcher.contains("make app"))
        XCTAssertTrue(launcher.contains("open \"${app_path}\""))
        XCTAssertTrue(launcher.contains(".build/Vifty.app"))
        XCTAssertFalse(launcher.contains(".build/debug/Vifty"))
        XCTAssertFalse(launcher.contains("repair-helper"))
        XCTAssertFalse(launcher.contains("make install"))
        XCTAssertTrue(makefile.contains("run-app: ## Build and open the local app bundle"))
        XCTAssertTrue(makefile.contains("./scripts/build-and-run-vifty.sh"))
    }

    func testRuntimeInstrumentationUsesPrivacySafeCategories() throws {
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let appLog = try read("Sources/Vifty/ViftyLog.swift")
        let daemonClient = try read("Sources/ViftyCore/ViftyDaemonClient.swift")
        let notifications = try read("Sources/Vifty/LocalNotifications.swift")
        let codexUsage = try read("Sources/Vifty/CodexUsage.swift")

        XCTAssertTrue(appModel.contains("pollingSignposter.beginInterval"))
        XCTAssertTrue(appModel.contains("pollingSignposter.endInterval"))
        XCTAssertTrue(appLog.contains("static let lifecycle"))
        XCTAssertTrue(appLog.contains("static let polling"))
        XCTAssertTrue(appLog.contains("static let notifications"))
        XCTAssertTrue(appLog.contains("static let fanControl"))
        XCTAssertTrue(appLog.contains("static let codexUsage"))
        XCTAssertTrue(daemonClient.contains("ViftyCoreLog.xpc"))
        XCTAssertTrue(notifications.contains("ViftyLog.notifications"))
        XCTAssertTrue(codexUsage.contains("ViftyLog.codexUsage"))
        XCTAssertFalse(appLog.contains("sensorID"))
        XCTAssertFalse(appLog.contains("profile"))
        XCTAssertFalse(appLog.contains("command"))
    }

    func testCodexUsagePipeShutdownDoesNotDrainToEOF() throws {
        let codexUsage = try read("Sources/Vifty/CodexUsage.swift")

        XCTAssertFalse(codexUsage.contains("readDataToEndOfFile"))
        XCTAssertTrue(codexUsage.contains("Descendants may inherit the pipe after Process exits."))
    }

    func testMainWindowPanesAreIndependentlyScrollableAndFillAvailableHeight() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("private var mainContent: some View"))
        XCTAssertTrue(contentView.contains("GeometryReader { proxy in"))
        XCTAssertTrue(contentView.contains("let layout = MainWindowLayout.resolve(width: proxy.size.width, height: proxy.size.height)"))
        XCTAssertTrue(contentView.contains("switch layout.mode"))
        XCTAssertTrue(contentView.contains("case .stacked:"))
        XCTAssertTrue(contentView.contains("VStack(alignment: .leading, spacing: 0)"))
        XCTAssertTrue(contentView.contains("sectionView(.telemetryEvidence, compactTelemetry: layout.compactTelemetry)"))
        XCTAssertTrue(contentView.contains("case .split:"))
        XCTAssertTrue(contentView.contains("HStack(alignment: .top, spacing: 0)"))
        XCTAssertTrue(contentView.contains("case .workbench:"))
        XCTAssertTrue(contentView.contains("paneSectionsView("))
        XCTAssertFalse(contentView.contains("workbenchControlRailSectionsView("))
        XCTAssertFalse(contentView.contains("Spacer(minLength: 24)"))
        XCTAssertTrue(contentView.contains(".scrollIndicators(.visible)"))
        XCTAssertTrue(contentView.contains(".frame(width: layout.controlPaneWidth)\n                        .frame(minHeight: proxy.size.height, maxHeight: proxy.size.height)"))
        XCTAssertTrue(contentView.contains(".frame(minWidth: layout.editorPaneMinWidth, idealWidth: layout.editorPaneIdealWidth, maxWidth: layout.editorPaneMaxWidth, minHeight: proxy.size.height, maxHeight: proxy.size.height)"))
        XCTAssertTrue(contentView.contains(".frame(\n                            minWidth: layout.telemetryPaneMinWidth,\n                            idealWidth: layout.telemetryPaneIdealWidth,\n                            maxWidth: layout.telemetryPaneMaxWidth,\n                            minHeight: proxy.size.height,\n                            maxHeight: proxy.size.height\n                        )"))
        XCTAssertFalse(contentView.contains(".frame(minWidth: 360, idealWidth: 400, maxWidth: 420, minHeight: proxy.size.height, maxHeight: proxy.size.height)"))
        XCTAssertTrue(contentView.contains("Divider()\n                            .frame(height: proxy.size.height)"))
        XCTAssertTrue(contentView.contains(".background(Color.secondary.opacity(0.035))"))
        XCTAssertTrue(contentView.contains("TelemetryOverviewPanel(\n                power: model.powerSnapshot"))
        XCTAssertTrue(contentView.contains("summary: compact ? model.compactTelemetryOverviewSummary : model.telemetryOverviewSummary"))
        XCTAssertTrue(contentView.contains("TelemetryLayoutPolicy.metricColumnCount(for: metricContainerWidth)"))
        XCTAssertTrue(contentView.contains(".onGeometryChange(for: CGFloat.self)"))
        XCTAssertFalse(contentView.contains("history: model.telemetryHistory"))
        XCTAssertFalse(contentView.contains("let history: TelemetryHistory"))
        XCTAssertFalse(contentView.contains("PowerPanel(snapshot: power, compact: compact)"))
        XCTAssertFalse(contentView.contains("HistoryPanel(history: model.telemetryHistory, compact: compact)"))
        XCTAssertTrue(contentView.contains("DisclosureGroup(\"All sensors\")"))
        XCTAssertTrue(contentView.contains("ForEach(sensors) { sensor in"))
        XCTAssertTrue(contentView.contains("SensorRow(sensor: sensor, selected: sensor.id == model.selectedSensor?.id, compact: true)"))
        XCTAssertFalse(contentView.contains("let visibleSensors = topTemperatureSensors"))
        XCTAssertFalse(contentView.contains("ForEach(visibleSensors)"))
        XCTAssertFalse(contentView.contains("private func topTemperatureSensors"))
        XCTAssertTrue(contentView.contains(".frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)"))
        XCTAssertTrue(contentView.contains("PowerDisplayFormatter.panelHeadline(for: power)"))
        XCTAssertTrue(contentView.contains("PowerDetailDisclosure(snapshot: power, compact: compact)"))
        XCTAssertTrue(contentView.contains("PowerDisplayFormatter.adapterDescription(for: adapter)"))
        XCTAssertFalse(contentView.contains("PowerMetric(label: summary.latestTemperatureLabel"))
        XCTAssertFalse(contentView.contains("if let temperatureText = summary.latestTemperatureText"))
        XCTAssertFalse(contentView.contains("if let sensors = model.snapshot?.temperatureSensors, !sensors.isEmpty {\n                ScrollView {"))
    }

    func testMainWindowUsesBehavioralSectionPlacementModel() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("MainWindowSectionPlacement.resolve(layout: layout)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .stackedFlow)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .splitControl)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .splitTelemetry)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .workbenchControlRail)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .workbenchEditor)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .workbenchTelemetry)"))
        XCTAssertTrue(contentView.contains("private func sectionView("))
        XCTAssertFalse(contentView.contains("let _ = placement"))
        XCTAssertFalse(contentView.contains("private var controlRailPane: some View"))
        XCTAssertFalse(contentView.contains("private var primaryEditorPane: some View"))
        XCTAssertFalse(contentView.contains("private var fanControlPane: some View"))
    }

    func testHistoryPanelShowsLocalSparklineVisualization() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertFalse(contentView.contains("private var summary: TelemetryHistorySummary"))
        XCTAssertFalse(appModel.contains("@Published var telemetryHistory"))
        XCTAssertTrue(appModel.contains("var telemetryHistory = TelemetryHistory() {"))
        XCTAssertTrue(appModel.contains("@Published private(set) var telemetryOverviewSummary = TelemetryHistorySummary(history: TelemetryHistory())"))
        XCTAssertTrue(appModel.contains("@Published private(set) var compactTelemetryOverviewSummary = TelemetryHistorySummary("))
        XCTAssertTrue(appModel.contains("private func refreshTelemetrySummaries()"))
        XCTAssertTrue(contentView.contains("TelemetryHistoryChart(summary: summary, compact: compact)"))
        XCTAssertTrue(contentView.contains("private struct TelemetryHistoryChart: View"))
        XCTAssertTrue(contentView.contains("summary.sampleWindowText"))
        XCTAssertTrue(contentView.contains("parts.append(\"\\(summary.sampleCountText) · last \\(sampleWindowText)\")"))
        XCTAssertTrue(contentView.contains("title: \"Temp\""))
        XCTAssertTrue(contentView.contains("startValueText: summary.temperatureValues.first.map(TelemetryHistorySummary.temperatureText)"))
        XCTAssertTrue(contentView.contains("currentValueText: summary.latestTemperatureText"))
        XCTAssertTrue(contentView.contains("title: summary.fanRPMSparklineTitle"))
        XCTAssertTrue(contentView.contains("startValueText: summary.fanRPMValues.first.map(TelemetryHistorySummary.fanRPMText)"))
        XCTAssertTrue(contentView.contains("currentValueText: summary.latestFanRPMText"))
        XCTAssertFalse(contentView.contains("title: \"Fan\""))
        XCTAssertTrue(contentView.contains("title: \"Power\""))
        XCTAssertTrue(contentView.contains("startValueText: nil"))
        XCTAssertTrue(contentView.contains("changeText: summary.temperatureChangeText"))
        XCTAssertTrue(contentView.contains("changeText: summary.fanRPMChangeText"))
        XCTAssertTrue(contentView.contains("changeText: summary.batteryPowerChangeText"))
        XCTAssertTrue(contentView.contains("summaryText: summary.thermalPressureSummaryText"))
        XCTAssertTrue(contentView.contains("private struct SparklinePath: View"))
        XCTAssertTrue(contentView.contains("startValueLabelText: startValueText"))
        XCTAssertTrue(contentView.contains("SparklineValueBadge(text: startValueLabelText, color: color)"))
        XCTAssertTrue(contentView.contains("SparklineValueBadge(text: valueLabelText, color: color)"))
        XCTAssertTrue(contentView.contains("private func startLabelPosition(near point: CGPoint, in size: CGSize) -> CGPoint"))
        XCTAssertTrue(contentView.contains("private func labelPosition(near point: CGPoint, in size: CGSize) -> CGPoint"))
        XCTAssertTrue(contentView.contains("private func smoothedValues(_ rawValues: [Double]) -> [Double]"))
        XCTAssertTrue(contentView.contains("path.addQuadCurve(to: midPoint, control: previousPoint)"))
        XCTAssertFalse(contentView.contains("import Charts"))
        XCTAssertFalse(contentView.contains("private func signedWattRangeText"))
        XCTAssertFalse(contentView.contains("UserDefaults.standard.set(history"))
    }

    func testMenuBarShowsReadOnlyRecentTelemetryTrend() throws {
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(appModel.contains("var recentTelemetryTrendSummary: String?"))
        XCTAssertTrue(appModel.contains("TelemetryHistorySummary("))
        XCTAssertTrue(appModel.contains("sampleLimit: 90"))
        XCTAssertTrue(appModel.contains("thermalPressureLimit: 24"))
        XCTAssertTrue(menuBarView.contains("if let recentTelemetryTrendSummary = model.recentTelemetryTrendSummary"))
        XCTAssertTrue(menuBarView.contains("Label(recentTelemetryTrendSummary, systemImage: \"chart.xyaxis.line\")"))
        XCTAssertFalse(appModel.contains("UserDefaults.standard.set(telemetryHistory"))
    }

    func testPrivateIOKitBridgeOnlyExportsHIDTemperatureReader() throws {
        let header = try read("Sources/ViftyPrivateIOKit/include/ViftyPrivateIOKit.h")
        let implementation = try read("Sources/ViftyPrivateIOKit/ViftyPrivateIOKit.c")

        XCTAssertTrue(header.contains("ViftyHIDTemperature"))
        XCTAssertTrue(header.contains("ViftyCopyHIDTemperatures"))
        XCTAssertTrue(implementation.contains("int ViftyCopyHIDTemperatures"))
        XCTAssertFalse(header.contains("ViftyOpenSMC"))
        XCTAssertFalse(implementation.contains("ViftyOpenSMC"))
        XCTAssertFalse(implementation.contains("IOServiceOpen"))
        XCTAssertFalse(implementation.contains("AppleSMCKeysEndpoint"))
        XCTAssertFalse(implementation.contains("SMCEndpoint1"))
    }

    func testAppBundleIsDockVisibleAndHasAppIcon() throws {
        let plist = try read("Resources/Info.plist")
        let makefile = try read("Makefile")
        let iconURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent("Resources/ViftyIcon.icns")

        XCTAssertTrue(plist.contains("<key>CFBundleIconFile</key>"))
        XCTAssertTrue(plist.contains("<string>ViftyIcon</string>"))
        XCTAssertFalse(plist.contains("<key>LSUIElement</key>"))
        XCTAssertTrue(makefile.contains("APP_ICON := Resources/ViftyIcon.icns"))
        XCTAssertTrue(makefile.contains("cp \"$(APP_ICON)\" \"$(CONTENTS)/Resources/ViftyIcon.icns\""))
        XCTAssertTrue(FileManager.default.fileExists(atPath: iconURL.path))
    }

    func testMenuBarAgentCoolingSurfaceShowsTitleRecoveryAndContextualAuto() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(menuBarView.contains("Label(model.agentCoolingPanelTitle, systemImage: \"cpu\")"))
        XCTAssertTrue(menuBarView.contains("if let agentCoolingRecoverySuggestion = model.agentCoolingRecoverySuggestion"))
        XCTAssertTrue(menuBarView.contains("Label(agentCoolingRecoverySuggestion, systemImage: \"exclamationmark.triangle\")"))
        XCTAssertTrue(menuBarView.contains("if model.agentCoolingNeedsAttention, model.agentCoolingRestoreActionAvailable {"))
        XCTAssertTrue(menuBarView.contains("Button(model.agentCoolingRestoreActionTitle) {"))
        XCTAssertTrue(menuBarView.contains(".help(model.agentCoolingRestoreActionHelp)"))
    }

    func testMenuBarPowerRowsAndStatusItemDisplayModeAreWired() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let settingsTools = try read("Sources/Vifty/SettingsToolsPanel.swift")
        let viftyApp = try read("Sources/Vifty/ViftyApp.swift")
        let statusItemController = try read("Sources/Vifty/ViftyStatusItemController.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let appPreferencesStore = try read("Sources/Vifty/AppPreferencesStore.swift")
        let menuBarPresentation = try read("Sources/Vifty/MenuBarStatusPresentation.swift")
        let pollSchedulePolicy = try read("Sources/Vifty/PollSchedulePolicy.swift")

        XCTAssertTrue(menuBarView.contains("Text(model.menuPanelTitle)"))
        XCTAssertFalse(menuBarView.contains("Text(model.menuTitle)"))
        XCTAssertFalse(menuBarView.contains("if let sensor = model.selectedSensor {"))
        XCTAssertFalse(menuBarView.contains("if let sensor = model.snapshot?.highestTemperature {"))
        XCTAssertTrue(menuBarView.contains("private var menuReadinessSection: some View"))
        XCTAssertTrue(menuBarView.contains("menuReadinessSection"))
        XCTAssertTrue(menuBarView.contains("menuHelperHealthSection"))
        XCTAssertTrue(menuBarView.contains("menuAgentCoolingSection"))
        XCTAssertTrue(menuBarView.contains("if let thermalSummary = model.thermalPressure.menuSummary"))
        XCTAssertFalse(menuBarView.contains("Label(\"Thermal pressure: \\(model.thermalPressure.displayName)\", systemImage: \"speedometer\")"))
        XCTAssertTrue(menuBarView.contains("PowerDisplayFormatter.adapterDetail(for: adapter)"))
        XCTAssertFalse(menuBarView.contains("PowerDisplayFormatter.batteryFlow(for: power)"))
        XCTAssertFalse(menuBarView.contains("private func adapterDetail(_ adapter: PowerAdapter)"))
        XCTAssertFalse(menuBarView.contains("Picker(\"Default mode\", selection: $model.startupMode)"))
        XCTAssertFalse(menuBarView.contains("Picker(\"Menu bar\", selection: $model.menuBarDisplayMode)"))
        XCTAssertFalse(menuBarView.contains("Picker(\"Codex display\", selection: $model.codexUsageDisplayStyle)"))
        XCTAssertFalse(menuBarView.contains("model.codexUsageDetailLines"))
        XCTAssertFalse(menuBarView.contains("Label(\"Copy Safe Command\", systemImage: \"terminal\")"))
        XCTAssertFalse(menuBarView.contains("Label(\"Notifications\", systemImage: \"bell\")"))
        XCTAssertTrue(menuBarView.contains("Label(model.compactControlOwnershipSummary"))
        XCTAssertTrue(menuBarView.contains("Text(verbatim: \"\\(fan.name) \\(fan.currentRPM) RPM · \\(fan.percentage)%\")"))
        XCTAssertTrue(contentView.contains("readinessStatusGroup\n            modePicker"))
        XCTAssertTrue(contentView.contains("private var readinessStatusGroup: some View"))
        XCTAssertTrue(contentView.contains("helperHealthCard\n            controlOwnerCard\n            agentCoolingCard"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertTrue(settingsView.contains("SettingsToolsPanel(model: model)"))
        XCTAssertTrue(settingsTools.contains("private var menuBarDisplaySettings: some View"))
        XCTAssertTrue(settingsTools.contains("private var quickSettingsStrip: some View"))
        XCTAssertTrue(settingsTools.contains("ViewThatFits(in: .horizontal)"))
        XCTAssertTrue(settingsTools.contains("HStack(spacing: 14)"))
        XCTAssertTrue(settingsTools.contains("VStack(alignment: .leading, spacing: 8) {\n                    curveProfileSettings\n                    startupModeSettings\n                    launchAtLoginSettings\n                }"))
        XCTAssertTrue(settingsTools.contains("private var startupModeSettings: some View"))
        XCTAssertTrue(settingsTools.contains("private var curveProfileSettings: some View"))
        XCTAssertTrue(settingsTools.contains("quickSettingsStrip"))
        XCTAssertTrue(settingsTools.contains("Picker(\"Default mode\", selection: $model.startupMode)"))
        XCTAssertTrue(settingsTools.contains("Picker(\"Curve profile\", selection: $model.selectedCurveProfileID)"))
        XCTAssertTrue(settingsTools.contains("Label(\"Menu bar\", systemImage: \"menubar.rectangle\")"))
        XCTAssertTrue(settingsTools.contains("Picker(\"Menu bar\", selection: $model.menuBarDisplayMode)"))
        XCTAssertTrue(settingsTools.contains("Picker(\"Codex display\", selection: $model.codexUsageDisplayStyle)"))
        XCTAssertTrue(settingsTools.contains("ForEach(MenuBarDisplayMode.allCases)"))
        XCTAssertTrue(settingsTools.contains("ForEach(MenuBarField.allCases)"))
        XCTAssertTrue(settingsTools.contains("ForEach(CodexUsageDisplayStyle.allCases)"))
        XCTAssertTrue(settingsTools.contains("private var codexUsageDisplayControls: some View {\n        VStack(alignment: .leading, spacing: 6)"))
        XCTAssertFalse(settingsTools.contains("private var codexUsageDisplayControls: some View {\n        HStack(spacing: 8)"))
        XCTAssertTrue(settingsTools.contains(".labelsHidden()"))
        XCTAssertFalse(viftyApp.contains("MenuBarExtra {"))
        XCTAssertFalse(viftyApp.contains("MenuBarExtraLabel"))
        XCTAssertTrue(viftyApp.contains("@NSApplicationDelegateAdaptor(ViftyAppDelegate.self) private var appDelegate"))
        XCTAssertTrue(viftyApp.contains("@StateObject private var model: AppModel"))
        XCTAssertTrue(viftyApp.contains("@MainActor\n    init()"))
        XCTAssertTrue(viftyApp.contains("_model = StateObject(wrappedValue: model)"))
        XCTAssertTrue(viftyApp.contains("appDelegate.model = model"))
        XCTAssertTrue(viftyApp.contains("appDelegate.openMainWindowHandler = { openWindow(id: \"main\") }"))
        XCTAssertTrue(viftyApp.contains("model.start()"))
        XCTAssertTrue(viftyApp.contains("final class ViftyAppDelegate: NSObject, NSApplicationDelegate"))
        XCTAssertTrue(viftyApp.contains("func applicationDidFinishLaunching(_ notification: Notification)"))
        XCTAssertTrue(viftyApp.contains("statusItemController = ViftyStatusItemController("))
        XCTAssertTrue(viftyApp.contains("statusItemController?.openMainWindow = { [weak self] in"))
        XCTAssertTrue(statusItemController.contains("NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)"))
        XCTAssertFalse(statusItemController.contains("model.objectWillChange"))
        XCTAssertTrue(statusItemController.contains("updateStatusItem()"))
        XCTAssertTrue(statusItemController.contains("MenuBarTelemetryPrimePolicy.launch"))
        XCTAssertTrue(statusItemController.contains("MenuBarTelemetryPrimePolicy.popover"))
        XCTAssertTrue(statusItemController.contains("scheduleTelemetryPrimeIfNeeded()"))
        XCTAssertTrue(statusItemController.contains("private let primeScheduler = MenuBarTelemetryPrimeScheduler()"))
        XCTAssertTrue(statusItemController.contains("scheduleTelemetryPrimeIfNeeded(policy: Self.popoverPrimePolicy)"))
        XCTAssertTrue(statusItemController.contains("primeScheduler.schedule"))
        XCTAssertFalse(statusItemController.contains("private var primeTask: Task<Void, Never>?"))
        XCTAssertTrue(statusItemController.contains("model.$menuBarStatusItemPresentation"))
        XCTAssertTrue(statusItemController.contains(".removeDuplicates()"))
        XCTAssertTrue(statusItemController.contains("private var lastAppliedPresentation: MenuBarStatusItemPresentation?"))
        XCTAssertTrue(statusItemController.contains("guard presentation != lastAppliedPresentation else { return }"))
        XCTAssertTrue(statusItemController.contains("primeStatusItemUntilTelemetryResolved("))
        XCTAssertTrue(statusItemController.contains("policy.shouldAttempt("))
        XCTAssertTrue(statusItemController.contains("await model.primeMenuBarStatusItemTelemetry(maxAttempts: 1)"))
        XCTAssertTrue(statusItemController.contains("guard model.menuBarStatusItemPresentation.needsTelemetryPrime else { return }"))
        XCTAssertTrue(statusItemController.contains("await Task.yield()"))
        XCTAssertTrue(statusItemController.contains("MenuBarView(openMainWindow: { [weak self] in"))
        XCTAssertTrue(statusItemController.contains("let presentation = model.menuBarStatusItemPresentation"))
        XCTAssertTrue(menuBarPresentation.contains("enum MenuBarDisplayMode"))
        XCTAssertTrue(menuBarPresentation.contains("enum MenuBarField"))
        XCTAssertTrue(menuBarPresentation.contains("struct MenuBarStatusItemPresentation"))
        XCTAssertTrue(menuBarPresentation.contains("enum ViftyStatusItemPresentation"))
        XCTAssertFalse(statusItemController.contains("enum ViftyStatusItemPresentation"))
        XCTAssertFalse(statusItemController.contains("private static let launchPrimeAttempts = 120"))
        XCTAssertTrue(appModel.contains("allowsPlaceholderText: menuBarAllowsPlaceholderStatusItemText"))
        XCTAssertTrue(statusItemController.contains("button.title = text"))
        XCTAssertTrue(statusItemController.contains("statusItem.length = NSStatusItem.variableLength"))
        XCTAssertFalse(statusItemController.contains("button.window?.displayIfNeeded()"))
        XCTAssertFalse(statusItemController.contains("button.needsLayout = true"))
        XCTAssertFalse(statusItemController.contains("button.needsDisplay = true"))
        XCTAssertTrue(statusItemController.contains("NSImage(systemSymbolName: \"fan\""))
        XCTAssertTrue(appModel.contains("private let preferencesStore: AppPreferencesStore"))
        XCTAssertTrue(appModel.contains("private var activePollTask: Task<Void, Never>?"))
        XCTAssertTrue(appModel.contains("private let pollSchedulePolicy = PollSchedulePolicy.standard"))
        XCTAssertTrue(pollSchedulePolicy.contains("idleInterval: .seconds(10)"))
        XCTAssertTrue(pollSchedulePolicy.contains("activeInterval: .seconds(5)"))
        XCTAssertTrue(appModel.contains("backgroundPollInterval()"))
        XCTAssertTrue(appModel.contains("@Published private(set) var menuBarStatusItemPresentation = MenuBarStatusItemPresentation.placeholder"))
        XCTAssertTrue(appModel.contains("@Published private(set) var menuBarStatusItemRevision = 0"))
        XCTAssertTrue(appModel.contains("private var currentMenuBarStatusItemPresentation: MenuBarStatusItemPresentation"))
        XCTAssertTrue(appModel.contains("refreshMenuBarStatusItemIfNeeded()"))
        XCTAssertTrue(appModel.contains("private func performPollOnce() async"))
        XCTAssertTrue(appModel.contains("if let activePollTask {\n            await activePollTask.value\n            return\n        }"))
        XCTAssertFalse(appModel.contains("pollingTask = Task { [weak self]"))
        XCTAssertTrue(appModel.contains("func primeMenuBarStatusItemTelemetry("))
        XCTAssertTrue(appModel.contains("var menuBarStatusItemText: String?"))
        XCTAssertTrue(appModel.contains("var menuBarLabelNeedsTelemetryPrime: Bool"))
        XCTAssertTrue(appModel.contains("var menuBarDisplaysCodexUsage: Bool"))
        XCTAssertTrue(appModel.contains("func setMenuBarCustomField(_ field: MenuBarField, enabled: Bool)"))
        XCTAssertTrue(appModel.contains("func applyStartupModePreferenceIfNeeded() async"))
        XCTAssertTrue(appModel.contains("persistAppPreferences()"))
        XCTAssertFalse(viftyApp.contains("await model.primeMenuBarStatusItemTelemetry(maxAttempts: 5)"))
        XCTAssertFalse(appModel.contains("Task.sleep(for: .seconds(2))"))
        XCTAssertTrue(appPreferencesStore.contains("var startupMode: ModeSelection"))
        XCTAssertTrue(appPreferencesStore.contains("app-preferences.json"))
        XCTAssertTrue(appPreferencesStore.contains("legacyDefaults: UserDefaults?"))
        XCTAssertTrue(appPreferencesStore.contains(".posixPermissions: NSNumber(value: 0o700)"))
        XCTAssertTrue(appPreferencesStore.contains(".posixPermissions: NSNumber(value: 0o600)"))
        XCTAssertFalse(appModel.contains("preferences.set("))
    }

    func testLaunchAtLoginToggleIsWiredThroughSystemLoginItems() throws {
        let launchAtLogin = try read("Sources/Vifty/LaunchAtLogin.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let settingsTools = try read("Sources/Vifty/SettingsToolsPanel.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(launchAtLogin.contains("SMAppService.mainApp.status"))
        XCTAssertTrue(launchAtLogin.contains("try service.register()"))
        XCTAssertTrue(launchAtLogin.contains("try service.unregister()"))
        XCTAssertTrue(launchAtLogin.contains("SMAppService.openSystemSettingsLoginItems()"))
        XCTAssertTrue(appModel.contains("private let launchAtLoginManager: LaunchAtLoginManaging"))
        XCTAssertTrue(appModel.contains("@Published private(set) var launchAtLoginStatus: LaunchAtLoginStatus = .disabled"))
        XCTAssertTrue(appModel.contains("var launchAtLoginEnabled: Bool"))
        XCTAssertTrue(appModel.contains("func setLaunchAtLoginEnabled(_ enabled: Bool)"))
        XCTAssertTrue(appModel.contains("launchAtLoginError = \"Could not update startup item: \\(error.localizedDescription)\""))
        XCTAssertFalse(appModel.contains("UserDefaults.standard.set(launchAtLogin"))
        XCTAssertFalse(appModel.contains("preferencesStore.save(AppPreferences(\n            launchAtLogin"))
        XCTAssertTrue(settingsTools.contains("private var launchAtLoginSettings: some View"))
        XCTAssertTrue(settingsTools.contains("Label(\"Start Vifty at startup\", systemImage: \"power\")"))
        XCTAssertTrue(settingsTools.contains("Toggle(isOn: launchAtLoginBinding)"))
        XCTAssertTrue(settingsTools.contains("model.openLaunchAtLoginSettings()"))
        XCTAssertTrue(settingsTools.contains("model.refreshLaunchAtLoginStatus()"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertTrue(settingsView.contains("SettingsToolsPanel(model: model)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Start Vifty at startup\", isOn: launchAtLoginBinding)"))
        XCTAssertFalse(menuBarView.contains("model.openLaunchAtLoginSettings()"))
        XCTAssertFalse(menuBarView.contains("model.refreshLaunchAtLoginStatus()"))
    }

    func testLocalInstallerRestartsRunningAppBeforeCopyingBundle() throws {
        let installScript = try read("scripts/install-vifty.sh")
        let readme = try read("README.md")

        XCTAssertTrue(installScript.contains("QUIT_RUNNING_APP=\"${QUIT_RUNNING_APP:-1}\""))
        XCTAssertTrue(installScript.contains("WAS_RUNNING=0"))
        XCTAssertTrue(installScript.contains("/usr/bin/pgrep -x \"${APP_NAME}\""))
        XCTAssertTrue(installScript.contains("tell application id \"tech.reidar.vifty\" to quit"))
        XCTAssertTrue(installScript.contains("/usr/bin/pkill -x \"${APP_NAME}\""))
        XCTAssertTrue(installScript.contains("quit_running_app_if_needed"))
        XCTAssertTrue(installScript.contains("\"${OPEN_AFTER_INSTALL}\" == \"1\" || \"${WAS_RUNNING}\" == \"1\""))
        XCTAssertTrue(readme.contains("the installer quits and relaunches it from the newly installed bundle"))
    }

    func testLocalInstallerReportsPrivilegedHelperDaemonDrift() throws {
        let installScript = try read("scripts/install-vifty.sh")
        let readme = try read("README.md")

        XCTAssertTrue(installScript.contains("shell_quote()"))
        XCTAssertTrue(installScript.contains("CHECK_HELPER_DAEMON=\"${CHECK_HELPER_DAEMON:-1}\""))
        XCTAssertTrue(installScript.contains("HELPER_TARGET=\"${VIFTY_HELPER_TARGET:-/Library/PrivilegedHelperTools/tech.reidar.vifty.daemon}\""))
        XCTAssertTrue(installScript.contains("report_helper_daemon_status"))
        XCTAssertTrue(installScript.contains("sha256_file \"${bundled_daemon}\""))
        XCTAssertTrue(installScript.contains("sha256_file \"${HELPER_TARGET}\""))
        XCTAssertTrue(installScript.contains("repair_command=\"REPAIR_HELPER_APP=$(shell_quote \"${DEST_APP}\") make repair-helper\""))
        XCTAssertTrue(installScript.contains("Fan helper matches the installed app daemon."))
        XCTAssertTrue(installScript.contains("Fan helper daemon differs from the installed app bundle."))
        XCTAssertTrue(installScript.contains("Open Vifty and choose Reinstall Helper or Repair Helper, or run: ${repair_command}"))
        XCTAssertTrue(installScript.contains("Do that before current-build manual/agent smoke evidence."))
        XCTAssertTrue(installScript.contains("AGENT_RUN_SMOKE_READINESS_JSON=1 make agent-run-smoke-readiness-current-build"))
        XCTAssertFalse(installScript.contains("repair-vifty-helper.sh"))

        XCTAssertTrue(readme.contains("The root LaunchDaemon helper is repaired only after an explicit user-approved action, not silently replaced by the app installer"))
        XCTAssertTrue(readme.contains("performs a read-only helper-daemon hash check"))
        XCTAssertTrue(readme.contains("REPAIR_HELPER_APP=/Applications/Vifty.app make repair-helper"))
        XCTAssertTrue(readme.contains("If the installer falls back to `~/Applications`, use the exact `REPAIR_HELPER_APP=... make repair-helper` command printed by the installer so the helper is repaired from that copied app bundle."))
        XCTAssertTrue(readme.contains("before treating current-build manual or agent smoke evidence as valid"))
    }

    func testLocalInstallerRetriesSwiftPMBuildDatabaseFailuresWithIsolatedBuildPath() throws {
        let installScript = try read("scripts/install-vifty.sh")
        let readme = try read("README.md")

        XCTAssertTrue(installScript.contains("BUILD_LOG=\"$(mktemp -t vifty-install-build.XXXXXX)\""))
        XCTAssertTrue(installScript.contains("is_swiftpm_build_database_error()"))
        XCTAssertTrue(installScript.contains("build\\\\.db|build database|disk I/O error|database is locked"))
        XCTAssertTrue(installScript.contains("build_app_bundle()"))
        XCTAssertTrue(installScript.contains("else\n    build_status=$?\n  fi"))
        XCTAssertTrue(installScript.contains("if [[ -z \"${SWIFT_BUILD_PATH:-}\" ]] && is_swiftpm_build_database_error; then"))
        XCTAssertTrue(installScript.contains("fallback_build_path=\"${TMPDIR:-/tmp}/vifty-install-swiftpm-$$\""))
        XCTAssertTrue(installScript.contains("==> SwiftPM build database failed; retrying with SWIFT_BUILD_PATH=${fallback_build_path}"))
        XCTAssertTrue(installScript.contains("SWIFT_BUILD_PATH=\"${fallback_build_path}\" make app CONFIGURATION=\"${CONFIGURATION}\""))
        XCTAssertTrue(installScript.contains("build_app_bundle"))

        XCTAssertTrue(readme.contains("If SwiftPM's local `.build/build.db` becomes unhealthy, the local installer retries once with an isolated temporary `SWIFT_BUILD_PATH` before failing."))
        XCTAssertTrue(readme.contains("Set `SWIFT_BUILD_PATH` yourself when you want a stable reusable build-product path."))
    }

    func testExplicitHelperRepairScriptPreservesPrivilegedRepairBoundary() throws {
        let script = try read("scripts/repair-vifty-helper.sh")
        let makefile = try read("Makefile")
        let readme = try read("README.md")

        XCTAssertTrue(script.contains("APP_PATH=\"${VIFTY_APP:-/Applications/Vifty.app}\""))
        XCTAssertTrue(script.contains("HELPER_TARGET=\"${VIFTY_HELPER_TARGET:-/Library/PrivilegedHelperTools/tech.reidar.vifty.daemon}\""))
        XCTAssertTrue(script.contains("PLIST_TARGET=\"${VIFTY_DAEMON_PLIST_TARGET:-/Library/LaunchDaemons/tech.reidar.vifty.daemon.plist}\""))
        XCTAssertTrue(script.contains("DRY_RUN=0"))
        XCTAssertTrue(script.contains("--dry-run"))
        XCTAssertTrue(script.contains("This is an explicit operator action and may prompt for administrator approval."))
        XCTAssertTrue(script.contains("It does not request cooling or write fan state directly."))
        XCTAssertTrue(script.contains("do shell script \"/bin/bash \" & quoted form of \"${ADMIN_SCRIPT_PATH}\" with administrator privileges"))
        XCTAssertTrue(script.contains("launchctl bootout system $(shell_quote \"$PLIST_TARGET\") 2>/dev/null || true"))
        XCTAssertTrue(script.contains("helper_tmp=\"\\$(mktemp $(shell_quote \"${HELPER_TARGET}.XXXXXX\"))\""))
        XCTAssertTrue(script.contains("plist_tmp=\"\\$(mktemp $(shell_quote \"${PLIST_TARGET}.XXXXXX\"))\""))
        XCTAssertTrue(script.contains("trap 'rm -f \"\\$helper_tmp\" \"\\$plist_tmp\"' EXIT"))
        XCTAssertTrue(script.contains("chmod 755 \"\\$helper_tmp\""))
        XCTAssertTrue(script.contains("chown root:wheel \"\\$helper_tmp\""))
        XCTAssertTrue(script.contains("chmod 644 \"\\$plist_tmp\""))
        XCTAssertTrue(script.contains("chown root:wheel \"\\$plist_tmp\""))
        XCTAssertTrue(script.contains("xattr -cr \"\\$helper_tmp\" \"\\$plist_tmp\" 2>/dev/null || true"))
        XCTAssertTrue(script.contains("/usr/libexec/PlistBuddy -c 'Delete :BundleProgram' \"\\$plist_tmp\""))
        XCTAssertTrue(script.contains("mv -f \"\\$helper_tmp\" $(shell_quote \"$HELPER_TARGET\")"))
        XCTAssertTrue(script.contains("mv -f \"\\$plist_tmp\" $(shell_quote \"$PLIST_TARGET\")"))
        XCTAssertTrue(script.contains("chmod 600 \"\\$log_path\""))
        XCTAssertTrue(script.contains("chown root:wheel \"\\$log_path\""))
        XCTAssertTrue(script.contains("launchctl bootstrap system $(shell_quote \"$PLIST_TARGET\")"))
        XCTAssertTrue(script.contains("launchctl kickstart -k $(shell_quote \"$SERVICE_TARGET\")"))
        XCTAssertTrue(script.contains("installed helper matches the app bundle."))
        XCTAssertTrue(script.contains("\"$VIFTYCTL\" diagnose --json"))
        XCTAssertFalse(script.contains("ViftyHelper setFixed"))
        XCTAssertFalse(script.contains("ViftyHelper auto"))

        XCTAssertTrue(makefile.contains("repair-helper: ## Explicitly repair the installed privileged helper"))
        XCTAssertTrue(makefile.contains("./scripts/repair-vifty-helper.sh --app \"$(REPAIR_HELPER_APP)\""))
        XCTAssertTrue(readme.contains("Source checkouts also provide `make repair-helper`"))
        XCTAssertTrue(readme.contains("After repair, the script compares the installed helper hash with the app bundle and prints read-only `viftyctl diagnose` recovery fields"))
    }

    func testAppWindowCurveProfileSelectorUsesSavedProfiles() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let settingsTools = try read("Sources/Vifty/SettingsToolsPanel.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertFalse(menuBarView.contains("@State private var selectedMenuCurveProfileID: UUID?"))
        XCTAssertFalse(menuBarView.contains("Picker(\"Curve profile\", selection: $selectedMenuCurveProfileID)"))
        XCTAssertTrue(settingsTools.contains("private var curveProfileSettings: some View"))
        XCTAssertFalse(contentView.contains("if !model.savedProfiles.isEmpty"))
        XCTAssertTrue(settingsTools.contains("Picker(\"Curve profile\", selection: $model.selectedCurveProfileID)"))
        XCTAssertTrue(settingsTools.contains("ForEach(model.savedProfiles)"))
        XCTAssertTrue(settingsTools.contains("_ = model.selectCurveProfile(id: newID)"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertTrue(settingsView.contains("SettingsToolsPanel(model: model)"))
        XCTAssertTrue(appModel.contains("func selectCurveProfile(id profileID: CurveProfile.ID?) -> Bool"))
        XCTAssertTrue(appModel.contains("@Published var selectedCurveProfileID: CurveProfile.ID?"))
        XCTAssertTrue(appModel.contains("selectedMode = .curve\n        loadProfile(profile)"))
    }

    func testMenuBarHighTemperatureAttentionIsWired() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("static let highTemperatureAttentionThreshold = 90.0"))
        XCTAssertTrue(appModel.contains("var temperatureAttentionSummary: String?"))
        XCTAssertTrue(appModel.contains("return sensor.celsius >= Self.highTemperatureAttentionThreshold ? \"High temp\" : nil"))
        XCTAssertTrue(appModel.contains("var fanWriteBlockedWhileHotSummary: String?"))
        XCTAssertTrue(appModel.contains("var fanWriteBlockedWhileHotRecoverySuggestion: String?"))
        XCTAssertTrue(appModel.contains("parts.append(\"Fan writes blocked\")"))
        XCTAssertTrue(menuBarView.contains("if let fanWriteBlockedWhileHotSummary = model.fanWriteBlockedWhileHotSummary"))
        XCTAssertTrue(menuBarView.contains("if let recovery = model.fanWriteBlockedWhileHotRecoverySuggestion"))
        XCTAssertTrue(menuBarView.contains("if let temperatureAttentionSummary = model.temperatureAttentionSummary"))
        XCTAssertTrue(menuBarView.contains("Label(temperatureAttentionSummary, systemImage: \"thermometer.high\")"))
        XCTAssertTrue(menuBarView.contains(".foregroundStyle(.orange)"))
    }

    func testMainWindowHotBlockedHelperAttentionIsWired() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("if let fanWriteBlockedWhileHotSummary = model.fanWriteBlockedWhileHotSummary"))
        XCTAssertTrue(contentView.contains("Text(fanWriteBlockedWhileHotSummary)"))
        XCTAssertTrue(contentView.contains("if let recovery = model.fanWriteBlockedWhileHotRecoverySuggestion"))
        XCTAssertTrue(contentView.contains("Text(recovery)"))
        XCTAssertTrue(contentView.contains(".background(Color.orange.opacity(0.12), in: RoundedRectangle(cornerRadius: 8))"))
    }

    func testMainWindowManualPendingHelperAttentionIsWired() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var manualControlAttentionSummary: String?"))
        XCTAssertTrue(appModel.contains("request pending · fan writes blocked"))
        XCTAssertTrue(appModel.contains("Use \\(autoRestoreActionTitle) to stop retries; copy support evidence if repair does not clear it."))
        XCTAssertTrue(appModel.contains("var modeSelectionActionRestoresAuto: Bool"))
        XCTAssertTrue(appModel.contains("selectedMode == .auto || manualControlAttentionSummary != nil"))
        XCTAssertTrue(appModel.contains("var modeSelectionActionDisabled: Bool"))
        XCTAssertTrue(appModel.contains("var helperSupportEvidenceContext: HelperSupportEvidenceContext"))
        XCTAssertTrue(appModel.contains("hotFanWrites="))
        XCTAssertTrue(appModel.contains("controlOwner="))
        XCTAssertTrue(contentView.contains("if let manualControlAttentionSummary = model.manualControlAttentionSummary"))
        XCTAssertTrue(contentView.contains("hourglass.badge.exclamationmark"))
        XCTAssertTrue(contentView.contains("model.performModeSelectionAction()"))
        XCTAssertTrue(contentView.contains(".disabled(model.modeSelectionActionDisabled)"))
        XCTAssertTrue(contentView.contains("if let recovery = model.manualControlAttentionRecoverySuggestion"))
        XCTAssertTrue(contentView.contains("Text(recovery)"))
    }

    func testFixedRPMPerFanEditorShowsFanSpecificRanges() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("Toggle(\"Per-fan targets\", isOn: $model.usePerFanFixedRPM)"))
        XCTAssertTrue(contentView.contains(".accessibilityLabel(\"Per-fan fixed RPM targets\")"))
        XCTAssertTrue(contentView.contains(".accessibilityHint(\"Set separate fixed RPM targets for each fan.\")"))
        XCTAssertTrue(contentView.contains("let controllableFans = fans.filter(\\.controllable)"))
        XCTAssertTrue(contentView.contains("if controllableFans.count > 1"))
        XCTAssertTrue(contentView.contains("model.ensureFixedFanTargets(for: controllableFans)"))
        XCTAssertTrue(contentView.contains("let targetRPM = model.fixedFanTargetRPM(for: fan)"))
        XCTAssertTrue(contentView.contains("let targetPercent = model.fixedFanTargetPercent(for: fan)"))
        XCTAssertTrue(contentView.contains("Text(\"\\(targetRPM) RPM · \\(targetPercent)%\")"))
        XCTAssertFalse(contentView.contains("Text(\"Range \\(fan.minimumRPM)-\\(fan.maximumRPM) RPM\")"))
        XCTAssertTrue(contentView.contains("in: Double(fan.minimumRPM)...Double(fan.maximumRPM)"))
        XCTAssertTrue(contentView.contains("model.setFixedFanRPM(Int(value.rounded()), for: fan, persist: false)"))
        XCTAssertTrue(contentView.contains("model.commitFixedFanTargetsAndApply()"))
        XCTAssertFalse(contentView.contains("model.setFixedFanRPM(Int(value.rounded()), for: fan)\n                                    model.applyModeSelection()"))
        XCTAssertTrue(contentView.contains(".help(\"\\(fan.name) fixed target. Range \\(fan.minimumRPM)-\\(fan.maximumRPM) RPM; currently \\(targetPercent)% of that fan's range.\")"))
        XCTAssertTrue(contentView.contains(".accessibilityLabel(\"\\(fan.name) fixed RPM target\")"))
        XCTAssertTrue(contentView.contains(".accessibilityValue(\"\\(targetRPM) RPM, \\(targetPercent)%\")"))
        XCTAssertTrue(contentView.contains(".accessibilityHint(\"\\(fan.name) target is clamped to \\(fan.minimumRPM)-\\(fan.maximumRPM) RPM.\")"))
        XCTAssertTrue(contentView.contains(".accessibilityLabel(\"Fixed RPM target\")"))
        XCTAssertTrue(contentView.contains(".accessibilityHint(\"Sets one fixed target for every controllable fan.\")"))
        XCTAssertTrue(contentView.contains("onEditingChanged: { isEditing in\n                        guard !isEditing else { return }\n                        model.applyModeSelection()"))
        XCTAssertTrue(contentView.contains("private struct CompactFanOverrideEditor: View"))
        XCTAssertTrue(contentView.contains("Stepper(value: startBinding, in: fan.minimumRPM...fan.maximumRPM, step: 50)"))
        XCTAssertTrue(contentView.contains("Stepper(value: midBinding, in: fan.minimumRPM...fan.maximumRPM, step: 50)"))
        XCTAssertTrue(contentView.contains("Stepper(value: maxBinding, in: fan.minimumRPM...fan.maximumRPM, step: 50)"))
        XCTAssertFalse(contentView.contains("Text(\"Fan \\(fan.id): \\(fan.name)\")"))
    }

    func testCurveEditorShowsDraggableChartForActualFanCurves() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let chartView = try read("Sources/Vifty/FanCurveChartEditor.swift")

        XCTAssertTrue(contentView.contains("FanCurveChartEditor("))
        XCTAssertTrue(contentView.contains("startTemp: $model.curveStartTemp"))
        XCTAssertTrue(contentView.contains("fanOverrides: model.fanOverrides"))
        XCTAssertTrue(chartView.contains("struct FanCurveChartEditor: View"))
        XCTAssertFalse(contentView.contains("private struct FanCurveChartEditor: View"))
        XCTAssertTrue(chartView.contains("private let chartHeight: CGFloat = 272"))
        XCTAssertTrue(chartView.contains(".frame(height: chartHeight)"))
        XCTAssertFalse(contentView.contains(".frame(height: 184)"))
        XCTAssertTrue(chartView.contains("private var liveCurveTargetText: String?"))
        XCTAssertTrue(chartView.contains("Text(liveCurveTargetText)"))
        XCTAssertTrue(chartView.contains("let targetRPM = targetRPM(at: liveTemperature, points: basePoints)"))
        XCTAssertTrue(chartView.contains("return \"Live \\(Int(liveTemperature.rounded())) C -> Base \\(formattedRPM(targetRPM))\""))
        let chartGeometry = try read("Sources/Vifty/FanCurveChartGeometry.swift")
        XCTAssertTrue(chartGeometry.contains("struct FanCurveChartGeometry"))
        XCTAssertTrue(chartGeometry.contains("func targetRPM(at temperature: Double, points: [FanCurveChartValue]) -> Int"))
        XCTAssertTrue(chartView.contains("private var chartGeometry: FanCurveChartGeometry"))
        XCTAssertFalse(contentView.contains("Text(\"Live: \\(sensor.celsius"))
        XCTAssertTrue(chartView.contains("DragGesture(minimumDistance: 0)"))
        XCTAssertTrue(chartView.contains("setCurvePoint(point, from: value.location, in: geometry.size)"))
        XCTAssertTrue(chartView.contains("private var fanCurveSeries: [FanCurveChartSeries]"))
        XCTAssertTrue(chartView.contains("guard usePerFanOverrides else { return [] }"))
        XCTAssertTrue(chartView.contains("FanCurveChartSeries(name: fan.name"))
        XCTAssertFalse(contentView.contains("label: fanCurveLabel(for: fan)"))
        XCTAssertFalse(contentView.contains("labelOffsetIndex: offset"))
        XCTAssertTrue(chartView.contains("drawCurve(series.points, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointValueLabels(for: series, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointValueLabels(for: baseCurveValueLabelSeries, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("private var baseCurveValueLabelSeries: FanCurveChartSeries"))
        XCTAssertFalse(contentView.contains("labelOffsetIndex: fanCurveSeries.count"))
        XCTAssertFalse(contentView.contains("if fanCurveSeries.isEmpty {"))
        XCTAssertFalse(contentView.contains("private func baseCurvePointValueLabels(in size: CGSize) -> some View"))
        XCTAssertFalse(contentView.contains("private func baseLabelPosition(for point: FanCurveChartPoint, pointIndex: Int, in size: CGSize) -> CGPoint"))
        XCTAssertFalse(contentView.contains("private func labelPosition(for point: FanCurveChartPoint, pointIndex: Int, seriesIndex: Int, in size: CGSize) -> CGPoint"))
        XCTAssertTrue(chartView.contains("chartAxisLabels(in: geometry.size)"))
        XCTAssertTrue(chartView.contains("chartAxisUnitLabels(in: geometry.size)"))
        XCTAssertTrue(chartView.contains("@State private var activeChartPoint: CurveChartPointKind?"))
        XCTAssertTrue(chartView.contains("if let activePoint = activeBasePoint"))
        XCTAssertTrue(chartView.contains("curvePointAxisGuides(for: [activePoint], color: .accentColor, in: geometry.size)"))
        XCTAssertTrue(chartView.contains("curvePointAxisValueLabels(for: [activePoint], color: .accentColor, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointAxisGuides(for: basePoints, color: .accentColor, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointAxisValueLabels(for: basePoints, color: .accentColor, in: geometry.size)"))
        XCTAssertTrue(chartView.contains("CurveChartAxisValue(text: rpmTickLabel(Int(rpmUpper.rounded()))"))
        XCTAssertTrue(chartView.contains("CurveChartAxisValue(text: temperatureTickLabel(Int(tempRange.upperBound.rounded()))"))
        XCTAssertTrue(chartView.contains("rpmTickLabel(Int(rpmUpper.rounded()))"))
        XCTAssertTrue(chartView.contains("temperatureTickLabel(Int(tempRange.upperBound.rounded()))"))
        XCTAssertTrue(chartView.contains("CurveChartAxisTitle(text: \"RPM\")"))
        XCTAssertTrue(chartView.contains("CurveChartAxisTitle(text: \"Temp C\")"))
        XCTAssertTrue(chartView.contains("CurveChartAxisReadout(text: point.rpmText, color: color"))
        XCTAssertTrue(chartView.contains("CurveChartAxisReadout(text: point.temperatureText, color: color"))
        XCTAssertTrue(chartView.contains("private func rpmAxisReadoutPosition(near pointPosition: CGPoint, pointIndex: Int, in rect: CGRect) -> CGPoint"))
        XCTAssertTrue(chartView.contains("private func temperatureAxisReadoutPosition(near pointPosition: CGPoint, pointIndex: Int, in rect: CGRect) -> CGPoint"))
        XCTAssertTrue(chartView.contains("private struct CurveChartAxisTitle: View"))
        XCTAssertTrue(chartView.contains("private struct CurveChartAxisReadout: View"))
        XCTAssertFalse(contentView.contains("private func fanCurveLabel(for fan: Fan) -> String"))
        XCTAssertTrue(chartView.contains("liveTemperatureLabel(temperature, in: size)"))
        XCTAssertTrue(chartView.contains("ChartHandle("))
        XCTAssertTrue(chartView.contains("label: point.label"))
        XCTAssertTrue(chartView.contains("valueText: value.chartValueText"))
        XCTAssertTrue(chartView.contains("showsValueLabel: activeChartPoint == point"))
        XCTAssertTrue(chartView.contains("valueLabelOffsetY: activeHandleLabelOffsetY(for: value)"))
        XCTAssertTrue(chartView.contains("onHoverChanged: { isHovering in"))
        XCTAssertTrue(chartView.contains("activeChartPoint = isHovering ? point : nil"))
        XCTAssertTrue(chartView.contains("activeChartPoint = point"))
        XCTAssertTrue(chartView.contains("setCurvePoint(point, from: value.location, in: geometry.size)"))
        XCTAssertTrue(chartView.contains(".onEnded { _ in activeChartPoint = nil }"))
        XCTAssertFalse(contentView.contains("valueLabelOffsetY: valueLabelOffsetY(for: value)"))
        XCTAssertTrue(chartView.contains("accessibilityValueText: value.accessibilityValueText"))
        XCTAssertFalse(contentView.contains("private struct ChartHandleValueLabel: View"))
        XCTAssertTrue(chartView.contains("private struct CurveChartHandleValueLabel: View"))
        XCTAssertTrue(chartView.contains("Text(valueText)"))
        XCTAssertTrue(chartView.contains("private func activeHandleLabelOffsetY(for point: FanCurveChartPoint) -> CGFloat"))
        XCTAssertFalse(contentView.contains("private func valueLabelOffsetY(for point: FanCurveChartPoint) -> CGFloat"))
        XCTAssertTrue(chartView.contains("Text(label)"))
        XCTAssertTrue(chartView.contains(".help(\"\\(label): \\(Int(temperature.rounded())) C · \\(Int(rpm.rounded()).formatted(.number.grouping(.automatic))) RPM\")"))
        XCTAssertTrue(chartView.contains("value.chartValueText"))
        XCTAssertFalse(contentView.contains("private struct CurveChartSeriesPointLabel: View"))
        XCTAssertFalse(contentView.contains("curvePointValueLabels(for: series, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointValueLabels(for: baseCurveValueLabelSeries, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("Text(point.chartValueText)"))
        XCTAssertFalse(contentView.contains("Text(\"\\(seriesLabel) \\(point.label)\")"))
        XCTAssertTrue(chartView.contains("private var curvePointSummaryStrip: some View"))
        XCTAssertTrue(chartView.contains("ForEach(basePoints) { point in"))
        XCTAssertTrue(chartView.contains("CurveChartPointSummaryChip(point: point)"))
        XCTAssertTrue(chartView.contains("private struct CurveChartPointSummaryChip: View"))
        XCTAssertTrue(chartView.contains("if !fanCurveSeries.isEmpty"))
        XCTAssertTrue(chartView.contains("chartLegendSwatch(.accentColor, label: \"Base\")"))
        XCTAssertTrue(chartView.contains("var chartValueText: String"))
        XCTAssertTrue(chartView.contains("var temperatureText: String"))
        XCTAssertTrue(chartView.contains("var rpmText: String"))
        XCTAssertTrue(chartView.contains("var accessibilityValueText: String"))
        XCTAssertTrue(chartView.contains(".accessibilityValue(accessibilityValueText)"))
        XCTAssertTrue(chartView.contains(".accessibilityValue(point.accessibilityValueText)"))
        XCTAssertTrue(chartView.contains("private struct CurveChartAxisValue: View"))
        XCTAssertTrue(contentView.contains("DisclosureGroup(\"Exact points\")"))
        XCTAssertTrue(contentView.contains("CurvePointEditor(title: \"Start\""))
        XCTAssertFalse(contentView.contains("import Charts"))
    }

    func testMainWindowNotificationSettingsAreWired() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let settingsTools = try read("Sources/Vifty/SettingsToolsPanel.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let notifications = try read("Sources/Vifty/LocalNotifications.swift")
        let notificationHistory = try read("Sources/Vifty/LocalNotificationHistoryStore.swift")

        XCTAssertTrue(settingsTools.contains("Label(\"Notifications\", systemImage: \"bell\")"))
        XCTAssertTrue(settingsTools.contains("Toggle(\"Helper failure\", isOn: $model.notificationSettings.helperFailure)"))
        XCTAssertTrue(settingsTools.contains("Toggle(\"High thermal pressure\", isOn: $model.notificationSettings.elevatedThermalPressure)"))
        XCTAssertTrue(settingsTools.contains("Toggle(\"Auto restore failure\", isOn: $model.notificationSettings.autoRestoreFailure)"))
        XCTAssertTrue(settingsTools.contains("Toggle(\"Plugged-in battery drain\", isOn: $model.notificationSettings.pluggedInBatteryDrain)"))
        XCTAssertTrue(settingsTools.contains("Toggle(\"Agent cooling attention\", isOn: $model.notificationSettings.agentCoolingAttention)"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertTrue(settingsView.contains("SettingsToolsPanel(model: model)"))
        XCTAssertFalse(menuBarView.contains("Label(\"Notifications\", systemImage: \"bell\")"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Helper failure\", isOn: $model.notificationSettings.helperFailure)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"High thermal pressure\", isOn: $model.notificationSettings.elevatedThermalPressure)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Auto restore failure\", isOn: $model.notificationSettings.autoRestoreFailure)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Plugged-in battery drain\", isOn: $model.notificationSettings.pluggedInBatteryDrain)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Agent cooling attention\", isOn: $model.notificationSettings.agentCoolingAttention)"))
        XCTAssertTrue(appModel.contains("notificationMinimumInterval: TimeInterval = 30 * 60"))
        XCTAssertTrue(appModel.contains("notificationTransitionState.shouldNotify"))
        XCTAssertTrue(appModel.contains("notificationHistoryStore.isCoolingDown"))
        XCTAssertTrue(appModel.contains("sustainedThermalPressureInterval: TimeInterval = 60"))
        XCTAssertTrue(notifications.contains("UNUserNotificationCenter"))
        XCTAssertTrue(notifications.contains("identifier: notification.requestIdentifier"))
        XCTAssertTrue(notifications.contains("removeDeliveredNotifications(withIdentifiers:"))
        XCTAssertTrue(notifications.contains("removePendingNotificationRequests(withIdentifiers:"))
        XCTAssertFalse(notifications.contains("UUID().uuidString"))
        XCTAssertTrue(notificationHistory.contains("notification-history.json"))
        XCTAssertTrue(notificationHistory.contains("0o700"))
        XCTAssertTrue(notificationHistory.contains("0o600"))
        XCTAssertFalse(notifications.contains("content.sound = .default"))
        XCTAssertTrue(notifications.contains("XCTestConfigurationFilePath"))
        XCTAssertTrue(notifications.contains("processName == \"xctest\""))
        XCTAssertTrue(notifications.contains("static let disabled = LocalNotificationSettings()"))
    }

    func testGlobalAutoActionsUseContextualRequestCopy() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var autoRestoreActionTitle: String"))
        XCTAssertTrue(appModel.contains("var modeSelectionActionTitle: String"))
        XCTAssertTrue(appModel.contains("helperWritePathBlockedSummary == nil ? \"Auto\" : \"Request Auto\""))
        XCTAssertTrue(appModel.contains("Request Auto restore; the write cannot be confirmed until the helper responds"))
        XCTAssertTrue(contentView.contains("Label(model.modeSelectionActionTitle"))
        XCTAssertTrue(contentView.contains(".help(model.modeSelectionActionHelp)"))
        XCTAssertFalse(contentView.contains("Label(\"Apply\""))
        XCTAssertTrue(menuBarView.contains("Button(model.autoRestoreActionTitle)"))
        XCTAssertTrue(menuBarView.contains(".help(model.autoRestoreActionHelp)"))
        XCTAssertFalse(menuBarView.contains("Button(\"Auto\")"))
    }

    private func read(_ relativePath: String) throws -> String {
        let url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent(relativePath)
        return try String(contentsOf: url, encoding: .utf8)
    }
}
