import Foundation
import XCTest

final class AppSourceRegressionTests: XCTestCase {
    func testAppOwnsTheOnlyProductionPollingStart() throws {
        let app = try read("Sources/Vifty/ViftyApp.swift")
        let content = try read("Sources/Vifty/ContentView.swift")
        let menu = try read("Sources/Vifty/MenuBarView.swift")
        let status = try read("Sources/Vifty/ViftyStatusItemController.swift")

        XCTAssertEqual(app.components(separatedBy: "model.start()").count - 1, 1)
        XCTAssertFalse(content.contains("model.start()"))
        XCTAssertFalse(menu.contains("model.start()"))
        XCTAssertFalse(status.contains("model.start()"))
    }

    func testExactCurvePointSlidersExposeDistinctUnitsAndHints() throws {
        let fanControlPanel = try read("Sources/Vifty/FanControlPanel.swift")

        XCTAssertTrue(fanControlPanel.contains("CurvePointEditor(title: \"Start\""))
        XCTAssertTrue(fanControlPanel.contains("CurvePointEditor(title: \"Ramp\""))
        XCTAssertTrue(fanControlPanel.contains("CurvePointEditor(title: \"High\""))
        XCTAssertTrue(fanControlPanel.contains("TemperatureDisplayFormatter.whole(temp)"))
        XCTAssertFalse(fanControlPanel.contains("\\(Int(temp.rounded())) C ->"))
        XCTAssertTrue(fanControlPanel.contains(".accessibilityLabel(\"\\(title) temperature\")"))
        XCTAssertTrue(fanControlPanel.contains(".accessibilityValue(\"\\(Int(temp.rounded())) degrees Celsius\")"))
        XCTAssertTrue(fanControlPanel.contains(".accessibilityHint(\"Sets the \\(title.lowercased()) curve temperature.\")"))
        XCTAssertTrue(fanControlPanel.contains(".accessibilityLabel(\"\\(title) RPM\")"))
        XCTAssertTrue(fanControlPanel.contains(".accessibilityValue(\"\\(Int(rpm.rounded())) RPM\")"))
        XCTAssertTrue(fanControlPanel.contains(".accessibilityHint(\"Sets the \\(title.lowercased()) curve fan speed.\")"))
    }

    func testChartPresentationDoesNotPublishUnusedPlotRange() throws {
        let presentation = try read("Sources/Vifty/FanCurveChartPresentation.swift")
        let chartEditor = try read("Sources/Vifty/FanCurveChartEditor.swift")

        XCTAssertFalse(presentation.contains("plotRPMRange"))
        XCTAssertTrue(chartEditor.contains("private var chartRPMRange: ClosedRange<Double>"))
        XCTAssertTrue(chartEditor.contains("includeFanRanges: usePerFanOverrides"))
    }

    func testExtractedSensorViewsUseEffectiveFallbackWhileKeepingRawDraftBinding() throws {
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let fanControlPanel = try read("Sources/Vifty/FanControlPanel.swift")
        let telemetryPanel = try read("Sources/Vifty/TelemetryEvidencePanel.swift")

        XCTAssertTrue(appModel.contains("var effectiveSelectedSensorID: String?"))
        XCTAssertTrue(contentView.contains("selectedSensorID: $model.selectedSensorID"))
        XCTAssertTrue(contentView.contains("effectiveSensor: model.selectedSensor"))
        XCTAssertTrue(contentView.contains("effectiveSensorID: model.effectiveSelectedSensorID"))
        XCTAssertTrue(fanControlPanel.contains("let effectiveSensor: TemperatureSensor?"))
        XCTAssertTrue(fanControlPanel.contains("let effectiveSensorID: String?"))
        XCTAssertTrue(fanControlPanel.contains("selection: displayedSensorSelection"))
        XCTAssertTrue(fanControlPanel.contains("liveTemperature: effectiveSensor?.celsius"))
        XCTAssertTrue(telemetryPanel.contains("let effectiveSensorID: String?"))
        XCTAssertTrue(telemetryPanel.contains("selectedSensorID: effectiveSensorID"))
    }

    func testMainWindowComposesDedicatedSurfaceViews() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("MainWindowHeader("))
        XCTAssertTrue(contentView.contains("ReadinessModePanel("))
        XCTAssertTrue(contentView.contains("FanControlPanel("))
        XCTAssertTrue(contentView.contains("TelemetryEvidencePanel("))
        XCTAssertFalse(contentView.contains("private struct TelemetryOverviewPanel"))
        XCTAssertFalse(contentView.contains("private struct FanRow"))
        XCTAssertFalse(contentView.contains("private struct SensorRow"))
    }

    func testManualControlsUseDraftApplySemantics() throws {
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let readinessPanel = try read("Sources/Vifty/ReadinessModePanel.swift")
        let controlSessionCard = try read("Sources/Vifty/ControlSessionCard.swift")

        XCTAssertTrue(appModel.contains("var currentFanControlDraft: FanControlDraft"))
        XCTAssertTrue(appModel.contains("var hasPendingFanControlChanges: Bool"))
        XCTAssertTrue(appModel.contains("@Published private(set) var fanControlApplyState"))
        XCTAssertTrue(appModel.contains("var controlSessionPresentation: ControlSessionPresentation"))
        XCTAssertTrue(appModel.contains("func markFanControlDraftPending()"))
        XCTAssertTrue(appModel.contains("func applyPendingFanControl()"))
        XCTAssertTrue(readinessPanel.contains("Text(\"Auto\").tag(ModeSelection.auto)"))
        XCTAssertTrue(readinessPanel.contains("Text(\"Fixed RPM\").tag(ModeSelection.fixed)"))
        XCTAssertTrue(readinessPanel.contains("Text(\"Temperature Curve\").tag(ModeSelection.curve)"))
        XCTAssertTrue(readinessPanel.contains("if selectedMode != .auto"))
        XCTAssertTrue(controlSessionCard.contains("Label(presentation.primaryActionTitle"))
        XCTAssertFalse(readinessPanel.contains("applyModeSelection"))
    }

    func testDaemonReadOnlySnapshotsUseShortCacheButFanWritesClearIt() throws {
        let daemon = try read("Sources/ViftyDaemon/main.swift")

        XCTAssertTrue(daemon.contains("private let snapshotCacheTTL: TimeInterval = 1"))
        XCTAssertTrue(daemon.contains("private let snapshotCacheLock = NSLock()"))
        XCTAssertTrue(daemon.contains("private var cachedSnapshot: (capturedAt: Date, snapshot: HardwareSnapshot)?"))
        XCTAssertTrue(daemon.contains("if let cached = cachedSnapshotIfFresh(now: now)"))
        XCTAssertTrue(daemon.contains("storeSnapshotCache(snapshot, capturedAt: now)"))
        XCTAssertTrue(daemon.contains("private func clearSnapshotCache()"))
        XCTAssertTrue(daemon.contains("Task {\n            defer { clearSnapshotCache() }\n            do {\n                let status = try await agentControl.prepare(decoded)"))
        XCTAssertTrue(daemon.contains("Task {\n            defer { clearSnapshotCache() }\n            do {\n                let status = try await agentControl.restoreAuto(reason: reason)"))
        XCTAssertTrue(daemon.contains("Task {\n            defer { clearSnapshotCache() }\n            let status = await agentControl.status()"))
        XCTAssertTrue(daemon.contains("defer { clearSnapshotCache() }\n        do {\n            let fan = try resolveWritableFan(fanID: fanID)"))
        XCTAssertTrue(daemon.contains("private func resolveWritableFan(fanID: Int) throws -> Fan"))
        XCTAssertTrue(daemon.contains("let snapshot = try hardware.localSnapshot()"))
        XCTAssertTrue(daemon.contains("snapshot.fans.first(where: { $0.id == fanID })"))
        XCTAssertTrue(daemon.contains("Fan \\(fanID) is not present in daemon hardware telemetry; refusing privileged fan write."))
        XCTAssertTrue(daemon.contains("throw ViftyError.noControllableFans"))
        XCTAssertTrue(daemon.contains("try LocalFanHelperClient().apply(FanCommand(fanID: fanID, mode: .fixedRPM(rpm)), fan: fan)\n                reply(true, nil)"))
        XCTAssertTrue(daemon.contains("try LocalFanHelperClient().restoreAuto(fan: fan)\n            let agentControl = self.agentControl"))
        XCTAssertFalse(daemon.contains("try LocalFanHelperClient().apply(FanCommand(fanID: fanID, mode: .fixedRPM(rpm)), fan: fan)\n                clearSnapshotCache()"))
        XCTAssertFalse(daemon.contains("try LocalFanHelperClient().restoreAuto(fan: fan)\n            clearSnapshotCache()"))
        XCTAssertFalse(daemon.contains("currentRPM: rpm"))
        XCTAssertFalse(daemon.contains("currentRPM: minimumRPM"))
        XCTAssertFalse(daemon.contains("minimumRPM: minimumRPM"))
        XCTAssertFalse(daemon.contains("maximumRPM: maximumRPM"))
        XCTAssertFalse(daemon.contains("controllable: true"))
    }

    func testMenuBarHelperRecoveryRoutesToTheMainWindow() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let presentation = try read("Sources/Vifty/MenuBarPanelPresentation.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var menuBarPanelPresentation: MenuBarPanelPresentation"))
        XCTAssertTrue(menuBarView.contains("let presentation = model.menuBarPanelPresentation"))
        XCTAssertTrue(menuBarView.contains("MenuBarStatusSummary(presentation: presentation)"))
        XCTAssertTrue(menuBarView.contains("perform(presentation.primaryAction)"))
        XCTAssertTrue(presentation.contains("primaryAction: .openMainWindow"))
        XCTAssertTrue(presentation.contains("primaryActionTitle: \"Open Vifty\""))
        XCTAssertFalse(menuBarView.contains("DaemonInstaller"))
        XCTAssertFalse(menuBarView.contains("HelperDiagnosticsSupport"))
        XCTAssertFalse(menuBarView.contains("model.restoreAuto()"))
    }

    func testOperatorSurfacesUseFilteredLastError() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let header = try read("Sources/Vifty/MainWindowHeader.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var visibleLastError: String?"))
        XCTAssertTrue(appModel.contains("lastErrorIsCoveredByHelperRecovery"))
        XCTAssertTrue(appModel.contains("private var menuBarPanelAttentionText: String?"))
        XCTAssertTrue(menuBarView.contains("MenuBarAttentionRow(text: attentionText)"))
        XCTAssertTrue(header.contains("if let visibleError"))
        XCTAssertFalse(menuBarView.contains("model.lastError"))
        XCTAssertFalse(header.contains("lastError"))
    }

    func testTerminationFailsClosedWhenAppModelIsUnavailable() throws {
        let app = try read("Sources/Vifty/ViftyApp.swift")

        XCTAssertTrue(app.contains("guard let model else { return .terminateCancel }"))
        XCTAssertFalse(app.contains("guard let model else { return .terminateNow }"))
    }

    func testWindowAndOperatorSurfacesUseSemanticMacOSPolish() throws {
        let app = try read("Sources/Vifty/ViftyApp.swift")
        let header = try read("Sources/Vifty/MainWindowHeader.swift")
        let sessionCard = try read("Sources/Vifty/ControlSessionCard.swift")
        let fanRow = try read("Sources/Vifty/FanStatusRow.swift")
        let sensorList = try read("Sources/Vifty/SensorListView.swift")
        let telemetryPanel = try read("Sources/Vifty/TelemetryEvidencePanel.swift")
        let chartEditor = try read("Sources/Vifty/FanCurveChartEditor.swift")
        let readinessPanel = try read("Sources/Vifty/ReadinessModePanel.swift")

        XCTAssertTrue(app.contains("Window(\"Vifty\", id: \"main\")"))
        XCTAssertTrue(app.contains(".defaultSize(width: 1180, height: 820)"))
        XCTAssertTrue(app.contains(".windowResizability(.contentMinSize)"))
        XCTAssertFalse(app.contains("WindowGroup"))
        XCTAssertTrue(header.contains(".lineLimit(1)"))
        XCTAssertTrue(readinessPanel.contains("Picker(selection: $selectedMode)"))
        XCTAssertFalse(readinessPanel.contains("Picker(\"Mode\", selection: $selectedMode)"))
        XCTAssertTrue(readinessPanel.contains(".accessibilityLabel(\"Mode\")"))

        for source in [sessionCard, fanRow, sensorList, telemetryPanel, chartEditor] {
            XCTAssertTrue(source.contains(".background(.regularMaterial, in: RoundedRectangle(cornerRadius: 8))"))
        }
        XCTAssertTrue(sessionCard.contains(".overlay(RoundedRectangle(cornerRadius: 8).stroke(accentColor.opacity(0.35), lineWidth: 1))"))
        XCTAssertTrue(sensorList.contains(".overlay(RoundedRectangle(cornerRadius: 8).stroke(selected ? Color.accentColor.opacity(0.55) : .clear, lineWidth: 1))"))
        XCTAssertFalse(sessionCard.contains("accentColor.opacity(0.10)"))
        XCTAssertFalse(sensorList.contains("Color.secondary.opacity(0.08)"))
        XCTAssertFalse(telemetryPanel.contains("Color.secondary.opacity(0.08)"))
        XCTAssertFalse(chartEditor.contains("Color.secondary.opacity(0.06)"))
        XCTAssertFalse(chartEditor.contains("glassEffect"))

        XCTAssertTrue(sensorList.contains("TemperatureDisplayFormatter.decimal(sensor.celsius)"))
        XCTAssertTrue(fanRow.contains("presentation.currentText"))
        XCTAssertTrue(fanRow.contains("presentation.targetText"))
        XCTAssertTrue(fanRow.contains("presentation.ownershipText"))
        XCTAssertTrue(fanRow.contains("presentation.deltaText"))
        XCTAssertTrue(chartEditor.contains("CurveChartAxisTitle(text: \"RPM\")"))
        XCTAssertTrue(chartEditor.contains("CurveChartAxisTitle(text: \"Temp °C\")"))
    }

    func testMainWindowHelperHealthShowsRepairAndReadOnlyDiagnosticsActions() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let header = try read("Sources/Vifty/MainWindowHeader.swift")
        let fanControlPanel = try read("Sources/Vifty/FanControlPanel.swift")
        let controlSessionCard = try read("Sources/Vifty/ControlSessionCard.swift")

        XCTAssertTrue(contentView.contains("@State private var helperDiagnosticsCopied = false"))
        XCTAssertTrue(header.contains("Label(helperActionTitle, systemImage: \"lock.shield\")"))
        XCTAssertTrue(header.contains("Label(\"Diagnostics only\", systemImage: \"doc.text.magnifyingglass\")"))
        XCTAssertTrue(fanControlPanel.contains("Label(\"Copy Support Evidence\", systemImage: \"doc.on.doc\")"))
        XCTAssertTrue(controlSessionCard.contains("presentation.primaryActionHelp"))
        XCTAssertTrue(contentView.contains("HelperDiagnosticsSupport.copySupportEvidenceCommand(context: model.helperSupportEvidenceContext)"))
        XCTAssertTrue(fanControlPanel.contains(".help(HelperDiagnosticsSupport.copyHelp)"))
        XCTAssertTrue(fanControlPanel.contains("Text(HelperDiagnosticsSupport.copiedMessage)"))
    }

    func testAgentWorkflowRuleCanBeCopiedFromNativeSettingsOnly() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let agentWorkflows = try read("Sources/Vifty/SettingsAgentWorkflowView.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(agentWorkflows.contains("@State private var agentRuleCopied = false"))
        XCTAssertTrue(agentWorkflows.contains("@State private var agentCommandCopied = false"))
        XCTAssertTrue(settingsView.contains("SettingsAgentWorkflowView(model: model)"))
        XCTAssertTrue(agentWorkflows.contains("SettingsCategorySection(title: \"Agent Workflows\", systemImage: \"terminal\")"))
        XCTAssertTrue(agentWorkflows.contains("Label(\"Copy Command\", systemImage: \"terminal\")"))
        XCTAssertTrue(agentWorkflows.contains("AgentWorkflowSupport.WorkloadCommandMode.allCases"))
        XCTAssertTrue(agentWorkflows.contains("AgentWorkflowSupport.safeWorkloadCommandTemplates"))
        XCTAssertTrue(agentWorkflows.contains("copyAgentWorkflowCommand(template, mode)"))
        XCTAssertTrue(agentWorkflows.contains(".help(AgentWorkflowSupport.copyCommandHelp)"))
        XCTAssertTrue(agentWorkflows.contains("Label(\"Copy Agent Rule\", systemImage: \"doc.on.doc\")"))
        XCTAssertTrue(agentWorkflows.contains("copyAgentWorkflowRule()"))
        XCTAssertTrue(agentWorkflows.contains(".help(AgentWorkflowSupport.copyHelp)"))
        XCTAssertTrue(agentWorkflows.contains("Text(AgentWorkflowSupport.copiedMessage)"))
        XCTAssertTrue(agentWorkflows.contains("Text(AgentWorkflowSupport.copiedCommandMessage)"))
        XCTAssertTrue(agentWorkflows.contains("private func copyAgentWorkflowCommand("))
        XCTAssertTrue(agentWorkflows.contains("private func copyAgentWorkflowRule()"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertFalse(contentView.contains("AgentWorkflowSupport"))

        XCTAssertFalse(menuBarView.contains("@State private var agentRuleCopied = false"))
        XCTAssertFalse(menuBarView.contains("@State private var agentCommandCopied = false"))
        XCTAssertFalse(menuBarView.contains("Label(\"Copy Safe Command\", systemImage: \"terminal\")"))
        XCTAssertFalse(menuBarView.contains("AgentWorkflowSupport.WorkloadCommandMode.allCases"))
        XCTAssertFalse(menuBarView.contains("AgentWorkflowSupport.safeWorkloadCommandTemplates"))
        XCTAssertFalse(menuBarView.contains("copyAgentWorkflowCommand(template, mode: mode)"))
        XCTAssertFalse(menuBarView.contains("AgentWorkflowSupport.copyWorkloadCommand(template, mode: mode)"))
        XCTAssertFalse(menuBarView.contains(".help(AgentWorkflowSupport.copyCommandHelp)"))
        XCTAssertFalse(menuBarView.contains("Label(\"Copy Agent Rule\", systemImage: \"terminal\")"))
        XCTAssertFalse(menuBarView.contains("AgentWorkflowSupport.copyAgentRule()"))
        XCTAssertFalse(menuBarView.contains(".help(AgentWorkflowSupport.copyHelp)"))
        XCTAssertFalse(menuBarView.contains("Text(AgentWorkflowSupport.copiedMessage)"))
        XCTAssertFalse(menuBarView.contains("Text(AgentWorkflowSupport.copiedCommandMessage)"))
    }

    func testMenuBarAndSettingsDoNotIssueHardwareControlCommands() throws {
        let sources = try [
            read("Sources/Vifty/MenuBarView.swift"),
            read("Sources/Vifty/SettingsGeneralView.swift"),
            read("Sources/Vifty/SettingsMenuBarView.swift"),
            read("Sources/Vifty/SettingsNotificationsView.swift"),
            read("Sources/Vifty/SettingsAgentWorkflowView.swift")
        ]
        let forbiddenCommands = [
            "FanCommand(",
            "LocalFanHelperClient",
            "setFixedFanRPM(",
            "applyCurrentModeSelection(",
            "restoreAuto()",
            "DaemonInstaller"
        ]

        for source in sources {
            for command in forbiddenCommands {
                XCTAssertFalse(source.contains(command), "Unexpected control command: \(command)")
            }
        }
    }

    func testMainWindowHeaderAndEmptyFanFallbackGateRepairActions() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let header = try read("Sources/Vifty/MainWindowHeader.swift")
        let fanControlPanel = try read("Sources/Vifty/FanControlPanel.swift")

        XCTAssertTrue(contentView.contains("MainWindowHeader("))
        XCTAssertTrue(contentView.contains("FanControlPanel("))
        XCTAssertTrue(header.contains("Label(\"Diagnostics only\", systemImage: \"doc.text.magnifyingglass\")"))
        XCTAssertTrue(fanControlPanel.contains("Button(action: onHelperAction)"))
        XCTAssertTrue(fanControlPanel.contains("Button(action: onCopyDiagnostics)"))
        XCTAssertTrue(fanControlPanel.contains("Label(\"Copy Support Evidence\", systemImage: \"doc.on.doc\")"))
    }

    func testEmptyTemperatureStateAndDeveloperLauncherAreBundleSafe() throws {
        let telemetryPanel = try read("Sources/Vifty/TelemetryEvidencePanel.swift")
        let launcher = try read("scripts/build-and-run-vifty.sh")
        let makefile = try read("Makefile")

        XCTAssertFalse(telemetryPanel.contains("thermometer.slash"))
        XCTAssertTrue(telemetryPanel.contains("thermometer.medium"))
        XCTAssertTrue(launcher.contains("make app"))
        XCTAssertTrue(launcher.contains("open \"${app_path}\""))
        XCTAssertTrue(launcher.contains(".build/Vifty.app"))
        XCTAssertFalse(launcher.contains(".build/debug/Vifty"))
        XCTAssertFalse(launcher.contains("repair-helper"))
        XCTAssertFalse(launcher.contains("make install"))
        XCTAssertTrue(makefile.contains("run-app: ## Build and open the local app bundle"))
        XCTAssertTrue(makefile.contains("./scripts/build-and-run-vifty.sh"))
    }

    func testRuntimeInstrumentationUsesPrivacySafeCategories() throws {
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let appLog = try read("Sources/Vifty/ViftyLog.swift")
        let daemonClient = try read("Sources/ViftyCore/ViftyDaemonClient.swift")
        let notifications = try read("Sources/Vifty/LocalNotifications.swift")
        let codexUsage = try read("Sources/Vifty/CodexUsage.swift")

        XCTAssertTrue(appModel.contains("pollingSignposter.beginInterval"))
        XCTAssertTrue(appModel.contains("pollingSignposter.endInterval"))
        XCTAssertTrue(appLog.contains("static let lifecycle"))
        XCTAssertTrue(appLog.contains("static let polling"))
        XCTAssertTrue(appLog.contains("static let notifications"))
        XCTAssertTrue(appLog.contains("static let fanControl"))
        XCTAssertTrue(appLog.contains("static let codexUsage"))
        XCTAssertTrue(daemonClient.contains("ViftyCoreLog.xpc"))
        XCTAssertTrue(notifications.contains("ViftyLog.notifications"))
        XCTAssertTrue(codexUsage.contains("ViftyLog.codexUsage"))
        XCTAssertFalse(appLog.contains("sensorID"))
        XCTAssertFalse(appLog.contains("profile"))
        XCTAssertFalse(appLog.contains("command"))
    }

    func testCodexUsagePipeShutdownDoesNotDrainToEOF() throws {
        let codexUsage = try read("Sources/Vifty/CodexUsage.swift")

        XCTAssertFalse(codexUsage.contains("readDataToEndOfFile"))
        XCTAssertTrue(codexUsage.contains("Descendants may inherit the pipe after Process exits."))
    }

    func testMainWindowPanesAreIndependentlyScrollableAndFillAvailableHeight() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let telemetryPanel = try read("Sources/Vifty/TelemetryEvidencePanel.swift")
        let sensorList = try read("Sources/Vifty/SensorListView.swift")

        XCTAssertTrue(contentView.contains("private var mainContent: some View"))
        XCTAssertTrue(contentView.contains("GeometryReader { proxy in"))
        XCTAssertTrue(contentView.contains("let layout = MainWindowLayout.resolve(width: proxy.size.width, height: proxy.size.height)"))
        XCTAssertTrue(contentView.contains("switch layout.mode"))
        XCTAssertTrue(contentView.contains("case .stacked:"))
        XCTAssertTrue(contentView.contains("VStack(alignment: .leading, spacing: 0)"))
        XCTAssertTrue(contentView.contains("sectionView(.telemetryEvidence, compactTelemetry: layout.compactTelemetry)"))
        XCTAssertTrue(contentView.contains("case .split:"))
        XCTAssertTrue(contentView.contains("HStack(alignment: .top, spacing: 0)"))
        XCTAssertTrue(contentView.contains("case .workbench:"))
        XCTAssertTrue(contentView.contains("paneSectionsView("))
        XCTAssertFalse(contentView.contains("workbenchControlRailSectionsView("))
        XCTAssertFalse(contentView.contains("Spacer(minLength: 24)"))
        XCTAssertTrue(contentView.contains(".scrollIndicators(.visible)"))
        XCTAssertTrue(contentView.contains(".frame(width: layout.controlPaneWidth)"))
        XCTAssertTrue(contentView.contains("minWidth: layout.editorPaneMinWidth"))
        XCTAssertTrue(contentView.contains(".frame(\n                            minWidth: layout.telemetryPaneMinWidth,\n                            idealWidth: layout.telemetryPaneIdealWidth,\n                            maxWidth: layout.telemetryPaneMaxWidth,\n                            minHeight: proxy.size.height,\n                            maxHeight: proxy.size.height\n                        )"))
        XCTAssertFalse(contentView.contains(".frame(minWidth: 360, idealWidth: 400, maxWidth: 420, minHeight: proxy.size.height, maxHeight: proxy.size.height)"))
        XCTAssertTrue(contentView.contains("Divider().frame(height: proxy.size.height)"))
        XCTAssertTrue(contentView.contains(".background(Color.secondary.opacity(0.035))"))
        XCTAssertTrue(contentView.contains("TelemetryEvidencePanel("))
        XCTAssertTrue(telemetryPanel.contains("TelemetryOverviewPanel("))
        XCTAssertTrue(telemetryPanel.contains("TelemetryLayoutPolicy.metricColumnCount(for: metricContainerWidth)"))
        XCTAssertTrue(telemetryPanel.contains(".onGeometryChange(for: CGFloat.self)"))
        XCTAssertFalse(telemetryPanel.contains("history: model.telemetryHistory"))
        XCTAssertTrue(telemetryPanel.contains("SensorListView("))
        XCTAssertFalse(telemetryPanel.contains("DisclosureGroup(\"All sensors\")"))
        XCTAssertFalse(telemetryPanel.contains("ForEach(sensors) { sensor in"))
        XCTAssertTrue(sensorList.contains("struct SensorListView: View"))
        XCTAssertTrue(sensorList.contains("LazyVStack(spacing: 6)"))
        XCTAssertTrue(sensorList.contains("SensorRowContent("))
        XCTAssertTrue(sensorList.contains("private struct SensorRowContent: View"))
        XCTAssertTrue(sensorList.contains(".accessibilityLabel(sensor.name)"))
        XCTAssertTrue(sensorList.contains(".accessibilityValue(\"\\(sensor.celsius, specifier: \"%.1f\") degrees Celsius, \\(sensor.source.rawValue)\")"))
        XCTAssertTrue(sensorList.contains(".accessibilityAddTraits(sensor.id == selectedSensorID ? [.isSelected] : [])"))
        XCTAssertTrue(telemetryPanel.contains("Highest \\(TemperatureDisplayFormatter.decimal(highest.celsius))"))
        XCTAssertFalse(telemetryPanel.contains("let visibleSensors = topTemperatureSensors"))
        XCTAssertTrue(contentView.contains(".frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)"))
        XCTAssertTrue(telemetryPanel.contains("PowerDisplayFormatter.panelHeadline(for: power)"))
        XCTAssertTrue(telemetryPanel.contains("PowerDetailDisclosure(snapshot: power, compact: compact)"))
        XCTAssertTrue(telemetryPanel.contains("PowerDisplayFormatter.adapterDescription(for: adapter)"))
        XCTAssertFalse(telemetryPanel.contains("PowerMetric(label: summary.latestTemperatureLabel"))
    }

    func testMainWindowUsesBehavioralSectionPlacementModel() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("MainWindowSectionPlacement.resolve(layout: layout)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .stackedFlow)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .splitControl)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .splitTelemetry)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .workbenchControlRail)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .workbenchEditor)"))
        XCTAssertTrue(contentView.contains("placement.sections(in: .workbenchTelemetry)"))
        XCTAssertTrue(contentView.contains("private func sectionView("))
        XCTAssertFalse(contentView.contains("let _ = placement"))
        XCTAssertFalse(contentView.contains("private var controlRailPane: some View"))
        XCTAssertFalse(contentView.contains("private var primaryEditorPane: some View"))
        XCTAssertFalse(contentView.contains("private var fanControlPane: some View"))
    }

    func testHistoryPanelShowsLocalSparklineVisualization() throws {
        let telemetryPanel = try read("Sources/Vifty/TelemetryEvidencePanel.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertFalse(telemetryPanel.contains("private var summary: TelemetryHistorySummary"))
        XCTAssertFalse(appModel.contains("@Published var telemetryHistory"))
        XCTAssertTrue(appModel.contains("var telemetryHistory = TelemetryHistory() {"))
        XCTAssertTrue(appModel.contains("@Published private(set) var telemetryOverviewSummary = TelemetryHistorySummary(history: TelemetryHistory())"))
        XCTAssertTrue(appModel.contains("@Published private(set) var compactTelemetryOverviewSummary = TelemetryHistorySummary("))
        XCTAssertTrue(appModel.contains("private func refreshTelemetrySummaries()"))
        XCTAssertTrue(telemetryPanel.contains("TelemetryHistoryChart(summary: summary, compact: compact)"))
        XCTAssertTrue(telemetryPanel.contains("private struct TelemetryHistoryChart: View"))
        XCTAssertTrue(telemetryPanel.contains("summary.sampleWindowText"))
        XCTAssertTrue(telemetryPanel.contains("parts.append(\"\\(summary.sampleCountText) · last \\(sampleWindowText)\")"))
        XCTAssertTrue(telemetryPanel.contains("title: \"Temp\""))
        XCTAssertTrue(telemetryPanel.contains("if summary.temperatureValues.count > 1"))
        XCTAssertTrue(telemetryPanel.contains("private struct HistorySparkline: View"))
        XCTAssertTrue(telemetryPanel.contains("startValueText: summary.temperatureValues.first.map(TelemetryHistorySummary.temperatureText)"))
        XCTAssertTrue(telemetryPanel.contains("currentValueText: summary.latestTemperatureText"))
        XCTAssertTrue(telemetryPanel.contains("rangeText: summary.temperatureRangeText"))
        XCTAssertTrue(telemetryPanel.contains("title: summary.fanRPMSparklineTitle"))
        XCTAssertTrue(telemetryPanel.contains("startValueText: summary.fanRPMValues.first.map(TelemetryHistorySummary.fanRPMText)"))
        XCTAssertTrue(telemetryPanel.contains("currentValueText: summary.latestFanRPMText"))
        XCTAssertTrue(telemetryPanel.contains("rangeText: summary.fanRPMRangeText"))
        XCTAssertTrue(telemetryPanel.contains("title: \"Power\""))
        XCTAssertTrue(telemetryPanel.contains("rangeText: summary.batteryPowerRangeText"))
        XCTAssertTrue(telemetryPanel.contains("changeText: summary.temperatureChangeText"))
        XCTAssertTrue(telemetryPanel.contains("changeText: summary.fanRPMChangeText"))
        XCTAssertTrue(telemetryPanel.contains("changeText: summary.batteryPowerChangeText"))
        XCTAssertTrue(telemetryPanel.contains("ThermalPressureTrail("))
        XCTAssertTrue(telemetryPanel.contains("pressures: summary.thermalPressureSamples"))
        XCTAssertTrue(telemetryPanel.contains("summaryText: summary.thermalPressureSummaryText"))
        XCTAssertTrue(telemetryPanel.contains("private struct ThermalPressureTrail: View"))
        let thermalPressureTrail = try XCTUnwrap(
            telemetryPanel
                .components(separatedBy: "private struct ThermalPressureTrail: View")
                .last?
                .components(separatedBy: "private struct PowerDetailDisclosure: View")
                .first
        )
        XCTAssertTrue(thermalPressureTrail.contains(".accessibilityLabel(\"Thermal pressure history \\(summaryText)\")"))
        XCTAssertTrue(thermalPressureTrail.contains(".accessibilityElement(children: .ignore)"))
        XCTAssertTrue(telemetryPanel.contains("private struct SparklinePath: View"))
        XCTAssertTrue(telemetryPanel.contains("startValueLabelText: startValueText"))
        XCTAssertTrue(telemetryPanel.contains("SparklineValueBadge(text: startValueLabelText, color: color)"))
        XCTAssertTrue(telemetryPanel.contains("SparklineValueBadge(text: valueLabelText, color: color)"))
        XCTAssertTrue(telemetryPanel.contains(".accessibilityLabel(accessibilityText)"))
        XCTAssertTrue(telemetryPanel.contains(".accessibilityElement(children: .ignore)"))
        XCTAssertTrue(telemetryPanel.contains("private func smoothedValues(_ rawValues: [Double]) -> [Double]"))
        XCTAssertFalse(telemetryPanel.contains("import Charts"))
        XCTAssertFalse(telemetryPanel.contains("private func signedWattRangeText"))
        XCTAssertFalse(telemetryPanel.contains("UserDefaults.standard.set(history"))
    }

    func testMenuBarShowsReadOnlyRecentTelemetryTrend() throws {
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(appModel.contains("var recentTelemetryTrendSummary: String?"))
        XCTAssertTrue(appModel.contains("TelemetryHistorySummary("))
        XCTAssertTrue(appModel.contains("sampleLimit: 90"))
        XCTAssertTrue(appModel.contains("thermalPressureLimit: 24"))
        XCTAssertFalse(menuBarView.contains("recentTelemetryTrendSummary"))
        XCTAssertFalse(appModel.contains("UserDefaults.standard.set(telemetryHistory"))
    }

    func testPrivateIOKitBridgeOnlyExportsHIDTemperatureReader() throws {
        let header = try read("Sources/ViftyPrivateIOKit/include/ViftyPrivateIOKit.h")
        let implementation = try read("Sources/ViftyPrivateIOKit/ViftyPrivateIOKit.c")

        XCTAssertTrue(header.contains("ViftyHIDTemperature"))
        XCTAssertTrue(header.contains("ViftyCopyHIDTemperatures"))
        XCTAssertTrue(implementation.contains("int ViftyCopyHIDTemperatures"))
        XCTAssertFalse(header.contains("ViftyOpenSMC"))
        XCTAssertFalse(implementation.contains("ViftyOpenSMC"))
        XCTAssertFalse(implementation.contains("IOServiceOpen"))
        XCTAssertFalse(implementation.contains("AppleSMCKeysEndpoint"))
        XCTAssertFalse(implementation.contains("SMCEndpoint1"))
    }

    func testAppBundleIsDockVisibleAndHasAppIcon() throws {
        let plist = try read("Resources/Info.plist")
        let makefile = try read("Makefile")
        let iconURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent("Resources/ViftyIcon.icns")

        XCTAssertTrue(plist.contains("<key>CFBundleIconFile</key>"))
        XCTAssertTrue(plist.contains("<string>ViftyIcon</string>"))
        XCTAssertFalse(plist.contains("<key>LSUIElement</key>"))
        XCTAssertTrue(makefile.contains("APP_ICON := Resources/ViftyIcon.icns"))
        XCTAssertTrue(makefile.contains("cp \"$(APP_ICON)\" \"$(CONTENTS)/Resources/ViftyIcon.icns\""))
        XCTAssertTrue(FileManager.default.fileExists(atPath: iconURL.path))
    }

    func testMenuBarAgentCoolingUsesResolvedSessionState() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let presentation = try read("Sources/Vifty/MenuBarPanelPresentation.swift")

        XCTAssertTrue(presentation.contains("input.isManualControlActive && input.controlSession.state != .blocked"))
        XCTAssertTrue(presentation.contains("input.controlSession.title"))
        XCTAssertTrue(menuBarView.contains("if presentation.showsRestoreAuto"))
        XCTAssertTrue(menuBarView.contains("Button(\"Restore Auto\", action: onRestoreAuto)"))
        XCTAssertFalse(menuBarView.contains("agentCooling"))
    }

    func testMenuBarPowerRowsAndStatusItemDisplayModeAreWired() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let controlSessionCard = try read("Sources/Vifty/ControlSessionCard.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let generalSettings = try read("Sources/Vifty/SettingsGeneralView.swift")
        let menuBarSettings = try read("Sources/Vifty/SettingsMenuBarView.swift")
        let viftyApp = try read("Sources/Vifty/ViftyApp.swift")
        let statusItemController = try read("Sources/Vifty/ViftyStatusItemController.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let appPreferencesStore = try read("Sources/Vifty/AppPreferencesStore.swift")
        let menuBarPresentation = try read("Sources/Vifty/MenuBarStatusPresentation.swift")
        let pollSchedulePolicy = try read("Sources/Vifty/PollSchedulePolicy.swift")

        XCTAssertTrue(menuBarView.contains("MenuBarStatusSummary(presentation: presentation)"))
        XCTAssertTrue(menuBarView.contains("MenuBarFanLines(lines: presentation.fanLines)"))
        XCTAssertTrue(menuBarView.contains(".frame(width: 320)"))
        XCTAssertFalse(menuBarView.contains("PowerDisplayFormatter"))
        XCTAssertFalse(menuBarView.contains("DaemonInstaller"))
        XCTAssertFalse(menuBarView.contains("Picker(\"Default mode\", selection: $model.startupMode)"))
        XCTAssertFalse(menuBarView.contains("Picker(\"Menu bar\", selection: $model.menuBarDisplayMode)"))
        XCTAssertFalse(menuBarView.contains("Picker(\"Codex display\", selection: $model.codexUsageDisplayStyle)"))
        XCTAssertTrue(contentView.contains("ReadinessModePanel("))
        XCTAssertTrue(controlSessionCard.contains("presentation.title"))
        XCTAssertFalse(controlSessionCard.contains("Fan Control Owner"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertTrue(settingsView.contains("TabView {"))
        XCTAssertTrue(settingsView.contains("SettingsGeneralView(model: model)"))
        XCTAssertTrue(settingsView.contains("SettingsMenuBarView(model: model)"))
        XCTAssertTrue(generalSettings.contains("Picker(\"Default mode\", selection: $model.startupMode)"))
        XCTAssertTrue(menuBarSettings.contains("Picker(\"Menu bar\", selection: $model.menuBarDisplayMode)"))
        XCTAssertTrue(menuBarSettings.contains("Picker(\"Codex display\", selection: $model.codexUsageDisplayStyle)"))
        XCTAssertTrue(menuBarSettings.contains("ForEach(MenuBarDisplayMode.allCases)"))
        XCTAssertTrue(menuBarSettings.contains("ForEach(MenuBarField.allCases)"))
        XCTAssertTrue(menuBarSettings.contains("ForEach(CodexUsageDisplayStyle.allCases)"))
        XCTAssertFalse(viftyApp.contains("MenuBarExtra {"))
        XCTAssertFalse(viftyApp.contains("MenuBarExtraLabel"))
        XCTAssertTrue(viftyApp.contains("@NSApplicationDelegateAdaptor(ViftyAppDelegate.self) private var appDelegate"))
        XCTAssertTrue(viftyApp.contains("@StateObject private var model: AppModel"))
        XCTAssertTrue(viftyApp.contains("@MainActor\n    init()"))
        XCTAssertTrue(viftyApp.contains("_model = StateObject(wrappedValue: model)"))
        XCTAssertTrue(viftyApp.contains("appDelegate.model = model"))
        XCTAssertTrue(viftyApp.contains("appDelegate.openMainWindowHandler = { openWindow(id: \"main\") }"))
        XCTAssertTrue(viftyApp.contains("model.start()"))
        XCTAssertTrue(viftyApp.contains("final class ViftyAppDelegate: NSObject, NSApplicationDelegate"))
        XCTAssertTrue(viftyApp.contains("func applicationDidFinishLaunching(_ notification: Notification)"))
        XCTAssertTrue(viftyApp.contains("statusItemController = ViftyStatusItemController("))
        XCTAssertTrue(viftyApp.contains("statusItemController?.openMainWindow = { [weak self] in"))
        XCTAssertTrue(statusItemController.contains("NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)"))
        XCTAssertFalse(statusItemController.contains("model.objectWillChange"))
        XCTAssertTrue(statusItemController.contains("updateStatusItem()"))
        XCTAssertTrue(statusItemController.contains("MenuBarTelemetryPrimePolicy.launch"))
        XCTAssertTrue(statusItemController.contains("MenuBarTelemetryPrimePolicy.popover"))
        XCTAssertTrue(statusItemController.contains("scheduleTelemetryPrimeIfNeeded()"))
        XCTAssertTrue(statusItemController.contains("private let primeScheduler = MenuBarTelemetryPrimeScheduler()"))
        XCTAssertTrue(statusItemController.contains("scheduleTelemetryPrimeIfNeeded(policy: Self.popoverPrimePolicy)"))
        XCTAssertTrue(statusItemController.contains("primeScheduler.schedule"))
        XCTAssertFalse(statusItemController.contains("private var primeTask: Task<Void, Never>?"))
        XCTAssertTrue(statusItemController.contains("model.$menuBarStatusItemPresentation"))
        XCTAssertTrue(statusItemController.contains(".removeDuplicates()"))
        XCTAssertTrue(statusItemController.contains("private var lastAppliedPresentation: MenuBarStatusItemPresentation?"))
        XCTAssertTrue(statusItemController.contains("guard presentation != lastAppliedPresentation else { return }"))
        XCTAssertTrue(statusItemController.contains("primeStatusItemUntilTelemetryResolved("))
        XCTAssertTrue(statusItemController.contains("policy.shouldAttempt("))
        XCTAssertTrue(statusItemController.contains("await model.primeMenuBarStatusItemTelemetry(maxAttempts: 1)"))
        XCTAssertTrue(statusItemController.contains("guard model.menuBarStatusItemPresentation.needsTelemetryPrime else { return }"))
        XCTAssertTrue(statusItemController.contains("await Task.yield()"))
        XCTAssertTrue(statusItemController.contains("MenuBarView(openMainWindow: { [weak self] in"))
        XCTAssertTrue(viftyApp.contains("onRestoreAuto: { [weak model] in"))
        XCTAssertTrue(statusItemController.contains("private let onRestoreAuto: () -> Void"))
        XCTAssertTrue(statusItemController.contains("onQuit: {"))
        XCTAssertTrue(statusItemController.contains("let presentation = model.menuBarStatusItemPresentation"))
        XCTAssertTrue(menuBarPresentation.contains("enum MenuBarDisplayMode"))
        XCTAssertTrue(menuBarPresentation.contains("enum MenuBarField"))
        XCTAssertTrue(menuBarPresentation.contains("struct MenuBarStatusItemPresentation"))
        XCTAssertTrue(menuBarPresentation.contains("enum ViftyStatusItemPresentation"))
        XCTAssertFalse(statusItemController.contains("enum ViftyStatusItemPresentation"))
        XCTAssertFalse(statusItemController.contains("private static let launchPrimeAttempts = 120"))
        XCTAssertTrue(appModel.contains("allowsPlaceholderText: menuBarAllowsPlaceholderStatusItemText"))
        XCTAssertTrue(statusItemController.contains("button.title = text"))
        XCTAssertTrue(statusItemController.contains("statusItem.length = NSStatusItem.variableLength"))
        XCTAssertFalse(statusItemController.contains("button.window?.displayIfNeeded()"))
        XCTAssertFalse(statusItemController.contains("button.needsLayout = true"))
        XCTAssertFalse(statusItemController.contains("button.needsDisplay = true"))
        XCTAssertTrue(statusItemController.contains("NSImage(systemSymbolName: \"fan\""))
        XCTAssertTrue(appModel.contains("private let preferencesStore: AppPreferencesStore"))
        XCTAssertTrue(appModel.contains("private var activePollTask: Task<Void, Never>?"))
        XCTAssertTrue(appModel.contains("private let pollSchedulePolicy = PollSchedulePolicy.standard"))
        XCTAssertTrue(pollSchedulePolicy.contains("idleInterval: .seconds(10)"))
        XCTAssertTrue(pollSchedulePolicy.contains("activeInterval: .seconds(5)"))
        XCTAssertTrue(appModel.contains("backgroundPollInterval()"))
        XCTAssertTrue(appModel.contains("@Published private(set) var menuBarStatusItemPresentation = MenuBarStatusItemPresentation.placeholder"))
        XCTAssertTrue(appModel.contains("@Published private(set) var menuBarStatusItemRevision = 0"))
        XCTAssertTrue(appModel.contains("private var currentMenuBarStatusItemPresentation: MenuBarStatusItemPresentation"))
        XCTAssertTrue(appModel.contains("refreshMenuBarStatusItemIfNeeded()"))
        XCTAssertTrue(appModel.contains("private func performPollOnce() async"))
        XCTAssertTrue(appModel.contains("if let activePollTask {\n            await activePollTask.value\n            return\n        }"))
        XCTAssertFalse(appModel.contains("pollingTask = Task { [weak self]"))
        XCTAssertTrue(appModel.contains("func primeMenuBarStatusItemTelemetry("))
        XCTAssertTrue(appModel.contains("var menuBarStatusItemText: String?"))
        XCTAssertTrue(appModel.contains("var menuBarLabelNeedsTelemetryPrime: Bool"))
        XCTAssertTrue(appModel.contains("var menuBarDisplaysCodexUsage: Bool"))
        XCTAssertTrue(appModel.contains("func setMenuBarCustomField(_ field: MenuBarField, enabled: Bool)"))
        XCTAssertTrue(appModel.contains("func applyStartupModePreferenceIfNeeded() async"))
        XCTAssertTrue(appModel.contains("persistAppPreferences()"))
        XCTAssertFalse(viftyApp.contains("await model.primeMenuBarStatusItemTelemetry(maxAttempts: 5)"))
        XCTAssertFalse(appModel.contains("Task.sleep(for: .seconds(2))"))
        XCTAssertTrue(appPreferencesStore.contains("var startupMode: ModeSelection"))
        XCTAssertTrue(appPreferencesStore.contains("app-preferences.json"))
        XCTAssertTrue(appPreferencesStore.contains("legacyDefaults: UserDefaults?"))
        XCTAssertTrue(appPreferencesStore.contains(".posixPermissions: NSNumber(value: 0o700)"))
        XCTAssertTrue(appPreferencesStore.contains(".posixPermissions: NSNumber(value: 0o600)"))
        XCTAssertFalse(appModel.contains("preferences.set("))
    }

    func testLaunchAtLoginToggleIsWiredThroughSystemLoginItems() throws {
        let launchAtLogin = try read("Sources/Vifty/LaunchAtLogin.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let generalSettings = try read("Sources/Vifty/SettingsGeneralView.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(launchAtLogin.contains("SMAppService.mainApp.status"))
        XCTAssertTrue(launchAtLogin.contains("try service.register()"))
        XCTAssertTrue(launchAtLogin.contains("try service.unregister()"))
        XCTAssertTrue(launchAtLogin.contains("SMAppService.openSystemSettingsLoginItems()"))
        XCTAssertTrue(appModel.contains("private let launchAtLoginManager: LaunchAtLoginManaging"))
        XCTAssertTrue(appModel.contains("@Published private(set) var launchAtLoginStatus: LaunchAtLoginStatus = .disabled"))
        XCTAssertTrue(appModel.contains("var launchAtLoginEnabled: Bool"))
        XCTAssertTrue(appModel.contains("func setLaunchAtLoginEnabled(_ enabled: Bool)"))
        XCTAssertTrue(appModel.contains("launchAtLoginError = \"Could not update startup item: \\(error.localizedDescription)\""))
        XCTAssertFalse(appModel.contains("UserDefaults.standard.set(launchAtLogin"))
        XCTAssertFalse(appModel.contains("preferencesStore.save(AppPreferences(\n            launchAtLogin"))
        XCTAssertTrue(generalSettings.contains("Toggle(\"Start Vifty at startup\", isOn: launchAtLoginBinding)"))
        XCTAssertTrue(generalSettings.contains("model.openLaunchAtLoginSettings()"))
        XCTAssertTrue(generalSettings.contains("model.refreshLaunchAtLoginStatus()"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertTrue(settingsView.contains("SettingsGeneralView(model: model)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Start Vifty at startup\", isOn: launchAtLoginBinding)"))
        XCTAssertFalse(menuBarView.contains("model.openLaunchAtLoginSettings()"))
        XCTAssertFalse(menuBarView.contains("model.refreshLaunchAtLoginStatus()"))
    }

    func testLocalInstallerRestartsRunningAppBeforeCopyingBundle() throws {
        let installScript = try read("scripts/install-vifty.sh")
        let readme = try read("README.md")

        XCTAssertTrue(installScript.contains("QUIT_RUNNING_APP=\"${QUIT_RUNNING_APP:-1}\""))
        XCTAssertTrue(installScript.contains("WAS_RUNNING=0"))
        XCTAssertTrue(installScript.contains("/usr/bin/pgrep -x \"${APP_NAME}\""))
        XCTAssertTrue(installScript.contains("tell application id \"tech.reidar.vifty\" to quit"))
        XCTAssertTrue(installScript.contains("/usr/bin/pkill -x \"${APP_NAME}\""))
        XCTAssertTrue(installScript.contains("quit_running_app_if_needed"))
        XCTAssertTrue(installScript.contains("\"${OPEN_AFTER_INSTALL}\" == \"1\" || \"${WAS_RUNNING}\" == \"1\""))
        XCTAssertTrue(readme.contains("the installer quits and relaunches it from the newly installed bundle"))
    }

    func testLocalInstallerReportsPrivilegedHelperDaemonDrift() throws {
        let installScript = try read("scripts/install-vifty.sh")
        let readme = try read("README.md")

        XCTAssertTrue(installScript.contains("shell_quote()"))
        XCTAssertTrue(installScript.contains("CHECK_HELPER_DAEMON=\"${CHECK_HELPER_DAEMON:-1}\""))
        XCTAssertTrue(installScript.contains("HELPER_TARGET=\"${VIFTY_HELPER_TARGET:-/Library/PrivilegedHelperTools/tech.reidar.vifty.daemon}\""))
        XCTAssertTrue(installScript.contains("report_helper_daemon_status"))
        XCTAssertTrue(installScript.contains("sha256_file \"${bundled_daemon}\""))
        XCTAssertTrue(installScript.contains("sha256_file \"${HELPER_TARGET}\""))
        XCTAssertTrue(installScript.contains("repair_command=\"REPAIR_HELPER_APP=$(shell_quote \"${DEST_APP}\") make repair-helper\""))
        XCTAssertTrue(installScript.contains("Fan helper matches the installed app daemon."))
        XCTAssertTrue(installScript.contains("Fan helper daemon differs from the installed app bundle."))
        XCTAssertTrue(installScript.contains("Open Vifty and choose Reinstall Helper or Repair Helper, or run: ${repair_command}"))
        XCTAssertTrue(installScript.contains("Do that before current-build manual/agent smoke evidence."))
        XCTAssertTrue(installScript.contains("AGENT_RUN_SMOKE_READINESS_JSON=1 make agent-run-smoke-readiness-current-build"))
        XCTAssertFalse(installScript.contains("repair-vifty-helper.sh"))

        XCTAssertTrue(readme.contains("The root LaunchDaemon helper is repaired only after an explicit user-approved action, not silently replaced by the app installer"))
        XCTAssertTrue(readme.contains("performs a read-only helper-daemon hash check"))
        XCTAssertTrue(readme.contains("REPAIR_HELPER_APP=/Applications/Vifty.app make repair-helper"))
        XCTAssertTrue(readme.contains("If the installer falls back to `~/Applications`, use the exact `REPAIR_HELPER_APP=... make repair-helper` command printed by the installer so the helper is repaired from that copied app bundle."))
        XCTAssertTrue(readme.contains("before treating current-build manual or agent smoke evidence as valid"))
    }

    func testLocalInstallerRetriesSwiftPMBuildDatabaseFailuresWithIsolatedBuildPath() throws {
        let installScript = try read("scripts/install-vifty.sh")
        let readme = try read("README.md")

        XCTAssertTrue(installScript.contains("BUILD_LOG=\"$(mktemp -t vifty-install-build.XXXXXX)\""))
        XCTAssertTrue(installScript.contains("is_swiftpm_build_database_error()"))
        XCTAssertTrue(installScript.contains("build\\\\.db|build database|disk I/O error|database is locked"))
        XCTAssertTrue(installScript.contains("build_app_bundle()"))
        XCTAssertTrue(installScript.contains("else\n    build_status=$?\n  fi"))
        XCTAssertTrue(installScript.contains("if [[ -z \"${SWIFT_BUILD_PATH:-}\" ]] && is_swiftpm_build_database_error; then"))
        XCTAssertTrue(installScript.contains("fallback_build_path=\"${TMPDIR:-/tmp}/vifty-install-swiftpm-$$\""))
        XCTAssertTrue(installScript.contains("==> SwiftPM build database failed; retrying with SWIFT_BUILD_PATH=${fallback_build_path}"))
        XCTAssertTrue(installScript.contains("SWIFT_BUILD_PATH=\"${fallback_build_path}\" make app CONFIGURATION=\"${CONFIGURATION}\""))
        XCTAssertTrue(installScript.contains("build_app_bundle"))

        XCTAssertTrue(readme.contains("If SwiftPM's local `.build/build.db` becomes unhealthy, the local installer retries once with an isolated temporary `SWIFT_BUILD_PATH` before failing."))
        XCTAssertTrue(readme.contains("Set `SWIFT_BUILD_PATH` yourself when you want a stable reusable build-product path."))
    }

    func testExplicitHelperRepairScriptPreservesPrivilegedRepairBoundary() throws {
        let script = try read("scripts/repair-vifty-helper.sh")
        let makefile = try read("Makefile")
        let readme = try read("README.md")

        XCTAssertTrue(script.contains("APP_PATH=\"${VIFTY_APP:-/Applications/Vifty.app}\""))
        XCTAssertTrue(script.contains("HELPER_TARGET=\"${VIFTY_HELPER_TARGET:-/Library/PrivilegedHelperTools/tech.reidar.vifty.daemon}\""))
        XCTAssertTrue(script.contains("PLIST_TARGET=\"${VIFTY_DAEMON_PLIST_TARGET:-/Library/LaunchDaemons/tech.reidar.vifty.daemon.plist}\""))
        XCTAssertTrue(script.contains("DRY_RUN=0"))
        XCTAssertTrue(script.contains("--dry-run"))
        XCTAssertTrue(script.contains("This is an explicit operator action and may prompt for administrator approval."))
        XCTAssertTrue(script.contains("It does not request cooling or write fan state directly."))
        XCTAssertTrue(script.contains("do shell script \"/bin/bash \" & quoted form of \"${ADMIN_SCRIPT_PATH}\" with administrator privileges"))
        XCTAssertTrue(script.contains("launchctl bootout system $(shell_quote \"$PLIST_TARGET\") 2>/dev/null || true"))
        XCTAssertTrue(script.contains("helper_tmp=\"\\$(mktemp $(shell_quote \"${HELPER_TARGET}.XXXXXX\"))\""))
        XCTAssertTrue(script.contains("plist_tmp=\"\\$(mktemp $(shell_quote \"${PLIST_TARGET}.XXXXXX\"))\""))
        XCTAssertTrue(script.contains("trap 'rm -f \"\\$helper_tmp\" \"\\$plist_tmp\"' EXIT"))
        XCTAssertTrue(script.contains("chmod 755 \"\\$helper_tmp\""))
        XCTAssertTrue(script.contains("chown root:wheel \"\\$helper_tmp\""))
        XCTAssertTrue(script.contains("chmod 644 \"\\$plist_tmp\""))
        XCTAssertTrue(script.contains("chown root:wheel \"\\$plist_tmp\""))
        XCTAssertTrue(script.contains("xattr -cr \"\\$helper_tmp\" \"\\$plist_tmp\" 2>/dev/null || true"))
        XCTAssertTrue(script.contains("/usr/libexec/PlistBuddy -c 'Delete :BundleProgram' \"\\$plist_tmp\""))
        XCTAssertTrue(script.contains("mv -f \"\\$helper_tmp\" $(shell_quote \"$HELPER_TARGET\")"))
        XCTAssertTrue(script.contains("mv -f \"\\$plist_tmp\" $(shell_quote \"$PLIST_TARGET\")"))
        XCTAssertTrue(script.contains("chmod 600 \"\\$log_path\""))
        XCTAssertTrue(script.contains("chown root:wheel \"\\$log_path\""))
        XCTAssertTrue(script.contains("launchctl bootstrap system $(shell_quote \"$PLIST_TARGET\")"))
        XCTAssertTrue(script.contains("launchctl kickstart -k $(shell_quote \"$SERVICE_TARGET\")"))
        XCTAssertTrue(script.contains("installed helper matches the app bundle."))
        XCTAssertTrue(script.contains("\"$VIFTYCTL\" diagnose --json"))
        XCTAssertFalse(script.contains("ViftyHelper setFixed"))
        XCTAssertFalse(script.contains("ViftyHelper auto"))

        XCTAssertTrue(makefile.contains("repair-helper: ## Explicitly repair the installed privileged helper"))
        XCTAssertTrue(makefile.contains("./scripts/repair-vifty-helper.sh --app \"$(REPAIR_HELPER_APP)\""))
        XCTAssertTrue(readme.contains("Source checkouts also provide `make repair-helper`"))
        XCTAssertTrue(readme.contains("After repair, the script compares the installed helper hash with the app bundle and prints read-only `viftyctl diagnose` recovery fields"))
    }

    func testAppWindowCurveProfileSelectorUsesSavedProfiles() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let fanControlPanel = try read("Sources/Vifty/FanControlPanel.swift")
        let profileToolbar = try read("Sources/Vifty/CurveProfileToolbar.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertFalse(menuBarView.contains("@State private var selectedMenuCurveProfileID: UUID?"))
        XCTAssertFalse(menuBarView.contains("Picker(\"Curve profile\", selection: $selectedMenuCurveProfileID)"))
        XCTAssertFalse(settingsView.contains("Curve profile"))
        XCTAssertFalse(settingsView.contains("selectedCurveProfileID"))
        XCTAssertFalse(contentView.contains("if !model.savedProfiles.isEmpty"))
        XCTAssertTrue(fanControlPanel.contains("CurveProfileToolbar("))
        XCTAssertTrue(contentView.contains("savedProfiles: model.savedProfiles"))
        XCTAssertTrue(contentView.contains("selectedCurveProfileID: $model.selectedCurveProfileID"))
        XCTAssertTrue(contentView.contains("selectCurveProfile: { _ = model.selectCurveProfile(id: $0) }"))
        XCTAssertTrue(profileToolbar.contains("Picker(\"Profile\", selection: $selectedProfileID)"))
        XCTAssertTrue(profileToolbar.contains("ForEach(profiles)"))
        XCTAssertTrue(profileToolbar.contains("Label(\"Presets\", systemImage: \"slider.horizontal.3\")"))
        XCTAssertTrue(profileToolbar.contains(".sheet(isPresented: $showSaveSheet)"))
        XCTAssertTrue(profileToolbar.contains(".confirmationDialog("))
        XCTAssertTrue(profileToolbar.contains("profilePendingDeletion"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertTrue(settingsView.contains("SettingsGeneralView(model: model)"))
        XCTAssertTrue(appModel.contains("func selectCurveProfile(id profileID: CurveProfile.ID?) -> Bool"))
        XCTAssertTrue(appModel.contains("@Published var selectedCurveProfileID: CurveProfile.ID?"))
        XCTAssertTrue(appModel.contains("selectedMode = .curve\n        loadProfile(profile)"))
    }

    func testMenuBarHighTemperatureAttentionIsWired() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("static let highTemperatureAttentionThreshold = 90.0"))
        XCTAssertTrue(appModel.contains("var temperatureAttentionSummary: String?"))
        XCTAssertTrue(appModel.contains("return sensor.celsius >= Self.highTemperatureAttentionThreshold ? \"High temp\" : nil"))
        XCTAssertTrue(appModel.contains("var fanWriteBlockedWhileHotSummary: String?"))
        XCTAssertTrue(appModel.contains("var fanWriteBlockedWhileHotRecoverySuggestion: String?"))
        XCTAssertTrue(appModel.contains("parts.append(\"Fan writes blocked\")"))
        XCTAssertTrue(appModel.contains("private var menuBarPanelAttentionText: String?"))
        XCTAssertTrue(menuBarView.contains("MenuBarAttentionRow(text: attentionText)"))
        XCTAssertTrue(menuBarView.contains("foregroundStyle(.orange)"))
    }

    func testMainWindowHotBlockedHelperAttentionIsWired() throws {
        let readinessPanel = try read("Sources/Vifty/ReadinessModePanel.swift")

        XCTAssertTrue(readinessPanel.contains("if let fanWriteBlockedWhileHotSummary"))
        XCTAssertTrue(readinessPanel.contains("Text(fanWriteBlockedWhileHotSummary)"))
        XCTAssertTrue(readinessPanel.contains("if let fanWriteBlockedWhileHotRecoverySuggestion"))
        XCTAssertTrue(readinessPanel.contains("Text(fanWriteBlockedWhileHotRecoverySuggestion)"))
        XCTAssertTrue(readinessPanel.contains(".background(Color.orange.opacity(0.12), in: RoundedRectangle(cornerRadius: 8))"))
    }

    func testMainWindowManualPendingHelperAttentionIsWired() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let readinessPanel = try read("Sources/Vifty/ReadinessModePanel.swift")
        let controlSessionCard = try read("Sources/Vifty/ControlSessionCard.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var manualControlAttentionSummary: String?"))
        XCTAssertTrue(appModel.contains("request pending · fan writes blocked"))
        XCTAssertTrue(appModel.contains("Use \\(autoRestoreActionTitle) to stop retries; copy support evidence if repair does not clear it."))
        XCTAssertTrue(appModel.contains("var modeSelectionActionRestoresAuto: Bool"))
        XCTAssertTrue(appModel.contains("selectedMode == .auto || manualControlAttentionSummary != nil"))
        XCTAssertTrue(appModel.contains("var modeSelectionActionDisabled: Bool"))
        XCTAssertTrue(appModel.contains("var helperSupportEvidenceContext: HelperSupportEvidenceContext"))
        XCTAssertTrue(appModel.contains("hotFanWrites="))
        XCTAssertTrue(appModel.contains("controlOwner="))
        XCTAssertTrue(readinessPanel.contains("if let manualControlAttentionSummary"))
        XCTAssertTrue(readinessPanel.contains("hourglass.badge.exclamationmark"))
        XCTAssertTrue(contentView.contains("model.performModeSelectionAction()"))
        XCTAssertTrue(controlSessionCard.contains(".disabled(presentation.primaryActionDisabled)"))
        XCTAssertTrue(readinessPanel.contains("if let manualControlAttentionRecoverySuggestion"))
        XCTAssertTrue(readinessPanel.contains("Text(manualControlAttentionRecoverySuggestion)"))
    }

    func testFixedRPMPerFanEditorShowsFanSpecificRanges() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let fanControlPanel = try read("Sources/Vifty/FanControlPanel.swift")

        XCTAssertTrue(fanControlPanel.contains("Toggle(\"Per-fan targets\", isOn: $usePerFanFixedRPM)"))
        XCTAssertTrue(fanControlPanel.contains(".accessibilityLabel(\"Per-fan fixed RPM targets\")"))
        XCTAssertTrue(fanControlPanel.contains(".accessibilityHint(\"Set separate fixed RPM targets for each fan.\")"))
        XCTAssertTrue(fanControlPanel.contains("let controllableFans = fans.filter(\\.controllable)"))
        XCTAssertTrue(fanControlPanel.contains("ensureFixedFanTargets(controllableFans)"))
        XCTAssertTrue(fanControlPanel.contains("let targetRPM = fixedFanTargetRPM(fan)"))
        XCTAssertTrue(fanControlPanel.contains("let targetPercent = fixedFanTargetPercent(fan)"))
        XCTAssertTrue(fanControlPanel.contains("in: Double(fan.minimumRPM)...Double(fan.maximumRPM)"))
        XCTAssertTrue(fanControlPanel.contains("setFixedFanRPM(Int(value.rounded()), fan)"))
        XCTAssertTrue(fanControlPanel.contains("commitFixedFanTargets()"))
        XCTAssertTrue(fanControlPanel.contains(".accessibilityLabel(\"Fixed RPM target\")"))
        XCTAssertTrue(fanControlPanel.contains("markDraftPending()"))
        XCTAssertTrue(fanControlPanel.contains("private struct CompactFanOverrideEditor: View"))
        XCTAssertTrue(fanControlPanel.contains("Stepper(value: startBinding, in: fan.minimumRPM...fan.maximumRPM, step: 50)"))
        XCTAssertFalse(contentView.contains("model.applyModeSelection()"))
    }

    func testCurveEditorShowsDraggableChartForActualFanCurves() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let fanControlPanel = try read("Sources/Vifty/FanControlPanel.swift")
        let chartView = try read("Sources/Vifty/FanCurveChartEditor.swift")

        XCTAssertTrue(fanControlPanel.contains("FanCurveChartEditor("))
        XCTAssertTrue(fanControlPanel.contains("startTemp: $curveStartTemp"))
        XCTAssertTrue(fanControlPanel.contains("fanOverrides: fanOverrides"))
        XCTAssertTrue(chartView.contains("struct FanCurveChartEditor: View"))
        XCTAssertFalse(contentView.contains("private struct FanCurveChartEditor: View"))
        XCTAssertTrue(chartView.contains("private let chartHeight: CGFloat = 272"))
        XCTAssertTrue(chartView.contains(".frame(height: chartHeight)"))
        XCTAssertFalse(contentView.contains(".frame(height: 184)"))
        XCTAssertTrue(chartView.contains("private var liveCurveTargetText: String?"))
        XCTAssertTrue(chartView.contains("Text(liveCurveTargetText)"))
        XCTAssertTrue(chartView.contains("let targetRPM = targetRPM(at: liveTemperature, points: basePoints)"))
        XCTAssertTrue(chartView.contains("return \"Live \\(TemperatureDisplayFormatter.whole(liveTemperature)) -> Base \\(formattedRPM(targetRPM))\""))
        let chartGeometry = try read("Sources/Vifty/FanCurveChartGeometry.swift")
        XCTAssertTrue(chartGeometry.contains("struct FanCurveChartGeometry"))
        XCTAssertTrue(chartGeometry.contains("func targetRPM(at temperature: Double, points: [FanCurveChartValue]) -> Int"))
        XCTAssertTrue(chartView.contains("private var chartGeometry: FanCurveChartGeometry"))
        XCTAssertFalse(contentView.contains("Text(\"Live: \\(sensor.celsius"))
        XCTAssertTrue(chartView.contains("DragGesture(minimumDistance: 0)"))
        XCTAssertTrue(chartView.contains("setCurvePoint(point, from: value.location, in: geometry.size)"))
        XCTAssertTrue(chartView.contains("private var chartPresentation: FanCurveChartPresentation"))
        XCTAssertTrue(chartView.contains("private var fanCurveSeries: [FanCurveSeriesPresentation]"))
        XCTAssertTrue(chartView.contains("chartPresentation.series"))
        XCTAssertTrue(chartView.contains("ForEach(fanCurveSeries.filter { !$0.matchesBase })"))
        XCTAssertTrue(chartView.contains("fanSeriesEndpointMarkers(series.points"))
        XCTAssertTrue(chartView.contains("series.matchesBase ? \"\\(series.name) · Matches base\" : series.name"))
        XCTAssertTrue(chartView.contains("chartLegendSwatch(.accentColor, label: \"Base\", dashed: false)"))
        XCTAssertTrue(chartView.contains("chartLegendSwatch("))
        XCTAssertLessThan(
            chartView.range(of: "drawCurve(basePoints, in: geometry.size)")!.lowerBound,
            chartView.range(of: "ForEach(fanCurveSeries.filter { !$0.matchesBase })")!.lowerBound
        )
        XCTAssertFalse(contentView.contains("label: fanCurveLabel(for: fan)"))
        XCTAssertFalse(contentView.contains("labelOffsetIndex: offset"))
        XCTAssertTrue(chartView.contains("drawCurve(series.points, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointValueLabels(for: series, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointValueLabels(for: baseCurveValueLabelSeries, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("private var baseCurveValueLabelSeries: FanCurveChartSeries"))
        XCTAssertFalse(contentView.contains("labelOffsetIndex: fanCurveSeries.count"))
        XCTAssertFalse(contentView.contains("if fanCurveSeries.isEmpty {"))
        XCTAssertFalse(contentView.contains("private func baseCurvePointValueLabels(in size: CGSize) -> some View"))
        XCTAssertFalse(contentView.contains("private func baseLabelPosition(for point: FanCurveChartPoint, pointIndex: Int, in size: CGSize) -> CGPoint"))
        XCTAssertFalse(contentView.contains("private func labelPosition(for point: FanCurveChartPoint, pointIndex: Int, seriesIndex: Int, in size: CGSize) -> CGPoint"))
        XCTAssertTrue(chartView.contains("chartAxisLabels(in: geometry.size)"))
        XCTAssertTrue(chartView.contains("chartAxisUnitLabels(in: geometry.size)"))
        XCTAssertTrue(chartView.contains("@State private var activeChartPoint: CurveChartPointKind?"))
        XCTAssertTrue(chartView.contains("if let activePoint = activeBasePoint"))
        XCTAssertTrue(chartView.contains("curvePointAxisGuides(for: [activePoint], color: .accentColor, in: geometry.size)"))
        XCTAssertTrue(chartView.contains("curvePointAxisValueLabels(for: [activePoint], color: .accentColor, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointAxisGuides(for: basePoints, color: .accentColor, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointAxisValueLabels(for: basePoints, color: .accentColor, in: geometry.size)"))
        XCTAssertTrue(chartView.contains("CurveChartAxisValue(text: rpmTickLabel(Int(rpmUpper.rounded()))"))
        XCTAssertTrue(chartView.contains("CurveChartAxisValue(text: temperatureTickLabel(Int(tempRange.upperBound.rounded()))"))
        XCTAssertTrue(chartView.contains("rpmTickLabel(Int(rpmUpper.rounded()))"))
        XCTAssertTrue(chartView.contains("temperatureTickLabel(Int(tempRange.upperBound.rounded()))"))
        XCTAssertTrue(chartView.contains("CurveChartAxisTitle(text: \"RPM\")"))
        XCTAssertTrue(chartView.contains("CurveChartAxisTitle(text: \"Temp °C\")"))
        XCTAssertTrue(chartView.contains("CurveChartAxisReadout(text: point.rpmText, color: color"))
        XCTAssertTrue(chartView.contains("CurveChartAxisReadout(text: point.temperatureText, color: color"))
        XCTAssertTrue(chartView.contains("private func rpmAxisReadoutPosition(near pointPosition: CGPoint, pointIndex: Int, in rect: CGRect) -> CGPoint"))
        XCTAssertTrue(chartView.contains("private func temperatureAxisReadoutPosition(near pointPosition: CGPoint, pointIndex: Int, in rect: CGRect) -> CGPoint"))
        XCTAssertTrue(chartView.contains("private struct CurveChartAxisTitle: View"))
        XCTAssertTrue(chartView.contains("private struct CurveChartAxisReadout: View"))
        XCTAssertFalse(contentView.contains("private func fanCurveLabel(for fan: Fan) -> String"))
        XCTAssertTrue(chartView.contains("liveTemperatureLabel(temperature, in: size)"))
        XCTAssertTrue(chartView.contains("ChartHandle("))
        XCTAssertTrue(chartView.contains("label: point.label"))
        XCTAssertTrue(chartView.contains("valueText: value.chartValueText"))
        XCTAssertTrue(chartView.contains("showsValueLabel: activeChartPoint == point"))
        XCTAssertTrue(chartView.contains("valueLabelOffsetY: activeHandleLabelOffsetY(for: value)"))
        XCTAssertTrue(chartView.contains("onHoverChanged: { isHovering in"))
        XCTAssertTrue(chartView.contains("activeChartPoint = isHovering ? point : nil"))
        XCTAssertTrue(chartView.contains("activeChartPoint = point"))
        XCTAssertTrue(chartView.contains("setCurvePoint(point, from: value.location, in: geometry.size)"))
        XCTAssertTrue(chartView.contains(".onEnded { _ in activeChartPoint = nil }"))
        XCTAssertFalse(contentView.contains("valueLabelOffsetY: valueLabelOffsetY(for: value)"))
        XCTAssertTrue(chartView.contains("accessibilityValueText: value.accessibilityValueText"))
        XCTAssertFalse(contentView.contains("private struct ChartHandleValueLabel: View"))
        XCTAssertTrue(chartView.contains("private struct CurveChartHandleValueLabel: View"))
        XCTAssertTrue(chartView.contains("Text(valueText)"))
        XCTAssertTrue(chartView.contains("private func activeHandleLabelOffsetY(for point: FanCurveChartPoint) -> CGFloat"))
        XCTAssertFalse(contentView.contains("private func valueLabelOffsetY(for point: FanCurveChartPoint) -> CGFloat"))
        XCTAssertTrue(chartView.contains("Text(label)"))
        XCTAssertTrue(chartView.contains(".help(\"\\(label): \\(TemperatureDisplayFormatter.whole(temperature)) · \\(Int(rpm.rounded()).formatted(.number.grouping(.automatic))) RPM\")"))
        XCTAssertTrue(chartView.contains(".accessibilityHint(\"Drag to edit with a pointer. Use Exact points below for keyboard editing.\")"))
        XCTAssertTrue(chartView.contains("value.chartValueText"))
        XCTAssertFalse(contentView.contains("private struct CurveChartSeriesPointLabel: View"))
        XCTAssertFalse(contentView.contains("curvePointValueLabels(for: series, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("curvePointValueLabels(for: baseCurveValueLabelSeries, in: geometry.size)"))
        XCTAssertFalse(contentView.contains("Text(point.chartValueText)"))
        XCTAssertFalse(contentView.contains("Text(\"\\(seriesLabel) \\(point.label)\")"))
        XCTAssertTrue(chartView.contains("private var curvePointSummaryStrip: some View"))
        XCTAssertTrue(chartView.contains("ForEach(basePoints) { point in"))
        XCTAssertTrue(chartView.contains("CurveChartPointSummaryChip(point: point)"))
        XCTAssertTrue(chartView.contains("private struct CurveChartPointSummaryChip: View"))
        XCTAssertTrue(chartView.contains("if !fanCurveSeries.isEmpty"))
        XCTAssertTrue(chartView.contains("chartLegendSwatch(.accentColor, label: \"Base\", dashed: false)"))
        XCTAssertTrue(chartView.contains("var chartValueText: String"))
        XCTAssertTrue(chartView.contains("var temperatureText: String"))
        XCTAssertTrue(chartView.contains("var rpmText: String"))
        XCTAssertTrue(chartView.contains("var accessibilityValueText: String"))
        XCTAssertTrue(chartView.contains(".accessibilityValue(accessibilityValueText)"))
        XCTAssertTrue(chartView.contains(".accessibilityHidden(true)"))
        XCTAssertFalse(chartView.contains(".accessibilityValue(point.accessibilityValueText)"))
        XCTAssertTrue(chartView.contains("private struct CurveChartAxisValue: View"))
        XCTAssertTrue(fanControlPanel.contains("DisclosureGroup(\"Exact points\")"))
        XCTAssertTrue(fanControlPanel.contains("CurvePointEditor(title: \"Start\""))
        XCTAssertFalse(contentView.contains("import Charts"))
    }

    func testFanStatusRowsAndSensorSelectionRemainPresentationOnly() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let fanControlPanel = try read("Sources/Vifty/FanControlPanel.swift")
        let presentation = try read("Sources/Vifty/FanStatusPresentation.swift")
        let fanStatusRow = try read("Sources/Vifty/FanStatusRow.swift")
        let sensorList = try read("Sources/Vifty/SensorListView.swift")

        XCTAssertTrue(presentation.contains("struct FanStatusPresentation: Equatable"))
        XCTAssertTrue(presentation.contains("appliedTargetRPM: Int?"))
        XCTAssertTrue(presentation.contains("draftTargetRPM: Int?"))
        XCTAssertTrue(presentation.contains("abs(fan.currentRPM - $0) >= 75"))
        XCTAssertTrue(fanControlPanel.contains("appliedTargetRPM: appliedTargetRPM(fan)"))
        XCTAssertTrue(fanControlPanel.contains("draftTargetRPM: draftTargetRPMPreview(fan)"))
        XCTAssertFalse(fanControlPanel.contains("private struct FanRow: View"))
        XCTAssertTrue(fanStatusRow.contains("struct FanStatusRow: View"))
        XCTAssertTrue(fanStatusRow.contains("let presentation: FanStatusPresentation"))
        XCTAssertTrue(fanStatusRow.contains(".accessibilityElement(children: .ignore)"))
        XCTAssertTrue(fanStatusRow.contains(".accessibilityValue(accessibilityValue)"))
        XCTAssertTrue(fanStatusRow.contains(".accessibilityHidden(true)"))
        XCTAssertTrue(sensorList.contains("let selectedSensorID: String?"))
        XCTAssertTrue(sensorList.contains("let onSelectSensor: (String) -> Void"))
        XCTAssertFalse(sensorList.contains("@Binding"))
        XCTAssertTrue(contentView.contains("onSelectSensor: selectSensor"))
        XCTAssertTrue(contentView.contains("model.selectedSensorID = sensorID"))
        XCTAssertTrue(contentView.contains("model.markFanControlDraftPending()"))
    }

    func testMainWindowNotificationSettingsAreWired() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let settingsView = try read("Sources/Vifty/ViftySettingsView.swift")
        let notificationSettings = try read("Sources/Vifty/SettingsNotificationsView.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let notifications = try read("Sources/Vifty/LocalNotifications.swift")
        let notificationHistory = try read("Sources/Vifty/LocalNotificationHistoryStore.swift")

        XCTAssertTrue(notificationSettings.contains("Toggle(\"Helper failure\", isOn: $model.notificationSettings.helperFailure)"))
        XCTAssertTrue(notificationSettings.contains("Toggle(\"High thermal pressure\", isOn: $model.notificationSettings.elevatedThermalPressure)"))
        XCTAssertTrue(notificationSettings.contains("Toggle(\"Auto restore failure\", isOn: $model.notificationSettings.autoRestoreFailure)"))
        XCTAssertTrue(notificationSettings.contains("Toggle(\"Plugged-in battery drain\", isOn: $model.notificationSettings.pluggedInBatteryDrain)"))
        XCTAssertTrue(notificationSettings.contains("Toggle(\"Agent cooling attention\", isOn: $model.notificationSettings.agentCoolingAttention)"))
        XCTAssertTrue(contentView.contains("SettingsLink"))
        XCTAssertTrue(settingsView.contains("SettingsNotificationsView(model: model)"))
        XCTAssertFalse(menuBarView.contains("Label(\"Notifications\", systemImage: \"bell\")"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Helper failure\", isOn: $model.notificationSettings.helperFailure)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"High thermal pressure\", isOn: $model.notificationSettings.elevatedThermalPressure)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Auto restore failure\", isOn: $model.notificationSettings.autoRestoreFailure)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Plugged-in battery drain\", isOn: $model.notificationSettings.pluggedInBatteryDrain)"))
        XCTAssertFalse(menuBarView.contains("Toggle(\"Agent cooling attention\", isOn: $model.notificationSettings.agentCoolingAttention)"))
        XCTAssertTrue(appModel.contains("notificationMinimumInterval: TimeInterval = 30 * 60"))
        XCTAssertTrue(appModel.contains("notificationTransitionState.shouldNotify"))
        XCTAssertTrue(appModel.contains("notificationHistoryStore.isCoolingDown"))
        XCTAssertTrue(appModel.contains("sustainedThermalPressureInterval: TimeInterval = 60"))
        XCTAssertTrue(notifications.contains("UNUserNotificationCenter"))
        XCTAssertTrue(notifications.contains("identifier: notification.requestIdentifier"))
        XCTAssertTrue(notifications.contains("removeDeliveredNotifications(withIdentifiers:"))
        XCTAssertTrue(notifications.contains("removePendingNotificationRequests(withIdentifiers:"))
        XCTAssertFalse(notifications.contains("UUID().uuidString"))
        XCTAssertTrue(notificationHistory.contains("notification-history.json"))
        XCTAssertTrue(notificationHistory.contains("0o700"))
        XCTAssertTrue(notificationHistory.contains("0o600"))
        XCTAssertFalse(notifications.contains("content.sound = .default"))
        XCTAssertTrue(notifications.contains("XCTestConfigurationFilePath"))
        XCTAssertTrue(notifications.contains("processName == \"xctest\""))
        XCTAssertTrue(notifications.contains("static let disabled = LocalNotificationSettings()"))
    }

    func testGlobalAutoActionsUseContextualRequestCopy() throws {
        let controlSessionCard = try read("Sources/Vifty/ControlSessionCard.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var autoRestoreActionTitle: String"))
        XCTAssertTrue(appModel.contains("var modeSelectionActionTitle: String"))
        XCTAssertTrue(appModel.contains("helperWritePathBlockedSummary == nil ? \"Auto\" : \"Request Auto\""))
        XCTAssertTrue(appModel.contains("Request Auto restore; the write cannot be confirmed until the helper responds"))
        XCTAssertTrue(controlSessionCard.contains("Label(presentation.primaryActionTitle"))
        XCTAssertTrue(controlSessionCard.contains(".help(presentation.primaryActionHelp)"))
        XCTAssertFalse(controlSessionCard.contains("Label(\"Apply\""))
        XCTAssertTrue(menuBarView.contains("Button(\"Restore Auto\", action: onRestoreAuto)"))
        XCTAssertTrue(menuBarView.contains(".help(\"Restore automatic macOS fan control.\")"))
        XCTAssertFalse(menuBarView.contains("model.restoreAuto()"))
    }

    func testMenuBarPresentationDoesNotForwardControlSessionDetails() throws {
        let presentation = try read("Sources/Vifty/MenuBarPanelPresentation.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertFalse(presentation.contains("controlSession.summary"))
        XCTAssertFalse(presentation.contains("controlSession.detail"))
        XCTAssertFalse(presentation.contains("controlSession.expiryText"))
        XCTAssertFalse(menuBarView.contains("presentation.detailText"))
    }

    private func read(_ relativePath: String) throws -> String {
        let url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent(relativePath)
        return try String(contentsOf: url, encoding: .utf8)
    }
}
