import Foundation
import XCTest

final class AppSourceRegressionTests: XCTestCase {
    func testMenuBarHelperHealthOffersRepairAndRefreshesAfterAction() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(menuBarView.contains("@StateObject private var daemonInstaller = DaemonInstaller()"))
        XCTAssertTrue(menuBarView.contains("@State private var helperRefreshTask: Task<Void, Never>?"))
        XCTAssertTrue(menuBarView.contains("Button(daemonInstaller.actionTitle)"))
        XCTAssertTrue(menuBarView.contains("if model.helperRepairActionAvailable {"))
        XCTAssertTrue(menuBarView.contains(".disabled(!daemonInstaller.canInstall)"))
        XCTAssertTrue(menuBarView.contains("daemonInstaller.installOrOpenApproval()"))
        XCTAssertTrue(menuBarView.contains("try? await Task.sleep(for: .milliseconds(750))"))
        XCTAssertTrue(menuBarView.contains("daemonInstaller.refresh()"))
        XCTAssertTrue(menuBarView.contains("daemonInstaller.actionDescription"))
        XCTAssertTrue(menuBarView.contains("Text(daemonInstaller.helperStatusSummary)"))
        XCTAssertTrue(menuBarView.contains("if let context = model.helperInstallRuntimeContext"))
        XCTAssertTrue(menuBarView.contains("@State private var helperDiagnosticsCopied = false"))
        XCTAssertTrue(menuBarView.contains("model.helperHealthMenuSummary"))
        XCTAssertTrue(menuBarView.contains("model.helperMenuRecoverySuggestion"))
        XCTAssertFalse(menuBarView.contains("model.helperRecoverySuggestion"))
        XCTAssertTrue(menuBarView.contains("Button {\n                            copyHelperDiagnosticsCommand()\n                        } label: {\n                            Label(\"Copy Support Evidence\", systemImage: \"doc.on.doc\")"))
        XCTAssertTrue(menuBarView.contains("HelperDiagnosticsSupport.copySupportEvidenceCommand(context: model.helperSupportEvidenceContext)"))
        XCTAssertTrue(menuBarView.contains(".help(HelperDiagnosticsSupport.copyHelp)"))
        XCTAssertTrue(menuBarView.contains("Text(HelperDiagnosticsSupport.copiedMessage)"))
        XCTAssertEqual(menuBarView.components(separatedBy: "await model.pollOnce()").count - 1, 2)
        XCTAssertTrue(menuBarView.contains("helperRefreshTask?.cancel()"))
    }

    func testOperatorSurfacesUseFilteredLastError() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var visibleLastError: String?"))
        XCTAssertTrue(appModel.contains("lastErrorIsCoveredByHelperRecovery"))
        XCTAssertTrue(menuBarView.contains("if let error = model.visibleLastError"))
        XCTAssertTrue(contentView.contains("if let error = model.visibleLastError"))
        XCTAssertFalse(menuBarView.contains("if let error = model.lastError"))
        XCTAssertFalse(contentView.contains("if let error = model.lastError"))
    }

    func testMainWindowHelperHealthShowsRepairAndReadOnlyDiagnosticsActions() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("daemonInstaller.actionDescription"))
        XCTAssertTrue(contentView.contains("Text(daemonInstaller.helperStatusSummary)"))
        XCTAssertTrue(contentView.contains("if let context = model.helperInstallRuntimeContext"))
        XCTAssertTrue(contentView.contains("@State private var helperDiagnosticsCopied = false"))
        XCTAssertTrue(contentView.contains("if model.helperRepairActionAvailable || model.helperHealthNeedsAttention {"))
        XCTAssertTrue(contentView.contains("if model.helperRepairActionAvailable {\n                            Button(daemonInstaller.actionTitle)"))
        XCTAssertTrue(contentView.contains("Button {\n                            copyHelperDiagnosticsCommand()\n                        } label: {\n                            Label(\"Copy Support Evidence\", systemImage: \"doc.on.doc\")"))
        XCTAssertTrue(contentView.contains("HelperDiagnosticsSupport.copySupportEvidenceCommand(context: model.helperSupportEvidenceContext)"))
        XCTAssertTrue(contentView.contains(".help(HelperDiagnosticsSupport.copyHelp)"))
        XCTAssertTrue(contentView.contains("Text(HelperDiagnosticsSupport.copiedMessage)"))
        XCTAssertTrue(contentView.contains("Text(suggestion)"))
        XCTAssertTrue(contentView.contains(".fixedSize(horizontal: false, vertical: true)"))
    }

    func testAgentWorkflowRuleCanBeCopiedFromMainWindowAndMenuBar() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(contentView.contains("@State private var agentRuleCopied = false"))
        XCTAssertTrue(contentView.contains("@State private var agentCommandCopied = false"))
        XCTAssertTrue(contentView.contains("agentWorkflowSettings"))
        XCTAssertTrue(contentView.contains("Label(\"Agent workflows\", systemImage: \"terminal\")"))
        XCTAssertTrue(contentView.contains("Label(\"Copy Command\", systemImage: \"terminal\")"))
        XCTAssertTrue(contentView.contains("AgentWorkflowSupport.WorkloadCommandMode.allCases"))
        XCTAssertTrue(contentView.contains("AgentWorkflowSupport.safeWorkloadCommandTemplates"))
        XCTAssertTrue(contentView.contains("copyAgentWorkflowCommand(template, mode: mode)"))
        XCTAssertTrue(contentView.contains("AgentWorkflowSupport.copyWorkloadCommand(template, mode: mode)"))
        XCTAssertTrue(contentView.contains(".help(AgentWorkflowSupport.copyCommandHelp)"))
        XCTAssertTrue(contentView.contains("Label(\"Copy Agent Rule\", systemImage: \"doc.on.doc\")"))
        XCTAssertTrue(contentView.contains("AgentWorkflowSupport.copyAgentRule()"))
        XCTAssertTrue(contentView.contains(".help(AgentWorkflowSupport.copyHelp)"))
        XCTAssertTrue(contentView.contains("Text(AgentWorkflowSupport.copiedMessage)"))
        XCTAssertTrue(contentView.contains("Text(AgentWorkflowSupport.copiedCommandMessage)"))

        XCTAssertTrue(menuBarView.contains("@State private var agentRuleCopied = false"))
        XCTAssertTrue(menuBarView.contains("@State private var agentCommandCopied = false"))
        XCTAssertTrue(menuBarView.contains("Label(\"Copy Safe Command\", systemImage: \"terminal\")"))
        XCTAssertTrue(menuBarView.contains("AgentWorkflowSupport.WorkloadCommandMode.allCases"))
        XCTAssertTrue(menuBarView.contains("AgentWorkflowSupport.safeWorkloadCommandTemplates"))
        XCTAssertTrue(menuBarView.contains("copyAgentWorkflowCommand(template, mode: mode)"))
        XCTAssertTrue(menuBarView.contains("AgentWorkflowSupport.copyWorkloadCommand(template, mode: mode)"))
        XCTAssertTrue(menuBarView.contains(".help(AgentWorkflowSupport.copyCommandHelp)"))
        XCTAssertTrue(menuBarView.contains("Label(\"Copy Agent Rule\", systemImage: \"terminal\")"))
        XCTAssertTrue(menuBarView.contains("AgentWorkflowSupport.copyAgentRule()"))
        XCTAssertTrue(menuBarView.contains(".help(AgentWorkflowSupport.copyHelp)"))
        XCTAssertTrue(menuBarView.contains("Text(AgentWorkflowSupport.copiedMessage)"))
        XCTAssertTrue(menuBarView.contains("Text(AgentWorkflowSupport.copiedCommandMessage)"))
    }

    func testMainWindowHeaderAndEmptyFanFallbackGateRepairActions() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("if model.helperRepairActionAvailable {\n                Button {\n                    performHelperAction()"))
        XCTAssertTrue(contentView.contains("Label(\"Diagnostics only\", systemImage: \"doc.text.magnifyingglass\")"))
        XCTAssertTrue(contentView.contains("if model.helperRepairActionAvailable {\n                        Button {\n                            performHelperAction()"))
        XCTAssertTrue(contentView.contains("} else {\n                        Button {\n                            copyHelperDiagnosticsCommand()"))
        XCTAssertTrue(contentView.contains("Label(\"Copy Support Evidence\", systemImage: \"doc.on.doc\")\n                                .frame(maxWidth: 260)"))
    }

    func testMainWindowPanesAreIndependentlyScrollableAndFillAvailableHeight() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("private var mainContent: some View"))
        XCTAssertTrue(contentView.contains("GeometryReader { proxy in"))
        XCTAssertTrue(contentView.contains("let layout = MainWindowLayout.resolve(width: proxy.size.width, height: proxy.size.height)"))
        XCTAssertTrue(contentView.contains("switch layout.mode"))
        XCTAssertTrue(contentView.contains("case .stacked:"))
        XCTAssertTrue(contentView.contains("VStack(alignment: .leading, spacing: 0)"))
        XCTAssertTrue(contentView.contains("sensorsPane(compact: layout.compactTelemetry)"))
        XCTAssertTrue(contentView.contains("case .split:"))
        XCTAssertTrue(contentView.contains("HStack(alignment: .top, spacing: 0)"))
        XCTAssertTrue(contentView.contains(".scrollIndicators(.visible)"))
        XCTAssertTrue(contentView.contains(".frame(minWidth: 360, idealWidth: 400, maxWidth: 420, minHeight: proxy.size.height, maxHeight: proxy.size.height)"))
        XCTAssertTrue(contentView.contains("Divider()\n                            .frame(height: proxy.size.height)"))
        XCTAssertTrue(contentView.contains(".background(Color.secondary.opacity(0.035))"))
        XCTAssertTrue(contentView.contains("TelemetryOverviewPanel(power: model.powerSnapshot, history: model.telemetryHistory, compact: compact)"))
        XCTAssertFalse(contentView.contains("PowerPanel(snapshot: power, compact: compact)"))
        XCTAssertFalse(contentView.contains("HistoryPanel(history: model.telemetryHistory, compact: compact)"))
        XCTAssertTrue(contentView.contains("DisclosureGroup(\"All sensors\")"))
        XCTAssertTrue(contentView.contains("ForEach(sensors) { sensor in"))
        XCTAssertTrue(contentView.contains("SensorRow(sensor: sensor, selected: sensor.id == model.selectedSensor?.id, compact: true)"))
        XCTAssertFalse(contentView.contains("let visibleSensors = topTemperatureSensors"))
        XCTAssertFalse(contentView.contains("ForEach(visibleSensors)"))
        XCTAssertFalse(contentView.contains("private func topTemperatureSensors"))
        XCTAssertTrue(contentView.contains(".frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)"))
        XCTAssertTrue(contentView.contains("PowerDisplayFormatter.panelHeadline(for: power)"))
        XCTAssertTrue(contentView.contains("PowerDetailDisclosure(snapshot: power, compact: compact)"))
        XCTAssertTrue(contentView.contains("PowerDisplayFormatter.adapterDescription(for: adapter)"))
        XCTAssertFalse(contentView.contains("PowerMetric(label: summary.latestTemperatureLabel"))
        XCTAssertFalse(contentView.contains("if let temperatureText = summary.latestTemperatureText"))
        XCTAssertFalse(contentView.contains("if let sensors = model.snapshot?.temperatureSensors, !sensors.isEmpty {\n                ScrollView {"))
    }

    func testHistoryPanelShowsLocalSparklineVisualization() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("TelemetryHistorySummary("))
        XCTAssertTrue(contentView.contains("TelemetryHistoryChart(summary: summary, compact: compact)"))
        XCTAssertTrue(contentView.contains("private struct TelemetryHistoryChart: View"))
        XCTAssertTrue(contentView.contains("summary.sampleWindowText"))
        XCTAssertTrue(contentView.contains("parts.append(\"\\(summary.sampleCountText) · last \\(sampleWindowText)\")"))
        XCTAssertTrue(contentView.contains("title: \"Temp\""))
        XCTAssertTrue(contentView.contains("startValueText: summary.temperatureValues.first.map(TelemetryHistorySummary.temperatureText)"))
        XCTAssertTrue(contentView.contains("currentValueText: summary.latestTemperatureText"))
        XCTAssertTrue(contentView.contains("title: summary.fanRPMSparklineTitle"))
        XCTAssertTrue(contentView.contains("startValueText: summary.fanRPMValues.first.map(TelemetryHistorySummary.fanRPMText)"))
        XCTAssertTrue(contentView.contains("currentValueText: summary.latestFanRPMText"))
        XCTAssertFalse(contentView.contains("title: \"Fan\""))
        XCTAssertTrue(contentView.contains("title: \"Power\""))
        XCTAssertTrue(contentView.contains("startValueText: nil"))
        XCTAssertTrue(contentView.contains("changeText: summary.temperatureChangeText"))
        XCTAssertTrue(contentView.contains("changeText: summary.fanRPMChangeText"))
        XCTAssertTrue(contentView.contains("changeText: summary.batteryPowerChangeText"))
        XCTAssertTrue(contentView.contains("summaryText: summary.thermalPressureSummaryText"))
        XCTAssertTrue(contentView.contains("private struct SparklinePath: View"))
        XCTAssertTrue(contentView.contains("startValueLabelText: startValueText"))
        XCTAssertTrue(contentView.contains("SparklineValueBadge(text: startValueLabelText, color: color)"))
        XCTAssertTrue(contentView.contains("SparklineValueBadge(text: valueLabelText, color: color)"))
        XCTAssertTrue(contentView.contains("private func startLabelPosition(near point: CGPoint, in size: CGSize) -> CGPoint"))
        XCTAssertTrue(contentView.contains("private func labelPosition(near point: CGPoint, in size: CGSize) -> CGPoint"))
        XCTAssertTrue(contentView.contains("private func smoothedValues(_ rawValues: [Double]) -> [Double]"))
        XCTAssertTrue(contentView.contains("path.addQuadCurve(to: midPoint, control: previousPoint)"))
        XCTAssertFalse(contentView.contains("import Charts"))
        XCTAssertFalse(contentView.contains("private func signedWattRangeText"))
        XCTAssertFalse(contentView.contains("UserDefaults.standard.set(history"))
    }

    func testMenuBarShowsReadOnlyRecentTelemetryTrend() throws {
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(appModel.contains("var recentTelemetryTrendSummary: String?"))
        XCTAssertTrue(appModel.contains("TelemetryHistorySummary("))
        XCTAssertTrue(appModel.contains("sampleLimit: 90"))
        XCTAssertTrue(appModel.contains("thermalPressureLimit: 24"))
        XCTAssertTrue(menuBarView.contains("if let recentTelemetryTrendSummary = model.recentTelemetryTrendSummary"))
        XCTAssertTrue(menuBarView.contains("Label(recentTelemetryTrendSummary, systemImage: \"chart.xyaxis.line\")"))
        XCTAssertFalse(appModel.contains("UserDefaults.standard.set(telemetryHistory"))
    }

    func testPrivateIOKitBridgeOnlyExportsHIDTemperatureReader() throws {
        let header = try read("Sources/ViftyPrivateIOKit/include/ViftyPrivateIOKit.h")
        let implementation = try read("Sources/ViftyPrivateIOKit/ViftyPrivateIOKit.c")

        XCTAssertTrue(header.contains("ViftyHIDTemperature"))
        XCTAssertTrue(header.contains("ViftyCopyHIDTemperatures"))
        XCTAssertTrue(implementation.contains("int ViftyCopyHIDTemperatures"))
        XCTAssertFalse(header.contains("ViftyOpenSMC"))
        XCTAssertFalse(implementation.contains("ViftyOpenSMC"))
        XCTAssertFalse(implementation.contains("IOServiceOpen"))
        XCTAssertFalse(implementation.contains("AppleSMCKeysEndpoint"))
        XCTAssertFalse(implementation.contains("SMCEndpoint1"))
    }

    func testAppBundleIsDockVisibleAndHasAppIcon() throws {
        let plist = try read("Resources/Info.plist")
        let makefile = try read("Makefile")
        let iconURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent("Resources/ViftyIcon.icns")

        XCTAssertTrue(plist.contains("<key>CFBundleIconFile</key>"))
        XCTAssertTrue(plist.contains("<string>ViftyIcon</string>"))
        XCTAssertFalse(plist.contains("<key>LSUIElement</key>"))
        XCTAssertTrue(makefile.contains("APP_ICON := Resources/ViftyIcon.icns"))
        XCTAssertTrue(makefile.contains("cp \"$(APP_ICON)\" \"$(CONTENTS)/Resources/ViftyIcon.icns\""))
        XCTAssertTrue(FileManager.default.fileExists(atPath: iconURL.path))
    }

    func testMenuBarAgentCoolingSurfaceShowsTitleRecoveryAndContextualAuto() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(menuBarView.contains("Label(model.agentCoolingPanelTitle, systemImage: \"cpu\")"))
        XCTAssertTrue(menuBarView.contains("if let agentCoolingRecoverySuggestion = model.agentCoolingRecoverySuggestion"))
        XCTAssertTrue(menuBarView.contains("Label(agentCoolingRecoverySuggestion, systemImage: \"exclamationmark.triangle\")"))
        XCTAssertTrue(menuBarView.contains("if model.agentCoolingNeedsAttention, model.agentCoolingRestoreActionAvailable {"))
        XCTAssertTrue(menuBarView.contains("Button(model.agentCoolingRestoreActionTitle) {"))
        XCTAssertTrue(menuBarView.contains(".help(model.agentCoolingRestoreActionHelp)"))
    }

    func testMenuBarPowerRowsAndStatusItemDisplayModeAreWired() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let viftyApp = try read("Sources/Vifty/ViftyApp.swift")
        let statusItemController = try read("Sources/Vifty/ViftyStatusItemController.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let appPreferencesStore = try read("Sources/Vifty/AppPreferencesStore.swift")

        XCTAssertTrue(menuBarView.contains("Text(model.menuPanelTitle)"))
        XCTAssertFalse(menuBarView.contains("Text(model.menuTitle)"))
        XCTAssertTrue(menuBarView.contains("if let sensor = model.selectedSensor {"))
        XCTAssertFalse(menuBarView.contains("if let sensor = model.snapshot?.highestTemperature {"))
        XCTAssertTrue(menuBarView.contains("PowerDisplayFormatter.adapterDetail(for: adapter)"))
        XCTAssertFalse(menuBarView.contains("private func adapterDetail(_ adapter: PowerAdapter)"))
        XCTAssertTrue(menuBarView.contains("Picker(\"Default mode\", selection: $model.startupMode)"))
        XCTAssertTrue(menuBarView.contains("Picker(\"Menu bar\", selection: $model.menuBarDisplayMode)"))
        XCTAssertTrue(contentView.contains("private var menuBarDisplaySettings: some View"))
        XCTAssertTrue(contentView.contains("private var startupModeSettings: some View"))
        XCTAssertTrue(contentView.contains("Picker(\"Default mode\", selection: $model.startupMode)"))
        XCTAssertTrue(contentView.contains("Label(\"Menu bar\", systemImage: \"menubar.rectangle\")"))
        XCTAssertTrue(contentView.contains("Picker(\"Menu bar\", selection: $model.menuBarDisplayMode)"))
        XCTAssertTrue(contentView.contains("Picker(\"Codex display\", selection: $model.codexUsageDisplayStyle)"))
        XCTAssertTrue(contentView.contains("ForEach(MenuBarDisplayMode.allCases)"))
        XCTAssertTrue(contentView.contains("ForEach(MenuBarField.allCases)"))
        XCTAssertTrue(contentView.contains("ForEach(CodexUsageDisplayStyle.allCases)"))
        XCTAssertTrue(contentView.contains(".labelsHidden()"))
        XCTAssertFalse(viftyApp.contains("MenuBarExtra {"))
        XCTAssertFalse(viftyApp.contains("MenuBarExtraLabel"))
        XCTAssertTrue(viftyApp.contains("@NSApplicationDelegateAdaptor(ViftyAppDelegate.self) private var appDelegate"))
        XCTAssertTrue(viftyApp.contains("@StateObject private var model: AppModel"))
        XCTAssertTrue(viftyApp.contains("@MainActor\n    init()"))
        XCTAssertTrue(viftyApp.contains("_model = StateObject(wrappedValue: model)"))
        XCTAssertTrue(viftyApp.contains("appDelegate.model = model"))
        XCTAssertTrue(viftyApp.contains("appDelegate.openMainWindowHandler = { openWindow(id: \"main\") }"))
        XCTAssertTrue(viftyApp.contains("model.start()"))
        XCTAssertTrue(viftyApp.contains("Task { @MainActor in\n            await model.primeMenuBarStatusItemTelemetry(maxAttempts: 5)\n        }"))
        XCTAssertTrue(viftyApp.contains("final class ViftyAppDelegate: NSObject, NSApplicationDelegate"))
        XCTAssertTrue(viftyApp.contains("func applicationDidFinishLaunching(_ notification: Notification)"))
        XCTAssertTrue(viftyApp.contains("model.start()\n        Task { @MainActor in\n            await model.primeMenuBarStatusItemTelemetry(maxAttempts: 5)\n        }"))
        XCTAssertTrue(viftyApp.contains("await model.primeMenuBarStatusItemTelemetry(maxAttempts: 5)"))
        XCTAssertTrue(viftyApp.contains("statusItemController = ViftyStatusItemController("))
        XCTAssertTrue(viftyApp.contains("statusItemController?.openMainWindow = { [weak self] in"))
        XCTAssertTrue(statusItemController.contains("NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)"))
        XCTAssertTrue(statusItemController.contains("model.objectWillChange"))
        XCTAssertTrue(statusItemController.contains("updateStatusItem()"))
        XCTAssertTrue(statusItemController.contains("private static let launchPrimeAttempts = 120"))
        XCTAssertTrue(statusItemController.contains("private static let launchPrimeRetryDelay: Duration = .milliseconds(750)"))
        XCTAssertTrue(statusItemController.contains("scheduleTelemetryPrimeIfNeeded()"))
        XCTAssertTrue(menuBarView.contains("Picker(\"Codex display\", selection: $model.codexUsageDisplayStyle)"))
        XCTAssertTrue(statusItemController.contains("model.$menuBarStatusItemRevision"))
        XCTAssertTrue(statusItemController.contains("primeStatusItemUntilTelemetryResolved("))
        XCTAssertTrue(statusItemController.contains("await model.primeMenuBarStatusItemTelemetry(maxAttempts: 1)"))
        XCTAssertTrue(statusItemController.contains("guard model.menuBarLabelNeedsTelemetryPrime else { return }"))
        XCTAssertTrue(statusItemController.contains("await Task.yield()"))
        XCTAssertTrue(statusItemController.contains("MenuBarView(openMainWindow: { [weak self] in"))
        XCTAssertTrue(statusItemController.contains("let statusItemText = resolvedStatusItemText"))
        XCTAssertTrue(statusItemController.contains("enum ViftyStatusItemPresentation"))
        XCTAssertTrue(statusItemController.contains("allowsPlaceholderText: model.menuBarAllowsPlaceholderStatusItemText"))
        XCTAssertTrue(statusItemController.contains("button.title = statusItemText ?? \"\""))
        XCTAssertTrue(statusItemController.contains("statusItem.length = NSStatusItem.variableLength"))
        XCTAssertTrue(statusItemController.contains("button.window?.displayIfNeeded()"))
        XCTAssertTrue(statusItemController.contains("NSImage(systemSymbolName: \"fan\""))
        XCTAssertTrue(appModel.contains("private let preferencesStore: AppPreferencesStore"))
        XCTAssertTrue(appModel.contains("private var activePollTask: Task<Void, Never>?"))
        XCTAssertTrue(appModel.contains("@Published private(set) var menuBarStatusItemRevision = 0"))
        XCTAssertTrue(appModel.contains("refreshMenuBarStatusItemIfNeeded(previousLabel: previousMenuBarLabel)"))
        XCTAssertTrue(appModel.contains("private func performPollOnce() async"))
        XCTAssertTrue(appModel.contains("if let activePollTask {\n            await activePollTask.value\n            return\n        }"))
        XCTAssertFalse(appModel.contains("pollingTask = Task { [weak self]"))
        XCTAssertTrue(appModel.contains("func primeMenuBarStatusItemTelemetry("))
        XCTAssertTrue(appModel.contains("var menuBarStatusItemText: String?"))
        XCTAssertTrue(appModel.contains("var menuBarLabelNeedsTelemetryPrime: Bool"))
        XCTAssertTrue(appModel.contains("var menuBarDisplaysCodexUsage: Bool"))
        XCTAssertTrue(appModel.contains("func setMenuBarCustomField(_ field: MenuBarField, enabled: Bool)"))
        XCTAssertTrue(appModel.contains("func applyStartupModePreferenceIfNeeded() async"))
        XCTAssertTrue(appModel.contains("persistAppPreferences()"))
        XCTAssertTrue(appPreferencesStore.contains("var startupMode: ModeSelection"))
        XCTAssertTrue(appPreferencesStore.contains("app-preferences.json"))
        XCTAssertTrue(appPreferencesStore.contains("legacyDefaults: UserDefaults?"))
        XCTAssertTrue(appPreferencesStore.contains(".posixPermissions: NSNumber(value: 0o700)"))
        XCTAssertTrue(appPreferencesStore.contains(".posixPermissions: NSNumber(value: 0o600)"))
        XCTAssertFalse(appModel.contains("preferences.set("))
    }

    func testLaunchAtLoginToggleIsWiredThroughSystemLoginItems() throws {
        let launchAtLogin = try read("Sources/Vifty/LaunchAtLogin.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")

        XCTAssertTrue(launchAtLogin.contains("SMAppService.mainApp.status"))
        XCTAssertTrue(launchAtLogin.contains("try service.register()"))
        XCTAssertTrue(launchAtLogin.contains("try service.unregister()"))
        XCTAssertTrue(launchAtLogin.contains("SMAppService.openSystemSettingsLoginItems()"))
        XCTAssertTrue(appModel.contains("private let launchAtLoginManager: LaunchAtLoginManaging"))
        XCTAssertTrue(appModel.contains("@Published private(set) var launchAtLoginStatus: LaunchAtLoginStatus = .disabled"))
        XCTAssertTrue(appModel.contains("var launchAtLoginEnabled: Bool"))
        XCTAssertTrue(appModel.contains("func setLaunchAtLoginEnabled(_ enabled: Bool)"))
        XCTAssertTrue(appModel.contains("launchAtLoginError = \"Could not update startup item: \\(error.localizedDescription)\""))
        XCTAssertFalse(appModel.contains("UserDefaults.standard.set(launchAtLogin"))
        XCTAssertFalse(appModel.contains("preferencesStore.save(AppPreferences(\n            launchAtLogin"))
        XCTAssertTrue(contentView.contains("private var launchAtLoginSettings: some View"))
        XCTAssertTrue(contentView.contains("Label(\"Start Vifty at startup\", systemImage: \"power\")"))
        XCTAssertTrue(contentView.contains("Toggle(isOn: launchAtLoginBinding)"))
        XCTAssertTrue(contentView.contains("model.openLaunchAtLoginSettings()"))
        XCTAssertTrue(contentView.contains("model.refreshLaunchAtLoginStatus()"))
        XCTAssertTrue(menuBarView.contains("Toggle(\"Start Vifty at startup\", isOn: launchAtLoginBinding)"))
        XCTAssertTrue(menuBarView.contains("model.openLaunchAtLoginSettings()"))
        XCTAssertTrue(menuBarView.contains("model.refreshLaunchAtLoginStatus()"))
    }

    func testLocalInstallerRestartsRunningAppBeforeCopyingBundle() throws {
        let installScript = try read("scripts/install-vifty.sh")
        let readme = try read("README.md")

        XCTAssertTrue(installScript.contains("QUIT_RUNNING_APP=\"${QUIT_RUNNING_APP:-1}\""))
        XCTAssertTrue(installScript.contains("WAS_RUNNING=0"))
        XCTAssertTrue(installScript.contains("/usr/bin/pgrep -x \"${APP_NAME}\""))
        XCTAssertTrue(installScript.contains("tell application id \"tech.reidar.vifty\" to quit"))
        XCTAssertTrue(installScript.contains("/usr/bin/pkill -x \"${APP_NAME}\""))
        XCTAssertTrue(installScript.contains("quit_running_app_if_needed"))
        XCTAssertTrue(installScript.contains("\"${OPEN_AFTER_INSTALL}\" == \"1\" || \"${WAS_RUNNING}\" == \"1\""))
        XCTAssertTrue(readme.contains("the installer quits and relaunches it from the newly installed bundle"))
    }

    func testLocalInstallerReportsPrivilegedHelperDaemonDrift() throws {
        let installScript = try read("scripts/install-vifty.sh")
        let readme = try read("README.md")

        XCTAssertTrue(installScript.contains("shell_quote()"))
        XCTAssertTrue(installScript.contains("CHECK_HELPER_DAEMON=\"${CHECK_HELPER_DAEMON:-1}\""))
        XCTAssertTrue(installScript.contains("HELPER_TARGET=\"${VIFTY_HELPER_TARGET:-/Library/PrivilegedHelperTools/tech.reidar.vifty.daemon}\""))
        XCTAssertTrue(installScript.contains("report_helper_daemon_status"))
        XCTAssertTrue(installScript.contains("sha256_file \"${bundled_daemon}\""))
        XCTAssertTrue(installScript.contains("sha256_file \"${HELPER_TARGET}\""))
        XCTAssertTrue(installScript.contains("repair_command=\"REPAIR_HELPER_APP=$(shell_quote \"${DEST_APP}\") make repair-helper\""))
        XCTAssertTrue(installScript.contains("Fan helper matches the installed app daemon."))
        XCTAssertTrue(installScript.contains("Fan helper daemon differs from the installed app bundle."))
        XCTAssertTrue(installScript.contains("Open Vifty and choose Reinstall Helper or Repair Helper, or run: ${repair_command}"))
        XCTAssertTrue(installScript.contains("Do that before current-build manual/agent smoke evidence."))
        XCTAssertTrue(installScript.contains("AGENT_RUN_SMOKE_READINESS_JSON=1 make agent-run-smoke-readiness-current-build"))
        XCTAssertFalse(installScript.contains("repair-vifty-helper.sh"))

        XCTAssertTrue(readme.contains("The root LaunchDaemon helper is repaired only after an explicit user-approved action, not silently replaced by the app installer"))
        XCTAssertTrue(readme.contains("performs a read-only helper-daemon hash check"))
        XCTAssertTrue(readme.contains("REPAIR_HELPER_APP=/Applications/Vifty.app make repair-helper"))
        XCTAssertTrue(readme.contains("If the installer falls back to `~/Applications`, use the exact `REPAIR_HELPER_APP=... make repair-helper` command printed by the installer so the helper is repaired from that copied app bundle."))
        XCTAssertTrue(readme.contains("before treating current-build manual or agent smoke evidence as valid"))
    }

    func testLocalInstallerRetriesSwiftPMBuildDatabaseFailuresWithIsolatedBuildPath() throws {
        let installScript = try read("scripts/install-vifty.sh")
        let readme = try read("README.md")

        XCTAssertTrue(installScript.contains("BUILD_LOG=\"$(mktemp -t vifty-install-build.XXXXXX)\""))
        XCTAssertTrue(installScript.contains("is_swiftpm_build_database_error()"))
        XCTAssertTrue(installScript.contains("build\\\\.db|build database|disk I/O error|database is locked"))
        XCTAssertTrue(installScript.contains("build_app_bundle()"))
        XCTAssertTrue(installScript.contains("else\n    build_status=$?\n  fi"))
        XCTAssertTrue(installScript.contains("if [[ -z \"${SWIFT_BUILD_PATH:-}\" ]] && is_swiftpm_build_database_error; then"))
        XCTAssertTrue(installScript.contains("fallback_build_path=\"${TMPDIR:-/tmp}/vifty-install-swiftpm-$$\""))
        XCTAssertTrue(installScript.contains("==> SwiftPM build database failed; retrying with SWIFT_BUILD_PATH=${fallback_build_path}"))
        XCTAssertTrue(installScript.contains("SWIFT_BUILD_PATH=\"${fallback_build_path}\" make app CONFIGURATION=\"${CONFIGURATION}\""))
        XCTAssertTrue(installScript.contains("build_app_bundle"))

        XCTAssertTrue(readme.contains("If SwiftPM's local `.build/build.db` becomes unhealthy, the local installer retries once with an isolated temporary `SWIFT_BUILD_PATH` before failing."))
        XCTAssertTrue(readme.contains("Set `SWIFT_BUILD_PATH` yourself when you want a stable reusable build-product path."))
    }

    func testExplicitHelperRepairScriptPreservesPrivilegedRepairBoundary() throws {
        let script = try read("scripts/repair-vifty-helper.sh")
        let makefile = try read("Makefile")
        let readme = try read("README.md")

        XCTAssertTrue(script.contains("APP_PATH=\"${VIFTY_APP:-/Applications/Vifty.app}\""))
        XCTAssertTrue(script.contains("HELPER_TARGET=\"${VIFTY_HELPER_TARGET:-/Library/PrivilegedHelperTools/tech.reidar.vifty.daemon}\""))
        XCTAssertTrue(script.contains("PLIST_TARGET=\"${VIFTY_DAEMON_PLIST_TARGET:-/Library/LaunchDaemons/tech.reidar.vifty.daemon.plist}\""))
        XCTAssertTrue(script.contains("DRY_RUN=0"))
        XCTAssertTrue(script.contains("--dry-run"))
        XCTAssertTrue(script.contains("This is an explicit operator action and may prompt for administrator approval."))
        XCTAssertTrue(script.contains("It does not request cooling or write fan state directly."))
        XCTAssertTrue(script.contains("do shell script \"/bin/bash \" & quoted form of \"${ADMIN_SCRIPT_PATH}\" with administrator privileges"))
        XCTAssertTrue(script.contains("launchctl bootout system $(shell_quote \"$PLIST_TARGET\") 2>/dev/null || true"))
        XCTAssertTrue(script.contains("helper_tmp=\"\\$(mktemp $(shell_quote \"${HELPER_TARGET}.XXXXXX\"))\""))
        XCTAssertTrue(script.contains("plist_tmp=\"\\$(mktemp $(shell_quote \"${PLIST_TARGET}.XXXXXX\"))\""))
        XCTAssertTrue(script.contains("trap 'rm -f \"\\$helper_tmp\" \"\\$plist_tmp\"' EXIT"))
        XCTAssertTrue(script.contains("chmod 755 \"\\$helper_tmp\""))
        XCTAssertTrue(script.contains("chown root:wheel \"\\$helper_tmp\""))
        XCTAssertTrue(script.contains("chmod 644 \"\\$plist_tmp\""))
        XCTAssertTrue(script.contains("chown root:wheel \"\\$plist_tmp\""))
        XCTAssertTrue(script.contains("xattr -cr \"\\$helper_tmp\" \"\\$plist_tmp\" 2>/dev/null || true"))
        XCTAssertTrue(script.contains("/usr/libexec/PlistBuddy -c 'Delete :BundleProgram' \"\\$plist_tmp\""))
        XCTAssertTrue(script.contains("mv -f \"\\$helper_tmp\" $(shell_quote \"$HELPER_TARGET\")"))
        XCTAssertTrue(script.contains("mv -f \"\\$plist_tmp\" $(shell_quote \"$PLIST_TARGET\")"))
        XCTAssertTrue(script.contains("chmod 600 \"\\$log_path\""))
        XCTAssertTrue(script.contains("chown root:wheel \"\\$log_path\""))
        XCTAssertTrue(script.contains("launchctl bootstrap system $(shell_quote \"$PLIST_TARGET\")"))
        XCTAssertTrue(script.contains("launchctl kickstart -k $(shell_quote \"$SERVICE_TARGET\")"))
        XCTAssertTrue(script.contains("installed helper matches the app bundle."))
        XCTAssertTrue(script.contains("\"$VIFTYCTL\" diagnose --json"))
        XCTAssertFalse(script.contains("ViftyHelper setFixed"))
        XCTAssertFalse(script.contains("ViftyHelper auto"))

        XCTAssertTrue(makefile.contains("repair-helper: ## Explicitly repair the installed privileged helper"))
        XCTAssertTrue(makefile.contains("./scripts/repair-vifty-helper.sh --app \"$(REPAIR_HELPER_APP)\""))
        XCTAssertTrue(readme.contains("Source checkouts also provide `make repair-helper`"))
        XCTAssertTrue(readme.contains("After repair, the script compares the installed helper hash with the app bundle and prints read-only `viftyctl diagnose` recovery fields"))
    }

    func testMenuBarCurveProfileSelectorUsesSavedProfiles() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(menuBarView.contains("@State private var selectedMenuCurveProfileID: UUID?"))
        XCTAssertTrue(menuBarView.contains("if !model.savedProfiles.isEmpty"))
        XCTAssertTrue(menuBarView.contains("Picker(\"Curve profile\", selection: $selectedMenuCurveProfileID)"))
        XCTAssertTrue(menuBarView.contains("ForEach(model.savedProfiles)"))
        XCTAssertTrue(menuBarView.contains("_ = model.selectCurveProfile(id: newID)"))
        XCTAssertTrue(appModel.contains("func selectCurveProfile(id profileID: CurveProfile.ID?) -> Bool"))
        XCTAssertTrue(appModel.contains("selectedMode = .curve\n        loadProfile(profile)"))
    }

    func testMenuBarHighTemperatureAttentionIsWired() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("static let highTemperatureAttentionThreshold = 90.0"))
        XCTAssertTrue(appModel.contains("var temperatureAttentionSummary: String?"))
        XCTAssertTrue(appModel.contains("return sensor.celsius >= Self.highTemperatureAttentionThreshold ? \"High temp\" : nil"))
        XCTAssertTrue(appModel.contains("var fanWriteBlockedWhileHotSummary: String?"))
        XCTAssertTrue(appModel.contains("var fanWriteBlockedWhileHotRecoverySuggestion: String?"))
        XCTAssertTrue(appModel.contains("parts.append(\"Fan writes blocked\")"))
        XCTAssertTrue(menuBarView.contains("if let fanWriteBlockedWhileHotSummary = model.fanWriteBlockedWhileHotSummary"))
        XCTAssertTrue(menuBarView.contains("if let recovery = model.fanWriteBlockedWhileHotRecoverySuggestion"))
        XCTAssertTrue(menuBarView.contains("if let temperatureAttentionSummary = model.temperatureAttentionSummary"))
        XCTAssertTrue(menuBarView.contains("Label(temperatureAttentionSummary, systemImage: \"thermometer.high\")"))
        XCTAssertTrue(menuBarView.contains(".foregroundStyle(.orange)"))
    }

    func testMainWindowHotBlockedHelperAttentionIsWired() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("if let fanWriteBlockedWhileHotSummary = model.fanWriteBlockedWhileHotSummary"))
        XCTAssertTrue(contentView.contains("Text(fanWriteBlockedWhileHotSummary)"))
        XCTAssertTrue(contentView.contains("if let recovery = model.fanWriteBlockedWhileHotRecoverySuggestion"))
        XCTAssertTrue(contentView.contains("Text(recovery)"))
        XCTAssertTrue(contentView.contains(".background(Color.orange.opacity(0.12), in: RoundedRectangle(cornerRadius: 8))"))
    }

    func testMainWindowManualPendingHelperAttentionIsWired() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var manualControlAttentionSummary: String?"))
        XCTAssertTrue(appModel.contains("request pending · fan writes blocked"))
        XCTAssertTrue(appModel.contains("Use \\(autoRestoreActionTitle) to stop retries; copy support evidence if repair does not clear it."))
        XCTAssertTrue(appModel.contains("var modeSelectionActionRestoresAuto: Bool"))
        XCTAssertTrue(appModel.contains("selectedMode == .auto || manualControlAttentionSummary != nil"))
        XCTAssertTrue(appModel.contains("var modeSelectionActionDisabled: Bool"))
        XCTAssertTrue(appModel.contains("var helperSupportEvidenceContext: HelperSupportEvidenceContext"))
        XCTAssertTrue(appModel.contains("hotFanWrites="))
        XCTAssertTrue(appModel.contains("controlOwner="))
        XCTAssertTrue(contentView.contains("if let manualControlAttentionSummary = model.manualControlAttentionSummary"))
        XCTAssertTrue(contentView.contains("hourglass.badge.exclamationmark"))
        XCTAssertTrue(contentView.contains("model.performModeSelectionAction()"))
        XCTAssertTrue(contentView.contains(".disabled(model.modeSelectionActionDisabled)"))
        XCTAssertTrue(contentView.contains("if let recovery = model.manualControlAttentionRecoverySuggestion"))
        XCTAssertTrue(contentView.contains("Text(recovery)"))
    }

    func testFixedRPMPerFanEditorShowsFanSpecificRanges() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("Toggle(\"Per-fan targets\", isOn: $model.usePerFanFixedRPM)"))
        XCTAssertTrue(contentView.contains(".accessibilityLabel(\"Per-fan fixed RPM targets\")"))
        XCTAssertTrue(contentView.contains(".accessibilityHint(\"Set separate fixed RPM targets for each fan.\")"))
        XCTAssertTrue(contentView.contains("let controllableFans = fans.filter(\\.controllable)"))
        XCTAssertTrue(contentView.contains("if controllableFans.count > 1"))
        XCTAssertTrue(contentView.contains("model.ensureFixedFanTargets(for: controllableFans)"))
        XCTAssertTrue(contentView.contains("let targetRPM = model.fixedFanTargetRPM(for: fan)"))
        XCTAssertTrue(contentView.contains("let targetPercent = model.fixedFanTargetPercent(for: fan)"))
        XCTAssertTrue(contentView.contains("Text(\"\\(targetRPM) RPM · \\(targetPercent)%\")"))
        XCTAssertFalse(contentView.contains("Text(\"Range \\(fan.minimumRPM)-\\(fan.maximumRPM) RPM\")"))
        XCTAssertTrue(contentView.contains("in: Double(fan.minimumRPM)...Double(fan.maximumRPM)"))
        XCTAssertTrue(contentView.contains(".help(\"\\(fan.name) fixed target. Range \\(fan.minimumRPM)-\\(fan.maximumRPM) RPM; currently \\(targetPercent)% of that fan's range.\")"))
        XCTAssertTrue(contentView.contains(".accessibilityLabel(\"\\(fan.name) fixed RPM target\")"))
        XCTAssertTrue(contentView.contains(".accessibilityValue(\"\\(targetRPM) RPM, \\(targetPercent)%\")"))
        XCTAssertTrue(contentView.contains(".accessibilityHint(\"\\(fan.name) target is clamped to \\(fan.minimumRPM)-\\(fan.maximumRPM) RPM.\")"))
        XCTAssertTrue(contentView.contains(".accessibilityLabel(\"Fixed RPM target\")"))
        XCTAssertTrue(contentView.contains(".accessibilityHint(\"Sets one fixed target for every controllable fan.\")"))
        XCTAssertTrue(contentView.contains("private struct CompactFanOverrideEditor: View"))
        XCTAssertTrue(contentView.contains("Stepper(value: startBinding, in: fan.minimumRPM...fan.maximumRPM, step: 50)"))
        XCTAssertTrue(contentView.contains("Stepper(value: midBinding, in: fan.minimumRPM...fan.maximumRPM, step: 50)"))
        XCTAssertTrue(contentView.contains("Stepper(value: maxBinding, in: fan.minimumRPM...fan.maximumRPM, step: 50)"))
        XCTAssertFalse(contentView.contains("Text(\"Fan \\(fan.id): \\(fan.name)\")"))
    }

    func testCurveEditorShowsDraggableChartForActualFanCurves() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")

        XCTAssertTrue(contentView.contains("FanCurveChartEditor("))
        XCTAssertTrue(contentView.contains("startTemp: $model.curveStartTemp"))
        XCTAssertTrue(contentView.contains("fanOverrides: model.fanOverrides"))
        XCTAssertTrue(contentView.contains("private struct FanCurveChartEditor: View"))
        XCTAssertTrue(contentView.contains("DragGesture(minimumDistance: 0)"))
        XCTAssertTrue(contentView.contains("setCurvePoint(point, from: value.location, in: geometry.size)"))
        XCTAssertTrue(contentView.contains("private var fanCurveSeries: [FanCurveChartSeries]"))
        XCTAssertTrue(contentView.contains("guard usePerFanOverrides else { return [] }"))
        XCTAssertTrue(contentView.contains("FanCurveChartSeries(name: fan.name"))
        XCTAssertTrue(contentView.contains("label: fanCurveLabel(for: fan)"))
        XCTAssertTrue(contentView.contains("labelOffsetIndex: offset"))
        XCTAssertTrue(contentView.contains("drawCurve(series.points, in: geometry.size)"))
        XCTAssertTrue(contentView.contains("curvePointValueLabels(for: series, in: geometry.size)"))
        XCTAssertTrue(contentView.contains("curvePointValueLabels(for: baseCurveValueLabelSeries, in: geometry.size)"))
        XCTAssertTrue(contentView.contains("private var baseCurveValueLabelSeries: FanCurveChartSeries"))
        XCTAssertTrue(contentView.contains("labelOffsetIndex: fanCurveSeries.count"))
        XCTAssertFalse(contentView.contains("if fanCurveSeries.isEmpty {"))
        XCTAssertFalse(contentView.contains("private func baseCurvePointValueLabels(in size: CGSize) -> some View"))
        XCTAssertFalse(contentView.contains("private func baseLabelPosition(for point: FanCurveChartPoint, pointIndex: Int, in size: CGSize) -> CGPoint"))
        XCTAssertTrue(contentView.contains("private func labelPosition(for point: FanCurveChartPoint, pointIndex: Int, seriesIndex: Int, in size: CGSize) -> CGPoint"))
        XCTAssertTrue(contentView.contains("chartAxisLabels(in: geometry.size)"))
        XCTAssertTrue(contentView.contains("chartAxisUnitLabels(in: geometry.size)"))
        XCTAssertTrue(contentView.contains("curvePointAxisGuides(for: basePoints, color: .accentColor, in: geometry.size)"))
        XCTAssertTrue(contentView.contains("curvePointAxisValueLabels(for: basePoints, color: .accentColor, in: geometry.size)"))
        XCTAssertTrue(contentView.contains("private func plotRect(in size: CGSize) -> CGRect"))
        XCTAssertTrue(contentView.contains("CurveChartAxisValue(text: rpmTickLabel(Int(rpmUpper.rounded()))"))
        XCTAssertTrue(contentView.contains("CurveChartAxisValue(text: temperatureTickLabel(Int(tempRange.upperBound.rounded()))"))
        XCTAssertTrue(contentView.contains("rpmTickLabel(Int(rpmUpper.rounded()))"))
        XCTAssertTrue(contentView.contains("temperatureTickLabel(Int(tempRange.upperBound.rounded()))"))
        XCTAssertTrue(contentView.contains("CurveChartAxisTitle(text: \"RPM\")"))
        XCTAssertTrue(contentView.contains("CurveChartAxisTitle(text: \"Temp C\")"))
        XCTAssertTrue(contentView.contains("CurveChartAxisReadout(text: point.rpmText, color: color"))
        XCTAssertTrue(contentView.contains("CurveChartAxisReadout(text: point.temperatureText, color: color"))
        XCTAssertTrue(contentView.contains("private func rpmAxisReadoutPosition(near pointPosition: CGPoint, pointIndex: Int, in rect: CGRect) -> CGPoint"))
        XCTAssertTrue(contentView.contains("private func temperatureAxisReadoutPosition(near pointPosition: CGPoint, pointIndex: Int, in rect: CGRect) -> CGPoint"))
        XCTAssertTrue(contentView.contains("private struct CurveChartAxisTitle: View"))
        XCTAssertTrue(contentView.contains("private struct CurveChartAxisReadout: View"))
        XCTAssertTrue(contentView.contains("private func fanCurveLabel(for fan: Fan) -> String"))
        XCTAssertTrue(contentView.contains("liveTemperatureLabel(temperature, in: size)"))
        XCTAssertTrue(contentView.contains("ChartHandle("))
        XCTAssertTrue(contentView.contains("label: point.label"))
        XCTAssertTrue(contentView.contains("valueText: value.chartValueText"))
        XCTAssertTrue(contentView.contains("valueLabelOffsetY: valueLabelOffsetY(for: value)"))
        XCTAssertTrue(contentView.contains("accessibilityValueText: value.accessibilityValueText"))
        XCTAssertFalse(contentView.contains("private struct ChartHandleValueLabel: View"))
        XCTAssertTrue(contentView.contains("private struct CurveChartHandleValueLabel: View"))
        XCTAssertTrue(contentView.contains("Text(valueText)"))
        XCTAssertTrue(contentView.contains("private func valueLabelOffsetY(for point: FanCurveChartPoint) -> CGFloat"))
        XCTAssertTrue(contentView.contains("Text(label)"))
        XCTAssertTrue(contentView.contains(".help(\"\\(label): \\(Int(temperature.rounded())) C · \\(Int(rpm.rounded()).formatted(.number.grouping(.automatic))) RPM\")"))
        XCTAssertTrue(contentView.contains("point.chartValueText"))
        XCTAssertTrue(contentView.contains("private struct CurveChartSeriesPointLabel: View"))
        XCTAssertTrue(contentView.contains("Text(point.chartValueText)"))
        XCTAssertTrue(contentView.contains("Text(\"\\(seriesLabel) \\(point.label)\")"))
        XCTAssertTrue(contentView.contains("var chartValueText: String"))
        XCTAssertTrue(contentView.contains("var temperatureText: String"))
        XCTAssertTrue(contentView.contains("var rpmText: String"))
        XCTAssertTrue(contentView.contains("var accessibilityValueText: String"))
        XCTAssertTrue(contentView.contains(".accessibilityValue(accessibilityValueText)"))
        XCTAssertTrue(contentView.contains(".accessibilityValue(valueText)"))
        XCTAssertTrue(contentView.contains("private struct CurveChartAxisValue: View"))
        XCTAssertTrue(contentView.contains("DisclosureGroup(\"Exact points\")"))
        XCTAssertTrue(contentView.contains("CurvePointEditor(title: \"Start\""))
        XCTAssertFalse(contentView.contains("import Charts"))
    }

    func testMenuBarNotificationSettingsAreWired() throws {
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")
        let notifications = try read("Sources/Vifty/LocalNotifications.swift")

        XCTAssertTrue(menuBarView.contains("Label(\"Notifications\", systemImage: \"bell\")"))
        XCTAssertTrue(menuBarView.contains("Toggle(\"Helper failure\", isOn: $model.notificationSettings.helperFailure)"))
        XCTAssertTrue(menuBarView.contains("Toggle(\"High thermal pressure\", isOn: $model.notificationSettings.elevatedThermalPressure)"))
        XCTAssertTrue(menuBarView.contains("Toggle(\"Auto restore failure\", isOn: $model.notificationSettings.autoRestoreFailure)"))
        XCTAssertTrue(menuBarView.contains("Toggle(\"Plugged-in battery drain\", isOn: $model.notificationSettings.pluggedInBatteryDrain)"))
        XCTAssertTrue(menuBarView.contains("Toggle(\"Agent cooling attention\", isOn: $model.notificationSettings.agentCoolingAttention)"))
        XCTAssertTrue(appModel.contains("notificationMinimumInterval: TimeInterval = 10 * 60"))
        XCTAssertTrue(appModel.contains("previousAgentCoolingNeedsAttention"))
        XCTAssertTrue(appModel.contains("sustainedThermalPressureInterval: TimeInterval = 60"))
        XCTAssertTrue(notifications.contains("UNUserNotificationCenter"))
        XCTAssertTrue(notifications.contains("XCTestConfigurationFilePath"))
        XCTAssertTrue(notifications.contains("processName == \"xctest\""))
        XCTAssertTrue(notifications.contains("static let disabled = LocalNotificationSettings()"))
    }

    func testGlobalAutoActionsUseContextualRequestCopy() throws {
        let contentView = try read("Sources/Vifty/ContentView.swift")
        let menuBarView = try read("Sources/Vifty/MenuBarView.swift")
        let appModel = try read("Sources/Vifty/AppModel.swift")

        XCTAssertTrue(appModel.contains("var autoRestoreActionTitle: String"))
        XCTAssertTrue(appModel.contains("var modeSelectionActionTitle: String"))
        XCTAssertTrue(appModel.contains("helperWritePathBlockedSummary == nil ? \"Auto\" : \"Request Auto\""))
        XCTAssertTrue(appModel.contains("Request Auto restore; the write cannot be confirmed until the helper responds"))
        XCTAssertTrue(contentView.contains("Label(model.modeSelectionActionTitle"))
        XCTAssertTrue(contentView.contains(".help(model.modeSelectionActionHelp)"))
        XCTAssertFalse(contentView.contains("Label(\"Apply\""))
        XCTAssertTrue(menuBarView.contains("Button(model.autoRestoreActionTitle)"))
        XCTAssertTrue(menuBarView.contains(".help(model.autoRestoreActionHelp)"))
        XCTAssertFalse(menuBarView.contains("Button(\"Auto\")"))
    }

    private func read(_ relativePath: String) throws -> String {
        let url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent(relativePath)
        return try String(contentsOf: url, encoding: .utf8)
    }
}
