import Foundation
import XCTest

final class DocumentationTrustSurfaceTests: XCTestCase {
    func testReadmeLinksCompatibilityAndHardwareValidation() throws {
        let readme = try read("README.md")

        XCTAssertTrue(readme.contains("[docs/compatibility.md](docs/compatibility.md)"))
        XCTAssertTrue(readme.contains("[docs/hardware-validation.md](docs/hardware-validation.md)"))
        XCTAssertTrue(readme.contains("[docs/support-triage.md](docs/support-triage.md)"))
        XCTAssertTrue(readme.contains("[docs/trust-model.md](docs/trust-model.md)"))
        XCTAssertTrue(readme.contains("[docs/release-status.md](docs/release-status.md)"))
        XCTAssertTrue(readme.contains("[docs/safe-agent-cooling.md](docs/safe-agent-cooling.md)"))
        XCTAssertTrue(readme.contains("[docs/unsupported-hardware.md](docs/unsupported-hardware.md)"))
        XCTAssertTrue(readme.contains("[docs/agent-integrations.md](docs/agent-integrations.md)"))
        XCTAssertTrue(readme.contains("[examples/viftyctl](examples/viftyctl/README.md)"))
    }

    func testSupportTriageGuideCoversEvidenceBuckets() throws {
        let agentCoolingTemplate = try read(".github/ISSUE_TEMPLATE/agent-cooling.yml")
        let releaseTrustTemplate = try read(".github/ISSUE_TEMPLATE/release-trust.yml")
        let contributing = try read("CONTRIBUTING.md")
        let bugReportTemplate = try read(".github/ISSUE_TEMPLATE/bug-report.yml")
        let triage = try read("docs/support-triage.md")

        XCTAssertTrue(contributing.contains("[docs/support-triage.md](docs/support-triage.md)"))
        XCTAssertTrue(contributing.contains("Release Trust Report"))
        XCTAssertTrue(contributing.contains("Agent Cooling Report"))
        XCTAssertTrue(bugReportTemplate.contains("docs/support-triage.md"))
        XCTAssertTrue(releaseTrustTemplate.contains("name: Release Trust Report"))
        XCTAssertTrue(releaseTrustTemplate.contains("labels: [\"release-trust\"]"))
        XCTAssertTrue(releaseTrustTemplate.contains("scripts/check-release-readiness.sh --mode source-first --version 1.1.0 --repo Reedtrullz/Vifty --json"))
        XCTAssertTrue(releaseTrustTemplate.contains("scripts/check-release-readiness.sh --mode developer-id --version 1.1.0 --repo Reedtrullz/Vifty --require-source-ref origin/main --json"))
        XCTAssertTrue(releaseTrustTemplate.contains("For unpublished source-first candidates, use `--require-source-ref <candidate-ref-or-sha>` only when the ref is intentionally the release commit."))
        XCTAssertTrue(releaseTrustTemplate.contains("Vifty-v<version>-unsigned-dev.zip"))
        XCTAssertTrue(releaseTrustTemplate.contains("source-first unsigned-dev app zips are tester convenience artifacts"))
        XCTAssertTrue(releaseTrustTemplate.contains("Vifty-v<version>-artifact-summary.json"))
        XCTAssertTrue(releaseTrustTemplate.contains("Vifty-v<version>-release-checklist.md"))
        XCTAssertTrue(releaseTrustTemplate.contains("scripts/verify-release-artifact.sh --team-id <TEAMID>"))
        XCTAssertTrue(releaseTrustTemplate.contains("scripts/review-validation-evidence.sh --mode release"))
        XCTAssertTrue(releaseTrustTemplate.contains("I did not bypass Gatekeeper"))
        XCTAssertTrue(releaseTrustTemplate.contains("source tags, CI artifacts, and local ad-hoc builds are not trusted public binary releases"))
        XCTAssertTrue(releaseTrustTemplate.contains("I did not run manual fan-write smoke tests or raw SMC commands"))
        XCTAssertTrue(agentCoolingTemplate.contains("name: Agent Cooling Report"))
        XCTAssertTrue(agentCoolingTemplate.contains("labels: [\"agent-cooling\"]"))
        XCTAssertTrue(agentCoolingTemplate.contains("viftyctl diagnose --json"))
        XCTAssertTrue(agentCoolingTemplate.contains("viftyctl status --json"))
        XCTAssertTrue(agentCoolingTemplate.contains("viftyctl audit --limit 20 --json"))
        XCTAssertTrue(agentCoolingTemplate.contains("Command stdout/stderr and exit code"))
        XCTAssertTrue(agentCoolingTemplate.contains("Auto restore state"))
        XCTAssertTrue(agentCoolingTemplate.contains("I did not run raw SMC commands"))
        XCTAssertTrue(agentCoolingTemplate.contains("safeToRequestCooling: false"))
        XCTAssertTrue(agentCoolingTemplate.contains("restoreAutoBeforeRequestingCooling"))
        XCTAssertTrue(triage.contains("Release trust"))
        XCTAssertTrue(triage.contains("Hardware validation"))
        XCTAssertTrue(triage.contains("Unsupported hardware safe block"))
        XCTAssertTrue(triage.contains("Helper install or approval"))
        XCTAssertTrue(triage.contains("SMC key or fan telemetry drift"))
        XCTAssertTrue(triage.contains("Agent-cooling lifecycle"))
        XCTAssertTrue(triage.contains("Agent Cooling Report"))
        XCTAssertTrue(triage.contains("UI or copy"))
        XCTAssertTrue(triage.contains("viftyctl diagnose --json"))
        XCTAssertTrue(triage.contains("viftyctl audit --limit 20 --json"))
        XCTAssertTrue(triage.contains("Release Trust Report"))
        XCTAssertTrue(triage.contains("scripts/check-release-readiness.sh --mode source-first --version <version> --repo Reedtrullz/Vifty --json"))
        XCTAssertTrue(triage.contains("Do not require `origin/main` for an already-published source-first tag after `main` has moved on."))
        XCTAssertTrue(triage.contains("Do not ask users to verify Developer ID signing, notarization, stapling, or Homebrew trust for `v1.1.0`"))
        XCTAssertTrue(triage.contains("Do not treat a source tag, CI artifact, unsigned-dev convenience zip, or local ad-hoc build as a trusted public binary release."))
        XCTAssertTrue(triage.contains(".github/repo-metadata.json"))
        XCTAssertTrue(triage.contains("scripts/check-github-metadata.sh --repo Reedtrullz/Vifty --json"))
        XCTAssertTrue(triage.contains("Do not ask reporters to run raw SMC writes"))
        XCTAssertTrue(triage.contains("manualSmokeTestResult"))
        XCTAssertTrue(triage.contains("passed-auto-restored"))
    }

    func testSecurityPolicyLinksTrustModel() throws {
        let security = try read("SECURITY.md")

        XCTAssertTrue(security.contains("[docs/trust-model.md](docs/trust-model.md)"))
        XCTAssertTrue(security.contains("[docs/release-status.md](docs/release-status.md)"))
        XCTAssertTrue(security.contains("not a substitute for a Developer ID signed, notarized, stapled release artifact"))
    }

    func testTrustModelNamesPrivilegedBoundariesAndWriteAllowlist() throws {
        let trustModel = try read("docs/trust-model.md")

        XCTAssertTrue(trustModel.contains("The SwiftUI app and `viftyctl` run unprivileged."))
        XCTAssertTrue(trustModel.contains("The LaunchDaemon runs as root and owns normal SMC fan writes."))
        XCTAssertTrue(trustModel.contains("F{n}Md"))
        XCTAssertTrue(trustModel.contains("F{n}md"))
        XCTAssertTrue(trustModel.contains("F{n}Tg"))
        XCTAssertTrue(trustModel.contains("Ftst"))
        XCTAssertTrue(trustModel.contains("Agents request bounded cooling intent. They do not get raw SMC write access."))
        XCTAssertTrue(trustModel.contains("Public releases should be Developer ID signed, notarized, stapled, and TeamID-gated over XPC."))
        XCTAssertTrue(trustModel.contains("[release-status.md](release-status.md)"))
    }

    func testReleaseStatusKeepsHomebrewInstallClaimsHonest() throws {
        let readme = try read("README.md")
        let releaseStatus = try read("docs/release-status.md")
        let release = try read("docs/release.md")

        XCTAssertTrue(readme.contains("Vifty `v1.1.0` is a source-first release because the project does not currently have Apple Developer Program credentials."))
        XCTAssertTrue(readme.contains("Vifty-v1.1.0-unsigned-dev.zip"))
        XCTAssertTrue(readme.contains("Do not use Homebrew as the recommended or trusted `v1.1.0` install path."))
        XCTAssertTrue(release.contains("[release-status.md](release-status.md)"))
        XCTAssertTrue(release.contains("Source-First Release Mode"))
        XCTAssertTrue(release.contains("This is a source-first release. Vifty v1.1.0 does not yet include a Developer ID signed or notarized public binary"))
        XCTAssertTrue(release.contains("scripts/check-release-readiness.sh \\"))
        XCTAssertTrue(release.contains("--mode source-first"))
        XCTAssertTrue(releaseStatus.contains("`v1.1.0` is a source-first public release because the project does not currently have Apple Developer Program credentials."))
        XCTAssertTrue(releaseStatus.contains("Trusted notarized Developer ID release:** unavailable until the project has Apple Developer Program credentials."))
        XCTAssertTrue(releaseStatus.contains("Source release:** canonical and recommended path for `v1.1.0`."))
        XCTAssertTrue(releaseStatus.contains("Unsigned convenience app zip:** optional tester convenience only."))
        XCTAssertTrue(releaseStatus.contains("Vifty-v1.1.0-unsigned-dev.zip"))
        XCTAssertTrue(releaseStatus.contains("Do not update the Homebrew cask for this source-first release"))
        XCTAssertTrue(releaseStatus.contains("Do not use `--require-source-ref origin/main` as a post-publication source-first check unless `origin/main` is intentionally still the release commit."))
        XCTAssertTrue(releaseStatus.contains("scripts/check-release-readiness.sh --mode source-first --version 1.1.0 --repo Reedtrullz/Vifty --json"))
        XCTAssertTrue(releaseStatus.contains("scripts/check-release-readiness.sh --mode developer-id --version <version> --repo Reedtrullz/Vifty --require-source-ref origin/main --json"))
    }

    func testCompatibilityPageRequiresReportBackedEvidence() throws {
        let compatibility = try read("docs/compatibility.md")

        XCTAssertTrue(compatibility.contains("Vifty's compatibility claims are evidence-based"))
        XCTAssertTrue(compatibility.contains("Hardware Validation Report"))
        XCTAssertTrue(compatibility.contains("scripts/collect-validation-evidence.sh"))
        XCTAssertTrue(compatibility.contains("scripts/review-validation-evidence.sh"))
        XCTAssertTrue(compatibility.contains("scripts/summarize-validation-reports.sh"))
        XCTAssertTrue(compatibility.contains("review-result.json"))
        XCTAssertTrue(compatibility.contains("supported-hardware-evidence-needs-manual-smoke"))
        XCTAssertTrue(compatibility.contains("validated-hardware-evidence"))
        XCTAssertTrue(compatibility.contains("manualSmokeTestResult: \"passed-auto-restored\""))
        XCTAssertTrue(compatibility.contains("viftyctl diagnose --json"))
        XCTAssertTrue(compatibility.contains("ViftyHelper probeLocal"))
        XCTAssertTrue(compatibility.contains("Do not run the manual smoke test when readiness is `blocked`"))
        XCTAssertTrue(compatibility.contains("Do not add a README compatibility badge or broad marketing claim until the status table has real report links."))
    }

    func testAgentWorkflowDocsKeepDirectPrepareTrapBounded() throws {
        let agentWorkflows = try read("docs/agent-workflows.md")
        let safeAgentCooling = try read("docs/safe-agent-cooling.md")

        for document in [agentWorkflows, safeAgentCooling] {
            XCTAssertTrue(document.contains("PREPARED=0"))
            XCTAssertTrue(document.contains("trap cleanup EXIT INT TERM HUP"))
            XCTAssertTrue(document.contains("restore-auto \\"))
            XCTAssertTrue(document.contains("|| status=70"))
            XCTAssertTrue(document.contains("PREPARED=1"))
        }

        XCTAssertTrue(agentWorkflows.contains("This pattern still has more moving parts than `viftyctl run`"))
        XCTAssertTrue(safeAgentCooling.contains("Direct prepare is the exception because the shell now owns cleanup"))
        XCTAssertFalse(agentWorkflows.contains("show what Vifty actually did without requesting cooling or reading raw SMC state.\n- `generatedAt`"))
    }

    func testUnsupportedHardwarePolicyDefinesSafeBlocks() throws {
        let readme = try read("README.md")
        let compatibility = try read("docs/compatibility.md")
        let hardwareValidation = try read("docs/hardware-validation.md")
        let trustModel = try read("docs/trust-model.md")
        let supportTriage = try read("docs/support-triage.md")
        let issueTemplate = try read(".github/ISSUE_TEMPLATE/hardware-validation.yml")
        let policy = try read("docs/unsupported-hardware.md")

        XCTAssertTrue(readme.contains("[docs/unsupported-hardware.md](docs/unsupported-hardware.md)"))
        XCTAssertTrue(compatibility.contains("[unsupported-hardware.md](unsupported-hardware.md)"))
        XCTAssertTrue(hardwareValidation.contains("[unsupported-hardware.md](unsupported-hardware.md)"))
        XCTAssertTrue(trustModel.contains("[unsupported-hardware.md](unsupported-hardware.md)"))
        XCTAssertTrue(supportTriage.contains("[unsupported-hardware.md](unsupported-hardware.md)"))
        XCTAssertTrue(issueTemplate.contains("docs/unsupported-hardware.md"))
        XCTAssertTrue(policy.contains("Apple Silicon MacBook Pro"))
        XCTAssertTrue(policy.contains("Unsupported hardware safe block"))
        XCTAssertTrue(policy.contains("safeToRequestCooling: false"))
        XCTAssertTrue(policy.contains("viftyctl diagnose --json"))
        XCTAssertTrue(policy.contains("viftyctl status --json"))
        XCTAssertTrue(policy.contains("review-result.json"))
        XCTAssertTrue(policy.contains("--mode unsupported-hardware"))
        XCTAssertTrue(policy.contains("Do not run manual fan-write smoke tests"))
        XCTAssertTrue(policy.contains("sudo ViftyHelper setFixed"))
        XCTAssertTrue(policy.contains("raw SMC tools"))
        XCTAssertTrue(policy.contains("must not be used as proof that fan control is supported"))
    }

    func testHardwareValidationTemplateKeepsUnsupportedReportsReadOnly() throws {
        let compatibility = try read("docs/compatibility.md")
        let issueTemplate = try read(".github/ISSUE_TEMPLATE/hardware-validation.yml")

        XCTAssertTrue(compatibility.contains("Always capture `sudo /Applications/Vifty.app/Contents/MacOS/ViftyHelper probeLocal` for supported MacBook Pro validation"))
        XCTAssertTrue(compatibility.contains("Follow [unsupported-hardware.md](unsupported-hardware.md) for unsupported-hardware safe-block reports."))
        XCTAssertTrue(issueTemplate.contains("ViftyHelper probeLocal output (supported hardware)"))
        XCTAssertTrue(issueTemplate.contains("supported Apple Silicon MacBook Pro validation"))
        XCTAssertTrue(issueTemplate.contains("Unsupported machines should follow docs/unsupported-hardware.md and collect read-only evidence only."))
        XCTAssertTrue(issueTemplate.contains("A `viftyctl diagnose --json` report showing the hardware gate is enough for unsupported safe-block reports."))
        XCTAssertTrue(issueTemplate.contains("Unsupported safe-block reports may leave this blank"))
        XCTAssertTrue(issueTemplate.contains("Only run the manual fan write smoke test on supported Apple Silicon MacBook Pro hardware"))

        let probeLocalSection = try XCTUnwrap(issueTemplate.range(of: "id: probe-local"))
        let manualSmokeSection = try XCTUnwrap(issueTemplate.range(of: "id: manual-smoke"))
        let section = String(issueTemplate[probeLocalSection.lowerBound..<manualSmokeSection.lowerBound])
        XCTAssertTrue(section.contains("required: false"))
        XCTAssertFalse(section.contains("required: true"))
    }

    func testPullRequestTemplateRequiresSafetyReview() throws {
        let contributing = try read("CONTRIBUTING.md")
        let template = try read(".github/PULL_REQUEST_TEMPLATE.md")

        XCTAssertTrue(contributing.contains("Fill out the PR safety impact section"))
        XCTAssertTrue(contributing.contains("fan/SMC writes"))
        XCTAssertTrue(contributing.contains("agent leases"))
        XCTAssertTrue(contributing.contains("Run `make verify`"))
        XCTAssertTrue(template.contains("## Safety Impact"))
        XCTAssertTrue(template.contains("Fan/SMC writes"))
        XCTAssertTrue(template.contains("Privileged daemon, helper, installer, signing, or XPC identity"))
        XCTAssertTrue(template.contains("`viftyctl`, agent leases, JSON contracts, or workload wrappers"))
        XCTAssertTrue(template.contains("Hardware validation, release trust, compatibility, or unsupported-hardware policy"))
        XCTAssertTrue(template.contains("UI state for Auto restore, helper health, fan ownership, or active agent cooling"))
        XCTAssertTrue(template.contains("Local persistence, permissions, telemetry, or audit history"))
        XCTAssertTrue(template.contains("## Verification"))
        XCTAssertTrue(template.contains("make verify"))
        XCTAssertTrue(template.contains("reject arbitrary keys"))
        XCTAssertTrue(template.contains("invalid fan IDs"))
        XCTAssertTrue(template.contains("safeToRequestCooling"))
        XCTAssertTrue(template.contains("recommendedAgentAction"))
        XCTAssertTrue(template.contains("fail closed"))
        XCTAssertTrue(template.contains("manual fan-write smoke tests when readiness is blocked"))
        XCTAssertTrue(template.contains("persistent telemetry beyond documented agent-control audit state"))
    }

    func testCodeownersNamesSafetySensitiveTrustSurfaces() throws {
        let codeowners = try read(".github/CODEOWNERS")

        XCTAssertTrue(codeowners.contains("# Agent control safety surface"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/AgentControlModels.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/AgentControlPolicy.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/AgentControlService.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/AgentControlStore.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/ViftyCtlArguments.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/ViftyCtlReadinessReport.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/ViftyCtlRunner.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCtl/"))
        XCTAssertTrue(codeowners.contains("# Agent-facing contracts and examples"))
        XCTAssertTrue(codeowners.contains("docs/agent-workflows.md"))
        XCTAssertTrue(codeowners.contains("docs/agent-integrations.md"))
        XCTAssertTrue(codeowners.contains("docs/safe-agent-cooling.md"))
        XCTAssertTrue(codeowners.contains("docs/examples/viftyctl/"))
        XCTAssertTrue(codeowners.contains("docs/schemas/"))
        XCTAssertTrue(codeowners.contains("examples/viftyctl/"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/agent-cooling.yml"))
        XCTAssertTrue(codeowners.contains("# IOKit / SMC surface"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/HardwareService.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/LocalFanHelperClient.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/SMCClient.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/RealMacHardwareService.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyPrivateIOKit/"))
        XCTAssertTrue(codeowners.contains("# Release, installer, and daemon plist"))
        XCTAssertTrue(codeowners.contains(".github/workflows/release.yml"))
        XCTAssertTrue(codeowners.contains(".github/workflows/ci.yml"))
        XCTAssertTrue(codeowners.contains("Casks/vifty.rb"))
        XCTAssertTrue(codeowners.contains("Resources/Info.plist"))
        XCTAssertTrue(codeowners.contains("Resources/Vifty.entitlements"))
        XCTAssertTrue(codeowners.contains("Resources/ViftyDaemon.entitlements"))
        XCTAssertTrue(codeowners.contains("Resources/tech.reidar.vifty.daemon.plist"))
        XCTAssertTrue(codeowners.contains("# Compatibility, validation, and policy surfaces"))
        XCTAssertTrue(codeowners.contains("docs/compatibility.md"))
        XCTAssertTrue(codeowners.contains("docs/hardware-validation.md"))
        XCTAssertTrue(codeowners.contains("docs/release.md"))
        XCTAssertTrue(codeowners.contains("docs/release-status.md"))
        XCTAssertTrue(codeowners.contains("docs/support-triage.md"))
        XCTAssertTrue(codeowners.contains("docs/trust-model.md"))
        XCTAssertTrue(codeowners.contains("docs/unsupported-hardware.md"))
        XCTAssertTrue(codeowners.contains(".github/repo-metadata.json"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/release-trust.yml"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/hardware-validation.yml"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/bug-report.yml"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/config.yml"))
        XCTAssertTrue(codeowners.contains("# Repo safety process"))
        XCTAssertTrue(codeowners.contains(".github/PULL_REQUEST_TEMPLATE.md"))
        XCTAssertTrue(codeowners.contains("AGENTS.md"))
        XCTAssertTrue(codeowners.contains("CONTRIBUTING.md"))
        XCTAssertTrue(codeowners.contains("SECURITY.md"))
    }

    func testReleaseAndHardwareDocsPointBackToCompatibilityStatus() throws {
        let release = try read("docs/release.md")
        let hardwareValidation = try read("docs/hardware-validation.md")
        let hardwareValidationTemplate = try read(".github/ISSUE_TEMPLATE/hardware-validation.yml")

        XCTAssertTrue(release.contains("make verify"))
        XCTAssertTrue(release.contains("[compatibility.md](compatibility.md)"))
        XCTAssertTrue(release.contains("scripts/verify-release-artifact.sh"))
        XCTAssertTrue(release.contains("scripts/collect-validation-evidence.sh"))
        XCTAssertTrue(release.contains("scripts/review-validation-evidence.sh"))
        XCTAssertTrue(release.contains("scripts/summarize-validation-reports.sh"))
        XCTAssertTrue(release.contains("review-result.json"))
        XCTAssertTrue(release.contains("validated-hardware-evidence"))
        XCTAssertTrue(release.contains("Vifty-v<version>-artifact-summary.json"))
        XCTAssertTrue(release.contains("review-summary.json"))
        XCTAssertTrue(hardwareValidation.contains("[compatibility.md](compatibility.md)"))
        XCTAssertTrue(hardwareValidation.contains("scripts/collect-validation-evidence.sh"))
        XCTAssertTrue(hardwareValidation.contains("scripts/review-validation-evidence.sh"))
        XCTAssertTrue(hardwareValidation.contains("scripts/summarize-validation-reports.sh"))
        XCTAssertTrue(hardwareValidation.contains("review-result.json"))
        XCTAssertTrue(hardwareValidation.contains("--manual-smoke-result passed-auto-restored"))
        XCTAssertTrue(hardwareValidation.contains("validated-hardware-evidence"))
        XCTAssertTrue(hardwareValidation.contains("review-summary.json"))
        XCTAssertTrue(hardwareValidationTemplate.contains("privacy-review.tsv"))
        XCTAssertTrue(hardwareValidationTemplate.contains("The privacy-review row should be 0 before public sharing"))
        XCTAssertTrue(hardwareValidationTemplate.contains("Review captured files for likely hostnames, /Users/... paths, serial-number labels, or hardware UUID labels before public sharing."))
    }

    func testAgentIntegrationDocsPreferGuardedRunAndForbidRawWrites() throws {
        let guide = try read("docs/safe-agent-cooling.md")
        let agentWorkflows = try read("docs/agent-workflows.md")
        let integrations = try read("docs/agent-integrations.md")

        XCTAssertTrue(guide.contains("read-only readiness first, one bounded workload lease, validated child command, then Auto restore"))
        XCTAssertTrue(guide.contains("call `sudo`, `ViftyHelper setFixed`, `ViftyHelper auto`, raw SMC tools, or arbitrary fan RPM writes"))
        XCTAssertTrue(guide.contains("request cooling when `diagnose --json` reports `state: \"blocked\"`"))
        XCTAssertTrue(guide.contains("prepare cooling before the child command has been resolved and validated"))
        XCTAssertTrue(guide.contains("recommendedAgentAction"))
        XCTAssertTrue(guide.contains("safeToRequestCooling"))
        XCTAssertTrue(guide.contains("VIFTY_GUARDED_RUN_FORCE_RETRY=1"))
        XCTAssertTrue(guide.contains("viftyctl audit --limit 20 --json"))
        XCTAssertTrue(guide.contains("The app's menu and main window also show the current fan-control owner."))
        XCTAssertTrue(agentWorkflows.contains("[safe-agent-cooling.md](safe-agent-cooling.md)"))
        XCTAssertTrue(agentWorkflows.contains("[agent-integrations.md](agent-integrations.md)"))
        XCTAssertTrue(agentWorkflows.contains("[examples/viftyctl](../examples/viftyctl/README.md)"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/swift-test.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/swift-release-build.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/xcode-test.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/npm-test.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/cargo-test.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/pytest.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/local-model.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/custom-workload.sh"))
        XCTAssertTrue(agentWorkflows.contains("VIFTY_GUARDED_RUN_FORCE_RETRY=1"))
        XCTAssertTrue(integrations.contains("[safe-agent-cooling.md](safe-agent-cooling.md)"))
        XCTAssertTrue(integrations.contains("Codex"))
        XCTAssertTrue(integrations.contains("Claude Code"))
        XCTAssertTrue(integrations.contains("Cursor"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/guarded-run.sh"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/swift-test.sh"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/cargo-test.sh"))
        XCTAssertTrue(integrations.contains("safeToRequestCooling"))
        XCTAssertTrue(integrations.contains("restoreAutoBeforeRequestingCooling"))
        XCTAssertTrue(integrations.contains("Never call raw SMC commands"))
        XCTAssertTrue(integrations.contains("Do not give agents permission to call `ViftyHelper setFixed`"))
        XCTAssertTrue(integrations.contains("VIFTY_GUARDED_RUN_FORCE_RETRY"))

        let exampleReadme = try read("examples/viftyctl/README.md")
        XCTAssertTrue(exampleReadme.contains("read-only `viftyctl diagnose --json`"))
        XCTAssertTrue(exampleReadme.contains("delegate to `viftyctl run --json`"))
        XCTAssertTrue(exampleReadme.contains("VIFTY_GUARDED_RUN_FORCE_RETRY=1"))
        XCTAssertTrue(exampleReadme.contains("swift-test.sh"))
        XCTAssertTrue(exampleReadme.contains("custom-workload.sh"))
        XCTAssertTrue(exampleReadme.contains("Do not edit these wrappers to call `sudo`, `ViftyHelper`, raw SMC tools"))
    }

    private func read(_ relativePath: String) throws -> String {
        let url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent(relativePath)
        return try String(contentsOf: url, encoding: .utf8)
    }
}
