import Foundation
import XCTest

final class DocumentationTrustSurfaceTests: XCTestCase {
    func testReadmePositionsViftyAroundDeveloperWorkloadCooling() throws {
        let readme = try read("README.md")

        XCTAssertTrue(readme.contains("safe local thermal control for Apple Silicon MacBook Pro developer workloads"))
        XCTAssertTrue(readme.contains("builds, tests, and local AI coding agents"))
        XCTAssertTrue(readme.contains("Vifty is not trying to be a general-purpose system monitor yet"))
        XCTAssertTrue(readme.contains("its wedge is auditable fan control, bounded agent cooling, helper recovery, and evidence-backed compatibility"))
        XCTAssertTrue(readme.contains("Optional local notifications"))
        XCTAssertTrue(readme.contains("off by default"))
        XCTAssertTrue(readme.contains("macOS UserNotifications only"))
        XCTAssertTrue(readme.contains("### Agent readiness checklist"))
        XCTAssertTrue(readme.contains("`viftyctl capabilities --json`"))
        XCTAssertTrue(readme.contains("`viftyctl diagnose --json`"))
        XCTAssertTrue(readme.contains("`safeToRequestCooling: true`"))
        XCTAssertTrue(readme.contains("`daemonControlPathReady: true`"))
        XCTAssertTrue(readme.contains("`recommendedAgentAction`"))
        XCTAssertTrue(readme.contains("`recommendedRecoveryAction`"))
        XCTAssertTrue(readme.contains("`examples/viftyctl/guarded-run.sh ... -- <command>`"))
        XCTAssertTrue(readme.contains("`VIFTY_GUARDED_RUN_ALLOW_UNCOOLED=1`"))
        XCTAssertTrue(readme.contains("The guarded wrapper still refuses helper-repair, restore-first, backoff, and daemon-control-unavailable states, and it refuses to combine uncooled fallback with `VIFTY_GUARDED_RUN_FORCE_RETRY=1`."))
        XCTAssertTrue(readme.contains("Do not fall back to `sudo`, `ViftyHelper setFixed`, `ViftyHelper auto`, raw SMC tools, or direct helper writes."))
    }

    func testReadmeLinksCompatibilityAndHardwareValidation() throws {
        let readme = try read("README.md")

        XCTAssertTrue(readme.contains("[docs/compatibility.md](docs/compatibility.md)"))
        XCTAssertTrue(readme.contains("[SUPPORT.md](SUPPORT.md)"))
        XCTAssertTrue(readme.contains("[docs/hardware-validation.md](docs/hardware-validation.md)"))
        XCTAssertTrue(readme.contains("[docs/support-triage.md](docs/support-triage.md)"))
        XCTAssertTrue(readme.contains("[docs/trust-model.md](docs/trust-model.md)"))
        XCTAssertTrue(readme.contains("[docs/release-status.md](docs/release-status.md)"))
        XCTAssertTrue(readme.contains("[docs/safe-agent-cooling.md](docs/safe-agent-cooling.md)"))
        XCTAssertTrue(readme.contains("[docs/unsupported-hardware.md](docs/unsupported-hardware.md)"))
        XCTAssertTrue(readme.contains("[docs/agent-integrations.md](docs/agent-integrations.md)"))
        XCTAssertTrue(readme.contains("[examples/viftyctl](examples/viftyctl/README.md)"))
        XCTAssertTrue(readme.contains("make validation-evidence"))
        XCTAssertTrue(readme.contains("read-only release/hardware collector"))
        XCTAssertTrue(readme.contains("scripts/collect-agent-cooling-evidence.sh"))
        XCTAssertTrue(readme.contains("scripts/review-agent-cooling-evidence.sh"))
        XCTAssertTrue(readme.contains("make agent-run-smoke-evidence"))
        XCTAssertTrue(readme.contains("after readiness is safe"))
    }

    func testReadmeDescribesFallbackHelperInstallPathAccurately() throws {
        let readme = try read("README.md")

        XCTAssertTrue(readme.contains("When you choose **Install Helper**, **Approve Helper**, **Repair Helper**, or **Reinstall Helper**"))
        XCTAssertTrue(readme.contains("Vifty starts the helper install or repair only after that user action; normal app launch only checks and reports helper status."))
        XCTAssertTrue(readme.contains("copies `ViftyDaemon` to `/Library/PrivilegedHelperTools/tech.reidar.vifty.daemon`"))
        XCTAssertTrue(readme.contains("removes stale `BundleProgram`"))
        XCTAssertTrue(readme.contains("patches the staged LaunchDaemon plist with `ProgramArguments`"))
        XCTAssertFalse(readme.contains("On first launch:"))
        XCTAssertFalse(readme.contains("launchd points at the daemon inside the installed app bundle"))
    }

    func testAgentInstructionsTrackCurrentHelperInstallAndTestCount() throws {
        let agents = try read("AGENTS.md")

        XCTAssertTrue(agents.contains("`swift test` runs `ViftyCoreTests` (748 tests)."))
        XCTAssertTrue(agents.contains("`Sources/Vifty/AppPreferencesStore.swift`"))
        XCTAssertTrue(agents.contains("No UserDefaults for structured data except legacy migration reads"))
        XCTAssertTrue(agents.contains("`Sources/Vifty/LocalNotifications.swift`"))
        XCTAssertTrue(agents.contains("administrator fallback install staging, bootout ordering"))
        XCTAssertTrue(agents.contains("no direct copy-to-target writes"))
    }

    func testAgentInstructionsTrackCurrentSourceFirstReleaseBoundary() throws {
        let agents = try read("AGENTS.md")

        XCTAssertTrue(agents.contains("`v1.1.1` is the current source-first hotfix while Apple Developer Program credentials are unavailable"))
        XCTAssertTrue(agents.contains("`v1.1.0` is superseded and must not be retagged or refreshed from later source"))
        XCTAssertTrue(agents.contains("Future trusted binary releases should use `.github/workflows/release.yml`"))
        XCTAssertFalse(agents.contains("`v1.1.0` is source-first because Apple Developer Program credentials are unavailable"))
    }

    func testSupportTriageGuideCoversEvidenceBuckets() throws {
        let agentCoolingTemplate = try read(".github/ISSUE_TEMPLATE/agent-cooling.yml")
        let releaseTrustTemplate = try read(".github/ISSUE_TEMPLATE/release-trust.yml")
        let contributing = try read("CONTRIBUTING.md")
        let bugReportTemplate = try read(".github/ISSUE_TEMPLATE/bug-report.yml")
        let support = try read("SUPPORT.md")
        let triage = try read("docs/support-triage.md")

        XCTAssertTrue(contributing.contains("[SUPPORT.md](SUPPORT.md)"))
        XCTAssertTrue(support.contains("[SECURITY.md](SECURITY.md)"))
        XCTAssertTrue(support.contains("[docs/support-triage.md](docs/support-triage.md)"))
        XCTAssertTrue(support.contains("[docs/hardware-validation.md](docs/hardware-validation.md)"))
        XCTAssertTrue(support.contains("[docs/unsupported-hardware.md](docs/unsupported-hardware.md)"))
        XCTAssertTrue(support.contains("[docs/safe-agent-cooling.md](docs/safe-agent-cooling.md)"))
        XCTAssertTrue(support.contains("[examples/viftyctl](examples/viftyctl/README.md)"))
        XCTAssertTrue(support.contains("Release Trust Report"))
        XCTAssertTrue(support.contains("Hardware Validation Report"))
        XCTAssertTrue(support.contains("Agent Cooling Report"))
        XCTAssertTrue(support.contains("scripts/collect-agent-cooling-evidence.sh"))
        XCTAssertTrue(support.contains("scripts/review-agent-cooling-evidence.sh"))
        XCTAssertTrue(support.contains("It does not request cooling"))
        XCTAssertTrue(support.contains("SMC keys"))
        XCTAssertTrue(support.contains("read-only launchd/helper install files"))
        XCTAssertTrue(support.contains("schema-backed"))
        XCTAssertTrue(support.contains("agent-cooling-evidence-summary.json"))
        XCTAssertTrue(support.contains("https://vifty.local/schemas/agent-cooling-evidence-summary.schema.json"))
        XCTAssertTrue(support.contains("https://vifty.local/schemas/agent-cooling-evidence-review.schema.json"))
        XCTAssertTrue(support.contains("diagnoseDecision"))
        XCTAssertTrue(support.contains("capabilitiesDecision"))
        XCTAssertTrue(support.contains("appInfo"))
        XCTAssertTrue(support.contains("acceptedCommandErrors"))
        XCTAssertTrue(support.contains("structured `HELPER_UNREACHABLE` command error"))
        XCTAssertTrue(support.contains("known v1.1.0 helper-unreachable issue"))
        XCTAssertTrue(support.contains("v1.1.1 source-first hotfix"))
        XCTAssertTrue(support.contains("do not retag v1.1.0 or replace its unsigned-dev assets"))
        XCTAssertTrue(support.contains("Missing or contradictory"))
        XCTAssertTrue(support.contains("unsafe capabilities contract"))
        XCTAssertTrue(support.contains("redaction-needed"))
        XCTAssertTrue(support.contains("blocked-readiness evidence"))
        XCTAssertTrue(support.contains("`v1.1.1`"))
        XCTAssertTrue(support.contains("source-first"))
        XCTAssertTrue(support.contains("unsigned `.app` zip is tester convenience only"))
        XCTAssertTrue(support.contains("viftyctl diagnose --json"))
        XCTAssertTrue(support.contains("viftyctl capabilities --json"))
        XCTAssertTrue(support.contains("viftyctl status --json"))
        XCTAssertTrue(support.contains("viftyctl audit --limit 20 --json"))
        XCTAssertTrue(support.contains("privacy-review.tsv"))
        XCTAssertTrue(support.contains("sudo ViftyHelper setFixed"))
        XCTAssertTrue(support.contains("raw SMC tools"))
        XCTAssertTrue(support.contains("state: \"blocked\""))
        XCTAssertTrue(support.contains("safeToRequestCooling: false"))
        XCTAssertTrue(support.contains("read-only evidence only"))
        XCTAssertTrue(contributing.contains("[docs/support-triage.md](docs/support-triage.md)"))
        XCTAssertTrue(contributing.contains("Release Trust Report"))
        XCTAssertTrue(contributing.contains("Agent Cooling Report"))
        XCTAssertTrue(bugReportTemplate.contains("docs/support-triage.md"))
        XCTAssertTrue(releaseTrustTemplate.contains("name: Release Trust Report"))
        XCTAssertTrue(releaseTrustTemplate.contains("labels: [\"release-trust\"]"))
        XCTAssertTrue(releaseTrustTemplate.contains("scripts/check-release-readiness.sh --mode source-first --version 1.1.1 --repo Reedtrullz/Vifty --json"))
        XCTAssertTrue(releaseTrustTemplate.contains("scripts/check-release-readiness.sh --mode developer-id --version 1.1.1 --repo Reedtrullz/Vifty --require-source-ref origin/main --json"))
        XCTAssertTrue(releaseTrustTemplate.contains("For unpublished source-first candidates, use `--require-source-ref <candidate-ref-or-sha>` only when the ref is intentionally the release commit."))
        XCTAssertTrue(releaseTrustTemplate.contains("Vifty-v<version>-unsigned-dev.zip"))
        XCTAssertTrue(releaseTrustTemplate.contains("Unsigned-dev checksum missing or mismatched"))
        XCTAssertTrue(releaseTrustTemplate.contains("the `.sha256` digest must match the zip bytes"))
        XCTAssertTrue(releaseTrustTemplate.contains("source-first unsigned-dev app zips are tester convenience artifacts"))
        XCTAssertTrue(releaseTrustTemplate.contains("Vifty-v<version>-artifact-summary.json"))
        XCTAssertTrue(releaseTrustTemplate.contains("Vifty-v<version>-release-checklist.md"))
        XCTAssertTrue(releaseTrustTemplate.contains("known helper-unreachable issue"))
        XCTAssertTrue(releaseTrustTemplate.contains("Do not retag v1.1.0 or replace its unsigned-dev assets with a main build"))
        XCTAssertTrue(releaseTrustTemplate.contains("Known source-first helper unreachable issue"))
        XCTAssertTrue(releaseTrustTemplate.contains("scripts/verify-release-artifact.sh --team-id <TEAMID>"))
        XCTAssertTrue(releaseTrustTemplate.contains("scripts/review-validation-evidence.sh --mode release"))
        XCTAssertTrue(releaseTrustTemplate.contains("I did not bypass Gatekeeper"))
        XCTAssertTrue(releaseTrustTemplate.contains("source tags, CI artifacts, and local ad-hoc builds are not trusted public binary releases"))
        XCTAssertTrue(releaseTrustTemplate.contains("I did not run manual fan-write smoke tests or raw SMC commands"))
        XCTAssertTrue(agentCoolingTemplate.contains("name: Agent Cooling Report"))
        XCTAssertTrue(agentCoolingTemplate.contains("labels: [\"agent-cooling\"]"))
        XCTAssertTrue(agentCoolingTemplate.contains("scripts/collect-agent-cooling-evidence.sh"))
        XCTAssertTrue(agentCoolingTemplate.contains("read-only launchd/helper install evidence"))
        XCTAssertTrue(agentCoolingTemplate.contains("It does not request cooling"))
        XCTAssertTrue(agentCoolingTemplate.contains("use `sudo`, or write SMC keys"))
        XCTAssertTrue(agentCoolingTemplate.contains("privacy-review.tsv"))
        XCTAssertTrue(agentCoolingTemplate.contains("redaction-needed"))
        XCTAssertTrue(agentCoolingTemplate.contains("viftyctl diagnose --json"))
        XCTAssertTrue(agentCoolingTemplate.contains("viftyctl capabilities --json"))
        XCTAssertTrue(agentCoolingTemplate.contains("runLifecycle"))
        XCTAssertTrue(agentCoolingTemplate.contains("metadataLimits"))
        XCTAssertTrue(agentCoolingTemplate.contains("viftyctl status --json"))
        XCTAssertTrue(agentCoolingTemplate.contains("viftyctl audit --limit 20 --json"))
        XCTAssertTrue(agentCoolingTemplate.contains("Command stdout/stderr and exit code"))
        XCTAssertTrue(agentCoolingTemplate.contains("Auto restore state"))
        XCTAssertTrue(agentCoolingTemplate.contains("I did not run raw SMC commands"))
        XCTAssertTrue(agentCoolingTemplate.contains("safeToRequestCooling: false"))
        XCTAssertTrue(agentCoolingTemplate.contains("daemonControlPathReady: false"))
        XCTAssertTrue(agentCoolingTemplate.contains("restoreAutoBeforeRequestingCooling"))
        XCTAssertTrue(triage.contains("Release trust"))
        XCTAssertTrue(triage.contains("Hardware validation"))
        XCTAssertTrue(triage.contains("Unsupported hardware safe block"))
        XCTAssertTrue(triage.contains("Helper install or approval"))
        XCTAssertTrue(triage.contains("SMC key or fan telemetry drift"))
        XCTAssertTrue(triage.contains("Agent-cooling lifecycle"))
        XCTAssertTrue(triage.contains("Agent Cooling Report"))
        XCTAssertTrue(triage.contains("make agent-run-smoke-evidence VIFTYCTL=/Applications/Vifty.app/Contents/MacOS/viftyctl"))
        XCTAssertTrue(triage.contains("use the supervised smoke target only after readiness is safe"))
        XCTAssertTrue(triage.contains("UI or copy"))
        XCTAssertTrue(triage.contains("read-only agent evidence bundle"))
        XCTAssertTrue(triage.contains("scripts/collect-agent-cooling-evidence.sh"))
        XCTAssertTrue(triage.contains("scripts/review-agent-cooling-evidence.sh"))
        XCTAssertTrue(triage.contains("agent-cooling-evidence-review.json"))
        XCTAssertTrue(triage.contains("https://vifty.local/schemas/agent-cooling-evidence-review.schema.json"))
        XCTAssertTrue(triage.contains("diagnoseDecision"))
        XCTAssertTrue(triage.contains("capabilitiesDecision"))
        XCTAssertTrue(triage.contains("appInfo"))
        XCTAssertTrue(triage.contains("acceptedCommandErrors"))
        XCTAssertTrue(triage.contains("blocked `diagnose` recommends `repairHelper`"))
        XCTAssertTrue(triage.contains("missing or contradict"))
        XCTAssertTrue(triage.contains("unsafe capabilities contract"))
        XCTAssertTrue(triage.contains("It captures `capabilities --json`, `diagnose --json`, `status --json`, and"))
        XCTAssertTrue(triage.contains("launchd/helper install evidence"))
        XCTAssertTrue(triage.contains("use `sudo`, or write SMC keys"))
        XCTAssertTrue(triage.contains("manifest/status/checksum drift"))
        XCTAssertTrue(triage.contains("blocked-readiness evidence"))
        XCTAssertTrue(triage.contains("lightweight agent"))
        XCTAssertTrue(triage.contains("evidence bundle"))
        XCTAssertTrue(triage.contains("fuller validation evidence bundle"))
        XCTAssertTrue(triage.contains("viftyctl diagnose --json"))
        XCTAssertTrue(triage.contains("viftyctl capabilities --json"))
        XCTAssertTrue(triage.contains("viftyctl audit --limit 20 --json"))
        XCTAssertTrue(triage.contains("Release Trust Report"))
        XCTAssertTrue(triage.contains("scripts/check-release-readiness.sh --mode source-first --version <version> --repo Reedtrullz/Vifty --json"))
        XCTAssertTrue(triage.contains("Do not require `origin/main` for an already-published source-first tag after `main` has moved on."))
        XCTAssertTrue(triage.contains("Do not ask users to verify Developer ID signing, notarization, stapling, or Homebrew trust for `v1.1.1`"))
        XCTAssertTrue(triage.contains("If a `v1.1.0` user reports \"Fan helper unreachable\" after updating"))
        XCTAssertTrue(triage.contains("direct the user to the `v1.1.1` source-first hotfix release"))
        XCTAssertTrue(triage.contains("known v1.1.0 helper-unreachable issue"))
        XCTAssertTrue(triage.contains("v1.1.1 source-first hotfix"))
        XCTAssertTrue(triage.contains("do not retag v1.1.0 or replace its unsigned-dev assets"))
        XCTAssertTrue(triage.contains("Do not treat a source tag, CI artifact, unsigned-dev convenience zip, or local ad-hoc build as a trusted public binary release."))
        XCTAssertTrue(triage.contains("When the UI says `Fixed request pending` or `Curve request pending`"))
        XCTAssertTrue(triage.contains("ui-context.txt"))
        XCTAssertTrue(triage.contains("without requesting cooling or writing SMC keys"))
        XCTAssertTrue(triage.contains("daemonControlPathReady: true"))
        XCTAssertTrue(triage.contains(".github/repo-metadata.json"))
        XCTAssertTrue(triage.contains("scripts/check-github-metadata.sh --repo Reedtrullz/Vifty --json"))
        XCTAssertTrue(triage.contains("Do not ask reporters to run raw SMC writes"))
        XCTAssertTrue(triage.contains("manualSmokeTestResult"))
        XCTAssertTrue(triage.contains("passed-auto-restored"))
        XCTAssertTrue(triage.contains("daemonControlPathReady"))
    }

    func testAgentCoolingTemplateKeepsBlockedReadinessEvidenceOnly() throws {
        let agentCoolingTemplate = try read(".github/ISSUE_TEMPLATE/agent-cooling.yml")

        XCTAssertTrue(agentCoolingTemplate.contains("state: \"blocked\""))
        XCTAssertTrue(agentCoolingTemplate.contains("safeToRequestCooling: false"))
        XCTAssertTrue(agentCoolingTemplate.contains("daemonControlPathReady: false"))
        XCTAssertTrue(agentCoolingTemplate.contains("do not retry `viftyctl prepare` or `viftyctl run`"))
        XCTAssertTrue(agentCoolingTemplate.contains("Preferred evidence bundle"))
        XCTAssertTrue(agentCoolingTemplate.contains("paste the blocked diagnose JSON plus `capabilities --json`, `status --json`, and `audit --limit 20 --json` instead"))
        XCTAssertTrue(agentCoolingTemplate.contains("Readiness blocked before cooling request"))
        XCTAssertTrue(agentCoolingTemplate.contains("paste the diagnose command that blocked instead"))
        XCTAssertTrue(agentCoolingTemplate.contains("I did not request or retry cooling while"))
    }

    func testSecurityPolicyLinksTrustModel() throws {
        let security = try read("SECURITY.md")

        XCTAssertTrue(security.contains("[docs/trust-model.md](docs/trust-model.md)"))
        XCTAssertTrue(security.contains("[docs/release-status.md](docs/release-status.md)"))
        XCTAssertTrue(security.contains("not a substitute for a Developer ID signed, notarized, stapled release artifact"))
    }

    func testTrustModelNamesPrivilegedBoundariesAndWriteAllowlist() throws {
        let trustModel = try read("docs/trust-model.md")

        XCTAssertTrue(trustModel.contains("The SwiftUI app and `viftyctl` run unprivileged."))
        XCTAssertTrue(trustModel.contains("The LaunchDaemon runs as root and owns normal SMC fan writes."))
        XCTAssertTrue(trustModel.contains("`tech.reidar.vifty.helper` for `ViftyHelper` read-only daemon probes."))
        XCTAssertTrue(trustModel.contains("F{n}Md"))
        XCTAssertTrue(trustModel.contains("F{n}md"))
        XCTAssertTrue(trustModel.contains("F{n}Tg"))
        XCTAssertTrue(trustModel.contains("Ftst"))
        XCTAssertTrue(trustModel.contains("Agents request bounded cooling intent. They do not get raw SMC write access."))
        XCTAssertTrue(trustModel.contains("Public releases should be Developer ID signed, notarized, stapled, and TeamID-gated over XPC."))
        XCTAssertTrue(trustModel.contains("[release-status.md](release-status.md)"))
    }

    func testDocsMakePrivateInterfaceRiskExplicit() throws {
        let readme = try read("README.md")
        let trustModel = try read("docs/trust-model.md")
        let compatibility = try read("docs/compatibility.md")

        XCTAssertTrue(readme.contains("Apple can change private SMC/HID behavior in macOS or new hardware revisions without notice."))
        XCTAssertTrue(readme.contains("Vifty treats unknown fan topology, missing sensors, invalid ranges, or drifting SMC mode/target telemetry as a reason to stay in macOS Auto and collect read-only evidence first."))
        XCTAssertTrue(readme.contains("Do not use raw SMC tools or manual fan writes to \"try a new model into support.\""))
        XCTAssertTrue(trustModel.contains("## Private Interface Risk"))
        XCTAssertTrue(trustModel.contains("Apple does not document or guarantee the SMC/HID interfaces Vifty uses."))
        XCTAssertTrue(trustModel.contains("A macOS update or new MacBook Pro revision can change service names, sensor keys, fan mode keys, mode values, or write behavior."))
        XCTAssertTrue(trustModel.contains("When private telemetry is absent, contradictory, or outside known fan ranges, Vifty must fail closed instead of guessing."))
        XCTAssertTrue(compatibility.contains("Private SMC/HID drift is compatibility evidence, not a prompt to experiment with writes."))
    }

    func testReleaseStatusKeepsHomebrewInstallClaimsHonest() throws {
        let readme = try read("README.md")
        let releaseStatus = try read("docs/release-status.md")
        let release = try read("docs/release.md")
        let cask = try read("Casks/vifty.rb")
        let sourceFirstNotes = try read("docs/release-notes/v1.1.0.md")
        let hotfixNotes = try read("docs/release-notes/v1.1.1.md")
        let unsignedDigestBoundary = "The unsigned-dev zip is valid only with its `.sha256` sidecar, and the SHA-256 digest in that sidecar must match the zip bytes."

        XCTAssertTrue(cask.contains("disable! date: \"2026-06-16\", because: \"requires a Developer ID signed and notarized release\""))
        XCTAssertTrue(readme.contains("The latest published public release is Vifty `v1.1.1`, a source-first hotfix release because the project does not currently have Apple Developer Program credentials."))
        XCTAssertTrue(readme.contains("**Three fan modes** — Auto, Fixed RPM with optional percentage-aware per-fan targets, and a 3-point Temperature Curve."))
        XCTAssertTrue(readme.contains("The immutable `v1.1.1` source tag is `a82f2237ff39c24a6b366dca8f95a17ee54fd972`."))
        XCTAssertTrue(readme.contains("Later `main` commits may contain post-release hardening"))
        XCTAssertTrue(readme.contains("Vifty-v1.1.1-unsigned-dev.zip"))
        XCTAssertTrue(readme.contains(unsignedDigestBoundary))
        XCTAssertTrue(readme.contains("""
        git fetch origin main --tags
        git checkout v1.1.1
        make verify
        make source-first-release-notes
        make unsigned-dev-artifact
        make source-first-readiness
        """))
        XCTAssertTrue(readme.contains("This verifies the immutable tag before generating release notes or the unsigned tester artifact."))
        XCTAssertTrue(readme.contains("Superseded release: the published `v1.1.0` source/unsigned-dev release predates helper-install hardening"))
        XCTAssertTrue(readme.contains("use the `v1.1.1` source-first hotfix release instead"))
        XCTAssertTrue(readme.contains("The Homebrew cask is intentionally disabled and parked until Vifty has a Developer ID signed, notarized, stapled, and verifier-passing `Vifty-v<version>.zip` release artifact."))
        XCTAssertTrue(readme.contains("Do not use Homebrew as the recommended or trusted source-first install path"))
        XCTAssertFalse(readme.contains("brew install --cask vifty"))
        XCTAssertTrue(release.contains("[release-status.md](release-status.md)"))
        XCTAssertTrue(release.contains("Source-First Release Mode"))
        XCTAssertTrue(release.contains("This is a source-first release. Vifty v<version> does not yet include a Developer ID signed or notarized public binary"))
        XCTAssertTrue(release.contains("RELEASE_VERSION=<version> make source-first-release-notes"))
        XCTAssertTrue(release.contains("The generated notes include a **Source Provenance** section with the source ref and immutable commit SHA."))
        XCTAssertTrue(release.contains("The Makefile target resolves `v<version>` by default"))
        XCTAssertTrue(release.contains("SOURCE_FIRST_SOURCE_REF=<candidate-ref-or-sha> RELEASE_VERSION=<version> make source-first-release-notes"))
        XCTAssertTrue(release.contains("including the generated immutable source provenance"))
        XCTAssertTrue(release.contains(unsignedDigestBoundary))
        XCTAssertFalse(release.contains("record the immutable `v<version>` tag commit SHA"))
        XCTAssertTrue(release.contains("RELEASE_VERSION=<version> make source-first-readiness"))
        XCTAssertTrue(release.contains("scripts/check-release-readiness.sh \\"))
        XCTAssertTrue(release.contains("--mode source-first"))
        XCTAssertTrue(release.contains("Keep `Casks/vifty.rb` disabled for the source-first release. Do not update its checksum, re-enable it, or point the cask at the unsigned-dev artifact."))
        XCTAssertTrue(release.contains("Remove the cask `disable!` stanza only for the Developer ID/notarized release lane"))
        XCTAssertTrue(releaseStatus.contains("the latest published public release is `v1.1.1`, a source-first hotfix release because the project does not currently have Apple Developer Program credentials."))
        XCTAssertTrue(releaseStatus.contains("The immutable `v1.1.1` source tag resolves to `a82f2237ff39c24a6b366dca8f95a17ee54fd972`"))
        XCTAssertTrue(releaseStatus.contains("Trusted notarized Developer ID release:** unavailable until the project has Apple Developer Program credentials."))
        XCTAssertTrue(releaseStatus.contains("`v1.1.1` is the recommended source tag."))
        XCTAssertTrue(releaseStatus.contains("Unsigned convenience app zip:** optional tester convenience only."))
        XCTAssertTrue(releaseStatus.contains("Vifty-v1.1.1-unsigned-dev.zip"))
        XCTAssertTrue(releaseStatus.contains(unsignedDigestBoundary))
        XCTAssertTrue(releaseStatus.contains("Do not update the Homebrew cask checksum for a source-first release"))
        XCTAssertTrue(releaseStatus.contains("`main` may move after `v1.1.1` publication."))
        XCTAssertTrue(releaseStatus.contains("Known issue: the published `v1.1.0` source/unsigned-dev release predates helper-install and app-polling hardening on `main`"))
        XCTAssertTrue(releaseStatus.contains("Do not retag `v1.1.0`, rebuild `Vifty-v1.1.0-unsigned-dev.zip` from later `main`, or claim the published `v1.1.0` convenience artifact is the official trusted binary."))
        XCTAssertTrue(releaseStatus.contains("The honest remediation is the `v1.1.1` source-first hotfix release"))
        XCTAssertTrue(releaseStatus.contains("`Resources/Info.plist` now carries `1.1.1`; `Casks/vifty.rb` remains on `1.1.0` and is explicitly disabled"))
        XCTAssertTrue(releaseStatus.contains("Do not update the Homebrew cask checksum for a source-first release, do not re-enable the cask, and do not point Homebrew at unsigned-dev artifacts."))
        XCTAssertTrue(releaseStatus.contains("## Source-First v1.1.1 Operator Checks"))
        XCTAssertOrder(
            in: releaseStatus,
            after: "## Source-First v1.1.1 Operator Checks",
            "git checkout v1.1.1",
            before: "make verify",
            message: "Published release boundary checks must verify the immutable v1.1.1 tag, not whatever main currently points at."
        )
        XCTAssertTrue(releaseStatus.contains("RELEASE_VERSION=1.1.1 make source-first-readiness"))
        XCTAssertTrue(releaseStatus.contains("reports `ready` with the attached `Vifty-v1.1.1-unsigned-dev.zip` and checksum assets"))
        XCTAssertTrue(releaseStatus.contains("names `a82f2237ff39c24a6b366dca8f95a17ee54fd972` as the immutable source tag commit"))
        XCTAssertTrue(releaseStatus.contains(".build/Vifty-v1.1.1-source-first-release-notes.md"))
        XCTAssertTrue(releaseStatus.contains("Vifty-v1.1.1-unsigned-dev.zip.sha256"))
        XCTAssertTrue(releaseStatus.contains("Source-first readiness proves the release notes/assets/trust boundaries for the immutable tag. It does not prove the release has no post-publication functional defects"))
        XCTAssertTrue(releaseStatus.contains("Do not use `--require-source-ref origin/main` as a post-publication source-first check unless `origin/main` is intentionally still the release commit."))
        XCTAssertTrue(releaseStatus.contains("scripts/check-release-readiness.sh --mode source-first --version 1.1.1 --repo Reedtrullz/Vifty --source-sha a82f2237ff39c24a6b366dca8f95a17ee54fd972 --json"))
        XCTAssertTrue(releaseStatus.contains("## Superseded v1.1.0 Boundary Audit"))
        XCTAssertFalse(releaseStatus.contains("## Source-First v1.1.0 Operator Checks"))
        XCTAssertTrue(releaseStatus.contains("Use these checks only to reproduce the already-published `v1.1.0` boundary."))
        XCTAssertFalse(releaseStatus.contains("Use these checks before publishing or updating the `v1.1.0` GitHub Release"))
        XCTAssertOrder(
            in: releaseStatus,
            after: "## Superseded v1.1.0 Boundary Audit",
            "git checkout v1.1.0",
            before: "make verify",
            message: "Superseded release audits must verify the immutable v1.1.0 tag, not later main hardening."
        )
        XCTAssertTrue(releaseStatus.contains("They should also include a source provenance section naming the immutable release tag commit"))
        XCTAssertTrue(releaseStatus.contains("make source-first-release-notes"))
        XCTAssertTrue(releaseStatus.contains("Those generated notes should tell maintainers to use `--require-source-ref <candidate-ref-or-sha>` only before publication or with an immutable intended release commit"))
        XCTAssertTrue(releaseStatus.contains("never as a blanket `origin/main` post-publication check"))
        XCTAssertTrue(releaseStatus.contains("make unsigned-dev-artifact"))
        XCTAssertTrue(releaseStatus.contains("make source-first-readiness"))
        XCTAssertTrue(releaseStatus.contains("scripts/check-release-readiness.sh --mode source-first --version 1.1.0 --repo Reedtrullz/Vifty --json"))
        XCTAssertTrue(releaseStatus.contains("scripts/check-release-readiness.sh --mode developer-id --version <version> --repo Reedtrullz/Vifty --require-source-ref origin/main --json"))
        XCTAssertTrue(sourceFirstNotes.contains("## Source Provenance"))
        XCTAssertTrue(sourceFirstNotes.contains("## Known Helper Issue"))
        XCTAssertTrue(sourceFirstNotes.contains("Do not retag `v1.1.0` or silently replace `Vifty-v1.1.0-unsigned-dev.zip` with a build from later `main`."))
        XCTAssertTrue(sourceFirstNotes.contains("The immutable `v1.1.0` source tag is `f7d2c636ebf582ac3809998c3fac819d5d87eb72`."))
        XCTAssertTrue(sourceFirstNotes.contains("Later `main` commits may contain post-release hardening"))
        XCTAssertTrue(sourceFirstNotes.contains(unsignedDigestBoundary))
        XCTAssertTrue(hotfixNotes.contains("# Vifty 1.1.1 Source-First Hotfix Notes"))
        XCTAssertTrue(hotfixNotes.contains("This is a source-first release. Vifty v1.1.1 does not yet include a Developer ID signed or notarized public binary"))
        XCTAssertTrue(hotfixNotes.contains("A convenience unsigned `.app` build is attached for testers who understand macOS Gatekeeper warnings and prefer not to build locally. For the most trusted path, build from source."))
        XCTAssertTrue(hotfixNotes.contains("supersedes the flawed `v1.1.0` unsigned-dev tester build"))
        XCTAssertTrue(hotfixNotes.contains("The bundled daemon is ad-hoc signed with the `tech.reidar.vifty.daemon` identifier"))
        XCTAssertTrue(hotfixNotes.contains("The `v1.1.1` tag is the source release boundary at commit `a82f2237ff39c24a6b366dca8f95a17ee54fd972`."))
        XCTAssertTrue(hotfixNotes.contains("Vifty-v1.1.1-unsigned-dev.zip"))
        XCTAssertTrue(hotfixNotes.contains(unsignedDigestBoundary))
        XCTAssertTrue(hotfixNotes.contains("Do not update the Homebrew cask checksum for this source-first release"))
    }

    func testHardwareValidationPreservesSourceFirstInstallProvenance() throws {
        let compatibility = try read("docs/compatibility.md")
        let hardwareValidation = try read("docs/hardware-validation.md")
        let issueTemplate = try read(".github/ISSUE_TEMPLATE/hardware-validation.yml")

        XCTAssertTrue(compatibility.contains("Install source matters."))
        XCTAssertTrue(compatibility.contains("source builds from the tag and `Vifty-v1.1.1-unsigned-dev.zip` reports can contribute hardware compatibility evidence"))
        XCTAssertTrue(compatibility.contains("Current `main` or other local ad-hoc builds can contribute candidate compatibility evidence only when they are recorded as `local-ad-hoc-build` with the exact source ref and 40-character commit SHA"))
        XCTAssertTrue(compatibility.contains("do not relabel post-release local builds as `source-build-tag`"))
        XCTAssertTrue(compatibility.contains("`install-provenance.tsv`"))
        XCTAssertTrue(compatibility.contains("installSource"))
        XCTAssertTrue(compatibility.contains("sourceArtifactSHA256"))
        XCTAssertTrue(compatibility.contains("Treat those as compatibility-only evidence, not release-trust evidence."))
        XCTAssertTrue(hardwareValidation.contains("For `v1.1.1`, record whether the app came from a source build from the tag or the optional `Vifty-v1.1.1-unsigned-dev.zip` tester artifact."))
        XCTAssertTrue(hardwareValidation.contains("VALIDATION_EVIDENCE_SOURCE_SHA=a82f2237ff39c24a6b366dca8f95a17ee54fd972"))
        XCTAssertTrue(hardwareValidation.contains("VALIDATION_EVIDENCE_SOURCE_ARTIFACT=./Vifty-v1.1.1-unsigned-dev.zip"))
        XCTAssertTrue(hardwareValidation.contains("VALIDATION_EVIDENCE_INSTALL_SOURCE=source-build-tag"))
        XCTAssertTrue(hardwareValidation.contains("VALIDATION_EVIDENCE_INSTALL_SOURCE=source-first-unsigned-dev-zip"))
        XCTAssertTrue(hardwareValidation.contains("install-provenance.tsv"))
        XCTAssertTrue(hardwareValidation.contains("missing `daemonControlPathReady`"))
        XCTAssertTrue(hardwareValidation.contains("--output-markdown .build/validation-reports/compatibility-matrix.md"))
        XCTAssertTrue(hardwareValidation.contains("`modelFamily`"))
        XCTAssertTrue(hardwareValidation.contains("countsByModelFamily"))
        XCTAssertTrue(hardwareValidation.contains("validatedHardwareReportsByModelFamily"))
        XCTAssertTrue(hardwareValidation.contains("The optional `--output-markdown` file is a conservative compatibility matrix draft"))
        XCTAssertTrue(hardwareValidation.contains("`recommendedAgentAction`, `recommendedRecoveryAction`, `daemonControlPathReady`, `agentRunSmokeResult`, and `agentRunSmokeSource`"))
        XCTAssertTrue(hardwareValidation.contains("rejects `source-build-tag`, `source-first-unsigned-dev-zip`, local ad-hoc, unrecorded, or other install sources as release-trust proof"))
        XCTAssertTrue(hardwareValidation.contains("Source-first and unsigned-dev `v1.1.1` hardware reports may leave release-artifact verifier evidence skipped or absent."))
        XCTAssertTrue(issueTemplate.contains("For `v1.1.1`, choose **Source build from tag**"))
        XCTAssertTrue(issueTemplate.contains("the Make target defaults to `VALIDATION_EVIDENCE_INSTALL_SOURCE=local-ad-hoc-build`, `VALIDATION_EVIDENCE_SOURCE_REF=main`, and the current `git rev-parse HEAD` source SHA"))
        XCTAssertTrue(issueTemplate.contains("Do not label post-release local builds as `source-build-tag` unless the installed app was actually built from an immutable release tag."))
        XCTAssertTrue(issueTemplate.contains("For current `main` reports, choose **Local ad-hoc build** and paste the exact source ref/SHA."))
        XCTAssertTrue(issueTemplate.contains("install-provenance.tsv"))
        XCTAssertTrue(issueTemplate.contains("Source/ref or artifact checksum"))
        XCTAssertTrue(issueTemplate.contains("None of those paths are Developer ID signed, notarized, Homebrew-trusted, or a trusted public binary release."))
        XCTAssertTrue(issueTemplate.contains("description: How did you install this build? For v1.1.1, prefer Source build from tag or Source-first unsigned-dev zip. For current main/local builds, choose Local ad-hoc build with the exact source SHA."))
        XCTAssertTrue(issueTemplate.contains("v1.1.1 / a82f2237ff39c24a6b366dca8f95a17ee54fd972 / Vifty-v1.1.1-unsigned-dev.zip sha256 ... or main / <40-character-source-sha>"))
        XCTAssertTrue(issueTemplate.contains("- Source build from tag"))
        XCTAssertTrue(issueTemplate.contains("- Source-first unsigned-dev zip"))
        XCTAssertTrue(issueTemplate.contains("- Local ad-hoc build"))
        XCTAssertTrue(issueTemplate.contains("Source-first source builds and unsigned-dev reports may skip release-artifact-summary evidence"))
    }

    func testCompatibilityPageRequiresReportBackedEvidence() throws {
        let compatibility = try read("docs/compatibility.md")
        let matrix = try read("docs/validation-reports/compatibility-matrix.md")
        let index = try read("docs/validation-reports/compatibility-index.json")
        let reportReadme = try read("docs/validation-reports/README.md")

        XCTAssertTrue(compatibility.contains("Vifty's compatibility claims are evidence-based"))
        XCTAssertTrue(compatibility.contains("Hardware Validation Report"))
        XCTAssertTrue(compatibility.contains("scripts/collect-validation-evidence.sh"))
        XCTAssertTrue(compatibility.contains("scripts/review-validation-evidence.sh"))
        XCTAssertTrue(compatibility.contains("scripts/summarize-validation-reports.sh"))
        XCTAssertTrue(compatibility.contains("review-result.json"))
        XCTAssertTrue(compatibility.contains("supported-hardware-evidence-needs-manual-smoke"))
        XCTAssertTrue(compatibility.contains("validated-hardware-evidence"))
        XCTAssertTrue(compatibility.contains("--output-markdown <reports-dir>/compatibility-matrix.md"))
        XCTAssertTrue(compatibility.contains("The generated `compatibility-matrix.md` ignores release-trust rows for hardware status"))
        XCTAssertTrue(compatibility.contains("`modelFamily` is the stable prefix derived from `modelIdentifier`"))
        XCTAssertTrue(compatibility.contains("`countsByModelFamily`"))
        XCTAssertTrue(compatibility.contains("`validatedHardwareReportsByModelFamily`"))
        XCTAssertTrue(compatibility.contains("The matrix evidence cell intentionally shows source ref plus short SHA, reviewed date, and manual/agent smoke status"))
        XCTAssertTrue(compatibility.contains("`reviewGeneratedAtUTC`"))
        XCTAssertTrue(compatibility.contains("manualSmokeTestResult: \"passed-auto-restored\""))
        XCTAssertTrue(compatibility.contains("Supervised `viftyctl run` smoke evidence is useful developer-workload proof"))
        XCTAssertTrue(compatibility.contains("`capabilities --json`"))
        XCTAssertTrue(compatibility.contains("safe `runLifecycle` contract, `policyStatusAvailable: true`, and policy/metadata limits"))
        XCTAssertTrue(compatibility.contains("accepted only when the adjacent smoke bundle has matching `manifest.tsv`, per-command `.status` files, and `checksums.tsv` coverage"))
        XCTAssertTrue(compatibility.contains("verifies the adjacent manifest/status/checksum files"))
        XCTAssertTrue(compatibility.contains("wait for `policy.prepareCooldownSeconds`"))
        XCTAssertTrue(compatibility.contains("`PREPARE_RATE_LIMITED` response with `retryAfterSeconds`"))
        XCTAssertTrue(compatibility.contains("The reviewer requires `rateLimitRetry` to match the initial `PREPARE_RATE_LIMITED` JSON"))
        XCTAssertTrue(compatibility.contains("requires the final `run` proof to reference the `viftyctl-run-retry` command files"))
        XCTAssertTrue(compatibility.contains("viftyctl diagnose --json"))
        XCTAssertTrue(compatibility.contains("ViftyHelper probeLocal"))
        XCTAssertTrue(compatibility.contains("| M1 Pro/Max MacBook Pro | Needs manual smoke |"))
        XCTAssertTrue(compatibility.contains("Two read-only local ad-hoc `MacBookPro18,1` candidate reports exist"))
        XCTAssertTrue(compatibility.contains("manualSmokeTestResult: \"not-recorded\""))
        XCTAssertTrue(matrix.contains("| MacBookPro18 | Needs manual smoke | 0 | 2 |"))
        XCTAssertTrue(matrix.contains("source: main@8cbabb9, main@b757c4b<br>reviewed: 2026-06-15, 2026-06-16<br>manual: not recorded"))
        XCTAssertTrue(index.contains("\"validatedHardwareReports\": 0"))
        XCTAssertTrue(index.contains("\"manualSmokeRequiredReports\": 2"))
        XCTAssertTrue(index.contains("\"source\": \"docs/validation-reports/2026-06-14-macbookpro18-local-readonly/review-result.json\""))
        XCTAssertTrue(index.contains("\"source\": \"docs/validation-reports/2026-06-16-macbookpro18-main-readonly/review-result.json\""))
        XCTAssertTrue(index.contains("\"reviewGeneratedAtUTC\": \"2026-06-15T14:55:54Z\""))
        XCTAssertTrue(index.contains("\"reviewGeneratedAtUTC\": \"2026-06-16T14:11:31Z\""))
        XCTAssertTrue(index.contains("\"sourceRef\": \"main\""))
        XCTAssertTrue(index.contains("\"sourceSHA\": \"b757c4b9434e55bc9bbde2be31b8a8cfe6c60442\""))
        XCTAssertTrue(index.contains("\"sourceSHA\": \"8cbabb90a67934a7fe6a79ab090ff5c3a6da796b\""))
        XCTAssertFalse(index.contains("/Users/"))
        XCTAssertTrue(reportReadme.contains("reviewed validation summaries, not raw evidence bundles"))
        XCTAssertTrue(reportReadme.contains("Candidate supported-hardware rows remain **Needs manual smoke**"))
        XCTAssertTrue(compatibility.contains("Do not run the manual smoke test when readiness is `blocked`"))
        XCTAssertTrue(compatibility.contains("Do not add a README compatibility badge or broad marketing claim until the status table has real report links."))
    }

    func testCompetitiveAnalysisCodifiesDifferentiatedRoadmap() throws {
        let analysis = try read("docs/competitive-analysis.md")
        let readme = try read("README.md")

        XCTAssertTrue(readme.contains("[docs/competitive-analysis.md](docs/competitive-analysis.md)"))
        XCTAssertTrue(analysis.contains("open-source, auditable thermal-control layer for Apple Silicon MacBook Pro developer workloads"))
        XCTAssertTrue(analysis.contains("Do not compete as a general-purpose system monitor yet."))
        XCTAssertTrue(analysis.contains("Macs Fan Control"))
        XCTAssertTrue(analysis.contains("TG Pro"))
        XCTAssertTrue(analysis.contains("iStat Menus"))
        XCTAssertTrue(analysis.contains("Stats"))
        XCTAssertTrue(analysis.contains("Hot and MacThrottle"))
        XCTAssertTrue(analysis.contains("Sensei"))
        XCTAssertTrue(analysis.contains("AlDente and coconutBattery"))
        XCTAssertTrue(analysis.contains("trusted release story"))
        XCTAssertTrue(analysis.contains("hardware validation evidence"))
        XCTAssertTrue(analysis.contains("helper repair clarity"))
        XCTAssertTrue(analysis.contains("menu-bar display modes"))
        XCTAssertTrue(analysis.contains("optional local notifications"))
        XCTAssertTrue(analysis.contains("Sparkle auto-update only in the future trusted binary lane"))
        XCTAssertTrue(analysis.contains("defer MCP and Shortcuts"))
        XCTAssertTrue(analysis.contains("No breaking changes to existing `viftyctl` JSON fields."))
        XCTAssertTrue(analysis.contains("Homebrew stays parked until a Developer ID signed, notarized release exists."))
        XCTAssertTrue(analysis.contains("Subtle in-memory trend sparklines are in scope when they help users judge build, test, or agent workload impact"))
        XCTAssertTrue(analysis.contains("full historical monitoring, cloud sync, analytics, and persistent telemetry remain out of scope without a separate privacy plan"))
    }

    func testDocsKeepTelemetryHistoryVisualizationLocalAndScoped() throws {
        let readme = try read("README.md")
        let trustModel = try read("docs/trust-model.md")
        let analysis = try read("docs/competitive-analysis.md")
        let plan = try read("docs/plans/2026-06-13-next-workplan.md")
        let agents = try read("AGENTS.md")

        XCTAssertTrue(readme.contains("subtle in-memory trend sparklines for recent selected temperature, fan RPM, power flow, and thermal-pressure state"))
        XCTAssertTrue(readme.contains("samples stay local and reset with the app"))
        XCTAssertTrue(readme.contains("Trend sparklines and readouts are rendered from the in-memory rolling buffer only"))
        XCTAssertTrue(readme.contains("no analytics, accounts, network uploads, cloud dependencies, or persistent telemetry export"))
        XCTAssertTrue(trustModel.contains("telemetry history and trend visualizations are derived from an in-memory rolling sample buffer only"))
        XCTAssertTrue(trustModel.contains("Vifty does not persist or export those samples"))
        XCTAssertTrue(analysis.contains("Do not compete as a general-purpose system monitor yet."))
        XCTAssertTrue(analysis.contains("full historical monitoring, cloud sync, analytics, and persistent telemetry remain out of scope without a separate privacy plan"))
        XCTAssertTrue(plan.contains("Keep history in memory unless a future privacy plan approves persistence."))
        XCTAssertTrue(plan.contains("No persistent telemetry is added."))
        XCTAssertTrue(agents.contains("Telemetry history is in-memory only"))
        XCTAssertFalse(readme.contains("persistent telemetry history"))
    }

    func testNextWorkplanPrioritizesAvailableHardwareAndTrustBoundaries() throws {
        let plan = try read("docs/plans/2026-06-13-next-workplan.md")
        let analysis = try read("docs/competitive-analysis.md")
        let agents = try read("AGENTS.md")

        XCTAssertTrue(analysis.contains("[plans/2026-06-13-next-workplan.md](plans/2026-06-13-next-workplan.md)"))
        XCTAssertTrue(agents.contains("`docs/plans/2026-06-13-next-workplan.md`"))
        XCTAssertTrue(plan.contains("available real hardware for immediate validation is the user's M1 Pro MacBook Pro"))
        XCTAssertTrue(plan.contains("Other M1 Max, M2, M3, M4, and newer MacBook Pro rows must remain \"needs report\" until contributor evidence exists."))
        XCTAssertTrue(plan.contains("source-build-tag"))
        XCTAssertTrue(plan.contains("source-first-unsigned-dev-zip"))
        XCTAssertTrue(plan.contains("local-ad-hoc-build"))
        XCTAssertTrue(plan.contains("make validation-evidence"))
        XCTAssertTrue(plan.contains("VALIDATION_EVIDENCE_INSTALL_SOURCE=source-build-tag"))
        XCTAssertTrue(plan.contains("VALIDATION_EVIDENCE_INCLUDE_PROBE_LOCAL=1"))
        XCTAssertTrue(plan.contains("scripts/review-validation-evidence.sh --bundle .build/vifty-validation-<timestamp>"))
        XCTAssertTrue(plan.contains("--manual-smoke-result passed-auto-restored"))
        XCTAssertTrue(plan.contains("scripts/collect-agent-run-smoke-evidence.sh"))
        XCTAssertTrue(plan.contains("the bounded `viftyctl run` lifecycle"))
        XCTAssertTrue(plan.contains("Ensure both left and right panes scroll predictably at minimum supported window sizes."))
        XCTAssertTrue(plan.contains("Keep the right-side operational panel full-height"))
        XCTAssertTrue(plan.contains("Avoid duplicate power information such as separate \"140 W adapter\" rows"))
        XCTAssertTrue(plan.contains("selected sensor temperature"))
        XCTAssertTrue(plan.contains("helper install, approval, unreachable, repair, unsupported, and healthy states"))
        XCTAssertTrue(plan.contains("Sparkle auto-update unavailable for source-first and unsigned-dev builds"))
        XCTAssertTrue(plan.contains("Homebrew cask updates before a verified Developer ID/notarized artifact exists"))
    }

    func testAutoUpdateDocsKeepSourceFirstBuildsOutOfSelfUpdatingLane() throws {
        let autoUpdate = try read("docs/auto-update.md")
        let readme = try read("README.md")
        let releaseStatus = try read("docs/release-status.md")

        XCTAssertTrue(readme.contains("[docs/auto-update.md](docs/auto-update.md)"))
        XCTAssertTrue(releaseStatus.contains("[auto-update.md](auto-update.md)"))
        XCTAssertTrue(autoUpdate.contains("Auto-update is not enabled for `v1.1.1` source-first or unsigned-dev builds."))
        XCTAssertTrue(autoUpdate.contains("Do not attach an updater to `Vifty-v<version>-unsigned-dev.zip`"))
        XCTAssertTrue(autoUpdate.contains("Sparkle 2"))
        XCTAssertTrue(autoUpdate.contains("Developer ID signed, notarized, stapled"))
        XCTAssertTrue(autoUpdate.contains("EdDSA-signed appcast"))
        XCTAssertTrue(autoUpdate.contains("HTTPS `SUFeedURL`"))
        XCTAssertTrue(autoUpdate.contains("`SUPublicEDKey`"))
        XCTAssertTrue(autoUpdate.contains("`SURequireSignedFeed`"))
        XCTAssertTrue(autoUpdate.contains("`SUVerifyUpdateBeforeExtraction`"))
        XCTAssertTrue(autoUpdate.contains("canonical `Vifty-v<version>.zip`"))
        XCTAssertTrue(autoUpdate.contains("Homebrew checksum handoff"))
        XCTAssertTrue(autoUpdate.contains("No updater network checks should run in source-first mode."))
    }

    func testReleaseDocsIncludeFutureAutoUpdateReadinessChecks() throws {
        let release = try read("docs/release.md")
        let trustModel = try read("docs/trust-model.md")

        XCTAssertTrue(release.contains("[auto-update.md](auto-update.md)"))
        XCTAssertTrue(release.contains("Sparkle auto-update is future Developer ID release work"))
        XCTAssertTrue(release.contains("Do not enable Sparkle for source-first or unsigned-dev artifacts."))
        XCTAssertTrue(release.contains("SUFeedURL"))
        XCTAssertTrue(release.contains("SUPublicEDKey"))
        XCTAssertTrue(release.contains("generate_appcast"))
        XCTAssertTrue(release.contains("signed appcast"))
        XCTAssertTrue(release.contains("canonical `Vifty-v<version>.zip`"))
        XCTAssertTrue(trustModel.contains("[auto-update.md](auto-update.md)"))
        XCTAssertTrue(trustModel.contains("Auto-update installs executable code and therefore belongs only to the future trusted binary lane."))
    }

    func testSourceFirstInfoPlistDoesNotAdvertiseSparkleFeed() throws {
        let plist = try read("Resources/Info.plist")

        XCTAssertFalse(plist.contains("SUFeedURL"))
        XCTAssertFalse(plist.contains("SUPublicEDKey"))
        XCTAssertFalse(plist.contains("SURequireSignedFeed"))
    }

    func testReadmeExplainsInstallTrustLevelsAndPrivilegedHelperReason() throws {
        let readme = try read("README.md")

        XCTAssertTrue(readme.contains("### Install trust levels"))
        XCTAssertTrue(readme.contains("1. **Source build:** recommended while Apple Developer Program credentials are unavailable."))
        XCTAssertTrue(readme.contains("2. **Unsigned tester app:** optional `Vifty-v1.1.1-unsigned-dev.zip` convenience build"))
        XCTAssertTrue(readme.contains("3. **Future trusted binary:** Developer ID signed, notarized, stapled, checksum-verified, and then eligible for Homebrew."))
        XCTAssertTrue(readme.contains("### Why a privileged helper?"))
        XCTAssertTrue(readme.contains("The normal SwiftUI app and `viftyctl` stay unprivileged."))
        XCTAssertTrue(readme.contains("the LaunchDaemon owns the narrow root path for SMC fan writes"))
        XCTAssertTrue(readme.contains("allowlisted fan mode keys `F{n}Md` / `F{n}md`, fan target keys `F{n}Tg`, and guarded `Ftst` unlock cleanup"))
        XCTAssertTrue(readme.contains("read-only through local IOKit or daemon snapshots"))
        XCTAssertTrue(readme.contains("[docs/trust-model.md](docs/trust-model.md)"))
    }

    func testCompatibilityPageNamesGeneratedMatrixAndPriorityReports() throws {
        let compatibility = try read("docs/compatibility.md")

        XCTAssertTrue(compatibility.contains("## Generated Compatibility Matrix"))
        XCTAssertTrue(compatibility.contains("Do not hand-edit the generated compatibility matrix."))
        XCTAssertTrue(compatibility.contains("Needs report"))
        XCTAssertTrue(compatibility.contains("helper health"))
        XCTAssertTrue(compatibility.contains("fan count"))
        XCTAssertTrue(compatibility.contains("min/max RPM"))
        XCTAssertTrue(compatibility.contains("Auto restore"))
        XCTAssertTrue(compatibility.contains("Fixed/Curve smoke"))
        XCTAssertTrue(compatibility.contains("`viftyctl diagnose --json`"))
        XCTAssertTrue(compatibility.contains("First-report priority is M1 Pro/Max, M2 Pro/Max, M3 Pro/Max, and M4 Pro/Max MacBook Pro hardware."))
    }

    func testAgentWorkflowDocsKeepDirectPrepareTrapBounded() throws {
        let agentWorkflows = try read("docs/agent-workflows.md")
        let safeAgentCooling = try read("docs/safe-agent-cooling.md")

        for document in [agentWorkflows, safeAgentCooling] {
            XCTAssertTrue(document.contains("PREPARED=0"))
            XCTAssertTrue(document.contains("trap cleanup EXIT INT TERM HUP"))
            XCTAssertTrue(document.contains("restore-auto \\"))
            XCTAssertTrue(document.contains("|| status=70"))
            XCTAssertTrue(document.contains("PREPARED=1"))
        }

        XCTAssertTrue(agentWorkflows.contains("This pattern still has more moving parts than `viftyctl run`"))
        XCTAssertTrue(safeAgentCooling.contains("Direct prepare is the exception because the shell now owns cleanup"))
        XCTAssertFalse(agentWorkflows.contains("show what Vifty actually did without requesting cooling or reading raw SMC state.\n- `generatedAt`"))
    }

    func testUnsupportedHardwarePolicyDefinesSafeBlocks() throws {
        let readme = try read("README.md")
        let compatibility = try read("docs/compatibility.md")
        let hardwareValidation = try read("docs/hardware-validation.md")
        let trustModel = try read("docs/trust-model.md")
        let supportTriage = try read("docs/support-triage.md")
        let issueTemplate = try read(".github/ISSUE_TEMPLATE/hardware-validation.yml")
        let policy = try read("docs/unsupported-hardware.md")

        XCTAssertTrue(readme.contains("[docs/unsupported-hardware.md](docs/unsupported-hardware.md)"))
        XCTAssertTrue(compatibility.contains("[unsupported-hardware.md](unsupported-hardware.md)"))
        XCTAssertTrue(hardwareValidation.contains("[unsupported-hardware.md](unsupported-hardware.md)"))
        XCTAssertTrue(trustModel.contains("[unsupported-hardware.md](unsupported-hardware.md)"))
        XCTAssertTrue(supportTriage.contains("[unsupported-hardware.md](unsupported-hardware.md)"))
        XCTAssertTrue(issueTemplate.contains("docs/unsupported-hardware.md"))
        XCTAssertTrue(policy.contains("Apple Silicon MacBook Pro"))
        XCTAssertTrue(policy.contains("Unsupported hardware safe block"))
        XCTAssertTrue(policy.contains("safeToRequestCooling: false"))
        XCTAssertTrue(policy.contains("viftyctl diagnose --json"))
        XCTAssertTrue(policy.contains("viftyctl status --json"))
        XCTAssertTrue(policy.contains("review-result.json"))
        XCTAssertTrue(policy.contains("--mode unsupported-hardware"))
        XCTAssertTrue(policy.contains("Do not run manual fan-write smoke tests"))
        XCTAssertTrue(policy.contains("sudo ViftyHelper setFixed"))
        XCTAssertTrue(policy.contains("raw SMC tools"))
        XCTAssertTrue(policy.contains("must not be used as proof that fan control is supported"))
    }

    func testHardwareValidationTemplateKeepsUnsupportedReportsReadOnly() throws {
        let compatibility = try read("docs/compatibility.md")
        let issueTemplate = try read(".github/ISSUE_TEMPLATE/hardware-validation.yml")

        XCTAssertTrue(compatibility.contains("Always capture `sudo /Applications/Vifty.app/Contents/MacOS/ViftyHelper probeLocal` for supported MacBook Pro validation"))
        XCTAssertTrue(compatibility.contains("Follow [unsupported-hardware.md](unsupported-hardware.md) for unsupported-hardware safe-block reports."))
        XCTAssertTrue(issueTemplate.contains("ViftyHelper probeLocal output (supported hardware)"))
        XCTAssertTrue(issueTemplate.contains("supported Apple Silicon MacBook Pro validation"))
        XCTAssertTrue(issueTemplate.contains("Unsupported machines should follow docs/unsupported-hardware.md and collect read-only evidence only."))
        XCTAssertTrue(issueTemplate.contains("A `viftyctl diagnose --json` report showing the hardware gate is enough for unsupported safe-block reports."))
        XCTAssertTrue(issueTemplate.contains("Unsupported safe-block reports may leave this blank"))
        XCTAssertTrue(issueTemplate.contains("Only run the manual fan write smoke test on supported Apple Silicon MacBook Pro hardware"))

        let probeLocalSection = try XCTUnwrap(issueTemplate.range(of: "id: probe-local"))
        let manualSmokeSection = try XCTUnwrap(issueTemplate.range(of: "id: manual-smoke"))
        let section = String(issueTemplate[probeLocalSection.lowerBound..<manualSmokeSection.lowerBound])
        XCTAssertTrue(section.contains("required: false"))
        XCTAssertFalse(section.contains("required: true"))
    }

    func testBugReportTemplateKeepsBlockedFanReportsReadOnlyFirst() throws {
        let bugReportTemplate = try read(".github/ISSUE_TEMPLATE/bug-report.yml")

        XCTAssertTrue(bugReportTemplate.contains("For fan, sensor, helper, or agent-cooling bugs, start with read-only diagnostics where possible."))
        XCTAssertTrue(bugReportTemplate.contains("If `viftyctl diagnose --json` reports unsupported hardware, `safeToRequestCooling: false`, or `daemonControlPathReady: false`"))
        XCTAssertTrue(bugReportTemplate.contains("do not run manual fan-write commands or raw SMC tools"))
        XCTAssertTrue(bugReportTemplate.contains("leave helper probe output blank unless a maintainer asks for it"))
        XCTAssertTrue(bugReportTemplate.contains("For supported Apple Silicon MacBook Pro hardware/sensor/fan bugs"))
        XCTAssertTrue(bugReportTemplate.contains("Unsupported or blocked safe-block reports may leave this blank"))

        let helperProbeSection = try XCTUnwrap(bugReportTemplate.range(of: "id: helper-probe"))
        let agentCommandSection = try XCTUnwrap(bugReportTemplate.range(of: "id: agent-command"))
        let section = String(bugReportTemplate[helperProbeSection.lowerBound..<agentCommandSection.lowerBound])
        XCTAssertTrue(section.contains("required: false"))
        XCTAssertFalse(section.contains("required: true"))
    }

    func testPullRequestTemplateRequiresSafetyReview() throws {
        let contributing = try read("CONTRIBUTING.md")
        let template = try read(".github/PULL_REQUEST_TEMPLATE.md")

        XCTAssertTrue(contributing.contains("Fill out the PR safety impact section"))
        XCTAssertTrue(contributing.contains("fan/SMC writes"))
        XCTAssertTrue(contributing.contains("agent leases"))
        XCTAssertTrue(contributing.contains("Run `make verify`"))
        XCTAssertTrue(contributing.contains("Current source-first tags may publish source plus clearly marked unsigned-dev tester artifacts"))
        XCTAssertTrue(contributing.contains("without claiming Developer ID signing, notarization, Homebrew trust, or official trusted binary status"))
        XCTAssertTrue(contributing.contains("Future trusted binary releases follow [docs/release.md](docs/release.md)"))
        XCTAssertTrue(template.contains("## Safety Impact"))
        XCTAssertTrue(template.contains("Fan/SMC writes"))
        XCTAssertTrue(template.contains("Privileged daemon, helper, installer, signing, or XPC identity"))
        XCTAssertTrue(template.contains("`viftyctl`, agent leases, JSON contracts, or workload wrappers"))
        XCTAssertTrue(template.contains("Hardware validation, release trust, compatibility, or unsupported-hardware policy"))
        XCTAssertTrue(template.contains("UI state for Auto restore, helper health, fan ownership, or active agent cooling"))
        XCTAssertTrue(template.contains("Local persistence, permissions, telemetry, or audit history"))
        XCTAssertTrue(template.contains("## Verification"))
        XCTAssertTrue(template.contains("make verify"))
        XCTAssertTrue(template.contains("reject arbitrary keys"))
        XCTAssertTrue(template.contains("invalid fan IDs"))
        XCTAssertTrue(template.contains("safeToRequestCooling"))
        XCTAssertTrue(template.contains("daemonControlPathReady"))
        XCTAssertTrue(template.contains("recommendedAgentAction"))
        XCTAssertTrue(template.contains("fail closed"))
        XCTAssertTrue(template.contains("manual fan-write smoke tests when readiness is blocked"))
        XCTAssertTrue(template.contains("persistent telemetry beyond documented agent-control audit state"))
    }

    func testCodeownersNamesSafetySensitiveTrustSurfaces() throws {
        let codeowners = try read(".github/CODEOWNERS")

        XCTAssertTrue(codeowners.contains("# Agent control safety surface"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/AgentControlModels.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/AgentControlPolicy.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/AgentControlService.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/AgentControlStore.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/ViftyCtlArguments.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/ViftyCtlReadinessReport.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/ViftyCtlRunner.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCtl/"))
        XCTAssertTrue(codeowners.contains("# Agent-facing contracts and examples"))
        XCTAssertTrue(codeowners.contains("docs/agent-workflows.md"))
        XCTAssertTrue(codeowners.contains("docs/agent-integrations.md"))
        XCTAssertTrue(codeowners.contains("docs/safe-agent-cooling.md"))
        XCTAssertTrue(codeowners.contains("docs/examples/viftyctl/"))
        XCTAssertTrue(codeowners.contains("docs/schemas/"))
        XCTAssertTrue(codeowners.contains("examples/viftyctl/"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/agent-cooling.yml"))
        XCTAssertTrue(codeowners.contains("# IOKit / SMC surface"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/HardwareService.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/LocalFanHelperClient.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/SMCClient.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyCore/RealMacHardwareService.swift"))
        XCTAssertTrue(codeowners.contains("Sources/ViftyPrivateIOKit/"))
        XCTAssertTrue(codeowners.contains("# Release, installer, and daemon plist"))
        XCTAssertTrue(codeowners.contains(".github/workflows/release.yml"))
        XCTAssertTrue(codeowners.contains(".github/workflows/ci.yml"))
        XCTAssertTrue(codeowners.contains("Casks/vifty.rb"))
        XCTAssertTrue(codeowners.contains("Resources/Info.plist"))
        XCTAssertTrue(codeowners.contains("Resources/Vifty.entitlements"))
        XCTAssertTrue(codeowners.contains("Resources/ViftyDaemon.entitlements"))
        XCTAssertTrue(codeowners.contains("Resources/tech.reidar.vifty.daemon.plist"))
        XCTAssertTrue(codeowners.contains("# Compatibility, validation, and policy surfaces"))
        XCTAssertTrue(codeowners.contains("docs/compatibility.md"))
        XCTAssertTrue(codeowners.contains("docs/hardware-validation.md"))
        XCTAssertTrue(codeowners.contains("docs/release.md"))
        XCTAssertTrue(codeowners.contains("docs/release-status.md"))
        XCTAssertTrue(codeowners.contains("docs/support-triage.md"))
        XCTAssertTrue(codeowners.contains("docs/trust-model.md"))
        XCTAssertTrue(codeowners.contains("docs/unsupported-hardware.md"))
        XCTAssertTrue(codeowners.contains("SUPPORT.md"))
        XCTAssertTrue(codeowners.contains(".github/repo-metadata.json"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/release-trust.yml"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/hardware-validation.yml"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/bug-report.yml"))
        XCTAssertTrue(codeowners.contains(".github/ISSUE_TEMPLATE/config.yml"))
        XCTAssertTrue(codeowners.contains("# Repo safety process"))
        XCTAssertTrue(codeowners.contains(".github/PULL_REQUEST_TEMPLATE.md"))
        XCTAssertTrue(codeowners.contains("AGENTS.md"))
        XCTAssertTrue(codeowners.contains("CONTRIBUTING.md"))
        XCTAssertTrue(codeowners.contains("SECURITY.md"))
    }

    func testReleaseAndHardwareDocsPointBackToCompatibilityStatus() throws {
        let release = try read("docs/release.md")
        let hardwareValidation = try read("docs/hardware-validation.md")
        let hardwareValidationTemplate = try read(".github/ISSUE_TEMPLATE/hardware-validation.yml")

        XCTAssertTrue(release.contains("make verify"))
        XCTAssertTrue(release.contains("[compatibility.md](compatibility.md)"))
        XCTAssertTrue(release.contains("scripts/verify-release-artifact.sh"))
        XCTAssertTrue(release.contains("scripts/collect-validation-evidence.sh"))
        XCTAssertTrue(release.contains("scripts/review-validation-evidence.sh"))
        XCTAssertTrue(release.contains("scripts/summarize-validation-reports.sh"))
        XCTAssertTrue(release.contains("--output-markdown <reports-dir>/compatibility-matrix.md"))
        XCTAssertTrue(release.contains("review-result.json"))
        XCTAssertTrue(release.contains("validation-review-result"))
        XCTAssertTrue(release.contains("agent-cooling evidence summary/review"))
        XCTAssertTrue(release.contains("validated-hardware-evidence"))
        XCTAssertTrue(release.contains("Vifty-v<version>-artifact-summary.json"))
        XCTAssertTrue(release.contains("review-summary.json"))
        XCTAssertTrue(release.contains("capabilities-contract.tsv"))
        XCTAssertTrue(hardwareValidation.contains("[compatibility.md](compatibility.md)"))
        XCTAssertTrue(hardwareValidation.contains("make validation-evidence"))
        XCTAssertTrue(hardwareValidation.contains("VALIDATION_EVIDENCE_INSTALL_SOURCE=source-build-tag"))
        XCTAssertTrue(hardwareValidation.contains("VALIDATION_EVIDENCE_RELEASE_SUMMARY=./Vifty-v<version>-artifact-summary.json"))
        XCTAssertTrue(hardwareValidation.contains("VALIDATION_EVIDENCE_INCLUDE_PROBE_LOCAL=1"))
        XCTAssertTrue(hardwareValidation.contains("scripts/collect-validation-evidence.sh"))
        XCTAssertTrue(hardwareValidation.contains("scripts/review-validation-evidence.sh"))
        XCTAssertTrue(hardwareValidation.contains("scripts/summarize-validation-reports.sh"))
        XCTAssertTrue(hardwareValidation.contains("review-result.json"))
        XCTAssertTrue(hardwareValidation.contains("https://vifty.local/schemas/validation-review-result.schema.json"))
        XCTAssertTrue(hardwareValidation.contains("--manual-smoke-result passed-auto-restored"))
        XCTAssertTrue(hardwareValidation.contains("## M1 Pro Local Validation Quick Path"))
        XCTAssertTrue(hardwareValidation.contains("MacBookPro18,1"))
        XCTAssertTrue(hardwareValidation.contains("Keep Fixed and Curve smoke human-supervised in the app UI"))
        XCTAssertTrue(hardwareValidation.contains("Do not automate UI clicking, raw `ViftyHelper setFixed`, raw `ViftyHelper auto`, or third-party SMC writes for support promotion."))
        XCTAssertTrue(hardwareValidation.contains("does not replace manual Auto/Fixed/Curve smoke for `validated-hardware-evidence`"))
        XCTAssertTrue(hardwareValidation.contains("## Supervised Agent Run Smoke Test"))
        XCTAssertTrue(hardwareValidation.contains("scripts/collect-agent-run-smoke-evidence.sh"))
        XCTAssertTrue(hardwareValidation.contains("make agent-run-smoke-evidence \\"))
        XCTAssertTrue(hardwareValidation.contains("VIFTYCTL=/Applications/Vifty.app/Contents/MacOS/viftyctl"))
        XCTAssertTrue(hardwareValidation.contains("AGENT_RUN_SMOKE_OUTPUT=<dir>"))
        XCTAssertTrue(hardwareValidation.contains("AGENT_RUN_SMOKE_DURATION=<duration>"))
        XCTAssertTrue(hardwareValidation.contains("AGENT_RUN_SMOKE_MAX_RPM_PERCENT=<percent>"))
        XCTAssertTrue(hardwareValidation.contains("AGENT_RUN_SMOKE_REASON=<text>"))
        XCTAssertTrue(hardwareValidation.contains("AGENT_RUN_SMOKE_AUDIT_LIMIT=<count>"))
        XCTAssertTrue(hardwareValidation.contains("agent-run-smoke-evidence-summary.json"))
        XCTAssertTrue(hardwareValidation.contains("`manifest.tsv` must match the summary `commands[]`"))
        XCTAssertTrue(hardwareValidation.contains("`checksums.tsv` must cover and recompute the summary, manifest, command stdout/stderr, and status files"))
        XCTAssertTrue(hardwareValidation.contains("`coolingLeasePrepared=true`, `autoRestoreAttempted=true`, `autoRestoreSucceeded=true`, and `childExitCode=0`"))
        XCTAssertTrue(hardwareValidation.contains("not read-only when readiness is"))
        XCTAssertTrue(hardwareValidation.contains("with at most one cooldown retry when the daemon tells"))
        XCTAssertTrue(hardwareValidation.contains("records retry metadata in `rateLimitRetry`"))
        XCTAssertTrue(hardwareValidation.contains("stores the final proof in `viftyctl-run-retry.json`"))
        XCTAssertTrue(hardwareValidation.contains("When `rateLimitRetry.attempted=true`"))
        XCTAssertTrue(hardwareValidation.contains("the reviewer also requires the initial `viftyctl-run` JSON to be structured `PREPARE_RATE_LIMITED` cooldown evidence"))
        XCTAssertTrue(hardwareValidation.contains("the final `run` proof must reference the `viftyctl-run-retry` stdout/stderr/status files"))
        XCTAssertTrue(hardwareValidation.contains("does not advertise"))
        XCTAssertTrue(hardwareValidation.contains("`policyStatusAvailable: true`"))
        XCTAssertTrue(hardwareValidation.contains("`run`"))
        XCTAssertTrue(hardwareValidation.contains("command, `test` workload, and safe `runLifecycle` contract"))
        XCTAssertTrue(hardwareValidation.contains("or when readiness is"))
        XCTAssertTrue(hardwareValidation.contains("blocked"))
        XCTAssertTrue(hardwareValidation.contains("viftyctl run \\"))
        XCTAssertTrue(hardwareValidation.contains("-- /bin/sleep 5"))
        XCTAssertTrue(hardwareValidation.contains("wait for the advertised prepare cooldown"))
        XCTAssertTrue(hardwareValidation.contains("policy.prepareCooldownSeconds"))
        XCTAssertTrue(hardwareValidation.contains("If the first run attempt returns `PREPARE_RATE_LIMITED`"))
        XCTAssertTrue(hardwareValidation.contains("wait for `retryAfterSeconds`, and retry once"))
        XCTAssertTrue(hardwareValidation.contains("/Applications/Vifty.app/Contents/MacOS/viftyctl capabilities --json"))
        XCTAssertTrue(hardwareValidation.contains("follow-up capabilities/status/audit/diagnose output"))
        XCTAssertTrue(hardwareValidation.contains("safe `runLifecycle` contract, `policyStatusAvailable: true`, and policy/metadata limits"))
        XCTAssertTrue(hardwareValidation.contains("It records the run proof fields"))
        XCTAssertTrue(hardwareValidation.contains("`coolingLeasePrepared`, `autoRestoreAttempted`, `autoRestoreSucceeded`, and"))
        XCTAssertTrue(hardwareValidation.contains("validates the child command before cooling"))
        XCTAssertTrue(hardwareValidation.contains("validated-hardware-evidence"))
        XCTAssertTrue(hardwareValidation.contains("review-summary.json"))
        XCTAssertTrue(hardwareValidation.contains("capabilities-contract.tsv"))
        XCTAssertTrue(hardwareValidationTemplate.contains("make validation-evidence"))
        XCTAssertTrue(hardwareValidationTemplate.contains("VALIDATION_EVIDENCE_INSTALL_SOURCE=source-build-tag"))
        XCTAssertTrue(hardwareValidationTemplate.contains("VALIDATION_EVIDENCE_SOURCE_REF=v1.1.1"))
        XCTAssertTrue(hardwareValidationTemplate.contains("VALIDATION_EVIDENCE_SOURCE_SHA=a82f2237ff39c24a6b366dca8f95a17ee54fd972"))
        XCTAssertTrue(hardwareValidationTemplate.contains("VALIDATION_EVIDENCE_SOURCE_ARTIFACT=./Vifty-v1.1.1-unsigned-dev.zip"))
        XCTAssertTrue(hardwareValidationTemplate.contains("VALIDATION_EVIDENCE_INSTALL_SOURCE=local-ad-hoc-build"))
        XCTAssertTrue(hardwareValidationTemplate.contains("privacy-review.tsv"))
        XCTAssertTrue(hardwareValidationTemplate.contains("Supervised viftyctl run smoke test"))
        XCTAssertTrue(hardwareValidationTemplate.contains("make agent-run-smoke-evidence VIFTYCTL=/Applications/Vifty.app/Contents/MacOS/viftyctl"))
        XCTAssertTrue(hardwareValidationTemplate.contains("/Applications/Vifty.app/Contents/Resources/collect-agent-run-smoke-evidence.sh --viftyctl /Applications/Vifty.app/Contents/MacOS/viftyctl"))
        XCTAssertTrue(hardwareValidationTemplate.contains("scripts/collect-agent-run-smoke-evidence.sh"))
        XCTAssertTrue(hardwareValidationTemplate.contains("agent-run-smoke-evidence-summary.json"))
        XCTAssertTrue(hardwareValidationTemplate.contains("viftyctl run --json -- /bin/sleep 5"))
        XCTAssertTrue(hardwareValidationTemplate.contains("wait for `policy.prepareCooldownSeconds` after any manual smoke test"))
        XCTAssertTrue(hardwareValidationTemplate.contains("`PREPARE_RATE_LIMITED` / `retryAfterSeconds` JSON"))
        XCTAssertTrue(hardwareValidationTemplate.contains("cooldown wait: waited policy.prepareCooldownSeconds=30 after manual smoke"))
        XCTAssertTrue(hardwareValidationTemplate.contains("capabilities --json: ..."))
        XCTAssertTrue(hardwareValidationTemplate.contains("follow-up `capabilities --json`, `status --json`, `audit --limit 20 --json`, and `diagnose --json` output"))
        XCTAssertTrue(hardwareValidationTemplate.contains("capabilities-contract.tsv"))
        XCTAssertTrue(hardwareValidationTemplate.contains("The privacy-review row should be 0 before public sharing"))
        XCTAssertTrue(hardwareValidationTemplate.contains("direct prepare/restore lifecycle"))
        XCTAssertTrue(hardwareValidationTemplate.contains("supervised force-retry support"))
        XCTAssertTrue(hardwareValidationTemplate.contains("Review captured files for likely hostnames, /Users/... paths, serial-number labels, or hardware UUID labels before public sharing."))
    }

    func testAgentIntegrationDocsPreferGuardedRunAndForbidRawWrites() throws {
        let guide = try read("docs/safe-agent-cooling.md")
        let agentWorkflows = try read("docs/agent-workflows.md")
        let integrations = try read("docs/agent-integrations.md")

        XCTAssertTrue(guide.contains("read-only readiness first, one bounded workload lease, validated child command, then Auto restore"))
        XCTAssertTrue(guide.contains("call `sudo`, `ViftyHelper setFixed`, `ViftyHelper auto`, raw SMC tools, or arbitrary fan RPM writes"))
        XCTAssertTrue(guide.contains("request cooling when `diagnose --json` reports `state: \"blocked\"`"))
        XCTAssertTrue(guide.contains("prepare cooling before the child command has been resolved and validated"))
        XCTAssertTrue(guide.contains("rejects malformed wrapper arguments before contacting Vifty"))
        XCTAssertTrue(guide.contains("advertised `run` command support"))
        XCTAssertTrue(guide.contains("requested workload support"))
        XCTAssertTrue(guide.contains("advertised unavailable exit code"))
        XCTAssertTrue(guide.contains("`policyStatusAvailable: true`"))
        XCTAssertTrue(guide.contains("`CHILD_COMMAND_FAILED`"))
        XCTAssertTrue(guide.contains("`PREPARE_RATE_LIMITED`"))
        XCTAssertTrue(guide.contains("recommendedAgentAction"))
        XCTAssertTrue(guide.contains("recommendedRecoveryAction"))
        XCTAssertTrue(guide.contains("safeToRequestCooling"))
        XCTAssertTrue(guide.contains("daemonControlPathReady"))
        XCTAssertTrue(guide.contains("VIFTY_GUARDED_RUN_FORCE_RETRY=1"))
        XCTAssertTrue(guide.contains("VIFTY_GUARDED_RUN_ALLOW_UNCOOLED=1"))
        XCTAssertTrue(guide.contains("the wrapper treats those as mutually exclusive operator choices"))
        XCTAssertTrue(guide.contains("only then execs the child directly"))
        XCTAssertTrue(guide.contains("refuses uncooled execution when Vifty recommends"))
        XCTAssertTrue(guide.contains("`repairHelper`,"))
        XCTAssertTrue(guide.contains("`daemonControlPathReady` is false"))
        XCTAssertTrue(guide.contains("The uncooled fallback is mutually exclusive"))
        XCTAssertTrue(guide.contains("viftyctl audit --limit 20 --json"))
        XCTAssertTrue(guide.contains("scripts/collect-agent-cooling-evidence.sh"))
        XCTAssertTrue(guide.contains("## Supervised Run Smoke Evidence"))
        XCTAssertTrue(guide.contains("make agent-run-smoke-evidence \\"))
        XCTAssertTrue(guide.contains("one bounded `viftyctl run --json` lease for `/bin/sleep 5`"))
        XCTAssertTrue(guide.contains("not as the first response to helper-unreachable"))
        XCTAssertTrue(guide.contains("blocked readiness states"))
        XCTAssertTrue(guide.contains("launchd/helper install evidence"))
        XCTAssertTrue(guide.contains("diagnoseDecision"))
        XCTAssertTrue(guide.contains("capabilitiesDecision"))
        XCTAssertTrue(guide.contains("appInfo"))
        XCTAssertTrue(guide.contains("acceptedCommandErrors"))
        XCTAssertTrue(agentWorkflows.contains("- `policyStatusAvailable`"))
        XCTAssertTrue(agentWorkflows.contains("If `policyStatusAvailable` is absent or false"))
        XCTAssertTrue(guide.contains("structured `HELPER_UNREACHABLE`"))
        XCTAssertTrue(guide.contains("known v1.1.0 helper-unreachable issue"))
        XCTAssertTrue(guide.contains("v1.1.1 source-first hotfix"))
        XCTAssertTrue(guide.contains("missing or"))
        XCTAssertTrue(guide.contains("force-retry"))
        XCTAssertTrue(guide.contains("requesting cooling"))
        XCTAssertTrue(guide.contains("privacy-review.tsv"))
        XCTAssertTrue(guide.contains("before posting the bundle publicly"))
        XCTAssertTrue(guide.contains("The app's menu and main window also show the current fan-control owner."))
        XCTAssertTrue(guide.contains("examples/viftyctl/xcode-build.sh"))
        XCTAssertTrue(guide.contains("examples/viftyctl/make-test.sh"))
        XCTAssertTrue(guide.contains("examples/viftyctl/make-verify.sh"))
        XCTAssertTrue(guide.contains("examples/viftyctl/npm-build.sh"))
        XCTAssertTrue(guide.contains("examples/viftyctl/cargo-build.sh"))
        XCTAssertTrue(agentWorkflows.contains("[safe-agent-cooling.md](safe-agent-cooling.md)"))
        XCTAssertTrue(agentWorkflows.contains("[agent-integrations.md](agent-integrations.md)"))
        XCTAssertTrue(agentWorkflows.contains("[examples/viftyctl](../examples/viftyctl/README.md)"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/swift-test.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/swift-release-build.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/xcode-build.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/xcode-test.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/make-test.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/make-verify.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/npm-build.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/npm-test.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/cargo-build.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/cargo-test.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/pytest.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/local-model.sh"))
        XCTAssertTrue(agentWorkflows.contains("examples/viftyctl/custom-workload.sh"))
        XCTAssertTrue(agentWorkflows.contains("VIFTY_GUARDED_RUN_FORCE_RETRY=1"))
        XCTAssertTrue(agentWorkflows.contains("VIFTY_GUARDED_RUN_ALLOW_UNCOOLED=1"))
        XCTAssertTrue(agentWorkflows.contains("the wrapper refuses that ambiguous mix"))
        XCTAssertTrue(agentWorkflows.contains("The wrapper also does not silently rerun workloads without cooling"))
        XCTAssertTrue(agentWorkflows.contains("missing option values"))
        XCTAssertTrue(agentWorkflows.contains("missing-value wrapper options"))
        XCTAssertTrue(integrations.contains("[safe-agent-cooling.md](safe-agent-cooling.md)"))
        XCTAssertTrue(integrations.contains("Codex"))
        XCTAssertTrue(integrations.contains("Claude Code"))
        XCTAssertTrue(integrations.contains("Cursor"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/guarded-run.sh"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/swift-test.sh"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/xcode-build.sh"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/make-verify.sh"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/npm-build.sh"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/cargo-build.sh"))
        XCTAssertTrue(integrations.contains("examples/viftyctl/cargo-test.sh"))
        XCTAssertTrue(integrations.contains("safeToRequestCooling"))
        XCTAssertTrue(integrations.contains("daemonControlPathReady"))
        XCTAssertTrue(integrations.contains("recommendedRecoveryAction"))
        XCTAssertTrue(integrations.contains("restoreAutoBeforeRequestingCooling"))
        XCTAssertTrue(integrations.contains("Never call raw SMC commands"))
        XCTAssertTrue(integrations.contains("Do not give agents permission to call `ViftyHelper setFixed`"))
        XCTAssertTrue(integrations.contains("the CLI no longer advertises `run`"))
        XCTAssertTrue(integrations.contains("the requested workload is not advertised"))
        XCTAssertTrue(integrations.contains("anything other than the advertised unavailable exit code"))
        XCTAssertTrue(integrations.contains("rejects malformed duration/RPM/reason arguments before contacting Vifty"))
        XCTAssertTrue(integrations.contains("advertised policy duration/RPM limits"))
        XCTAssertTrue(integrations.contains("`metadataLimits` are missing"))
        XCTAssertTrue(integrations.contains("requested duration/RPM/reason exceeds those advertised limits"))
        XCTAssertTrue(integrations.contains("VIFTY_GUARDED_RUN_FORCE_RETRY"))
        XCTAssertTrue(integrations.contains("VIFTY_GUARDED_RUN_ALLOW_UNCOOLED"))
        XCTAssertTrue(integrations.contains("refuses to combine force retry with `VIFTY_GUARDED_RUN_ALLOW_UNCOOLED`"))
        XCTAssertTrue(integrations.contains("avoid the uncooled fallback when Vifty recommends helper repair, backing off, restoring Auto first, or when the daemon control path is unavailable"))
        XCTAssertTrue(integrations.contains("the wrapper still refuses helper-repair, restore-first, backoff, daemon-control-unavailable states, and force-retry combinations"))
        XCTAssertTrue(integrations.contains("keep Vifty optional without masking Vifty failures"))
        XCTAssertTrue(integrations.contains("Do not add a fallback after `guarded-run.sh` that catches its nonzero exit and reruns the same child command"))
        XCTAssertTrue(integrations.contains("use `VIFTY_GUARDED_RUN_ALLOW_UNCOOLED=1` only when the user explicitly asked"))

        let exampleReadme = try read("examples/viftyctl/README.md")
        XCTAssertTrue(exampleReadme.contains("preflight that the child command is a regular executable path or resolves to one on `PATH`"))
        XCTAssertTrue(exampleReadme.contains("reject malformed wrapper arguments before contacting Vifty"))
        XCTAssertTrue(exampleReadme.contains("read-only `viftyctl capabilities --json`"))
        XCTAssertTrue(exampleReadme.contains("require advertised `run` command support"))
        XCTAssertTrue(exampleReadme.contains("require the requested workload name"))
        XCTAssertTrue(exampleReadme.contains("nonzero exit to match the advertised unavailable exit code"))
        XCTAssertTrue(exampleReadme.contains("safe `runLifecycle` contract"))
        XCTAssertTrue(exampleReadme.contains("require `policyStatusAvailable: true` before trusting policy duration/RPM limits"))
        XCTAssertTrue(exampleReadme.contains("If a capabilities payload does not advertise `runLifecycle`"))
        XCTAssertTrue(exampleReadme.contains("directControlLifecycle"))
        XCTAssertTrue(exampleReadme.contains("`restore-auto` rejects"))
        XCTAssertTrue(exampleReadme.contains("restore is not key-scoped"))
        XCTAssertTrue(exampleReadme.contains("checks `supportsForceRetry` before passing `--force`"))
        XCTAssertTrue(exampleReadme.contains("read-only `viftyctl diagnose --json`"))
        XCTAssertTrue(exampleReadme.contains("require `recommendedAgentAction`, `recommendedRecoveryAction`, `safeToRequestCooling`, and `daemonControlPathReady`"))
        XCTAssertTrue(exampleReadme.contains("print recovery guidance for helper repair, Auto restore, workload backoff, policy inspection, or hardware-evidence follow-up"))
        XCTAssertTrue(exampleReadme.contains("delegate to `viftyctl run --json`"))
        XCTAssertTrue(exampleReadme.contains("VIFTY_GUARDED_RUN_FORCE_RETRY=1"))
        XCTAssertTrue(exampleReadme.contains("VIFTY_GUARDED_RUN_ALLOW_UNCOOLED=1"))
        XCTAssertTrue(exampleReadme.contains("the wrapper refuses\nthat ambiguous mix"))
        XCTAssertTrue(exampleReadme.contains("then execs the child directly"))
        XCTAssertTrue(exampleReadme.contains("will not use this fallback"))
        XCTAssertTrue(exampleReadme.contains("`repairHelper`, `backOffWorkload`, or"))
        XCTAssertTrue(exampleReadme.contains("`restoreAutoBeforeRetry`, when `daemonControlPathReady` is false, or when"))
        XCTAssertTrue(exampleReadme.contains("swift-test.sh"))
        XCTAssertTrue(exampleReadme.contains("xcode-build.sh"))
        XCTAssertTrue(exampleReadme.contains("make-test.sh"))
        XCTAssertTrue(exampleReadme.contains("make-verify.sh"))
        XCTAssertTrue(exampleReadme.contains("npm-build.sh"))
        XCTAssertTrue(exampleReadme.contains("cargo-build.sh"))
        XCTAssertTrue(exampleReadme.contains("custom-workload.sh"))
        XCTAssertTrue(exampleReadme.contains("Do not edit these wrappers to call `sudo`, `ViftyHelper`, raw SMC tools"))
    }

    func testStrategyWorkplanReflectsCurrentSourceFirstState() throws {
        let workplan = try read("docs/plans/2026-06-11-vifty-strategy-workplan.md")

        XCTAssertTrue(workplan.contains("Post-release local hardening is on `main` after the published `v1.1.1` source-first hotfix tag"))
        XCTAssertTrue(workplan.contains("`a82f2237ff39c24a6b366dca8f95a17ee54fd972`"))
        XCTAssertTrue(workplan.contains("current local trust gate verifies the full XCTest suite"))
        XCTAssertTrue(workplan.contains("command-error recovery-action metadata"))
        XCTAssertTrue(workplan.contains("readiness recovery-action metadata"))
        XCTAssertTrue(workplan.contains("daemon control-path readiness evidence"))
        XCTAssertTrue(workplan.contains("guarded-run readiness recovery-action checks"))
        XCTAssertTrue(workplan.contains("VIFTY_GUARDED_RUN_ALLOW_UNCOOLED=1"))
        XCTAssertTrue(workplan.contains("refusal to combine force retry with uncooled fallback"))
        XCTAssertTrue(workplan.contains("refuses uncooled execution for `repairHelper`, `backOffWorkload`, `restoreAutoBeforeRetry`, and `daemonControlPathReady=false`"))
        XCTAssertTrue(workplan.contains("community/support surface checks"))
        XCTAssertTrue(workplan.contains("validation report index schema"))
        XCTAssertTrue(workplan.contains("validation review-result schema"))
        XCTAssertTrue(workplan.contains("optional conservative `compatibility-matrix.md` draft"))
        XCTAssertTrue(workplan.contains("preserves install provenance, source checksums, `modelFamily`, agent decisions, recovery guidance, agent-run smoke evidence, and daemon control-path readiness in compatibility indexes"))
        XCTAssertTrue(workplan.contains("make agent-run-smoke-evidence VIFTYCTL=/Applications/Vifty.app/Contents/MacOS/viftyctl"))
        XCTAssertTrue(workplan.contains("/Applications/Vifty.app/Contents/Resources/collect-agent-run-smoke-evidence.sh"))
        XCTAssertTrue(workplan.contains("scripts/collect-agent-run-smoke-evidence.sh"))
        XCTAssertTrue(workplan.contains("agent-run-smoke-evidence-summary.json"))
        XCTAssertTrue(workplan.contains("https://vifty.local/schemas/agent-run-smoke-evidence-summary.schema.json"))
        XCTAssertTrue(workplan.contains("--agent-run-smoke-summary <path>"))
        XCTAssertTrue(workplan.contains("run proof fields for `coolingLeasePrepared`, `autoRestoreAttempted`, `autoRestoreSucceeded`, and `childExitCode`"))
        XCTAssertTrue(workplan.contains("verifies the adjacent smoke bundle manifest rows, per-command status/stdout/stderr files, and checksum coverage/recomputed digests"))
        XCTAssertTrue(workplan.contains("requires passed captured summaries to report a prepared lease, attempted Auto restore, successful Auto restore, and child exit `0`"))
        XCTAssertTrue(workplan.contains("it stops before `viftyctl run` when capabilities are unsafe or readiness is blocked"))
        XCTAssertTrue(workplan.contains("validated hardware reports by model family"))
        XCTAssertTrue(workplan.contains("the Markdown draft ignores release-trust rows for hardware status"))
        XCTAssertTrue(workplan.contains("source-first Source Provenance enforcement"))
        XCTAssertTrue(workplan.contains("Source-first release operations now have Makefile targets"))
        XCTAssertTrue(workplan.contains("source-provenance section"))
        XCTAssertTrue(workplan.contains("immutable tag commit"))
        XCTAssertTrue(workplan.contains("Vifty-v1.1.1-unsigned-dev.zip"))
        XCTAssertTrue(workplan.contains("Vifty-v1.1.1-unsigned-dev.zip.sha256"))
        XCTAssertTrue(workplan.contains("capabilities run-lifecycle/direct-control coverage"))
        XCTAssertTrue(workplan.contains("guarded-run advertised run-command/workload support checks"))
        XCTAssertTrue(workplan.contains("guarded-run wrapper-argument preflight checks"))
        XCTAssertTrue(workplan.contains("guarded-run advertised unavailable-exit checks"))
        XCTAssertTrue(workplan.contains("missing option-value parse failures"))
        XCTAssertTrue(workplan.contains("directControlLifecycle"))
        XCTAssertTrue(workplan.contains("restore-auto scoped-option rejection"))
        XCTAssertTrue(workplan.contains("blocked readiness is explicitly evidence-only"))
        XCTAssertTrue(workplan.contains("`recommendedAgentAction`, `recommendedRecoveryAction`, `safeToRequestCooling`, and `daemonControlPathReady`"))
        XCTAssertTrue(workplan.contains("do not retry `viftyctl prepare` or `viftyctl run`"))
        XCTAssertTrue(workplan.contains("scripts/collect-agent-cooling-evidence.sh"))
        XCTAssertTrue(workplan.contains("launchd/helper install evidence"))
        XCTAssertTrue(workplan.contains("agent-cooling-evidence-summary.json"))
        XCTAssertTrue(workplan.contains("https://vifty.local/schemas/agent-cooling-evidence-summary.schema.json"))
        XCTAssertTrue(workplan.contains("agent-cooling-evidence-review.json"))
        XCTAssertTrue(workplan.contains("https://vifty.local/schemas/agent-cooling-evidence-review.schema.json"))
        XCTAssertTrue(workplan.contains("`diagnoseDecision` summary"))
        XCTAssertTrue(workplan.contains("`capabilitiesDecision` summary"))
        XCTAssertTrue(workplan.contains("`appInfo` summary"))
        XCTAssertTrue(workplan.contains("`acceptedCommandErrors`"))
        XCTAssertTrue(workplan.contains("infers missing legacy `daemonControlPathReady`"))
        XCTAssertTrue(workplan.contains("absent legacy `metadataLimits` as a warning"))
        XCTAssertTrue(workplan.contains("missing or contradictory diagnose decision fields"))
        XCTAssertTrue(workplan.contains("unsafe capabilities contract fields"))
        XCTAssertTrue(workplan.contains("unsafe command errors"))
        XCTAssertTrue(workplan.contains("without requesting cooling, restoring Auto, calling `ViftyHelper`, using `sudo`, or writing SMC keys"))
        XCTAssertTrue(workplan.contains("Its privacy review flags likely hostnames"))
        XCTAssertTrue(workplan.contains("duplicate wrapper options"))
        XCTAssertTrue(workplan.contains("do not retag `v1.1.0` or `v1.1.1`"))
        XCTAssertTrue(workplan.contains("not a silent retag"))
        XCTAssertTrue(workplan.contains("do not promote Homebrew until the future Developer ID lane passes"))
        XCTAssertFalse(workplan.contains("435 XCTest cases"))
        XCTAssertFalse(workplan.contains("469 XCTest cases"))
        XCTAssertFalse(workplan.contains("current local trust gate verifies 463 XCTest cases"))
        XCTAssertFalse(workplan.contains("446 XCTest cases"))
        XCTAssertFalse(workplan.contains("445 XCTest cases"))
        XCTAssertFalse(workplan.contains("442 XCTest cases"))
        XCTAssertFalse(workplan.contains("441 XCTest cases"))
        XCTAssertFalse(workplan.contains("439 XCTest cases"))
        XCTAssertFalse(workplan.contains("401 XCTest cases"))
        XCTAssertFalse(workplan.contains("Review the full dirty tree"))
    }

    private func read(_ relativePath: String) throws -> String {
        let url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent(relativePath)
        return try String(contentsOf: url, encoding: .utf8)
    }

    private func XCTAssertOrder(
        in text: String,
        after anchor: String,
        _ first: String,
        before second: String,
        message: String,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        guard let anchorRange = text.range(of: anchor) else {
            XCTFail("Missing anchor marker: \(anchor). \(message)", file: file, line: line)
            return
        }
        let scopedText = String(text[anchorRange.lowerBound...])
        guard let firstRange = scopedText.range(of: first) else {
            XCTFail("Missing first marker: \(first). \(message)", file: file, line: line)
            return
        }
        guard let secondRange = scopedText.range(of: second) else {
            XCTFail("Missing second marker: \(second). \(message)", file: file, line: line)
            return
        }
        XCTAssertLessThan(firstRange.lowerBound, secondRange.lowerBound, message, file: file, line: line)
    }
}
