import Foundation
import XCTest

final class MakefileTrustGateTests: XCTestCase {
    func testVerifyTargetRunsLocalTrustGates() throws {
        let makefile = try read("Makefile")

        XCTAssertTrue(makefile.contains("verify: ## Run local trust gates without installing"))
        XCTAssertTrue(makefile.contains("validation-evidence: ## Collect read-only release/hardware validation evidence"))
        XCTAssertTrue(makefile.contains("validation-evidence-current-build: ## Build current app and collect read-only local-ad-hoc validation evidence"))
        XCTAssertTrue(makefile.contains("agent-cooling-evidence: ## Collect read-only agent/helper support evidence"))
        XCTAssertTrue(makefile.contains("agent-cooling-evidence-review: ## Review a read-only agent/helper support evidence bundle"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-evidence: ## Collect supervised supported-hardware viftyctl run smoke evidence"))
        XCTAssertTrue(makefile.contains("source-first-release-notes: ## Write source-first release notes for the current version"))
        XCTAssertTrue(makefile.contains("unsigned-dev-artifact: ## Build source-first unsigned tester zip and checksum"))
        XCTAssertTrue(makefile.contains("source-first-readiness: ## Check published source-first release readiness"))
        XCTAssertTrue(makefile.contains("RELEASE_VERSION ?= $(shell /usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' Resources/Info.plist)"))
        XCTAssertTrue(makefile.contains("RELEASE_REPO ?= Reedtrullz/Vifty"))
        XCTAssertTrue(makefile.contains("SOURCE_FIRST_SOURCE_REF ?= v$(RELEASE_VERSION)"))
        XCTAssertTrue(makefile.contains("UNSIGNED_DEV_SOURCE_REF ?= v$(RELEASE_VERSION)"))
        XCTAssertTrue(makefile.contains("RELEASE_METADATA_MODE ?= source-first"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_APP ?= /Applications/Vifty.app"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_OUTPUT ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_INSTALL_SOURCE ?= not-recorded"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_SOURCE_REF ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_SOURCE_SHA ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_SOURCE_ARTIFACT ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_RELEASE_SUMMARY ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_RELEASE_CHECKLIST ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_INCLUDE_PROBE_LOCAL ?= 0"))
        XCTAssertTrue(makefile.contains("CURRENT_BUILD_SOURCE_REF ?= $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null)"))
        XCTAssertTrue(makefile.contains("CURRENT_BUILD_SOURCE_SHA ?= $(shell git rev-parse HEAD 2>/dev/null)"))
        XCTAssertTrue(makefile.contains("AGENT_EVIDENCE_BUNDLE ?="))
        XCTAssertTrue(makefile.contains("AGENT_EVIDENCE_REVIEW_SUMMARY ?="))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_OUTPUT ?="))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_DURATION ?= 2m"))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_MAX_RPM_PERCENT ?= 55"))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_REASON ?= agent run smoke test"))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_AUDIT_LIMIT ?= 20"))
        XCTAssertTrue(makefile.contains("/bin/bash -n scripts/*.sh examples/viftyctl/*.sh"))
        XCTAssertTrue(makefile.contains("scripts/check-community-standards.sh"))
        XCTAssertTrue(makefile.contains("scripts/validate-release-metadata.sh --mode \"$(RELEASE_METADATA_MODE)\""))
        XCTAssertTrue(makefile.contains("swift test"))
        XCTAssertTrue(makefile.contains("swift build -Xswiftc -warnings-as-errors"))
        XCTAssertTrue(makefile.contains("$(MAKE) app CONFIGURATION=release"))
        XCTAssertTrue(makefile.contains("SCHEMAS := $(CONTENTS)/Resources/schemas"))
        XCTAssertTrue(makefile.contains("cp docs/schemas/*.schema.json \"$(SCHEMAS)/\""))
        XCTAssertTrue(makefile.contains("install -m 755 scripts/collect-agent-cooling-evidence.sh \"$(CONTENTS)/Resources/collect-agent-cooling-evidence.sh\""))
        XCTAssertTrue(makefile.contains("install -m 755 scripts/collect-agent-run-smoke-evidence.sh \"$(CONTENTS)/Resources/collect-agent-run-smoke-evidence.sh\""))
        XCTAssertTrue(makefile.contains("plutil -lint \"$(CONTENTS)/Info.plist\""))
        XCTAssertTrue(makefile.contains("plutil -lint \"$(DAEMON_PLIST)\""))
        XCTAssertTrue(makefile.contains("test -x \"$(CONTENTS)/Resources/collect-agent-cooling-evidence.sh\""))
        XCTAssertTrue(makefile.contains("test -x \"$(CONTENTS)/Resources/collect-agent-run-smoke-evidence.sh\""))
        XCTAssertTrue(makefile.contains("codesign --verify --deep --strict \"$(APP_DIR)\""))
        XCTAssertTrue(makefile.contains("--identifier tech.reidar.vifty.helper \"$(MACOS)/ViftyHelper\""))
        XCTAssertTrue(makefile.contains("--identifier tech.reidar.vifty.daemon \"$(MACOS)/ViftyDaemon\""))
        XCTAssertTrue(makefile.contains("Identifier=tech.reidar.vifty.helper"))
        XCTAssertTrue(makefile.contains("Identifier=tech.reidar.vifty.daemon"))
        XCTAssertTrue(makefile.contains("Identifier=tech.reidar.vifty.ctl"))
    }

    func testVerifyTargetIsListedAsPhonyAndHelpVisible() throws {
        let makefile = try read("Makefile")

        XCTAssertTrue(makefile.contains(".PHONY: app install pkg validation-evidence validation-evidence-current-build agent-cooling-evidence agent-cooling-evidence-review agent-run-smoke-evidence source-first-release-notes unsigned-dev-artifact source-first-readiness clean-app clean-pkg test verify help clean"))
        XCTAssertTrue(makefile.contains("verify: ## Run local trust gates without installing"))
        XCTAssertTrue(makefile.contains("validation-evidence: ## Collect read-only release/hardware validation evidence"))
        XCTAssertTrue(makefile.contains("validation-evidence-current-build: ## Build current app and collect read-only local-ad-hoc validation evidence"))
        XCTAssertTrue(makefile.contains("scripts/collect-validation-evidence.sh --app \"$(VALIDATION_EVIDENCE_APP)\""))
        XCTAssertTrue(makefile.contains("--install-source \"$(VALIDATION_EVIDENCE_INSTALL_SOURCE)\""))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_SOURCE_REF),--source-ref \"$(VALIDATION_EVIDENCE_SOURCE_REF)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_SOURCE_SHA),--source-sha \"$(VALIDATION_EVIDENCE_SOURCE_SHA)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_SOURCE_ARTIFACT),--source-artifact \"$(VALIDATION_EVIDENCE_SOURCE_ARTIFACT)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_RELEASE_SUMMARY),--release-summary \"$(VALIDATION_EVIDENCE_RELEASE_SUMMARY)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_RELEASE_CHECKLIST),--release-checklist \"$(VALIDATION_EVIDENCE_RELEASE_CHECKLIST)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_OUTPUT),--output \"$(VALIDATION_EVIDENCE_OUTPUT)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(filter 1 true yes,$(VALIDATION_EVIDENCE_INCLUDE_PROBE_LOCAL)),--include-probe-local,)"))
        XCTAssertTrue(makefile.contains("status=\"$$(git status --porcelain --untracked-files=all 2>/dev/null)\""))
        XCTAssertTrue(makefile.contains("validation-evidence-current-build requires a clean git worktree so source ref/SHA match the built app"))
        XCTAssertTrue(makefile.contains("$(MAKE) app CONFIGURATION=release SIGNING_IDENTITY=\"$(SIGNING_IDENTITY)\" VIFTY_XPC_ALLOWED_TEAM_ID=\"$(VIFTY_XPC_ALLOWED_TEAM_ID)\""))
        XCTAssertTrue(makefile.contains("$(MAKE) validation-evidence VALIDATION_EVIDENCE_APP=\"$(APP_DIR)\" VALIDATION_EVIDENCE_INSTALL_SOURCE=local-ad-hoc-build VALIDATION_EVIDENCE_SOURCE_REF=\"$(CURRENT_BUILD_SOURCE_REF)\" VALIDATION_EVIDENCE_SOURCE_SHA=\"$(CURRENT_BUILD_SOURCE_SHA)\""))
        XCTAssertTrue(makefile.contains("agent-cooling-evidence: ## Collect read-only agent/helper support evidence"))
        XCTAssertTrue(makefile.contains("scripts/collect-agent-cooling-evidence.sh --viftyctl \"$(VIFTYCTL)\""))
        XCTAssertTrue(makefile.contains("agent-cooling-evidence-review: ## Review a read-only agent/helper support evidence bundle"))
        XCTAssertTrue(makefile.contains("scripts/review-agent-cooling-evidence.sh --bundle \"$(AGENT_EVIDENCE_BUNDLE)\""))
        XCTAssertTrue(makefile.contains("agent-run-smoke-evidence: ## Collect supervised supported-hardware viftyctl run smoke evidence"))
        XCTAssertTrue(makefile.contains("scripts/collect-agent-run-smoke-evidence.sh --viftyctl \"$(VIFTYCTL)\""))
        XCTAssertTrue(makefile.contains("--duration \"$(AGENT_RUN_SMOKE_DURATION)\""))
        XCTAssertTrue(makefile.contains("--max-rpm-percent \"$(AGENT_RUN_SMOKE_MAX_RPM_PERCENT)\""))
        XCTAssertTrue(makefile.contains("--reason \"$(AGENT_RUN_SMOKE_REASON)\""))
        XCTAssertTrue(makefile.contains("--audit-limit \"$(AGENT_RUN_SMOKE_AUDIT_LIMIT)\""))
        XCTAssertTrue(makefile.contains("$(if $(AGENT_RUN_SMOKE_OUTPUT),--output \"$(AGENT_RUN_SMOKE_OUTPUT)\",)"))
        XCTAssertTrue(makefile.contains("source-first-release-notes: ## Write source-first release notes for the current version"))
        XCTAssertTrue(makefile.contains("unsigned-dev-artifact: ## Build source-first unsigned tester zip and checksum"))
        XCTAssertTrue(makefile.contains("source-first-readiness: ## Check published source-first release readiness"))
        XCTAssertTrue(makefile.contains("scripts/write-release-checklist.sh --mode source-first --version \"$(RELEASE_VERSION)\" $(if $(SOURCE_FIRST_SOURCE_REF),--source-ref \"$(SOURCE_FIRST_SOURCE_REF)\",)"))
        XCTAssertTrue(makefile.contains("scripts/build-unsigned-dev-artifact.sh --version \"$(RELEASE_VERSION)\" $(if $(UNSIGNED_DEV_SOURCE_REF),--require-source-ref \"$(UNSIGNED_DEV_SOURCE_REF)\",)"))
        XCTAssertTrue(makefile.contains("scripts/check-release-readiness.sh --mode source-first --version \"$(RELEASE_VERSION)\" --repo \"$(RELEASE_REPO)\" --json"))
    }

    private func read(_ relativePath: String) throws -> String {
        let url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent(relativePath)
        return try String(contentsOf: url, encoding: .utf8)
    }
}
