import Foundation
import XCTest

final class MakefileTrustGateTests: XCTestCase {
    func testVerifyTargetRunsLocalTrustGates() throws {
        let makefile = try read("Makefile")

        XCTAssertTrue(makefile.contains("verify: ## Run local trust gates without installing"))
        XCTAssertTrue(makefile.contains("repair-helper: ## Explicitly repair the installed privileged helper"))
        XCTAssertTrue(makefile.contains("validation-evidence: ## Collect read-only release/hardware validation evidence"))
        XCTAssertTrue(makefile.contains("validation-evidence-current-build: ## Build current app and collect read-only local-ad-hoc validation evidence"))
        XCTAssertTrue(makefile.contains("validation-evidence-review: ## Review a captured validation evidence bundle"))
        XCTAssertTrue(makefile.contains("manual-smoke-readiness: ## Read-only preflight before human Fixed/Curve smoke"))
        XCTAssertTrue(makefile.contains("manual-smoke-readiness-current-build: ## Build current app and run read-only manual smoke preflight"))
        XCTAssertTrue(makefile.contains("agent-cooling-evidence: ## Collect read-only agent/helper support evidence"))
        XCTAssertTrue(makefile.contains("agent-cooling-evidence-review: ## Review a read-only agent/helper support evidence bundle"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-readiness: ## Read-only preflight before supervised viftyctl run smoke"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-readiness-current-build: ## Build current app and run read-only agent smoke preflight"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-evidence: ## Collect supervised supported-hardware viftyctl run smoke evidence"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-evidence-current-build: ## Build current app and collect supervised local viftyctl run smoke evidence"))
        XCTAssertTrue(makefile.contains("source-first-release-notes: ## Write source-first release notes for the current version"))
        XCTAssertTrue(makefile.contains("unsigned-dev-artifact: ## Build source-first unsigned tester zip and checksum"))
        XCTAssertTrue(makefile.contains("source-first-readiness: ## Check published source-first release readiness"))
        XCTAssertTrue(makefile.contains("RELEASE_VERSION ?= $(shell /usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' Resources/Info.plist)"))
        XCTAssertTrue(makefile.contains("RELEASE_REPO ?= Reedtrullz/Vifty"))
        XCTAssertTrue(makefile.contains("SOURCE_FIRST_SOURCE_REF ?= v$(RELEASE_VERSION)"))
        XCTAssertTrue(makefile.contains("UNSIGNED_DEV_SOURCE_REF ?= v$(RELEASE_VERSION)"))
        XCTAssertTrue(makefile.contains("RELEASE_METADATA_MODE ?= source-first"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_APP ?= /Applications/Vifty.app"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_OUTPUT ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_INSTALL_SOURCE ?= not-recorded"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_SOURCE_REF ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_SOURCE_SHA ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_SOURCE_ARTIFACT ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_RELEASE_SUMMARY ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_RELEASE_CHECKLIST ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_INCLUDE_PROBE_LOCAL ?= 0"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_CURRENT_BUILD_INCLUDE_PROBE_LOCAL ?= 1"))
        XCTAssertTrue(makefile.contains("REPAIR_HELPER_APP ?= /Applications/Vifty.app"))
        XCTAssertTrue(makefile.contains("CURRENT_BUILD_SOURCE_REF ?= $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null)"))
        XCTAssertTrue(makefile.contains("CURRENT_BUILD_SOURCE_SHA ?= $(shell git rev-parse HEAD 2>/dev/null)"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_BUNDLE ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_REVIEW_MODE ?= supported-hardware"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_REVIEW_SUMMARY ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_MANUAL_SMOKE_RESULT ?= not-recorded"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_MANUAL_SMOKE_SOURCE ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_MANUAL_SMOKE_READINESS_SUMMARY ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_AGENT_RUN_SMOKE_RESULT ?= not-recorded"))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_AGENT_RUN_SMOKE_SOURCE ?="))
        XCTAssertTrue(makefile.contains("VALIDATION_EVIDENCE_AGENT_RUN_SMOKE_SUMMARY ?="))
        XCTAssertTrue(makefile.contains("MANUAL_SMOKE_READINESS_JSON ?= 0"))
        XCTAssertTrue(makefile.contains("MANUAL_SMOKE_READINESS_SUMMARY ?="))
        XCTAssertTrue(makefile.contains("MANUAL_SMOKE_EXPECTED_DAEMON ?="))
        XCTAssertTrue(makefile.contains("MANUAL_SMOKE_REQUIRE_DAEMON_MATCH ?= 0"))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_READINESS_JSON ?= 0"))
        XCTAssertTrue(makefile.contains("AGENT_EVIDENCE_OUTPUT ?="))
        XCTAssertTrue(makefile.contains("AGENT_EVIDENCE_GUARDED_RUN_STDERR ?="))
        XCTAssertTrue(makefile.contains("AGENT_EVIDENCE_BUNDLE ?="))
        XCTAssertTrue(makefile.contains("AGENT_EVIDENCE_REVIEW_SUMMARY ?="))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_OUTPUT ?="))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_DURATION ?= 2m"))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_MAX_RPM_PERCENT ?= 55"))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_REASON ?= agent run smoke test"))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_AUDIT_LIMIT ?= 20"))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_INSTALL_SOURCE ?= not-recorded"))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_SOURCE_REF ?="))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_SOURCE_SHA ?="))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_SOURCE_ARTIFACT ?="))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_EXPECTED_DAEMON ?="))
        XCTAssertTrue(makefile.contains("AGENT_RUN_SMOKE_REQUIRE_DAEMON_MATCH ?= 0"))
        XCTAssertTrue(makefile.contains("SWIFT_BUILD_PATH ?="))
        XCTAssertTrue(makefile.contains("SWIFT_BUILD_ARGS = $(if $(SWIFT_BUILD_PATH),--build-path \"$(SWIFT_BUILD_PATH)\",)"))
        XCTAssertTrue(makefile.contains("SWIFT_PRODUCTS_DIR = $(if $(SWIFT_BUILD_PATH),$(SWIFT_BUILD_PATH)/$(CONFIGURATION),.build/$(CONFIGURATION))"))
        XCTAssertTrue(makefile.contains("/bin/bash -n scripts/*.sh examples/viftyctl/*.sh"))
        XCTAssertTrue(makefile.contains("scripts/check-community-standards.sh"))
        XCTAssertTrue(makefile.contains("scripts/validate-release-metadata.sh --mode \"$(RELEASE_METADATA_MODE)\""))
        XCTAssertTrue(makefile.contains("swift test $(SWIFT_BUILD_ARGS)"))
        XCTAssertTrue(makefile.contains("swift build $(SWIFT_BUILD_ARGS) -Xswiftc -warnings-as-errors"))
        XCTAssertTrue(makefile.contains("$(MAKE) app CONFIGURATION=release"))
        XCTAssertTrue(makefile.contains("SCHEMAS := $(CONTENTS)/Resources/schemas"))
        XCTAssertTrue(makefile.contains("WRAPPERS := $(CONTENTS)/Resources/viftyctl-wrappers"))
        XCTAssertTrue(makefile.contains("swift build $(SWIFT_BUILD_ARGS) -c $(CONFIGURATION)"))
        XCTAssertTrue(makefile.contains("cp \"$(SWIFT_PRODUCTS_DIR)/Vifty\" \"$(MACOS)/Vifty\""))
        XCTAssertTrue(makefile.contains("cp \"$(SWIFT_PRODUCTS_DIR)/ViftyHelper\" \"$(MACOS)/ViftyHelper\""))
        XCTAssertTrue(makefile.contains("cp \"$(SWIFT_PRODUCTS_DIR)/ViftyCtl\" \"$(MACOS)/viftyctl\""))
        XCTAssertTrue(makefile.contains("cp \"$(SWIFT_PRODUCTS_DIR)/ViftyDaemon\" \"$(MACOS)/ViftyDaemon\""))
        XCTAssertTrue(makefile.contains("cp docs/schemas/*.schema.json \"$(SCHEMAS)/\""))
        XCTAssertTrue(makefile.contains("install -m 755 scripts/collect-agent-cooling-evidence.sh \"$(CONTENTS)/Resources/collect-agent-cooling-evidence.sh\""))
        XCTAssertTrue(makefile.contains("install -m 755 scripts/check-manual-smoke-readiness.sh \"$(CONTENTS)/Resources/check-manual-smoke-readiness.sh\""))
        XCTAssertTrue(makefile.contains("install -m 755 scripts/check-agent-run-smoke-readiness.sh \"$(CONTENTS)/Resources/check-agent-run-smoke-readiness.sh\""))
        XCTAssertTrue(makefile.contains("install -m 755 scripts/collect-agent-run-smoke-evidence.sh \"$(CONTENTS)/Resources/collect-agent-run-smoke-evidence.sh\""))
        XCTAssertTrue(makefile.contains("install -m 755 examples/viftyctl/*.sh \"$(WRAPPERS)/\""))
        XCTAssertTrue(makefile.contains("install -m 644 examples/viftyctl/README.md \"$(WRAPPERS)/README.md\""))
        XCTAssertTrue(makefile.contains("plutil -lint \"$(CONTENTS)/Info.plist\""))
        XCTAssertTrue(makefile.contains("plutil -lint \"$(DAEMON_PLIST)\""))
        XCTAssertTrue(makefile.contains("test -x \"$(CONTENTS)/Resources/collect-agent-cooling-evidence.sh\""))
        XCTAssertTrue(makefile.contains("test -x \"$(CONTENTS)/Resources/check-manual-smoke-readiness.sh\""))
        XCTAssertTrue(makefile.contains("test -x \"$(CONTENTS)/Resources/check-agent-run-smoke-readiness.sh\""))
        XCTAssertTrue(makefile.contains("test -x \"$(CONTENTS)/Resources/collect-agent-run-smoke-evidence.sh\""))
        XCTAssertTrue(makefile.contains("test -x scripts/check-manual-smoke-readiness.sh"))
        XCTAssertTrue(makefile.contains("test -x scripts/check-agent-run-smoke-readiness.sh"))
        XCTAssertTrue(makefile.contains("test -x scripts/repair-vifty-helper.sh"))
        XCTAssertTrue(makefile.contains("source_wrappers=\"$$(find examples/viftyctl -maxdepth 1 -type f -name '*.sh' -exec basename {} \\; | sort)\""))
        XCTAssertTrue(makefile.contains("bundle_wrappers=\"$$(find \"$(WRAPPERS)\" -maxdepth 1 -type f -name '*.sh' -exec basename {} \\; | sort)\""))
        XCTAssertTrue(makefile.contains("Bundled viftyctl wrapper list does not match source examples."))
        XCTAssertTrue(makefile.contains("test -x \"examples/viftyctl/$$wrapper\""))
        XCTAssertTrue(makefile.contains("test -x \"$(WRAPPERS)/$$wrapper\""))
        XCTAssertTrue(makefile.contains("test -f \"$(WRAPPERS)/README.md\""))
        XCTAssertTrue(makefile.contains("codesign --verify --deep --strict \"$(APP_DIR)\""))
        XCTAssertTrue(makefile.contains("--identifier tech.reidar.vifty.helper \"$(MACOS)/ViftyHelper\""))
        XCTAssertTrue(makefile.contains("--identifier tech.reidar.vifty.daemon \"$(MACOS)/ViftyDaemon\""))
        XCTAssertTrue(makefile.contains("Identifier=tech.reidar.vifty.helper"))
        XCTAssertTrue(makefile.contains("Identifier=tech.reidar.vifty.daemon"))
        XCTAssertTrue(makefile.contains("Identifier=tech.reidar.vifty.ctl"))
    }

    func testVerifyTargetIsListedAsPhonyAndHelpVisible() throws {
        let makefile = try read("Makefile")

        XCTAssertTrue(makefile.contains(".PHONY: app install repair-helper pkg validation-evidence validation-evidence-current-build validation-evidence-review manual-smoke-readiness manual-smoke-readiness-current-build agent-cooling-evidence agent-cooling-evidence-review agent-run-smoke-readiness agent-run-smoke-readiness-current-build agent-run-smoke-evidence agent-run-smoke-evidence-current-build source-first-release-notes unsigned-dev-artifact source-first-readiness clean-app clean-pkg test verify help clean"))
        XCTAssertTrue(makefile.contains("verify: ## Run local trust gates without installing"))
        XCTAssertTrue(makefile.contains("repair-helper: ## Explicitly repair the installed privileged helper"))
        XCTAssertTrue(makefile.contains("./scripts/repair-vifty-helper.sh --app \"$(REPAIR_HELPER_APP)\""))
        XCTAssertTrue(makefile.contains("validation-evidence: ## Collect read-only release/hardware validation evidence"))
        XCTAssertTrue(makefile.contains("validation-evidence-current-build: ## Build current app and collect read-only local-ad-hoc validation evidence"))
        XCTAssertTrue(makefile.contains("validation-evidence-review: ## Review a captured validation evidence bundle"))
        XCTAssertTrue(makefile.contains("scripts/collect-validation-evidence.sh --app \"$(VALIDATION_EVIDENCE_APP)\""))
        XCTAssertTrue(makefile.contains("--install-source \"$(VALIDATION_EVIDENCE_INSTALL_SOURCE)\""))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_SOURCE_REF),--source-ref \"$(VALIDATION_EVIDENCE_SOURCE_REF)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_SOURCE_SHA),--source-sha \"$(VALIDATION_EVIDENCE_SOURCE_SHA)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_SOURCE_ARTIFACT),--source-artifact \"$(VALIDATION_EVIDENCE_SOURCE_ARTIFACT)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_RELEASE_SUMMARY),--release-summary \"$(VALIDATION_EVIDENCE_RELEASE_SUMMARY)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_RELEASE_CHECKLIST),--release-checklist \"$(VALIDATION_EVIDENCE_RELEASE_CHECKLIST)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_OUTPUT),--output \"$(VALIDATION_EVIDENCE_OUTPUT)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(filter 1 true yes,$(VALIDATION_EVIDENCE_INCLUDE_PROBE_LOCAL)),--include-probe-local,)"))
        XCTAssertTrue(makefile.contains("status=\"$$(git status --porcelain --untracked-files=all 2>/dev/null)\""))
        XCTAssertTrue(makefile.contains("validation-evidence-current-build requires a clean git worktree so source ref/SHA match the built app"))
        XCTAssertTrue(makefile.contains("$(MAKE) app CONFIGURATION=release SIGNING_IDENTITY=\"$(SIGNING_IDENTITY)\" VIFTY_XPC_ALLOWED_TEAM_ID=\"$(VIFTY_XPC_ALLOWED_TEAM_ID)\""))
        XCTAssertTrue(makefile.contains("$(MAKE) validation-evidence VALIDATION_EVIDENCE_APP=\"$(APP_DIR)\" VALIDATION_EVIDENCE_INSTALL_SOURCE=local-ad-hoc-build VALIDATION_EVIDENCE_SOURCE_REF=\"$(CURRENT_BUILD_SOURCE_REF)\" VALIDATION_EVIDENCE_SOURCE_SHA=\"$(CURRENT_BUILD_SOURCE_SHA)\" VALIDATION_EVIDENCE_INCLUDE_PROBE_LOCAL=\"$(VALIDATION_EVIDENCE_CURRENT_BUILD_INCLUDE_PROBE_LOCAL)\""))
        XCTAssertTrue(makefile.contains("if [ -z \"$(VALIDATION_EVIDENCE_BUNDLE)\" ]; then echo \"VALIDATION_EVIDENCE_BUNDLE is required\""))
        XCTAssertTrue(makefile.contains("scripts/review-validation-evidence.sh --bundle \"$(VALIDATION_EVIDENCE_BUNDLE)\" --mode \"$(VALIDATION_EVIDENCE_REVIEW_MODE)\""))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_REVIEW_SUMMARY),--summary \"$(VALIDATION_EVIDENCE_REVIEW_SUMMARY)\",)"))
        XCTAssertTrue(makefile.contains("--manual-smoke-result \"$(VALIDATION_EVIDENCE_MANUAL_SMOKE_RESULT)\""))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_MANUAL_SMOKE_SOURCE),--manual-smoke-source \"$(VALIDATION_EVIDENCE_MANUAL_SMOKE_SOURCE)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_MANUAL_SMOKE_READINESS_SUMMARY),--manual-smoke-readiness-summary \"$(VALIDATION_EVIDENCE_MANUAL_SMOKE_READINESS_SUMMARY)\",)"))
        XCTAssertTrue(makefile.contains("--agent-run-smoke-result \"$(VALIDATION_EVIDENCE_AGENT_RUN_SMOKE_RESULT)\""))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_AGENT_RUN_SMOKE_SOURCE),--agent-run-smoke-source \"$(VALIDATION_EVIDENCE_AGENT_RUN_SMOKE_SOURCE)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(VALIDATION_EVIDENCE_AGENT_RUN_SMOKE_SUMMARY),--agent-run-smoke-summary \"$(VALIDATION_EVIDENCE_AGENT_RUN_SMOKE_SUMMARY)\",)"))
        XCTAssertTrue(makefile.contains("manual-smoke-readiness: ## Read-only preflight before human Fixed/Curve smoke"))
        XCTAssertTrue(makefile.contains("scripts/check-manual-smoke-readiness.sh --viftyctl \"$(VIFTYCTL)\""))
        XCTAssertTrue(makefile.contains("$(if $(MANUAL_SMOKE_EXPECTED_DAEMON),--expected-daemon \"$(MANUAL_SMOKE_EXPECTED_DAEMON)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(filter 1 true yes,$(MANUAL_SMOKE_REQUIRE_DAEMON_MATCH)),--require-daemon-match,)"))
        XCTAssertTrue(makefile.contains("$(if $(filter 1 true yes,$(MANUAL_SMOKE_READINESS_JSON)),--json,)"))
        XCTAssertTrue(makefile.contains("$(if $(MANUAL_SMOKE_READINESS_SUMMARY),--summary \"$(MANUAL_SMOKE_READINESS_SUMMARY)\",)"))
        XCTAssertTrue(makefile.contains("manual-smoke-readiness-current-build: ## Build current app and run read-only manual smoke preflight"))
        XCTAssertTrue(makefile.contains("manual-smoke-readiness-current-build requires a clean git worktree so the preflight uses the built app from the current source ref"))
        XCTAssertTrue(makefile.contains("$(MAKE) manual-smoke-readiness VIFTYCTL=\"$(MACOS)/viftyctl\" MANUAL_SMOKE_EXPECTED_DAEMON=\"$(MACOS)/ViftyDaemon\" MANUAL_SMOKE_REQUIRE_DAEMON_MATCH=1"))
        XCTAssertTrue(makefile.contains("agent-cooling-evidence: ## Collect read-only agent/helper support evidence"))
        XCTAssertTrue(makefile.contains("scripts/collect-agent-cooling-evidence.sh --viftyctl \"$(VIFTYCTL)\""))
        XCTAssertTrue(makefile.contains("$(if $(AGENT_EVIDENCE_GUARDED_RUN_STDERR),--guarded-run-stderr-file \"$(AGENT_EVIDENCE_GUARDED_RUN_STDERR)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(AGENT_EVIDENCE_GUARDED_RUN_SCRIPT),--guarded-run-script \"$(AGENT_EVIDENCE_GUARDED_RUN_SCRIPT)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(AGENT_EVIDENCE_GUARDED_RUN_PREFLIGHT),--guarded-run-preflight $(AGENT_EVIDENCE_GUARDED_RUN_PREFLIGHT),)"))
        XCTAssertTrue(makefile.contains("agent-cooling-evidence-review: ## Review a read-only agent/helper support evidence bundle"))
        XCTAssertTrue(makefile.contains("scripts/review-agent-cooling-evidence.sh --bundle \"$(AGENT_EVIDENCE_BUNDLE)\""))
        XCTAssertTrue(makefile.contains("agent-run-smoke-readiness: ## Read-only preflight before supervised viftyctl run smoke"))
        XCTAssertTrue(makefile.contains("scripts/check-agent-run-smoke-readiness.sh --viftyctl \"$(VIFTYCTL)\""))
        XCTAssertTrue(makefile.contains("$(if $(filter 1 true yes,$(AGENT_RUN_SMOKE_READINESS_JSON)),--json,)"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-readiness-current-build: ## Build current app and run read-only agent smoke preflight"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-readiness-current-build requires a clean git worktree so the preflight uses the built app from the current source ref"))
        XCTAssertTrue(makefile.contains("$(MAKE) agent-run-smoke-readiness VIFTYCTL=\"$(MACOS)/viftyctl\" AGENT_RUN_SMOKE_EXPECTED_DAEMON=\"$(MACOS)/ViftyDaemon\" AGENT_RUN_SMOKE_REQUIRE_DAEMON_MATCH=1"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-evidence: ## Collect supervised supported-hardware viftyctl run smoke evidence"))
        XCTAssertTrue(makefile.contains("scripts/collect-agent-run-smoke-evidence.sh --viftyctl \"$(VIFTYCTL)\""))
        XCTAssertTrue(makefile.contains("--duration \"$(AGENT_RUN_SMOKE_DURATION)\""))
        XCTAssertTrue(makefile.contains("--max-rpm-percent \"$(AGENT_RUN_SMOKE_MAX_RPM_PERCENT)\""))
        XCTAssertTrue(makefile.contains("--reason \"$(AGENT_RUN_SMOKE_REASON)\""))
        XCTAssertTrue(makefile.contains("--audit-limit \"$(AGENT_RUN_SMOKE_AUDIT_LIMIT)\""))
        XCTAssertTrue(makefile.contains("--install-source \"$(AGENT_RUN_SMOKE_INSTALL_SOURCE)\""))
        XCTAssertTrue(makefile.contains("$(if $(AGENT_RUN_SMOKE_SOURCE_REF),--source-ref \"$(AGENT_RUN_SMOKE_SOURCE_REF)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(AGENT_RUN_SMOKE_SOURCE_SHA),--source-sha \"$(AGENT_RUN_SMOKE_SOURCE_SHA)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(AGENT_RUN_SMOKE_SOURCE_ARTIFACT),--source-artifact \"$(AGENT_RUN_SMOKE_SOURCE_ARTIFACT)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(AGENT_RUN_SMOKE_EXPECTED_DAEMON),--expected-daemon \"$(AGENT_RUN_SMOKE_EXPECTED_DAEMON)\",)"))
        XCTAssertTrue(makefile.contains("$(if $(filter 1 true yes,$(AGENT_RUN_SMOKE_REQUIRE_DAEMON_MATCH)),--require-daemon-match,)"))
        XCTAssertTrue(makefile.contains("$(if $(AGENT_RUN_SMOKE_OUTPUT),--output \"$(AGENT_RUN_SMOKE_OUTPUT)\",)"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-evidence-current-build: ## Build current app and collect supervised local viftyctl run smoke evidence"))
        XCTAssertTrue(makefile.contains("agent-run-smoke-evidence-current-build requires a clean git worktree so the smoke test uses the built app from the current source ref"))
        XCTAssertTrue(makefile.contains("$(MAKE) app CONFIGURATION=release SIGNING_IDENTITY=\"$(SIGNING_IDENTITY)\" VIFTY_XPC_ALLOWED_TEAM_ID=\"$(VIFTY_XPC_ALLOWED_TEAM_ID)\""))
        XCTAssertTrue(makefile.contains("$(MAKE) agent-run-smoke-evidence VIFTYCTL=\"$(MACOS)/viftyctl\" AGENT_RUN_SMOKE_INSTALL_SOURCE=local-ad-hoc-build AGENT_RUN_SMOKE_SOURCE_REF=\"$(CURRENT_BUILD_SOURCE_REF)\" AGENT_RUN_SMOKE_SOURCE_SHA=\"$(CURRENT_BUILD_SOURCE_SHA)\" AGENT_RUN_SMOKE_EXPECTED_DAEMON=\"$(MACOS)/ViftyDaemon\" AGENT_RUN_SMOKE_REQUIRE_DAEMON_MATCH=1"))
        XCTAssertTrue(makefile.contains("source-first-release-notes: ## Write source-first release notes for the current version"))
        XCTAssertTrue(makefile.contains("unsigned-dev-artifact: ## Build source-first unsigned tester zip and checksum"))
        XCTAssertTrue(makefile.contains("source-first-readiness: ## Check published source-first release readiness"))
        XCTAssertTrue(makefile.contains("scripts/write-release-checklist.sh --mode source-first --version \"$(RELEASE_VERSION)\" $(if $(SOURCE_FIRST_SOURCE_REF),--source-ref \"$(SOURCE_FIRST_SOURCE_REF)\",)"))
        XCTAssertTrue(makefile.contains("scripts/build-unsigned-dev-artifact.sh --version \"$(RELEASE_VERSION)\" $(if $(UNSIGNED_DEV_SOURCE_REF),--require-source-ref \"$(UNSIGNED_DEV_SOURCE_REF)\",)"))
        XCTAssertTrue(makefile.contains("scripts/check-release-readiness.sh --mode source-first --version \"$(RELEASE_VERSION)\" --repo \"$(RELEASE_REPO)\" --json"))
    }

    private func read(_ relativePath: String) throws -> String {
        let url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent(relativePath)
        return try String(contentsOf: url, encoding: .utf8)
    }
}
