#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/collect-agent-cooling-evidence.sh [options]

Collect read-only Vifty agent/helper support evidence for Agent Cooling reports.

Options:
  --viftyctl <path>      viftyctl path (default:
                         /Applications/Vifty.app/Contents/MacOS/viftyctl)
  --output <dir>         Output directory (default:
                         .build/vifty-agent-cooling-<timestamp>)
  --audit-limit <count>  Bounded audit event count, 1 through 200 (default: 20)
  -h, --help             Show this help.

This script is read-only. It runs only:
  viftyctl capabilities --json
  viftyctl diagnose --json
  viftyctl status --json
  viftyctl audit --limit <count> --json

It does not request cooling leases, restore Auto, call ViftyHelper, or write SMC
keys. If diagnose exits nonzero because readiness is blocked, the JSON and exit
status are still captured for maintainers.
USAGE
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

VIFTYCTL="${VIFTYCTL:-/Applications/Vifty.app/Contents/MacOS/viftyctl}"
OUTPUT_DIR="${VIFTY_AGENT_EVIDENCE_OUTPUT_DIR:-}"
AUDIT_LIMIT="${VIFTY_AGENT_EVIDENCE_AUDIT_LIMIT:-20}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --viftyctl)
      if [[ $# -lt 2 ]]; then
        echo "error: --viftyctl requires a path" >&2
        exit 64
      fi
      VIFTYCTL="$2"
      shift 2
      ;;
    --output)
      if [[ $# -lt 2 ]]; then
        echo "error: --output requires a directory" >&2
        exit 64
      fi
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --audit-limit)
      if [[ $# -lt 2 ]]; then
        echo "error: --audit-limit requires a count" >&2
        exit 64
      fi
      AUDIT_LIMIT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

if [[ ! "${AUDIT_LIMIT}" =~ ^[0-9]+$ ]] || [[ "${AUDIT_LIMIT}" -lt 1 ]] || [[ "${AUDIT_LIMIT}" -gt 200 ]]; then
  echo "error: --audit-limit must be an integer from 1 through 200" >&2
  exit 64
fi

if [[ ! -x "${VIFTYCTL}" ]]; then
  echo "error: viftyctl is not executable: ${VIFTYCTL}" >&2
  exit 69
fi

if [[ -z "${OUTPUT_DIR}" ]]; then
  timestamp="$(date -u +"%Y%m%dT%H%M%SZ")"
  OUTPUT_DIR="${ROOT_DIR}/.build/vifty-agent-cooling-${timestamp}"
fi

if [[ -e "${OUTPUT_DIR}" ]]; then
  if [[ ! -d "${OUTPUT_DIR}" ]]; then
    echo "error: output path exists but is not a directory: ${OUTPUT_DIR}" >&2
    exit 73
  fi
  if [[ -n "$(ls -A "${OUTPUT_DIR}" 2>/dev/null)" ]]; then
    echo "error: output directory is not empty: ${OUTPUT_DIR}" >&2
    exit 73
  fi
fi

mkdir -p "${OUTPUT_DIR}"
MANIFEST_PATH="${OUTPUT_DIR}/manifest.tsv"
CHECKSUM_PATH="${OUTPUT_DIR}/checksums.tsv"
SUMMARY_JSON_PATH="${OUTPUT_DIR}/agent-cooling-evidence-summary.json"
GENERATED_AT_UTC="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

printf 'name\tstatus\tstdout\tstderr\n' > "${MANIFEST_PATH}"

run_capture() {
  local name="$1"
  local stdout_name="$2"
  shift 2

  local stdout_path="${OUTPUT_DIR}/${stdout_name}"
  local stderr_name="${name}.stderr"
  local stderr_path="${OUTPUT_DIR}/${stderr_name}"
  local status_path="${OUTPUT_DIR}/${name}.status"
  local status

  set +e
  "$@" > "${stdout_path}" 2> "${stderr_path}"
  status=$?
  set -e

  printf '%s\n' "${status}" > "${status_path}"
  printf '%s\t%s\t%s\t%s\n' "${name}" "${status}" "${stdout_name}" "${stderr_name}" >> "${MANIFEST_PATH}"
}

run_capture "viftyctl-capabilities" "viftyctl-capabilities.json" \
  "${VIFTYCTL}" capabilities --json
run_capture "viftyctl-diagnose" "viftyctl-diagnose.json" \
  "${VIFTYCTL}" diagnose --json
run_capture "viftyctl-status" "viftyctl-status.json" \
  "${VIFTYCTL}" status --json
run_capture "viftyctl-audit" "viftyctl-audit.json" \
  "${VIFTYCTL}" audit --limit "${AUDIT_LIMIT}" --json

cat > "${OUTPUT_DIR}/README.txt" <<EOF
Vifty agent/helper support evidence
===================================

This bundle was generated by scripts/collect-agent-cooling-evidence.sh.

It is read-only evidence for Agent Cooling reports, helper-unreachable reports,
rate limits, expired leases, restore failures, and guarded-run issues.

It does not request cooling leases, restore Auto, call ViftyHelper, or write SMC keys.

Attach or paste:
- viftyctl-diagnose.json
- viftyctl-capabilities.json
- viftyctl-status.json
- viftyctl-audit.json
- manifest.tsv
- agent-cooling-evidence-summary.json
- privacy-review.tsv

If viftyctl-diagnose.status is 75, readiness was blocked. Do not retry prepare
or run while diagnose reports blocked readiness, safeToRequestCooling=false, or
daemonControlPathReady=false.

Before sharing publicly, check privacy-review.tsv. A nonzero privacy review
means the named files may contain private local paths, hostnames, serial-number
labels, hardware-identifier labels, or other identifiers.
EOF

cat > "${OUTPUT_DIR}/metadata.txt" <<EOF
generatedAtUTC=${GENERATED_AT_UTC}
readOnly=true
coolingCommandsRun=false
viftyctl=${VIFTYCTL}
auditLimit=${AUDIT_LIMIT}
EOF

write_summary_json() {
  ruby -rjson -e '
    manifest_path, generated_at, viftyctl, audit_limit = ARGV
    checks = File.readlines(manifest_path, chomp: true).drop(1).map do |line|
      name, status, stdout, stderr = line.split("\t", 4)
      {
        "name" => name,
        "status" => status.to_i,
        "stdout" => stdout,
        "stderr" => stderr,
        "statusFile" => "#{name}.status"
      }
    end
    puts JSON.pretty_generate({
      "schemaVersion" => 1,
      "generatedAtUTC" => generated_at,
      "readOnly" => true,
      "coolingCommandsRun" => false,
      "viftyctl" => viftyctl,
      "auditLimit" => audit_limit.to_i,
      "commands" => checks
    })
  ' "${MANIFEST_PATH}" "${GENERATED_AT_UTC}" "${VIFTYCTL}" "${AUDIT_LIMIT}" > "${SUMMARY_JSON_PATH}"
}

capture_privacy_review() {
  local name="privacy-review"
  local stdout_name="privacy-review.tsv"
  local stdout_path="${OUTPUT_DIR}/${stdout_name}"
  local stderr_name="${name}.stderr"
  local stderr_path="${OUTPUT_DIR}/${stderr_name}"
  local status_path="${OUTPUT_DIR}/${name}.status"
  local host_name=""
  local short_host_name=""
  local status

  host_name="$(/bin/hostname 2>/dev/null || true)"
  short_host_name="$(/bin/hostname -s 2>/dev/null || true)"

  set +e
  ruby -e '
    bundle, home_path, host_name, short_host_name = ARGV
    ignored = {
      "privacy-review.tsv" => true,
      "privacy-review.stderr" => true,
      "privacy-review.status" => true,
      "checksums.tsv" => true
    }
    common_host_tokens = %w[localhost mac macbook macbookpro]
    host_tokens = [host_name, short_host_name]
      .map(&:to_s)
      .map(&:strip)
      .uniq
      .select { |value| value.length >= 5 }
      .reject { |value| common_host_tokens.include?(value.downcase.gsub(/[^a-z0-9]/, "")) }
    patterns = [
      ["serial-number-label", /serial\s+number|IOPlatformSerialNumber/i],
      ["hardware-uuid-label", /hardware\s+uuid|platform\s+uuid|IOPlatformUUID/i],
      ["user-home-path", %r{/Users/[^/\s]+}]
    ]
    if home_path.to_s.start_with?("/Users/")
      patterns << ["current-home-path", Regexp.new(Regexp.escape(home_path))]
    end
    host_tokens.each do |token|
      patterns << ["local-hostname", Regexp.new(Regexp.escape(token), Regexp::IGNORECASE)]
    end

    findings = []
    Dir.children(bundle).sort.each do |entry|
      next if ignored[entry]
      path = File.join(bundle, entry)
      next unless File.file?(path)
      begin
        File.foreach(path).with_index(1) do |line, line_number|
          patterns.each do |kind, pattern|
            findings << [entry, line_number, kind] if line.match?(pattern)
          end
        end
      rescue ArgumentError
        next
      end
    end

    puts "finding\tfile\tline\tkind"
    if findings.empty?
      puts "none\t-\t-\tpassed"
      exit 0
    end

    findings.each do |file, line, kind|
      puts "redaction-needed\t#{file}\t#{line}\t#{kind}"
    end
    warn "privacy review found local identifiers; review or redact the named files before sharing the bundle"
    exit 1
  ' "${OUTPUT_DIR}" "${HOME:-}" "${host_name}" "${short_host_name}" > "${stdout_path}" 2> "${stderr_path}"
  status=$?
  set -e

  printf '%s\n' "${status}" > "${status_path}"
  printf '%s\t%s\t%s\t%s\n' "${name}" "${status}" "${stdout_name}" "${stderr_name}" >> "${MANIFEST_PATH}"
}

# Write a provisional summary so privacy review also scans generated summary JSON.
write_summary_json
capture_privacy_review
write_summary_json

printf 'sha256\tbytes\tfile\n' > "${CHECKSUM_PATH}"
while IFS= read -r -d '' file_path; do
  relative_path="${file_path#"${OUTPUT_DIR}/"}"
  if [[ "${relative_path}" == "checksums.tsv" ]]; then
    continue
  fi
  sha="$(shasum -a 256 "${file_path}" | awk '{ print $1 }')"
  bytes="$(wc -c < "${file_path}" | tr -d '[:space:]')"
  printf '%s\t%s\t%s\n' "${sha}" "${bytes}" "${relative_path}" >> "${CHECKSUM_PATH}"
done < <(find "${OUTPUT_DIR}" -type f -print0)

echo "Agent cooling evidence written to ${OUTPUT_DIR}"
