#!/bin/bash -p
if [[ "$0" != "vifty-release-clean" ]]; then
  release_token="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
  if [[ "${release_token}" == *[[:space:]]* ]]; then
    echo "error: GitHub token must not contain whitespace" >&2
    exit 65
  fi
  exec 9<<<"${release_token}"
  unset release_token GH_TOKEN GITHUB_TOKEN
  exec /usr/bin/env -i \
    LANG=C.UTF-8 LC_ALL=C.UTF-8 \
    HOME="${HOME:-}" TMPDIR="${TMPDIR:-/tmp}" USER="${USER:-}" LOGNAME="${LOGNAME:-}" \
    VIFTY_GH_TOKEN_FD=9 GH_HOST="${GH_HOST:-}" \
    /bin/bash -p -c 'source "$1" "${@:2}"' vifty-release-clean "$0" "$@"
fi
set -euo pipefail
umask 077

INHERITED_GH_TOKEN=""
if [[ "${VIFTY_GH_TOKEN_FD:-}" == "9" ]]; then
  IFS= read -r INHERITED_GH_TOKEN <&9 || true
  exec 9<&-
fi
unset VIFTY_GH_TOKEN_FD GH_TOKEN GITHUB_TOKEN

inherited_functions="$(builtin declare -F)"
if [[ -n "${inherited_functions}" ]]; then
  builtin printf '%s\n' "error: inherited shell functions are not allowed" >&2
  exit 65
fi

for hostile_name in \
  BASH_ENV ENV RUBYOPT RUBYLIB TAR_OPTIONS \
  http_proxy https_proxy all_proxy no_proxy \
  HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY \
  CURL_CA_BUNDLE SSL_CERT_FILE SSL_CERT_DIR \
  GIT_DIR GIT_WORK_TREE GIT_COMMON_DIR GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
  GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_NAMESPACE GIT_REPLACE_REF_BASE \
  GIT_CONFIG GIT_CONFIG_SYSTEM GIT_CONFIG_GLOBAL GIT_CONFIG_COUNT \
  GIT_CONFIG_PARAMETERS GIT_EXEC_PATH GIT_EXTERNAL_DIFF GIT_DIFF_OPTS \
  GIT_PROXY_COMMAND GIT_SSL_CAINFO GIT_SSL_CAPATH GIT_SSH GIT_SSH_COMMAND \
  GIT_ASKPASS SSH_ASKPASS \
  GH_CONFIG_DIR XDG_CONFIG_HOME GH_PATH GH_FORCE_TTY GITHUB_API_URL; do
  if [[ -n "${!hostile_name:-}" ]]; then
    echo "error: hostile release environment is not allowed: ${hostile_name}" >&2
    exit 65
  fi
done
unset BASH_ENV ENV RUBYOPT RUBYLIB CDPATH GITHUB_API_URL

PATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/usr/local/bin"
export PATH
export GIT_NO_REPLACE_OBJECTS=1

GH_BIN=""
for gh_candidate in /opt/homebrew/bin/gh /usr/local/bin/gh /usr/bin/gh; do
  if [[ -x "${gh_candidate}" ]]; then
    GH_BIN="${gh_candidate}"
    break
  fi
done
GIT_BIN="/usr/bin/git"
RUBY_BIN="/usr/bin/ruby"

CANONICAL_HOME="$("${RUBY_BIN}" -retc -e '
  begin
    passwd_home = Etc.getpwuid(Process.uid).dir
    abort("passwd home must be an absolute path") unless
      passwd_home.is_a?(String) && passwd_home.start_with?("/") && passwd_home != "/"
    resolved_home = File.realpath(passwd_home)
    abort("canonical passwd home must be a directory") unless File.directory?(resolved_home)
    print resolved_home
  rescue ArgumentError, SystemCallError => error
    abort("cannot resolve canonical passwd home: #{error.message}")
  end
')" || {
  echo "error: failed to resolve the current uid's canonical passwd home" >&2
  exit 65
}
if [[ -z "${CANONICAL_HOME}" || "${CANONICAL_HOME}" != /* ||
      ! -d "${CANONICAL_HOME}" || -L "${CANONICAL_HOME}" ]]; then
  echo "error: current uid does not have a safe canonical passwd home" >&2
  exit 65
fi
HOME="${CANONICAL_HOME}"
export HOME

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd -P)"
SELF_PATH="scripts/push-and-dispatch-signed-release-tag.sh"
GOVERNANCE_TOOL_PATH="scripts/check-release-governance.sh"
VALIDATOR_PATH="scripts/validate-release-governance-evidence.rb"
MANIFEST_CHECKER_PATH="scripts/check-release-manifest.sh"
RELEASE_PREP_DIFF_CHECKER_PATH="scripts/check-release-prep-diff.sh"
WORKFLOW_CONTRACT_PATH="scripts/check-workflow-contract.rb"
GH_TOOLCHAIN_VERIFIER_PATH="scripts/verify-release-gh-toolchain.rb"
GH_TOOLCHAIN_POLICY_PATH=".github/release-gh-toolchain.json"
ALLOWED_SIGNERS_PATH=".github/release-signers.allowed"
RELEASE_MANIFEST_PATH=".github/release-manifest.json"
RELEASE_WORKFLOW_PATH=".github/workflows/release.yml"
INFO_PLIST_PATH="Resources/Info.plist"

REPOSITORY="Reedtrullz/Vifty"
TAG=""
COMMIT=""
SAFE_GH_TOKEN=""
TAG_OBJECT=""
TAGGER_TIME=""
SIGNED_EVIDENCE_SHA=""
TAG_PUSH_JOURNALED_AT=""
WORKFLOW_ID=""
RUN_ID=""
RUN_URL=""
TAG_PUSHED=0
WORKFLOW_RUN_OBSERVED=0
WORKFLOW_RUN_VERIFIED=0
PUSH_EXIT_CODE=""
REMOTE_TAG_STATE="not-checked"
TRIGGER_STATE="not-observed"
TRIGGER_CORRELATION="not-checked"
PUSH_DISPOSITION="not-attempted"
PUSH_OWNERSHIP="not-established"
SUCCESS=0
FAILURE_RECEIPT_CLASSIFIED=0
CURRENT_STAGE="initialization"
RECEIPT_READY=0
RECEIPT_PATH=""
LOCK_PATH=""
LOCK_HELD=0
RETIREMENT_MARKER_PATH=""
TRANSACTION_ROOT=""

usage() {
  cat >&2 <<'USAGE'
Usage: scripts/push-and-dispatch-signed-release-tag.sh --tag v<version> --commit <sha> [options]

Revalidates one existing local SSH-signed annotated release tag, creates that
exact absent tag on github.com with a compare-and-swap push, reads it back, and
observes the unique first-attempt Release run generated by GitHub's tag-push
trigger. The local receipt is evidence only and never authorizes retry or tag
reuse. Any failure after the tag push begins permanently retires that tag.
Observe only that original tag-push run/release; never manually dispatch or
rerun it. Cut a new patch only if the original transaction did not publish.

Options:
  --repository <owner/repo>  GitHub repository (default: Reedtrullz/Vifty).
  --tag <tag>                Existing tag, formatted v<major>.<minor>.<patch>.
  --commit <sha>             Exact 40-character protected-main/tag commit.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repository) REPOSITORY="${2:-}"; shift 2 ;;
    --tag) TAG="${2:-}"; shift 2 ;;
    --commit) COMMIT="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown argument: $1" >&2; usage; exit 64 ;;
  esac
done

if [[ "${REPOSITORY}" != "Reedtrullz/Vifty" ]]; then
  echo "error: --repository must be exactly Reedtrullz/Vifty" >&2
  exit 64
fi
if [[ ! "${TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "error: --tag must be v<major>.<minor>.<patch>" >&2
  exit 64
fi
if [[ ! "${COMMIT}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "error: --commit must be a full lowercase commit SHA" >&2
  exit 64
fi
if [[ -n "${GH_HOST:-}" && "${GH_HOST}" != "github.com" ]]; then
  echo "error: release push requires github.com, not GH_HOST=${GH_HOST}" >&2
  exit 65
fi
if [[ -z "${GH_BIN}" ]]; then
  echo "error: gh CLI is required for the protected release push" >&2
  exit 69
fi

cd "${ROOT_DIR}"
ROOT_DIR="$(pwd -P)"
if [[ "${SCRIPT_DIR}/$(basename "${BASH_SOURCE[0]}")" != "${ROOT_DIR}/${SELF_PATH}" ||
      ! -f "${ROOT_DIR}/${SELF_PATH}" || -L "${ROOT_DIR}/${SELF_PATH}" ]]; then
  echo "error: release helper must run from the canonical committed repository path" >&2
  exit 65
fi

safe_repo_git() {
  GIT_CONFIG_NOSYSTEM=1 \
    GIT_CONFIG_SYSTEM=/dev/null \
    GIT_CONFIG_GLOBAL=/dev/null \
    GIT_CONFIG_COUNT=7 \
    GIT_CONFIG_KEY_0=core.hooksPath GIT_CONFIG_VALUE_0=/dev/null \
    GIT_CONFIG_KEY_1=core.fsmonitor GIT_CONFIG_VALUE_1=false \
    GIT_CONFIG_KEY_2=core.untrackedCache GIT_CONFIG_VALUE_2=false \
    GIT_CONFIG_KEY_3=core.attributesFile GIT_CONFIG_VALUE_3=/dev/null \
    GIT_CONFIG_KEY_4=core.excludesFile GIT_CONFIG_VALUE_4=/dev/null \
    GIT_CONFIG_KEY_5=core.worktree GIT_CONFIG_VALUE_5="${ROOT_DIR}" \
    GIT_CONFIG_KEY_6=core.bare GIT_CONFIG_VALUE_6=false \
    "${GIT_BIN}" -C "${ROOT_DIR}" "$@"
}

safe_bare_git() {
  local bare_root="$1"
  shift
  GIT_CONFIG_NOSYSTEM=1 \
    GIT_CONFIG_SYSTEM=/dev/null \
    GIT_CONFIG_GLOBAL=/dev/null \
    GIT_CONFIG_COUNT=6 \
    GIT_CONFIG_KEY_0=core.hooksPath GIT_CONFIG_VALUE_0=/dev/null \
    GIT_CONFIG_KEY_1=core.fsmonitor GIT_CONFIG_VALUE_1=false \
    GIT_CONFIG_KEY_2=core.untrackedCache GIT_CONFIG_VALUE_2=false \
    GIT_CONFIG_KEY_3=core.attributesFile GIT_CONFIG_VALUE_3=/dev/null \
    GIT_CONFIG_KEY_4=core.excludesFile GIT_CONFIG_VALUE_4=/dev/null \
    GIT_CONFIG_KEY_5=core.bare GIT_CONFIG_VALUE_5=true \
    "${GIT_BIN}" -C "${bare_root}" "$@"
}

assert_safe_gh_config() {
  local unix_socket token
  unix_socket="$("${GH_BIN}" config get http_unix_socket --host github.com 2>/dev/null || true)"
  if [[ -n "${unix_socket}" ]]; then
    echo "error: GitHub CLI http_unix_socket must be empty for github.com" >&2
    exit 65
  fi
  token="${INHERITED_GH_TOKEN:-}"
  if [[ -z "${token}" ]]; then
    token="$("${GH_BIN}" auth token --hostname github.com 2>/dev/null || true)"
  fi
  if [[ -z "${token}" || "${token}" == *[[:space:]]* ||
        ! -d /var/empty || -w /var/empty ]]; then
    echo "error: an authenticated github.com token and trusted empty gh config root are required" >&2
    exit 65
  fi
  SAFE_GH_TOKEN="${token}"
  unset GH_TOKEN GITHUB_TOKEN
}

safe_gh() {
  GH_CONFIG_DIR=/var/empty \
    GH_TOKEN="${SAFE_GH_TOKEN}" \
    GH_HOST=github.com \
    GH_NO_UPDATE_NOTIFIER=1 \
    GH_NO_EXTENSION_UPDATE_NOTIFIER=1 \
    "${GH_BIN}" "$@"
}

run_clean_script_with_token() {
  local script_path="$1"
  local status
  shift
  exec 9<<<"${SAFE_GH_TOKEN}"
  set +e
  VIFTY_GH_TOKEN_FD=9 \
    /bin/bash -p -c 'source "$1" "${@:2}"' \
      vifty-release-clean "${script_path}" "$@"
  status=$?
  set -e
  exec 9<&-
  return "${status}"
}

write_receipt() {
  local status="$1"
  local stage="$2"
  local receipt_dir receipt_tmp now
  [[ "${RECEIPT_READY}" == "1" ]] || return 0
  receipt_dir="$(dirname "${RECEIPT_PATH}")"
  if [[ -L "${TRANSACTION_ROOT}" || ! -d "${TRANSACTION_ROOT}" ||
        -L "${receipt_dir}" || ! -d "${receipt_dir}" ||
        -L "${RECEIPT_PATH}" ||
        ( -e "${RECEIPT_PATH}" && ! -f "${RECEIPT_PATH}" ) ]]; then
    echo "error: fixed receipt path changed to an unsafe filesystem object" >&2
    return 1
  fi
  now="$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)"
  receipt_tmp="$(mktemp "${receipt_dir}/.${TAG}.receipt.XXXXXX")"
  /bin/chmod 600 "${receipt_tmp}"
  "${RUBY_BIN}" -rjson -e '
    status, stage, repository, tag, commit, tag_object, evidence_sha,
      tag_push_journaled_at, tag_pushed, workflow_run_observed,
      workflow_run_verified, push_exit_code, remote_tag_state, trigger_state,
      trigger_correlation, push_disposition, push_ownership,
      workflow_id, run_id, run_url, observed_at = ARGV
    tag_pushed_value =
      if remote_tag_state == "exact"
        true
      elsif remote_tag_state == "absent"
        false
      end
    value = {
      "schemaVersion" => 2,
      "status" => status,
      "stage" => stage,
      "repository" => repository,
      "releaseTag" => tag,
      "commitSHA" => commit,
      "tagObjectSHA" => tag_object.empty? ? nil : tag_object,
      "signedGovernanceEvidenceSHA256" => evidence_sha.empty? ? nil : evidence_sha,
      "tagPushJournaledAt" => tag_push_journaled_at.empty? ? nil : tag_push_journaled_at,
      "tagPushed" => tag_pushed_value,
      "tagPushConfirmed" => tag_pushed == "1",
      "workflowTrigger" => "push",
      "workflowRunObserved" => workflow_run_observed == "1",
      "workflowRunVerified" => workflow_run_verified == "1",
      "pushExitCode" => push_exit_code.empty? ? nil : push_exit_code.to_i,
      "remoteTagState" => remote_tag_state,
      "triggerState" => trigger_state,
      "triggerCorrelation" => trigger_correlation,
      "pushDisposition" => push_disposition,
      "pushOwnership" => push_ownership,
      "receiptAuthorizesRetry" => false,
      "workflowID" => workflow_id.empty? ? nil : workflow_id.to_i,
      "workflowRunID" => run_id.empty? ? nil : run_id.to_i,
      "workflowRunURL" => run_url.empty? ? nil : run_url,
      "observedAt" => observed_at
    }
    puts JSON.pretty_generate(value)
  ' "${status}" "${stage}" "${REPOSITORY}" "${TAG}" "${COMMIT}" "${TAG_OBJECT}" \
    "${SIGNED_EVIDENCE_SHA}" "${TAG_PUSH_JOURNALED_AT}" "${TAG_PUSHED}" \
    "${WORKFLOW_RUN_OBSERVED}" "${WORKFLOW_RUN_VERIFIED}" \
    "${PUSH_EXIT_CODE}" "${REMOTE_TAG_STATE}" "${TRIGGER_STATE}" \
    "${TRIGGER_CORRELATION}" "${PUSH_DISPOSITION}" \
    "${PUSH_OWNERSHIP}" "${WORKFLOW_ID}" "${RUN_ID}" "${RUN_URL}" \
    "${now}" \
    > "${receipt_tmp}"
  /bin/chmod 600 "${receipt_tmp}"
  "${RUBY_BIN}" -e 'File.open(ARGV.fetch(0), "r") { |file| file.fsync }' "${receipt_tmp}"
  if [[ -L "${receipt_dir}" || ! -d "${receipt_dir}" ||
        -L "${RECEIPT_PATH}" ||
        ( -e "${RECEIPT_PATH}" && ! -f "${RECEIPT_PATH}" ) ]]; then
    /bin/unlink "${receipt_tmp}" 2>/dev/null || true
    echo "error: fixed receipt path changed before atomic replacement" >&2
    return 1
  fi
  /bin/mv -f -- "${receipt_tmp}" "${RECEIPT_PATH}"
  /bin/chmod 600 "${RECEIPT_PATH}"
  /bin/sync
}

create_retirement_marker() {
  local created_at
  created_at="${TAG_PUSH_JOURNALED_AT}"
  if [[ -L "${RETIREMENT_MARKER_PATH}" || -e "${RETIREMENT_MARKER_PATH}" ]]; then
    echo "error: durable retired-tag marker already exists for ${TAG}" >&2
    return 1
  fi
  "${RUBY_BIN}" -rjson -e '
    path, repository, tag, commit, tag_object, created_at = ARGV
    value = {
      "schemaVersion" => 1,
      "status" => "retired-at-push-boundary",
      "repository" => repository,
      "releaseTag" => tag,
      "commitSHA" => commit,
      "tagObjectSHA" => tag_object,
      "createdAt" => created_at,
      "retiredTag" => true,
      "authorizesRetry" => false
    }
    flags = File::WRONLY | File::CREAT | File::EXCL
    File.open(path, flags, 0o600) do |file|
      file.write(JSON.pretty_generate(value) + "\n")
      file.flush
      file.fsync
    end
    File.open(File.dirname(path), File::RDONLY) { |directory| directory.fsync }
  ' "${RETIREMENT_MARKER_PATH}" "${REPOSITORY}" "${TAG}" "${COMMIT}" \
    "${TAG_OBJECT}" "${created_at}"
  /bin/chmod 600 "${RETIREMENT_MARKER_PATH}"
}

scratch="$(mktemp -d "${TMPDIR:-/tmp}/vifty-release-push.XXXXXX")"
cleanup() {
  local exit_status=$?
  trap - EXIT
  if [[ "${exit_status}" -ne 0 && "${TAG_PUSHED}" == "1" &&
        "${FAILURE_RECEIPT_CLASSIFIED}" != "1" ]]; then
    set +e
    write_receipt "failed-after-tag-push" "${CURRENT_STAGE}"
    set -e
  fi
  if [[ "${LOCK_HELD}" == "1" && -f "${LOCK_PATH}" && ! -L "${LOCK_PATH}" &&
        "$(< "${LOCK_PATH}")" == "$$" ]]; then
    /bin/unlink "${LOCK_PATH}" 2>/dev/null || true
  fi
  /bin/rm -rf "${scratch}"
  exit "${exit_status}"
}
trap cleanup EXIT

if [[ -z "${HOME:-}" || "${HOME}" != /* || ! -d "${HOME}" || -L "${HOME}" ]]; then
  echo "error: HOME must be an absolute real directory for durable release transactions" >&2
  exit 65
fi
library_dir="${HOME}/Library"
application_support_dir="${library_dir}/Application Support"
vifty_state_dir="${application_support_dir}/Vifty"
transactions_dir="${vifty_state_dir}/ReleaseTransactions"
TRANSACTION_ROOT="${transactions_dir}/Reedtrullz-Vifty"
receipt_dir="${TRANSACTION_ROOT}/${TAG}"
for directory in "${library_dir}" "${application_support_dir}" "${vifty_state_dir}" \
  "${transactions_dir}" "${TRANSACTION_ROOT}" "${receipt_dir}"; do
  if [[ -L "${directory}" || ( -e "${directory}" && ! -d "${directory}" ) ]]; then
    echo "error: durable release transaction directory is unsafe: ${directory}" >&2
    exit 65
  fi
  if [[ ! -d "${directory}" ]]; then
    /bin/mkdir -m 700 "${directory}"
  fi
done
/bin/chmod 700 "${vifty_state_dir}" "${transactions_dir}" "${TRANSACTION_ROOT}" "${receipt_dir}"
RECEIPT_PATH="${receipt_dir}/receipt.json"
LOCK_PATH="${receipt_dir}/transaction.lock"
RETIREMENT_MARKER_PATH="${receipt_dir}/retired.json"
if [[ -L "${RECEIPT_PATH}" || ( -e "${RECEIPT_PATH}" && ! -f "${RECEIPT_PATH}" ) ||
      -L "${LOCK_PATH}" || ( -e "${LOCK_PATH}" && ! -f "${LOCK_PATH}" ) ||
      -L "${RETIREMENT_MARKER_PATH}" ||
      ( -e "${RETIREMENT_MARKER_PATH}" && ! -f "${RETIREMENT_MARKER_PATH}" ) ]]; then
  echo "error: fixed release transaction path is unsafe" >&2
  exit 65
fi
if ! /usr/bin/shlock -f "${LOCK_PATH}" -p "$$"; then
  echo "error: another live release transaction already holds ${LOCK_PATH}" >&2
  exit 75
fi
LOCK_HELD=1
RECEIPT_READY=1

if [[ -f "${RETIREMENT_MARKER_PATH}" ]]; then
  echo "error: durable retired-tag marker blocks ${TAG}; inspect ${RETIREMENT_MARKER_PATH} without deleting or reusing the tag" >&2
  exit 75
fi

if [[ -f "${RECEIPT_PATH}" ]]; then
  set +e
  prior_receipt_result="$("${RUBY_BIN}" -rjson -e '
    receipt = JSON.parse(File.read(ARGV.fetch(0)))
    abort("receipt must be an object") unless receipt.is_a?(Hash)
    repository, tag, commit = ARGV.drop(1)
    abort("receipt schema mismatch") unless receipt["schemaVersion"] == 2
    abort("receipt repository mismatch") unless receipt["repository"] == repository
    abort("receipt tag mismatch") unless receipt["releaseTag"] == tag
    abort("receipt commit mismatch") unless receipt["commitSHA"] == commit
    abort("receipt retry flag must remain false") unless receipt["receiptAuthorizesRetry"] == false
    retryable =
      receipt["status"] == "validated-pre-push" &&
      receipt["stage"] == "validated-pre-push" &&
      receipt["tagPushed"].nil? &&
      receipt["tagPushConfirmed"] == false &&
      receipt["workflowTrigger"] == "push" &&
      receipt["workflowRunObserved"] == false &&
      receipt["workflowRunVerified"] == false &&
      receipt["pushExitCode"].nil? &&
      receipt["remoteTagState"] == "not-checked" &&
      receipt["triggerState"] == "not-observed" &&
      receipt["tagPushJournaledAt"].nil? &&
      receipt["pushDisposition"] == "not-attempted" &&
      receipt["pushOwnership"] == "not-established"
    if retryable
      print "safe-pre-mutation"
      exit 0
    end
    print "retired-after-mutation-boundary"
    exit 2
  ' "${RECEIPT_PATH}" "${REPOSITORY}" "${TAG}" "${COMMIT}" 2>&1)"
  prior_receipt_status=$?
  set -e
  if [[ "${prior_receipt_status}" -ne 0 ]]; then
    echo "error: existing release receipt blocks this transaction (${prior_receipt_result}); inspect it without overwriting or reusing the tag" >&2
    exit 75
  fi
fi

for path in \
  "${SELF_PATH}" \
  "${GOVERNANCE_TOOL_PATH}" \
  "scripts/check-release-environment.sh" \
  "scripts/check-release-secrets.sh" \
  "${VALIDATOR_PATH}" \
  "${MANIFEST_CHECKER_PATH}" \
  "${RELEASE_PREP_DIFF_CHECKER_PATH}" \
  "${WORKFLOW_CONTRACT_PATH}" \
  "${GH_TOOLCHAIN_VERIFIER_PATH}" \
  "${GH_TOOLCHAIN_POLICY_PATH}" \
  "${ALLOWED_SIGNERS_PATH}" \
  "${RELEASE_MANIFEST_PATH}" \
  "${RELEASE_WORKFLOW_PATH}" \
  "${INFO_PLIST_PATH}"; do
  if [[ ! -f "${ROOT_DIR}/${path}" || -L "${ROOT_DIR}/${path}" ]]; then
    echo "error: required release file is missing or not regular: ${path}" >&2
    exit 66
  fi
done

if ! worktree_status="$(safe_repo_git status --porcelain=v1 --untracked-files=all)"; then
  echo "error: failed to inspect release worktree state" >&2
  exit 65
fi
if [[ -n "${worktree_status}" ]]; then
  echo "error: release push requires a completely clean worktree" >&2
  exit 65
fi
head_commit="$(safe_repo_git rev-parse --verify 'HEAD^{commit}' 2>/dev/null || true)"
if [[ "${head_commit}" != "${COMMIT}" ]]; then
  echo "error: checked-out HEAD ${head_commit:-missing} does not match ${COMMIT}" >&2
  exit 65
fi

TAG_OBJECT="$(safe_repo_git rev-parse --verify "refs/tags/${TAG}^{tag}" 2>/dev/null || true)"
if [[ ! "${TAG_OBJECT}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "error: local ${TAG} must be one annotated tag object" >&2
  exit 65
fi
tag_commit="$(safe_repo_git rev-parse --verify "${TAG_OBJECT}^{commit}" 2>/dev/null || true)"
if [[ "${tag_commit}" != "${COMMIT}" ]]; then
  echo "error: local ${TAG} resolves to ${tag_commit:-missing}, not ${COMMIT}" >&2
  exit 65
fi

parent_commit="$(safe_repo_git rev-parse --verify "${COMMIT}^" 2>/dev/null || true)"
if [[ ! "${parent_commit}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "error: release commit must have one trusted first parent" >&2
  exit 65
fi
protected_release_paths=(
  ".github/release-gh-toolchain.json"
  ".github/release-signers.allowed"
  ".github/workflows/ci.yml"
  ".github/workflows/release.yml"
  "scripts/check-release-environment.sh"
  "scripts/check-release-governance.sh"
  "scripts/check-release-manifest-history-from-git.sh"
  "scripts/check-release-manifest-history.rb"
  "scripts/check-release-manifest.sh"
  "scripts/check-release-prep-diff.sh"
  "scripts/check-release-provenance.sh"
  "scripts/check-release-secrets.sh"
  "scripts/check-workflow-contract.rb"
  "scripts/create-signed-release-tag.sh"
  "scripts/lib/release_artifact_contract.rb"
  "scripts/push-and-dispatch-signed-release-tag.sh"
  "scripts/release-candidate-inventory.rb"
  "scripts/render-release-facts.sh"
  "scripts/run-actionlint.sh"
  "scripts/sign-release-candidate.sh"
  "scripts/validate-release-governance-evidence.rb"
  "scripts/validate-release-metadata.sh"
  "scripts/verify-release-artifact.sh"
  "scripts/verify-release-gh-toolchain.rb"
  "scripts/write-release-checklist.sh"
)
for protected_path in "${protected_release_paths[@]}"; do
  current_blob="$(safe_repo_git rev-parse --verify "${COMMIT}:${protected_path}" 2>/dev/null || true)"
  parent_blob="$(safe_repo_git rev-parse --verify "${parent_commit}:${protected_path}" 2>/dev/null || true)"
  if [[ ! "${current_blob}" =~ ^[0-9a-f]{40}$ || "${current_blob}" != "${parent_blob}" ||
        ! -f "${ROOT_DIR}/${protected_path}" || -L "${ROOT_DIR}/${protected_path}" ]]; then
    echo "error: protected release tooling must be byte-identical to the exact first parent: ${protected_path}" >&2
    exit 65
  fi
done
commit_signers="${scratch}/commit-release-signers.allowed"
parent_signers="${scratch}/parent-release-signers.allowed"
commit_gh_policy="${scratch}/commit-release-gh-toolchain.json"
parent_gh_policy="${scratch}/parent-release-gh-toolchain.json"
safe_repo_git show "${COMMIT}:${ALLOWED_SIGNERS_PATH}" > "${commit_signers}"
safe_repo_git show "${parent_commit}:${ALLOWED_SIGNERS_PATH}" > "${parent_signers}"
safe_repo_git show "${COMMIT}:${GH_TOOLCHAIN_POLICY_PATH}" > "${commit_gh_policy}"
safe_repo_git show "${parent_commit}:${GH_TOOLCHAIN_POLICY_PATH}" > "${parent_gh_policy}"
if ! /usr/bin/cmp -s "${commit_signers}" "${parent_signers}" ||
   ! /usr/bin/cmp -s "${ROOT_DIR}/${ALLOWED_SIGNERS_PATH}" "${commit_signers}"; then
  echo "error: release signer policy must be byte-identical to the exact first parent" >&2
  exit 65
fi
if ! /usr/bin/cmp -s "${commit_gh_policy}" "${parent_gh_policy}" ||
   ! /usr/bin/cmp -s "${ROOT_DIR}/${GH_TOOLCHAIN_POLICY_PATH}" "${commit_gh_policy}"; then
  echo "error: release gh toolchain policy must be byte-identical to the exact first parent" >&2
  exit 65
fi
/bin/chmod 400 "${commit_signers}" "${parent_signers}"
if ! safe_repo_git \
  -c gpg.format=ssh \
  -c gpg.ssh.program=/usr/bin/ssh-keygen \
  -c "gpg.ssh.allowedSignersFile=${commit_signers}" \
  verify-tag "${TAG_OBJECT}" >/dev/null; then
  echo "error: ${TAG} does not verify against the continuous release signer policy" >&2
  exit 65
fi

committed_root="${scratch}/committed-source"
/bin/mkdir -p "${committed_root}"
if ! safe_repo_git archive --format=tar "${COMMIT}" |
  /usr/bin/tar -xf - -C "${committed_root}"; then
  echo "error: failed to materialize exact committed release tooling" >&2
  exit 65
fi

verify_committed_file() {
  local path="$1"
  local working_sha committed_sha
  if [[ ! -f "${committed_root}/${path}" || -L "${committed_root}/${path}" ]]; then
    echo "error: exact commit lacks a regular release file: ${path}" >&2
    return 1
  fi
  working_sha="$(/usr/bin/shasum -a 256 "${ROOT_DIR}/${path}" | /usr/bin/awk '{print $1}')"
  committed_sha="$(/usr/bin/shasum -a 256 "${committed_root}/${path}" | /usr/bin/awk '{print $1}')"
  if [[ "${working_sha}" != "${committed_sha}" ]]; then
    echo "error: working ${path} does not match exact release commit ${COMMIT}" >&2
    return 1
  fi
}

for path in \
  "${SELF_PATH}" \
  "${GOVERNANCE_TOOL_PATH}" \
  "scripts/check-release-environment.sh" \
  "scripts/check-release-secrets.sh" \
  "${VALIDATOR_PATH}" \
  "${MANIFEST_CHECKER_PATH}" \
  "${RELEASE_PREP_DIFF_CHECKER_PATH}" \
  "${WORKFLOW_CONTRACT_PATH}" \
  "${GH_TOOLCHAIN_VERIFIER_PATH}" \
  "${GH_TOOLCHAIN_POLICY_PATH}" \
  "${ALLOWED_SIGNERS_PATH}" \
  "${RELEASE_MANIFEST_PATH}" \
  "${RELEASE_WORKFLOW_PATH}" \
  "${INFO_PLIST_PATH}"; do
  verify_committed_file "${path}"
done

version="${TAG#v}"
"${committed_root}/${RELEASE_PREP_DIFF_CHECKER_PATH}" \
  --root "${ROOT_DIR}" \
  --commit "${COMMIT}" >/dev/null
VIFTY_RELEASE_MANIFEST_ROOT="${committed_root}" \
  VIFTY_RELEASE_SOURCE_REPOSITORY_ROOT="${ROOT_DIR}" \
  "${committed_root}/${MANIFEST_CHECKER_PATH}" \
    --publication-version "${version}" \
    --base-ref "${parent_commit}" \
    --require-base >/dev/null
VIFTY_WORKFLOW_CONTRACT_ROOT="${committed_root}" \
  "${RUBY_BIN}" "${committed_root}/${WORKFLOW_CONTRACT_PATH}" >/dev/null
plist_version="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' \
  "${committed_root}/${INFO_PLIST_PATH}")"
if [[ "${plist_version}" != "${version}" ]]; then
  echo "error: ${TAG} does not match committed Info.plist version ${plist_version}" >&2
  exit 65
fi

raw_tag="${scratch}/tag-object.txt"
signed_evidence="${scratch}/signed-governance-evidence.json"
tag_metadata="${scratch}/tag-metadata.json"
safe_repo_git cat-file tag "${TAG_OBJECT}" > "${raw_tag}"
if ! "${RUBY_BIN}" -rbase64 -rjson -rtime -e '
  raw = File.binread(ARGV.fetch(0))
  tag = ARGV.fetch(1)
  commit = ARGV.fetch(2)
  evidence_path = ARGV.fetch(3)
  metadata_path = ARGV.fetch(4)
  header, body = raw.split("\n\n", 2)
  abort("annotated tag body is missing") unless header && body
  abort("annotated tag name mismatch") unless header.lines.grep(/\Atag /) == ["tag #{tag}\n"]
  abort("annotated tag object mismatch") unless header.lines.grep(/\Aobject /) == ["object #{commit}\n"]
  abort("annotated tag type must be commit") unless header.lines.grep(/\Atype /) == ["type commit\n"]
  tagger = header.lines.grep(/\Atagger /)
  match = tagger.length == 1 && tagger.fetch(0).match(/ (\d+) [+-]\d{4}\n?\z/)
  abort("annotated tagger timestamp is missing") unless match
  prefix = "Vifty-Release-Governance-Base64: "
  fields = body.lines.select { |line| line.start_with?(prefix) }
  abort("signed tag must contain exactly one governance evidence field") unless fields.length == 1
  encoded = fields.fetch(0).delete_suffix("\n").delete_suffix("\r").delete_prefix(prefix)
  evidence = Base64.strict_decode64(encoded)
  abort("embedded governance evidence is empty or oversized") if evidence.empty? || evidence.bytesize > 1_048_576
  File.binwrite(evidence_path, evidence)
  File.write(metadata_path, JSON.generate({
    "taggerTime" => Time.at(match[1].to_i).utc.iso8601,
    "evidenceSHA256" => Digest::SHA256.hexdigest(evidence)
  }))
' -rdigest "${raw_tag}" "${TAG}" "${COMMIT}" "${signed_evidence}" "${tag_metadata}"; then
  echo "error: failed to extract the exact signed governance evidence" >&2
  exit 65
fi
TAGGER_TIME="$("${RUBY_BIN}" -rjson -e 'print JSON.parse(File.read(ARGV.fetch(0))).fetch("taggerTime")' "${tag_metadata}")"
SIGNED_EVIDENCE_SHA="$("${RUBY_BIN}" -rjson -e 'print JSON.parse(File.read(ARGV.fetch(0))).fetch("evidenceSHA256")' "${tag_metadata}")"

unverified_gh_bin="${GH_BIN}"
GH_BIN="${scratch}/pinned-gh"
"${RUBY_BIN}" "${committed_root}/${GH_TOOLCHAIN_VERIFIER_PATH}" \
  --policy "${committed_root}/${GH_TOOLCHAIN_POLICY_PATH}" \
  --source "${unverified_gh_bin}" \
  --destination "${GH_BIN}" > "${scratch}/gh-toolchain-verification.json"

current_time="$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)"
"${RUBY_BIN}" "${committed_root}/${VALIDATOR_PATH}" \
  --root "${ROOT_DIR}" \
  --evidence "${signed_evidence}" \
  --repository "${REPOSITORY}" \
  --tag "${TAG}" \
  --commit "${COMMIT}" \
  --tagger-time "${TAGGER_TIME}" \
  --current-time "${current_time}" > "${scratch}/signed-governance-validation.json"

assert_safe_gh_config

ci_runs_json="$(safe_gh run list \
    --repo "github.com/${REPOSITORY}" \
    --workflow .github/workflows/ci.yml \
    --limit 100 \
    --json databaseId,headBranch,headSha,status,conclusion,event,url)"
if ! source_ci_run_id="$("${RUBY_BIN}" -rjson -e '
  runs = JSON.parse(STDIN.read)
  abort("CI run list must be an array") unless runs.is_a?(Array)
  commit = ARGV.fetch(0)
  matches = runs.select do |run|
    run.is_a?(Hash) &&
      run["headSha"] == commit &&
      run["headBranch"] == "main" &&
      run["event"] == "push" &&
      run["status"] == "completed" &&
      run["conclusion"] == "success" &&
      run["databaseId"].is_a?(Integer) &&
      run["databaseId"].positive?
  end
  abort("no successful exact-main push CI run") if matches.empty?
  print matches.max_by { |run| run.fetch("databaseId") }.fetch("databaseId")
' "${COMMIT}" <<< "${ci_runs_json}")"; then
  echo "error: no successful completed main-push CI run exists for ${COMMIT}" >&2
  exit 65
fi

remote_main_sha() {
  local payload
  payload="$(safe_gh api --hostname github.com \
    -H 'Cache-Control: no-cache' -H 'Pragma: no-cache' \
    "repos/${REPOSITORY}/branches/main")"
  "${RUBY_BIN}" -rjson -e '
    value = JSON.parse(STDIN.read).dig("commit", "sha")
    abort("remote main lacks an exact commit SHA") unless
      value.is_a?(String) && value.match?(/\A[0-9a-f]{40}\z/)
    print value
  ' <<< "${payload}"
}

read_exact_ref_response() {
  local namespace="$1"
  local name="$2"
  local response api_status parsed encoded_body
  EXACT_REF_HTTP_STATUS=""
  EXACT_REF_BODY=""
  set +e
  response="$(safe_gh api --hostname github.com --include \
    -H 'Cache-Control: no-cache' -H 'Pragma: no-cache' \
    "repos/${REPOSITORY}/git/ref/${namespace}/${name}" \
    2>"${scratch}/exact-${namespace}-ref.stderr")"
  api_status=$?
  set -e
  if ! parsed="$("${RUBY_BIN}" -rbase64 -e '
    response = STDIN.read
    statuses = []
    response.to_enum(:scan, /^HTTP\/\S+\s+(\d{3})[^\r\n]*\r?$/).each do
      match = Regexp.last_match
      statuses << [match[1], match.end(0)]
    end
    abort("exact-ref response must contain one HTTP status") unless statuses.length == 1
    status, status_end = statuses.fetch(0)
    separator = response.match(/\r?\n\r?\n/, status_end)
    body = separator ? response.byteslice(separator.end(0)..) : ""
    abort("successful exact-ref response lacks a body") if status == "200" && body.empty?
    print status, "\t", Base64.strict_encode64(body)
  ' <<< "${response}")"; then
    return 1
  fi
  EXACT_REF_HTTP_STATUS="${parsed%%$'\t'*}"
  encoded_body="${parsed#*$'\t'}"
  EXACT_REF_BODY="$("${RUBY_BIN}" -rbase64 -e \
    'print Base64.strict_decode64(ARGV.fetch(0))' "${encoded_body}")"
  if [[ "${api_status}" -eq 0 && "${EXACT_REF_HTTP_STATUS}" == "200" ]]; then
    return 0
  fi
  if [[ "${api_status}" -ne 0 && "${EXACT_REF_HTTP_STATUS}" == "404" ]]; then
    return 0
  fi
  return 1
}

require_remote_tag_absent() {
  if ! read_exact_ref_response tags "${TAG}"; then
    echo "error: exact remote tag state is unknown" >&2
    return 1
  fi
  if [[ "${EXACT_REF_HTTP_STATUS}" == "404" ]]; then
    return 0
  fi
  if ! "${RUBY_BIN}" -rjson -e '
    ref = JSON.parse(STDIN.read)
    tag = ARGV.fetch(0)
    abort("exact tag ref response must be an object") unless ref.is_a?(Hash)
    abort("exact tag ref name mismatch") unless ref["ref"] == "refs/tags/#{tag}"
    object = ref["object"]
    abort("exact tag ref object is malformed") unless
      object.is_a?(Hash) &&
        %w[tag commit].include?(object["type"]) &&
        object["sha"].is_a?(String) &&
        object["sha"].match?(/\A[0-9a-f]{40}\z/)
  ' "${TAG}" <<< "${EXACT_REF_BODY}"; then
    echo "error: exact remote tag response is malformed" >&2
    return 1
  fi
  echo "error: remote tag already exists" >&2
  return 1
}

require_remote_branch_absent() {
  if ! read_exact_ref_response heads "${TAG}"; then
    echo "error: exact same-named remote branch state is unknown" >&2
    return 1
  fi
  if [[ "${EXACT_REF_HTTP_STATUS}" == "404" ]]; then
    return 0
  fi
  if ! "${RUBY_BIN}" -rjson -e '
    ref = JSON.parse(STDIN.read)
    name = ARGV.fetch(0)
    abort("exact branch ref response must be an object") unless ref.is_a?(Hash)
    abort("exact branch ref name mismatch") unless ref["ref"] == "refs/heads/#{name}"
    object = ref["object"]
    abort("exact branch ref object is malformed") unless
      object.is_a?(Hash) &&
        object["type"] == "commit" &&
        object["sha"].is_a?(String) &&
        object["sha"].match?(/\A[0-9a-f]{40}\z/)
  ' "${TAG}" <<< "${EXACT_REF_BODY}"; then
    echo "error: exact same-named remote branch response is malformed" >&2
    return 1
  fi
  echo "error: same-named remote branch already exists" >&2
  return 1
}

require_release_absent() {
  local release_pages
  if ! release_pages="$(safe_gh api --hostname github.com --paginate --slurp \
    -H 'Cache-Control: no-cache' -H 'Pragma: no-cache' \
    "repos/${REPOSITORY}/releases?per_page=100")"; then
    echo "error: release ${TAG} absence was not provable from the authenticated complete release listing" >&2
    return 1
  fi
  if ! "${RUBY_BIN}" -rjson -e '
    pages = JSON.parse(STDIN.read)
    tag = ARGV.fetch(0)
    abort("release listing must be paginated arrays") unless
      pages.is_a?(Array) && pages.all? { |page| page.is_a?(Array) }
    releases = pages.flatten(1)
    abort("release listing entries must expose tag_name") unless
      releases.all? { |release| release.is_a?(Hash) && release["tag_name"].is_a?(String) }
    matches = releases.select { |release| release["tag_name"] == tag }
    abort("an existing draft or published release already owns #{tag}") unless matches.empty?
  ' "${TAG}" <<< "${release_pages}"; then
    echo "error: release ${TAG} already exists (draft or published), or complete release absence was not provable" >&2
    return 1
  fi
}

active_release_workflow_id() {
  local workflow_json
  workflow_json="$(safe_gh api --hostname github.com \
    -H 'Cache-Control: no-cache' -H 'Pragma: no-cache' \
    "repos/${REPOSITORY}/actions/workflows/release.yml")"
  "${RUBY_BIN}" -rjson -e '
    workflow = JSON.parse(STDIN.read)
    abort("release workflow path mismatch") unless workflow["path"] == ".github/workflows/release.yml"
    abort("release workflow is not active") unless workflow["state"] == "active"
    id = workflow["id"]
    abort("release workflow ID is invalid") unless id.is_a?(Integer) && id.positive?
    print id
  ' <<< "${workflow_json}"
}

if [[ "$(remote_main_sha)" != "${COMMIT}" ]]; then
  echo "error: protected remote main changed before release push" >&2
  exit 65
fi
require_remote_tag_absent
require_remote_branch_absent
WORKFLOW_ID="$(active_release_workflow_id)"

fresh_evidence="${scratch}/fresh-governance-evidence.json"
run_clean_script_with_token "${committed_root}/${GOVERNANCE_TOOL_PATH}" \
  --repo "${REPOSITORY}" \
  --environment release \
  --branch main \
  --tag "${TAG}" \
  --expected-main "${COMMIT}" \
  --output "${fresh_evidence}" >/dev/null
fresh_time="$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)"
"${RUBY_BIN}" "${committed_root}/${VALIDATOR_PATH}" \
  --root "${ROOT_DIR}" \
  --evidence "${fresh_evidence}" \
  --repository "${REPOSITORY}" \
  --tag "${TAG}" \
  --commit "${COMMIT}" \
  --tagger-time "${fresh_time}" \
  --current-time "${fresh_time}" > "${scratch}/fresh-governance-validation.json"
if ! "${RUBY_BIN}" -rjson -e '
  signed = JSON.parse(File.read(ARGV.fetch(0)))
  fresh = JSON.parse(File.read(ARGV.fetch(1)))
  %w[repository expectedMainSHA authenticatedActor].each do |key|
    abort("fresh governance #{key} differs from signed evidence") unless fresh[key] == signed[key]
  end
  %w[releaseEnvironmentEvidence tagRulesetEvidence releaseSecrets].each do |key|
    abort("fresh governance #{key} differs from signed evidence") unless fresh[key] == signed[key]
  end
' "${signed_evidence}" "${fresh_evidence}"; then
  echo "error: fresh administrator governance differs from the signed evidence" >&2
  exit 65
fi

# The final mutable-local-state check occurs immediately before the irreversible
# operation. The receipt directory is private canonical-user state outside the
# release source checkout.
prepush_time="$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)"
"${RUBY_BIN}" "${committed_root}/${VALIDATOR_PATH}" \
  --root "${ROOT_DIR}" \
  --evidence "${signed_evidence}" \
  --repository "${REPOSITORY}" \
  --tag "${TAG}" \
  --commit "${COMMIT}" \
  --tagger-time "${TAGGER_TIME}" \
  --current-time "${prepush_time}" > "${scratch}/prepush-signed-governance-validation.json"
"${RUBY_BIN}" "${committed_root}/${VALIDATOR_PATH}" \
  --root "${ROOT_DIR}" \
  --evidence "${fresh_evidence}" \
  --repository "${REPOSITORY}" \
  --tag "${TAG}" \
  --commit "${COMMIT}" \
  --tagger-time "${fresh_time}" \
  --current-time "${prepush_time}" > "${scratch}/prepush-fresh-governance-validation.json"
if [[ "$(safe_repo_git rev-parse --verify 'HEAD^{commit}' 2>/dev/null || true)" != "${COMMIT}" ]] ||
   [[ "$(safe_repo_git rev-parse --verify "refs/tags/${TAG}^{tag}" 2>/dev/null || true)" != "${TAG_OBJECT}" ]] ||
   [[ -n "$(safe_repo_git status --porcelain=v1 --untracked-files=all)" ]]; then
  echo "error: worktree, HEAD, or signed tag changed during release validation" >&2
  exit 65
fi
if [[ "$(remote_main_sha)" != "${COMMIT}" ]]; then
  echo "error: protected remote main changed immediately before release push" >&2
  exit 65
fi
require_remote_tag_absent
require_remote_branch_absent
require_release_absent

write_receipt "validated-pre-push" "validated-pre-push"

bundle_path="${scratch}/tag.bundle"
bare_root="${scratch}/push.git"
empty_template="${scratch}/empty-git-template"
/bin/mkdir -m 700 "${empty_template}"
safe_repo_git bundle create "${bundle_path}" "refs/tags/${TAG}"
GIT_CONFIG_NOSYSTEM=1 \
GIT_CONFIG_SYSTEM=/dev/null \
GIT_CONFIG_GLOBAL=/dev/null \
GIT_CONFIG_COUNT=2 \
GIT_CONFIG_KEY_0=core.hooksPath GIT_CONFIG_VALUE_0=/dev/null \
GIT_CONFIG_KEY_1=init.templateDir GIT_CONFIG_VALUE_1="${empty_template}" \
  "${GIT_BIN}" init --bare --template="${empty_template}" "${bare_root}" >/dev/null
safe_bare_git "${bare_root}" fetch --no-tags "${bundle_path}" \
  "refs/tags/${TAG}:refs/tags/${TAG}" >/dev/null
if [[ "$(safe_bare_git "${bare_root}" rev-parse --verify "refs/tags/${TAG}^{tag}")" != "${TAG_OBJECT}" ]] ||
   [[ "$(safe_bare_git "${bare_root}" rev-parse --verify "refs/tags/${TAG}^{commit}")" != "${COMMIT}" ]]; then
  echo "error: isolated push repository did not preserve the exact tag object" >&2
  exit 65
fi
if ! safe_bare_git "${bare_root}" \
  -c gpg.format=ssh \
  -c gpg.ssh.program=/usr/bin/ssh-keygen \
  -c "gpg.ssh.allowedSignersFile=${commit_signers}" \
  verify-tag "${TAG_OBJECT}" >/dev/null; then
  echo "error: isolated push repository signature verification failed" >&2
  exit 65
fi

askpass_dir="${scratch}/askpass"
/bin/mkdir -m 700 "${askpass_dir}"
askpass_path="${askpass_dir}/askpass.sh"
askpass_token_path="${askpass_dir}/token"
builtin printf '%s\n' "${SAFE_GH_TOKEN}" > "${askpass_token_path}"
/bin/chmod 600 "${askpass_token_path}"
/usr/bin/printf '%s\n' \
  '#!/bin/bash -p' \
  'case "${1:-}" in' \
  '  *Username*) /usr/bin/printf "%s\n" "x-access-token" ;;' \
  '  *Password*)' \
  '    token_file="${VIFTY_GIT_TOKEN_FILE:?}"' \
  '    [[ "${token_file}" == /* && -f "${token_file}" && ! -L "${token_file}" ]] || exit 1' \
  '    [[ "$(/usr/bin/stat -f %Lp "${token_file}")" == "600" ]] || exit 1' \
  '    IFS= read -r token < "${token_file}" || exit 1' \
  '    [[ -n "${token}" && "${token}" != *[[:space:]]* ]] || exit 1' \
  '    /usr/bin/printf "%s\n" "${token}"' \
  '    unset token' \
  '    ;;' \
  '  *) exit 1 ;;' \
  'esac' > "${askpass_path}"
/bin/chmod 700 "${askpass_path}"

CURRENT_STAGE="pushing-exact-annotated-tag"
remote_url="https://github.com/${REPOSITORY}.git"
CURRENT_STAGE="push-started"
TAG_PUSH_JOURNALED_AT="$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)"
REMOTE_TAG_STATE="unknown"
PUSH_DISPOSITION="started-outcome-unknown"
create_retirement_marker
write_receipt "push-started-remote-outcome-unknown" "${CURRENT_STAGE}"
set +e
push_output="$(
  GIT_ASKPASS="${askpass_path}" \
  GIT_TERMINAL_PROMPT=0 \
  VIFTY_GIT_TOKEN_FILE="${askpass_token_path}" \
  safe_bare_git "${bare_root}" push \
    --porcelain \
    --force-with-lease="refs/tags/${TAG}:" \
    "${remote_url}" \
    "${TAG_OBJECT}:refs/tags/${TAG}" 2>&1
)"
PUSH_EXIT_CODE=$?
set -e
CURRENT_STAGE="push-response-readback"
if "${RUBY_BIN}" -e '
  tag = ARGV.fetch(0)
  status_lines = STDIN.each_line.map(&:chomp).select { |line| line.match?(/\A[ =*+!-]\t/) }
  abort("push porcelain must report exactly one ref status") unless status_lines.length == 1
  fields = status_lines.fetch(0).split("\t", -1)
  abort("push did not report exact new-tag creation") unless
    fields.length >= 3 &&
      fields[0] == "*" &&
      fields[1].end_with?(":refs/tags/#{tag}") &&
      fields[2] == "[new tag]"
' "${TAG}" <<< "${push_output}" >/dev/null 2>&1; then
  PUSH_OWNERSHIP="created-by-this-transaction"
else
  PUSH_OWNERSHIP="not-established"
fi
/bin/unlink "${askpass_token_path}" "${askpass_path}" 2>/dev/null || true

classify_remote_tag() {
  local classification tag_json tag_status
  if ! read_exact_ref_response tags "${TAG}"; then
    REMOTE_TAG_STATE="unknown"
    return 0
  fi
  if [[ "${EXACT_REF_HTTP_STATUS}" == "404" ]]; then
    REMOTE_TAG_STATE="absent"
    return 0
  fi
  set +e
  classification="$("${RUBY_BIN}" -rjson -e '
    ref = JSON.parse(STDIN.read)
    name, object = ARGV
    abort("exact tag ref response must be an object") unless ref.is_a?(Hash)
    abort("exact tag ref name mismatch") unless ref["ref"] == "refs/tags/#{name}"
    if ref.dig("object", "type") == "tag" &&
       ref.dig("object", "sha") == object
      print "candidate"
    else
      print "mismatched"
    end
  ' "${TAG}" "${TAG_OBJECT}" <<< "${EXACT_REF_BODY}")"
  tag_status=$?
  set -e
  if [[ "${tag_status}" -ne 0 ]]; then
    REMOTE_TAG_STATE="unknown"
    return 0
  fi
  if [[ "${classification}" != "candidate" ]]; then
    REMOTE_TAG_STATE="${classification}"
    return 0
  fi

  set +e
  tag_json="$(safe_gh api --hostname github.com \
    -H 'Cache-Control: no-cache' -H 'Pragma: no-cache' \
    "repos/${REPOSITORY}/git/tags/${TAG_OBJECT}" 2>/dev/null)"
  tag_status=$?
  set -e
  if [[ "${tag_status}" -ne 0 ]]; then
    REMOTE_TAG_STATE="unknown"
    return 0
  fi
  if "${RUBY_BIN}" -rjson -e '
    tag = JSON.parse(STDIN.read)
    expected_name, expected_commit, expected_object = ARGV
    abort("remote annotated tag object SHA mismatch") unless tag["sha"] == expected_object
    abort("remote annotated tag name mismatch") unless tag["tag"] == expected_name
    abort("remote annotated tag target mismatch") unless
      tag.dig("object", "type") == "commit" &&
        tag.dig("object", "sha") == expected_commit
  ' "${TAG}" "${COMMIT}" "${TAG_OBJECT}" <<< "${tag_json}" >/dev/null 2>&1; then
    REMOTE_TAG_STATE="exact"
  else
    REMOTE_TAG_STATE="mismatched"
  fi
}

for ((readback_attempt = 1; readback_attempt <= 30; readback_attempt++)); do
  classify_remote_tag
  if [[ "${REMOTE_TAG_STATE}" == "exact" || "${REMOTE_TAG_STATE}" == "mismatched" ]]; then
    break
  fi
  [[ "${readback_attempt}" == "30" ]] || /bin/sleep 2
done

case "${REMOTE_TAG_STATE}" in
  exact)
    TAG_PUSHED=1
    CURRENT_STAGE="tag-pushed-readback-pending"
    if [[ "${PUSH_EXIT_CODE}" -eq 0 ]]; then
      if [[ "${PUSH_OWNERSHIP}" == "created-by-this-transaction" ]]; then
        PUSH_DISPOSITION="accepted-exact"
        write_receipt "tag-pushed-run-observation-pending" "${CURRENT_STAGE}"
      else
        PUSH_DISPOSITION="exact-tag-not-created-by-this-transaction"
        write_receipt "push-ownership-not-established" "${CURRENT_STAGE}"
        FAILURE_RECEIPT_CLASSIFIED=1
        echo "error: push did not prove exact new-tag ownership; ${TAG} is retired and its tag-push workflow state must be inspected" >&2
        exit 75
      fi
    else
      if [[ "${push_output}" == *"[rejected]"* ||
            "${push_output}" == *"stale info"* ||
            "${push_output}" == *"remote rejected"* ]]; then
        PUSH_DISPOSITION="definite-rejection-remote-exact"
        write_receipt "push-definite-rejection-remote-exact" "${CURRENT_STAGE}"
      else
        PUSH_DISPOSITION="ambiguous-response-remote-exact"
        write_receipt "push-response-ambiguous-remote-exact" "${CURRENT_STAGE}"
      fi
      FAILURE_RECEIPT_CLASSIFIED=1
      echo "error: nonzero tag-push response retires ${TAG}; its workflow may already exist and this tag must not be reused" >&2
      exit 75
    fi
    ;;
  absent)
    PUSH_DISPOSITION="failed-remote-absent"
    write_receipt "push-failed-tag-absent" "${CURRENT_STAGE}"
    echo "error: exact tag push did not create the remote tag (push exit ${PUSH_EXIT_CODE})" >&2
    exit 69
    ;;
  mismatched)
    PUSH_DISPOSITION="remote-mismatched"
    write_receipt "push-result-remote-mismatched" "${CURRENT_STAGE}"
    echo "error: github.com tag readback resolves to a different object; no deletion was attempted" >&2
    exit 65
    ;;
  *)
    REMOTE_TAG_STATE="unknown"
    PUSH_DISPOSITION="remote-unknown"
    write_receipt "push-result-remote-unknown" "${CURRENT_STAGE}"
    echo "error: exact remote tag state is unknown after push exit ${PUSH_EXIT_CODE}; no deletion was attempted" >&2
    exit 69
    ;;
esac

postpush_workflow_id="$(active_release_workflow_id)"
if [[ "${postpush_workflow_id}" != "${WORKFLOW_ID}" ]]; then
  echo "error: active Release workflow identity changed after tag creation" >&2
  exit 65
fi

if [[ "$(remote_main_sha)" != "${COMMIT}" ]]; then
  echo "error: protected remote main changed after tag creation" >&2
  exit 65
fi
require_remote_branch_absent

postpush_evidence="${scratch}/postpush-governance-evidence.json"
run_clean_script_with_token "${committed_root}/${GOVERNANCE_TOOL_PATH}" \
  --repo "${REPOSITORY}" \
  --environment release \
  --branch main \
  --tag "${TAG}" \
  --expected-main "${COMMIT}" \
  --expected-existing-tag-object "${TAG_OBJECT}" \
  --output "${postpush_evidence}" >/dev/null
postpush_time="$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)"
"${RUBY_BIN}" "${committed_root}/${VALIDATOR_PATH}" \
  --root "${ROOT_DIR}" \
  --evidence "${postpush_evidence}" \
  --repository "${REPOSITORY}" \
  --tag "${TAG}" \
  --commit "${COMMIT}" \
  --tagger-time "${TAGGER_TIME}" \
  --current-time "${postpush_time}" \
  --expected-existing-tag-object "${TAG_OBJECT}" \
  > "${scratch}/postpush-governance-validation.json"
if ! "${RUBY_BIN}" -rjson -rtime -e '
  signed = JSON.parse(File.read(ARGV.fetch(0)))
  post = JSON.parse(File.read(ARGV.fetch(1)))
  repository, tag, commit, object = ARGV.drop(2)
  abort("post-push governance is not a live authorized readback") unless
    post["status"] == "passed" &&
      post["releaseAuthorized"] == true &&
      post["evidenceScope"] == "administrator-posttag" &&
      post["apiHost"] == "github.com" &&
      post["dataSource"] == "github-api-live" &&
      post["liveAuthenticatedGitHubReadback"] == true
  abort("post-push governance identity mismatch") unless
    post["repository"] == repository &&
      post["authenticatedActor"] == signed["authenticatedActor"] &&
      post["releaseTag"] == tag &&
      post["expectedMainSHA"] == commit &&
      post["tagAbsentVerified"] == false &&
      post["existingTagVerified"] == true &&
      post["existingTagObjectSHA"] == object
  started = Time.iso8601(post.fetch("observationStartedAt"))
  observed = Time.iso8601(post.fetch("observedAt"))
  now = Time.now.utc
  abort("post-push governance timestamps are invalid") unless
    observed >= started && now >= observed && now.to_i - started.to_i <= 900
  %w[releaseEnvironmentEvidence tagRulesetEvidence releaseSecrets].each do |key|
    abort("post-push governance #{key} differs from signed evidence") unless post[key] == signed[key]
  end
' "${signed_evidence}" "${postpush_evidence}" \
  "${REPOSITORY}" "${TAG}" "${COMMIT}" "${TAG_OBJECT}"; then
  echo "error: post-push administrator governance does not preserve the signed release contract" >&2
  exit 65
fi

TRIGGER_STATE="waiting-for-tag-push-run"
TRIGGER_CORRELATION="not-checked"
CURRENT_STAGE="tag-push-run-observation"
write_receipt "tag-pushed-run-pending" "${CURRENT_STAGE}"

matching_run="${scratch}/matching-run.json"
run_found=0
for ((attempt = 1; attempt <= 30; attempt++)); do
  set +e
  runs_json="$(safe_gh run list \
    --repo "github.com/${REPOSITORY}" \
    --workflow "${WORKFLOW_ID}" \
    --event push \
    --all \
    --limit 100 \
    --json databaseId,displayTitle,event,headBranch,headSha,status,url,workflowDatabaseId,workflowName,createdAt,attempt \
    2>"${scratch}/run-list.stderr")"
  run_list_status=$?
  set -e
  if [[ "${run_list_status}" -ne 0 ]]; then
    /bin/sleep 2
    continue
  fi
  set +e
  "${RUBY_BIN}" -rjson -rtime -e '
    begin
      runs = JSON.parse(STDIN.read)
    rescue JSON::ParserError
      exit 3
    end
    exit 3 unless runs.is_a?(Array) && runs.all? { |run| run.is_a?(Hash) }
    tag, commit, workflow_id, journaled_at, output_path = ARGV
    title = "Release #{tag}"
    matches = runs.select { |run| run["displayTitle"] == title }
    exit 2 if matches.empty?
    abort("tag push matched more than one release run") unless matches.length == 1
    run = matches.fetch(0)
    id = run["databaseId"]
    abort("release run ID is invalid") unless id.is_a?(Integer) && id.positive?
    abort("release run listing workflow mismatch") unless
      run["workflowDatabaseId"] == workflow_id.to_i && run["workflowName"] == "Release"
    abort("release run listing event/ref mismatch") unless
      run["event"] == "push" && run["headBranch"] == tag && run["headSha"] == commit
    abort("release run listing must be its first attempt") unless run["attempt"] == 1
    begin
      created_at = Time.iso8601(run.fetch("createdAt")).utc
      journaled = Time.iso8601(journaled_at).utc
    rescue KeyError, ArgumentError
      abort("release run listing creation time is invalid")
    end
    now = Time.now.utc
    abort("release run predates the tag-push journal") if created_at < journaled - 60
    abort("release run creation time is implausibly in the future") if created_at > now + 60
    File.write(output_path, JSON.generate(run))
  ' "${TAG}" "${COMMIT}" "${WORKFLOW_ID}" "${TAG_PUSH_JOURNALED_AT}" \
    "${matching_run}" <<< "${runs_json}"
  match_status=$?
  set -e
  if [[ "${match_status}" -eq 0 ]]; then
    RUN_ID="$("${RUBY_BIN}" -rjson -e '
      value = JSON.parse(File.read(ARGV.fetch(0))).fetch("databaseId")
      abort("release run ID is invalid") unless value.is_a?(Integer) && value.positive?
      print value
    ' "${matching_run}")"
    run_found=1
    break
  fi
  if [[ "${match_status}" -eq 1 ]]; then
    TRIGGER_STATE="ambiguous"
    TRIGGER_CORRELATION="ambiguous"
    CURRENT_STAGE="tag-push-run-ambiguous"
    write_receipt "tag-push-run-ambiguous" "${CURRENT_STAGE}"
    FAILURE_RECEIPT_CLASSIFIED=1
    echo "error: tag push matched multiple or conflicting Release runs; do not rerun, dispatch manually, or reuse this tag" >&2
    exit 65
  fi
  /bin/sleep 2
done

if [[ "${run_found}" != "1" ]]; then
  TRIGGER_STATE="unobserved"
  TRIGGER_CORRELATION="unconfirmed"
  CURRENT_STAGE="tag-push-run-unobserved"
  write_receipt "tag-push-run-unobserved" "${CURRENT_STAGE}"
  FAILURE_RECEIPT_CLASSIFIED=1
  echo "error: no unique tag-push Release run was observed; do not rerun, dispatch manually, or reuse this tag—inspect the original tag and public release state" >&2
  exit 69
fi

WORKFLOW_RUN_OBSERVED=1
TRIGGER_CORRELATION="observed-unverified"
TRIGGER_STATE="observed-unverified"
CURRENT_STAGE="tag-push-run-observed-verification-pending"
write_receipt "tag-push-run-observed-verification-pending" "${CURRENT_STAGE}"
run_verified=0
run_semantic_failure=0
for ((attempt = 1; attempt <= 30; attempt++)); do
  set +e
  run_view_json="$(safe_gh api --hostname github.com \
    -H 'Cache-Control: no-cache' -H 'Pragma: no-cache' \
    "repos/${REPOSITORY}/actions/runs/${RUN_ID}" \
    2>"${scratch}/run-view.stderr")"
  run_view_status=$?
  set -e
  if [[ "${run_view_status}" -ne 0 ]]; then
    /bin/sleep 2
    continue
  fi
  set +e
  "${RUBY_BIN}" -rjson -rtime -e '
    begin
      run = JSON.parse(STDIN.read)
    rescue JSON::ParserError
      exit 2
    end
    exit 2 unless run.is_a?(Hash)
    run_id, workflow_id, tag, commit, repository, journaled_at, evidence_path = ARGV
    signed_actor = JSON.parse(File.read(evidence_path)).fetch("authenticatedActor")
    abort("release run ID mismatch") unless run["id"] == run_id.to_i
    abort("release workflow ID mismatch") unless run["workflow_id"] == workflow_id.to_i
    abort("release workflow name mismatch") unless run["name"] == "Release"
    abort("release workflow path mismatch") unless run["path"] == ".github/workflows/release.yml"
    abort("release run title mismatch") unless run["display_title"] == "Release #{tag}"
    abort("release run event mismatch") unless run["event"] == "push"
    abort("release run head ref mismatch") unless run["head_branch"] == tag
    abort("release run head SHA mismatch") unless run["head_sha"] == commit
    abort("release run must be its first attempt") unless run["run_attempt"] == 1
    abort("release run actor mismatch") unless
      run.dig("actor", "login") == signed_actor["login"] &&
        run.dig("actor", "id") == signed_actor["id"]
    abort("release run repository mismatch") unless run.dig("repository", "full_name") == repository
    expected_url = "https://github.com/#{repository}/actions/runs/#{run_id}"
    abort("release run URL mismatch") unless run["html_url"] == expected_url
    begin
      created_at = Time.iso8601(run.fetch("created_at")).utc
      journaled = Time.iso8601(journaled_at).utc
    rescue KeyError, ArgumentError
      abort("release run createdAt is invalid")
    end
    now = Time.now.utc
    abort("release run predates the tag-push journal") if created_at < journaled - 60
    abort("release run createdAt is implausibly in the future") if created_at > now + 60
    print run["html_url"]
  ' "${RUN_ID}" "${WORKFLOW_ID}" "${TAG}" "${COMMIT}" \
    "${REPOSITORY}" "${TAG_PUSH_JOURNALED_AT}" "${signed_evidence}" \
    <<< "${run_view_json}" > "${scratch}/run-url"
  verification_status=$?
  set -e
  if [[ "${verification_status}" -eq 0 ]]; then
    run_verified=1
    break
  fi
  if [[ "${verification_status}" -eq 1 ]]; then
    run_semantic_failure=1
    break
  fi
  /bin/sleep 2
done
if [[ "${run_verified}" != "1" ]]; then
  CURRENT_STAGE="tag-push-run-verification-failed"
  if [[ "${run_semantic_failure}" == "1" ]]; then
    receipt_status="tag-push-run-mismatched"
  else
    receipt_status="tag-push-run-observed-unverified"
  fi
  write_receipt "${receipt_status}" "${CURRENT_STAGE}"
  FAILURE_RECEIPT_CLASSIFIED=1
  echo "error: release workflow run does not bind the exact actor, workflow, tag, commit, repository, push event, and first attempt; do not rerun or reuse this tag—observe run ${RUN_ID}" >&2
  exit 65
fi
RUN_URL="$(< "${scratch}/run-url")"
WORKFLOW_RUN_VERIFIED=1
TRIGGER_STATE="confirmed"
TRIGGER_CORRELATION="confirmed"
CURRENT_STAGE="completed"
write_receipt "completed" "${CURRENT_STAGE}"
SUCCESS=1

printf 'Pushed immutable tag %s (%s) and verified tag-push Release run %s\n' \
  "${TAG}" "${TAG_OBJECT}" "${RUN_URL}"
printf 'Receipt: %s\n' "${RECEIPT_PATH}"
